### ISSUE TITLE
Running `optirun glxgears` not increasing frames

### ISSUE THREAD

**Issue by darosior** [Bumblebee-Project/Bumblebee#1018]
Hi,

*Laptop* : Clevo N8xEJEK (also called Saturne JD7-8-S2H20 by LDLC)
*GPUs* : Nvidia gtx geforce 1050 + intel graphics
*Kernel* : 4.19
*Distro* : Debian buster (stretch -> testing)
*DM* : lightdm and gdm3

I installed bumblebee using the nvidia driver from buster (390 I think) and I have set
```
Driver=nvidia
PMMethod=none
AlwaysUnloadKernelDriver=true
```
in the config.

I can use lightDM using my intel GPU. However I'll got the same number of frames using optirun or not :
```
optirun glxgears -info
```

**Comment by ilovesusu** [comment]
you can exec
`vblank_mode=0 optirun glxgears -info`

**Comment by darosior** [comment]
That just worked ! Thank you.
I got 2900 FPS, is it a safe solution for the long term ? I mean is there anyother drawbacks than battery waste ?
