### ISSUE TITLE
Bumblebee stable ubuntu disco (19.04) Release does not have a Release file.

### ISSUE THREAD

**Issue by rbashish** [Bumblebee-Project/Bumblebee#1028]
I always get this error when trying to  **`sudo apt-get update`** or through Software & Updates.
Attached is the screenshot of error - How do I fix this?

![Screenshot from 2019-04-27 22-16-10](https://user-images.githubusercontent.com/6831399/56852527-261d8800-693a-11e9-959d-43b617ac653c.png)

I also get the same error when opening **Ubuntu Software**. Attached is the screenshot.

![Screenshot from 2019-04-27 22-29-41](https://user-images.githubusercontent.com/6831399/56852736-7269c780-693c-11e9-87f6-7f683a3f69b7.png)

**Comment by bluca** [comment]
That's because there is no PPA for Disco, just use the version from the distribution and remove it from the sources.

**Comment by rbashish** [comment]
> That's because there is no PPA for Disco, just use the version from the distribution and remove it from the sources.

Well thanks for providing that information and as suggested removed from the sources. Now I'm not bothered by those popup and error messages on terminal. But wonder why and how if it does not have PPA, get added to the  source list?

**Comment by bluca** [comment]
I guess you had added it in the past before the upgrade to disco, I think Ubuntu disables third party repos on upgrade but also changes the distro keyword, I imagine you then re enabled it manually at some point after the upgrade
