### ISSUE TITLE
Night light does not work with intel-virtual-output

### ISSUE THREAD

**Issue by alexandru-calinoiu** [Bumblebee-Project/Bumblebee#1031]
I have a thinkpad extreme with a nvidia discreat gpu, the only way I can git external monitors to work is via `intel-virtual-output`

This works mostly fine, the problem is that the gnome night light won't work on external monitors, what can I do about it?

**Comment by haarp** [comment]
Try running it with DISPLAY=:8

**Comment by alexandru-calinoiu** [comment]
Gave up on bumblebee for now using optimus manager to switch sessions.
