### ISSUE TITLE
optirun glxgears  [ERROR]Cannot access secondary GPU

### ISSUE THREAD

**Issue by jusaclown** [Bumblebee-Project/Bumblebee#1041]
At first 
**$ optirun glxgears**
 _[ERROR]Cannot access secondary GPU - error: [XORG] (EE) Failed to load module "mouse" (module does not exist, 0)_

so, I installed "xserver-xorg-input-mouse" by apt，however,
**$ optirun glxgears**
_[ERROR]Cannot access secondary GPU - error: [XORG] (EE)
[ERROR]Aborting because fallback start is disabled._ 

**$ uname -a**
_Linux yamup 5.2.0-kali2-amd64 #1 SMP Debian 5.2.9-2kali1 (2019-08-22) x86_64 GNU/Linux_

**$ optirun -vvv glxgears**
_[ 2865.771830] [DEBUG]Reading file: /etc/bumblebee/bumblebee.conf
[ 2865.772088] [INFO]Configured driver: nvidia
[ 2865.772325] [DEBUG]optirun version 3.2.1 starting...
[ 2865.772336] [DEBUG]Active configuration:
[ 2865.772339] [DEBUG] bumblebeed config file: /etc/bumblebee/bumblebee.conf
[ 2865.772342] [DEBUG] X display: :8
[ 2865.772345] [DEBUG] LD_LIBRARY_PATH: /usr/lib/x86_64-linux-gnu/nvidia:/usr/lib/i386-linux-gnu/nvidia:/usr/lib/nvidia
[ 2865.772349] [DEBUG] Socket path: /var/run/bumblebee.socket
[ 2865.772354] [DEBUG] Accel/display bridge: auto
[ 2865.772364] [DEBUG] VGL Compression: proxy
[ 2865.772370] [DEBUG] VGLrun extra options: 
[ 2865.772378] [DEBUG] Primus LD Path: /usr/lib/x86_64-linux-gnu/primus:/usr/lib/i386-linux-gnu/primus:/usr/lib/primus:/usr/lib32/primus
[ 2865.772443] [DEBUG]Using auto-detected bridge primus
[ 2866.123249] [INFO]Response: No - error: [XORG] (EE)_ 

_[ 2866.123265] [ERROR]Cannot access secondary GPU - error: [XORG] (EE)_ 

_[ 2866.123276] [DEBUG]Socket closed.
[ 2866.123292] [ERROR]Aborting because fallback start is disabled.
[ 2866.123298] [DEBUG]Killing all remaining processes._

**$ dkms status** 
_bbswitch, 0.8, 5.2.0-kali2-amd64, x86_64: installed
lime-forensics, 1.8.1-2, 5.2.0-kali2-amd64, x86_64: installed
nvidia-current, 430.50, 5.2.0-kali2-amd64, x86_64: installed
nvidia-legacy-390xx, 390.129, 4.19.0-kali5-amd64, x86_64: installed
nvidia-legacy-390xx, 390.129, 5.2.0-kali2-amd64, x86_64: installed
virtualbox, 6.0.12, 5.2.0-kali2-amd64, x86_64: installed_

**$ bumblebeed --debug**
_[ 2827.101662] [DEBUG]Found card: 01:00.0 (discrete)
[ 2827.101695] [DEBUG]Found card: 00:02.0 (integrated)
[ 2827.102370] [DEBUG]Reading file: /etc/bumblebee/bumblebee.conf
[ 2827.102671] [INFO]Configured driver: nvidia
[ 2827.102693] [DEBUG]Skipping auto-detection, using configured driver 'nvidia'
[ 2827.102802] [DEBUG]bbswitch has been detected.
[ 2827.102816] [INFO]Switching method 'bbswitch' is available and will be used.
[ 2827.102834] [DEBUG]Active configuration:
[ 2827.102851] [DEBUG] bumblebeed config file: /etc/bumblebee/bumblebee.conf
[ 2827.102868] [DEBUG] X display: :8
[ 2827.102884] [DEBUG] LD_LIBRARY_PATH: /usr/lib/x86_64-linux-gnu/nvidia:/usr/lib/i386-linux-gnu/nvidia:/usr/lib/nvidia
[ 2827.102903] [DEBUG] Socket path: /var/run/bumblebee.socket
[ 2827.102919] [DEBUG] pidfile: /var/run/bumblebeed.pid
[ 2827.102934] [DEBUG] xorg.conf file: /etc/bumblebee/xorg.conf.nvidia
[ 2827.102951] [DEBUG] xorg.conf.d dir: /etc/bumblebee/xorg.conf.d
[ 2827.102968] [DEBUG] Xorg binary: /usr/lib/xorg/Xorg
[ 2827.102984] [DEBUG] ModulePath: /usr/lib/nvidia/nvidia,/usr/lib/xorg/modules
[ 2827.103003] [DEBUG] GID name: bumblebee
[ 2827.103021] [DEBUG] Power method: auto
[ 2827.103040] [DEBUG] Stop X on exit: 1
[ 2827.103051] [DEBUG] Driver: nvidia
[ 2827.103069] [DEBUG] Driver module: nvidia
[ 2827.103085] [DEBUG] Card shutdown state: 1
[ 2827.103166] [DEBUG]Configuration test passed.
[ 2827.103216] [ERROR]Daemon already running, pid 714_

I tried some solutions ,  but they didn't work. I hope you can help me

**Comment by felixdoerre** [comment]
> nvidia-current, 430.50

That seems to be similar to the bug described here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=939401
I assume, you have the "nonglvnd"-version of the nvidia driver installed which is broken since 430.40 (the nvidia X server just crashes). As nvidia is removing the nonglvnd-driver variant, no one expects a "bugfix" for that problem.

I currently use a "trick" (on debian) to be able to use bumblebee with the "glvnd"-variant of the nvidia-driver, but I don't know how/if this works on kalilinux: I installed the "glvnd"-nvidia driver (which caused the primus launcher to be removed, but the primus-libraries stayed) and now I launch my applications with `optirun -- env PRIMUS_libGLa=/usr/lib/x86_64-linux-gnu/libGLX_nvidia.so.0:/usr/lib/i386-linux-gnu/libGLX_nvidia.so.0 glxgears`. Even if it is not required for a compliant `libGLX_nvidia.so.0` to be able to be used with primus, this seems to work, at least for 430.40, which I currently have installed.

**Comment by jusaclown** [comment]
> > nvidia-current, 430.50
> 
> That seems to be similar to the bug described here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=939401
> I assume, you have the "nonglvnd"-version of the nvidia driver installed which is broken since 430.40 (the nvidia X server just crashes). As nvidia is removing the nonglvnd-driver variant, no one expects a "bugfix" for that problem.
> 
> I currently use a "trick" (on debian) to be able to use bumblebee with the "glvnd"-variant of the nvidia-driver, but I don't know how/if this works on kalilinux: I installed the "glvnd"-nvidia driver (which caused the primus launcher to be removed, but the primus-libraries stayed) and now I launch my applications with `optirun -- env PRIMUS_libGLa=/usr/lib/x86_64-linux-gnu/libGLX_nvidia.so.0:/usr/lib/i386-linux-gnu/libGLX_nvidia.so.0 glxgears`. Even if it is not required for a compliant `libGLX_nvidia.so.0` to be able to be used with primus, this seems to work, at least for 430.40, which I currently have installed.

Thank you very much, this helped me solve this problem. Thank you.

**Comment by xiaojie0815** [comment]
> > > nvidia-current, 430.50
> > 
> > 
> > That seems to be similar to the bug described here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=939401
> > I assume, you have the "nonglvnd"-version of the nvidia driver installed which is broken since 430.40 (the nvidia X server just crashes). As nvidia is removing the nonglvnd-driver variant, no one expects a "bugfix" for that problem.
> > I currently use a "trick" (on debian) to be able to use bumblebee with the "glvnd"-variant of the nvidia-driver, but I don't know how/if this works on kalilinux: I installed the "glvnd"-nvidia driver (which caused the primus launcher to be removed, but the primus-libraries stayed) and now I launch my applications with `optirun -- env PRIMUS_libGLa=/usr/lib/x86_64-linux-gnu/libGLX_nvidia.so.0:/usr/lib/i386-linux-gnu/libGLX_nvidia.so.0 glxgears`. Even if it is not required for a compliant `libGLX_nvidia.so.0` to be able to be used with primus, this seems to work, at least for 430.40, which I currently have installed.
> 
> Thank you very much, this helped me solve this problem. Thank you.

Now how to solve this problem, can you write a detailed solution? thank you very much for your help

> > > nvidia-current, 430.50
> > 
> > 
> > That seems to be similar to the bug described here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=939401
> > I assume, you have the "nonglvnd"-version of the nvidia driver installed which is broken since 430.40 (the nvidia X server just crashes). As nvidia is removing the nonglvnd-driver variant, no one expects a "bugfix" for that problem.
> > I currently use a "trick" (on debian) to be able to use bumblebee with the "glvnd"-variant of the nvidia-driver, but I don't know how/if this works on kalilinux: I installed the "glvnd"-nvidia driver (which caused the primus launcher to be removed, but the primus-libraries stayed) and now I launch my applications with `optirun -- env PRIMUS_libGLa=/usr/lib/x86_64-linux-gnu/libGLX_nvidia.so.0:/usr/lib/i386-linux-gnu/libGLX_nvidia.so.0 glxgears`. Even if it is not required for a compliant `libGLX_nvidia.so.0` to be able to be used with primus, this seems to work, at least for 430.40, which I currently have installed.
> 
> Thank you very much, this helped me solve this problem. Thank you.

Now how to solve this problem, can you write a detailed solution? thank you very much for your help

**Comment by jusaclown** [comment]
> Now how to solve this problem, can you write a detailed solution? thank you very much for your help

**1. $ sudo apt install nvidia-driver-libs nvidia-driver-libs:i386
2. $ service bumblebeed restart
3. $ optirun -- env PRIMUS_libGLa=/usr/lib/x86_64-linux-gnu/libGLX_nvidia.so.0:/usr/lib/i386-linux-gnu/libGLX_nvidia.so.0 glxgears**  
Also, you can add "_export PRIMUS_libGLa=/usr/lib/x86_64-linux-gnu/libGLX_nvidia.so.0:/usr/lib/i386-linux-gnu/libGLX_nvidia.so.0_" to "_~/.bashrc_" and then you can use "_optirun  glxgears_"
I don't know why it works, but it's really useful.

**Comment by xiaojie0815** [comment]
> > Now how to solve this problem, can you write a detailed solution? thank you very much for your help
> 
> **1. $ sudo apt install nvidia-driver-libs nvidia-driver-libs:i386 2. $ service bumblebeed restart 3. $ optirun -- env PRIMUS_libGLa=/usr/lib/x86_64-linux-gnu/libGLX_nvidia.so.0:/usr/lib/i386-linux-gnu/libGLX_nvidia.so.0 glxgears**
> Also, you can add "_export PRIMUS_libGLa=/usr/lib/x86_64-linux-gnu/libGLX_nvidia.so.0:/usr/lib/i386-linux-gnu/libGLX_nvidia.so.0_" to "_~/.bashrc_" and then you can use "_optirun glxgears_"
> I don't know why it works, but it's really useful.
apt-get autoremove --purge bumblebee* nvidia*
sudo apt install nvidia-driver-libs nvidia-driver-libs
optirun glxgears normal operation
but hashcat (v5.1.0) starting...
No devices found/left.

**Comment by xiaojie0815** [comment]
apt-get autoremove --purge bumblebee* nvidia*
sudo apt install nvidia-driver-libs nvidia-driver-libs
optirun glxgears normal operation
but hashcat (v5.1.0) starting...
No devices found/left.

**Comment by xiaojie0815** [comment]
> > 现在如何解决这个问题，您能写一个详细的解决方案吗？非常感谢您的帮助
> 


apt-get autoremove --purge bumblebee* nvidia*
sudo apt install nvidia-driver-libs nvidia-driver-libs
optirun glxgears normal operation
but hashcat (v5.1.0) starting...
No devices found/left.

**Comment by xiaojie0815** [comment]
> > Now how to solve this problem, can you write a detailed solution? thank you very much for your help
> 
apt-get autoremove --purge bumblebee* nvidia*
sudo apt install nvidia-driver-libs nvidia-driver-libs
optirun glxgears normal operation
but hashcat (v5.1.0) starting...
No devices found/left.

**Comment by jusaclown** [comment]
> No devices found/left.
ooooh, me too. add _--force_ ? I don't know.
