### ISSUE TITLE
Bricked GPU?

### ISSUE THREAD

**Issue by npip99** [Bumblebee-Project/Bumblebee#1043]
bbswitch was working great for about 8 hours after I first installed it. It'd activate and deactivate as much as I want, and lasted though several reboots, and lasted multiple tests with sleep mode. Then, after it was asleep for a few hours, upon opening the lid the computer was just frozen. Tried to reboot, and now it's gone. The GPU is no longer showing up in "lspci", or "lshw -C video", it's just gone. Looking at the kernel log, when it's loading all of the pcie slots, it just skips the part where it loads the GPU. In earlier logs I can see the order of the pcie slots being loaded, it was very consistent. In recent logs, its in the same order, before and after, except for the part where the GPU pcie would load, and it's just not there anymore, no error, it's as if it wasn't even plugged in. I desperately hope it's not bricked, I don't have the money to replace it likes its nothing, my laptop is so new. Is there any hope? How should I even begin to troubleshoot this?

Ubuntu 18.04.3
Razer Blade 14"
i7 6700-HQ CPU @ 2.60 GHz
GTX 1060m
16GB RAM

**Comment by SwimmingTiger** [comment]
Try a BIOS reset. If you can do a BIOS update, do it once, which may fix the problem.  It is not necessary to update to the new version. Refreshing with the same version also allows the BIOS settings to be reset.

If you can't find a BIOS file to flash, you can only try resetting it in the BIOS setup interface. The effect is not clear.

In addition, it seems that the Nvidia closed source driver already has a beta version that supports Optimus switching, you can try it.
https://www.linuxuprising.com/2019/08/nvidia-43517-linux-beta-driver-adds.html

**Comment by SwimmingTiger** [comment]
In addition, the final solution is to install Windows and view the status of the Nvidia GPU. If the GPU does not work properly in Windows after resetting the BIOS, you may need to repair it.

**Comment by npip99** [comment]
It didn't work in Windows either, but after 1.5 months of it spending a few days working, a few days not working, and back and forth, it's now pretty stable and working so I guess it's good to go, but something weird on the hardware level broke.
