### ISSUE TITLE
please update README to include pkg-config

### ISSUE THREAD

**Issue by selvidgej** [Bumblebee-Project/Bumblebee#1051]
I ran into issues following the README because when running autoreconf -fi I would receive the error 
`configure.ac:74: error: possibly undefined macro: AC_DEFINE`

In order to not get this error your distro also requires pkg-config to be installed. 
It would be helpful to also add this to the prerequisites portion of the README for anyone else seeing this error.

**Comment by felixdoerre** [comment]
Isn't `pkg-config` already listed as the first entry under "Build Requirements" in the [README](https://github.com/Bumblebee-Project/Bumblebee/blob/master/README.markdown#build-requirements)?

**Comment by selvidgej** [comment]
I have no idea how i missed that... I went and looked for it twice before posting too. Late nights are not good for the brain sometimes
