### ISSUE TITLE
[XORG] (EE) Failed to load module "glx" (module does not exist, 0)

### ISSUE THREAD

**Issue by KibSquib48** [Bumblebee-Project/Bumblebee#1076]
I've been trying to use the optirun command to make sure I set up bumblebee properly but I keep getting this issue and it seems like nobody else has gotten it, or at least github's issue search algorithm isn't being helpful because I don't see any other issue about this exact problem.

I have the official proprietary nvidia drivers installed and I have done everything the installation guide in the wiki says. I have changed the configuration file a bit to fix some other issues I had like "Failed to load module "nvidia" (module does not exist, 0)" and "Failed to load module "mouse" (module does not exist, 0)", if that matters.

**Comment by KibSquib48** [comment]
Closed, I've reinstalled the OS a few hours after this post as something unrelated was messed up and I'm no longer trying to install bumblebee at the moment

**Comment by nm17** [comment]
Did you figure it out in the end?

**Comment by KibSquib48** [comment]
> Did you figure it out in the end?

sadly no

**Comment by DavidGriffith** [comment]
I'm currently having this problem after slogging through #920 to solve the problems of `Failed to load module "mouse" (module does not exist, 0)"`.  Is anyone still working on weird problems like these?
