### ISSUE TITLE
Nvidia antialiasing

### ISSUE THREAD

**Issue by dariomadeo** [Bumblebee-Project/Bumblebee#296]
Hi all,

I'm enjoying bumblebee a lot in the last month (most important thing, I get my VirtualBox use Nvidia acceleration for playing :D ).
I really appreciate the work done!
I have a question... when I change nvidia antialiasing settings nothing change, same video quality.
How can I get thru this?
Thanx in advance! ! !

**Comment by kubriel** [comment]
i think VGL_SAMPLES variable is not affecting rendering here on debian jessie

./glsanity-bbee
Checking native (usually Mesa/i965) GL
Running 64-bit tests
info:  libGL.so.1:    loaded from: /usr/lib/x86_64-linux-gnu/libGL.so.1
info:  libGL.so.1:    symlink to: /usr/lib/mesa-diverted/x86_64-linux-gnu/libGL.so.1.2.0
info:  X display:    :0.0
info:  X Ext. "GLX":    present
info:  X Ext. "NV-GLX":    not present; OK for non-nVidia drivers
info:  GLX server:    SGI
info:  GLX client:    Mesa Project and SGI
info:  GL vendor:    Intel Open Source Technology Center
info:  GL renderer:    Mesa DRI Intel(R) Haswell Mobile
info:  GL version:    3.0 Mesa 10.3.2
Checking secondary (usually NVIDIA) GL
Running 64-bit tests
info:  libGL.so.1:    loaded from: /usr/lib/x86_64-linux-gnu/nvidia/libGL.so.1
info:  libGL.so.1:    symlink to: /usr/lib/x86_64-linux-gnu/nvidia/current/libGL.so.340.65
info:  X display:    :8
info:  X Ext. "GLX":    present
info:  X Ext. "NV-GLX":    present
info:  GLX server:    NVIDIA Corporation
info:  GLX client:    NVIDIA Corporation
info:  GL vendor:    NVIDIA Corporation
info:  GL renderer:    GeForce 840M/PCIe/SSE2
info:  GL version:    4.4.0 NVIDIA 340.65
Testing offloading with primus
Running 64-bit tests
info:  libGL.so.1:    loaded from: /usr/lib/x86_64-linux-gnu/primus/libGL.so.1
info:  X display:    :0.0
info:  X Ext. "GLX":    present
info:  X Ext. "NV-GLX":    not present; OK for non-nVidia drivers
info:  GLX server:    NVIDIA Corporation
info:  GLX client:    primus
info:  GL vendor:    NVIDIA Corporation
info:  GL renderer:    GeForce 840M/PCIe/SSE2
info:  GL version:    4.4.0 NVIDIA 340.65


baseboard-manufacturer: Acer
baseboard-product-name: EA50_HWS
baseboard-version     : V1.01
system-manufacturer   : Acer
system-product-name   : Aspire E5-572G
system-version        : V1.01
bios-vendor           : Insyde Corp.
bios-version          : V1.01
bios-release-date     : 05/30/2014

Debian GNU/Linux 8 \n \l
3.16.0-4-amd64 

http://kubriel.servus.at/uploads/bumblebee-bugreport-20160123_190627.tar.gz
