### ISSUE TITLE
Asus N53sv triple monitor setup

### ISSUE THREAD

**Issue by dazzlersa** [Bumblebee-Project/Bumblebee#352]
Hi

I have followed the wiki guide to a tee, but when i type the optirun command to start optimusstart.sh it doesnt do anythine, until i press control+c to end it.

The syslog shows the following:
Mar  7 11:03:22 darryl-lap kernel: [  445.441718] bbswitch: enabling discrete graphics
Mar  7 11:03:22 darryl-lap kernel: [  445.830207] pci 0000:01:00.0: >power state changed by ACPI to D0
Mar  7 11:03:22 darryl-lap kernel: [  445.830226] pci 0000:01:00.0: >power state changed by ACPI to D0
Mar  7 11:03:22 darryl-lap kernel: [  445.830319] pci 0000:01:00.0: >power state changed by ACPI to D0
Mar  7 11:03:22 darryl-lap kernel: [  445.830327] pci 0000:01:00.0: >power state changed by ACPI to D0
Mar  7 11:03:22 darryl-lap kernel: [  445.851240] nvidia 0000:01:00.0: >power state changed by ACPI to D0
Mar  7 11:03:22 darryl-lap kernel: [  445.851246] nvidia 0000:01:00.0: >power state changed by ACPI to D0
Mar  7 11:03:22 darryl-lap kernel: [  445.851261] vgaarb: device changed decodes: PCI:0000:01:00.0,olddecodes=none,decodes=none:owns=none
Mar  7 11:03:22 darryl-lap kernel: [  445.851348] NVRM: loading NVIDIA UNIX x86_64 Kernel Module  304.64  Tue Oct 30 10:58:20 PDT 2012
Mar  7 11:03:22 darryl-lap acpid: client 2866[0:1001] has disconnected
Mar  7 11:03:22 darryl-lap acpid: client 2866[0:1001] has disconnected
Mar  7 11:03:22 darryl-lap acpid: client connected from 2893[0:1001]
Mar  7 11:03:22 darryl-lap acpid: 1 client rule loaded
Mar  7 11:03:23 darryl-lap acpid: client connected from 2893[0:1001]
Mar  7 11:03:23 darryl-lap acpid: 1 client rule loaded
Mar  7 11:03:23 darryl-lap bumblebeed[1346]: [XORG] (WW) Hotplugging is on, devices using drivers 'kbd', 'mouse' or 'vmmouse' will be disabled.
Mar  7 11:03:23 darryl-lap bumblebeed[1346]: [XORG] (WW) Disabling Keyboard0
Mar  7 11:03:23 darryl-lap bumblebeed[1346]: [XORG] (WW) Disabling Mouse0
Mar  7 11:03:23 darryl-lap bumblebeed[1346]: [XORG] (WW) evdev: Microsoft Microsoft® 2.4GHz Transceiver v6.0: ignoring absolute axes.
Mar  7 11:03:23 darryl-lap bumblebeed[1346]: [XORG] (WW) evdev: Microsoft Microsoft® 2.4GHz Transceiver v6.0: ignoring absolute axes.
Mar  7 11:03:23 darryl-lap bumblebeed[1346]: [XORG] (EE) synaptics: ETPS/2 Elantech Touchpad: Synaptics driver unable to detect protocol
Mar  7 11:03:23 darryl-lap bumblebeed[1346]: [XORG] (EE) PreInit returned 11 for "ETPS/2 Elantech Touchpad"

Anyone able to help?

**Comment by ArchangeGabriel** [comment]
This report is three years old and has nothings relevant in it. I’m closing, in the event you still have an issue, please open a new bug describing it properly.
