### ISSUE TITLE
Optirun <application> not showing erros on logs but also not appearing in the external monitor

### ISSUE THREAD

**Issue by armaduarte** [Bumblebee-Project/Bumblebee#362]
Hi All,

Distro: Kali Linux (Kali GNU/Linux 1.0 \n \l)
Kernel: Linux Merovingian 3.7-trunk-amd64 #1 SMP Debian 3.7.2-0+kali6 x86_64 GNU/Linux
Manufacter and Model: 
baseboard-manufacturer: Dell Inc.
baseboard-product-name: 0MY6GN
baseboard-version     : A00
system-manufacturer   : Dell Inc.         
system-product-name   : Dell System XPS L502X
system-version        : Not Specified
bios-vendor           : Dell Inc.         
bios-version          : A10
bios-release-date     : 02/20/2012

BumbleBee Version: optirun (Bumblebee) 3.0.1
BumbleBee BugReport: https://www.dropbox.com/s/10qisr77wmh57as/bumblebee-bugreport-20130318_112924.tar.gz

The Problem:
I've successfully installed the nVidia driver (version 304 that supports my GT 540M) using DKMS. I've used the guidelines from here: http://wiki.debian.org/NvidiaGraphicsDrivers

Then I've installed BumbleBee successfully using the guidelines from here: http://wiki.debian.org/Bumblebee

I'm able to run optirun and it uses my nVidia card as displayed in the output (shortened) from the command: optirun glxgears -info:

GL_RENDERER   = GeForce GT 540M/PCIe/SSE2
GL_VERSION    = 4.2.0 NVIDIA 304.64
GL_VENDOR     = NVIDIA Corporation

I don't want nVidia to start in boot time, I just need to open applications in my external monitor, so I did everything from here (extra screen part) https://github.com/Bumblebee-Project/Bumblebee/wiki/Multi-monitor-setup

Then, it seems to run fine, I do "optirun true", then export the DISPLAY to :8 as said in the link above but... nothing appears in my external monitor.

Here's the optirun output:
6554 frames in 5.0 seconds = 1310.668 FPS

And the /var/log/Xorg.8.log when I add the HDMI device:
[  2416.174] (II) NVIDIA(GPU-0): Display (SUN X7200A (DFP-0)) does not support NVIDIA 3D Vision
[  2416.174] (II) NVIDIA(GPU-0):     stereo.

I'm asking your help because my problem seems different. I don't have any error message in any logs so it's complicated to debug. And my problem didn't seems to fit in any "problem report" that I have read.

Please help me.

**Comment by ArchangeGabriel** [comment]
This report is three years old… I’m closing, in the event you still have an issue with this, fell free to reopen.
