### ISSUE TITLE
Bumblebee 3.2: Screen 0 deleted because of no matching config section

### ISSUE THREAD

**Issue by hotice** [Bumblebee-Project/Bumblebee#397]
After upgrading to Bumblebee 3.2 from the testing PPA (I'm using Ubuntu 13.04, nvidia-310), Bumblebee stopped working. I've checked the config files and everything seems to be ok.

Here's what I get when running optirun -vv:

andrei@ubuntu-desktop:~$ optirun -vv bumblebee
[  197.063630] [DEBUG]Reading file: /etc/bumblebee/bumblebee.conf
[  197.064420] [INFO]Configured driver: nvidia
[  197.064734] [DEBUG]optirun version 3.2 starting...
[  197.064758] [DEBUG]Active configuration:
[  197.064768] [DEBUG] bumblebeed config file: /etc/bumblebee/bumblebee.conf
[  197.064778] [DEBUG] X display: :8
[  197.064787] [DEBUG] LD_LIBRARY_PATH: /usr/lib/nvidia-310:/usr/lib32/nvidia-310
[  197.064798] [DEBUG] Socket path: /var/run/bumblebee.socket
[  197.064807] [DEBUG] Accel/display bridge: auto
[  197.064816] [DEBUG] VGL Compression: proxy
[  197.064825] [DEBUG] VGLrun extra options: 
[  197.064834] [DEBUG] Primus LD Path: /usr/lib/x86_64-linux-gnu/primus:/usr/lib/i386-linux-gnu/primus
[  197.064864] [DEBUG]Using auto-detected bridge primus
[  197.466915] [INFO]Response: No - error: [XORG](EE) Screen 0 deleted because of no matching config section.

[  197.466929] [ERROR]Cannot access secondary GPU - error: [XORG](EE) Screen 0 deleted because of no matching config section.

[  197.466933] [DEBUG]Socket closed.
[  197.466945] [ERROR]Aborting because fallback start is disabled.
[  197.466948] [DEBUG]Killing all remaining processes.

Edit: duplicate, I have no idea how I didn't see the original report, sorry :)

**Comment by mrdimfox** [comment]
Sorry @hotice, but where are you found the the answer?
