### ISSUE TITLE
[VGL] ERROR: Could not open display :8 if a program forks and exits optirun

### ISSUE THREAD

**Issue by isness** [Bumblebee-Project/Bumblebee#42]
Hello,

Today I got bumblebee updated to v3.0 and there seems to be a problem. Although optirun works for simple apps like glxgears and so on, I got trouble running some games with wine. I get this this error "[VGL] ERROR: Could not open display :8.". Other minor wine apps work with optirun just fine. Power management also seems to be working now. My laptop is Dell Inspiron N5110
Xorg.8.log: http://pastebin.com/CFJLbyFU
syslog: http://pastebin.com/HvUEvp8Q

```
uname -a: 3.2.0-10-generic-pae #17-Ubuntu SMP Thu Jan 19 21:44:50 UTC 2012 i686 i686 i386 GNU/Linux
```

Thank you.

**Comment by jleclanche** [comment]
@ArchangeGabriel Really? I'm having the same issue with `primusrun`

**Comment by ArchangeGabriel** [comment]
@jleclanche Could you open a new issue stating what does work and what does not while trying all of `optirun -b virtualgl`, `optirun -b primus` and `primusrun` (plus eventually running a shell using all of those and running you application within that shell)? Thanks.

**Comment by sammcj** [comment]
Howdy, This is still an issue even with the latest (24/10/2016) bumblebee.

- NVidia drivers x86_64-367.57
- Fedora 25, all updates applied daily
- Stable kernel 4.8.3-300.fc25
- PCI Device: `01:00.0 3d controller: NVIDIA Corporation Device 134b (rev a2)`
- Xiaomi MI laptop

Error: 

```bash Bumblebee daemon reported: error: [XORG]  (EE) /dev/dri/card0: failed to set DRM interface version 1.4: Permission Denied```

primusrun gives the exact same error.

I have tried the following suggestions:

- Ensuring my user is a member of the 'video' group
- The little zenity script @Lekensteyn wrote
- Updating /etc/bumblebee/xorg.conf.nvidia to add the 'Screen' section
- Disabling power saving and setting KeepUnusedXServer to true
- Tried running an application as the root user itself
- Trying another driver version

Interesting part:

as some others have mentioned, dmesg shows ACPI Warnings about 

```bash
\_SB.PCI0.RP01.PXSX._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20160422/nsarguments-95)

vgaarb: this pci device is not a vga device
```

To me, it looks like ACPI is looking at the wrong PCI address, or the wrong identifier (if thats the correct term for the last digit i.e. .0 or .1 on a PCI address?

**Comment by Lekensteyn** [comment]
@sammcj the last digit of a PCI address is called a function. **If** you have an Optimus laptop with multiple GPUs, please check with your distro documentation on properly installing/configuring Bumblebee.
