### ISSUE TITLE
[Nvidia driver Debian Experimental]Could not load GPU Driver

### ISSUE THREAD

**Issue by Bulbyzarr** [Bumblebee-Project/Bumblebee#452]
Hi guys,

I have a problem when i want to launch bumblebee with the experimental driver from debian (version 319.32)
- Kernel 3.10.1 + Nvidia 304.88 works without problem
- Kernel 3.10.1 + Nvidia 319.32 does not works.

When I launch "primusrun glxgears", i have this error :
primus: fatal: Bumblebee daemon reported: error: Could not load GPU driver

I found that the module name are differents between both versions :
- Kernel 3.10.3 + Nvidia 304.88 => nvidia.ko
- Kernel 3.10.3 + Nvidia 319.32 => nvidia-current.ko

in "/lib/modules/3.10-1-amd64/updates/dkms"

So, in "/etc/bumblebee/bumblebee.conf", i replace "KernelDriver=nvidia" by "KernelDriver=nvidia-current" OR  "KernelDriver=nvidia_current" and restart bumblebee, i have always this error.

Thanks,
Max

**Comment by sebastianlacuesta** [comment]
Hola,

sebastianlacuesta@gmail.com quiere seguirte.

****** ¿Es sebastianlacuesta@gmail.com tu amiga? ******
Sí: http://invites.flipmailer.com/signup_e.html?fullname=Bumblebee-project/bumblebee&amp;email=reply@reply.github.com&amp;invitername=Sebastián&amp;inviterid=14074416&amp;userid=0&amp;token=0&amp;emailmasterid=968bac8b-c349-4d4e-910a-9bcbe39f337a&amp;from=sebastianlacuesta@gmail.com&src=txt_yes

No: http://invites.flipmailer.com/signup_e.html?fullname=Bumblebee-project/bumblebee&amp;email=reply@reply.github.com&amp;invitername=Sebastián&amp;inviterid=14074416&amp;userid=0&amp;token=0&amp;emailmasterid=968bac8b-c349-4d4e-910a-9bcbe39f337a&amp;from=sebastianlacuesta@gmail.com&src=txt_no







Haz clic aquí para eliminarte de estos correos electrónicos
http://invites.flipmailer.com/uns_inviter.jsp?email=reply@reply.github.com&amp;iid=968bac8b-c349-4d4e-910a-9bcbe39f337a&amp;from=sebastianlacuesta@gmail.com

**Comment by sebastianlacuesta** [comment]
Hola,

sebastianlacuesta@gmail.com quiere seguirte.

****** ¿Es sebastianlacuesta@gmail.com tu amiga? ******
Sí: http://invites.infoaxe.net/signup_e.html?fullname=Bumblebee-project/bumblebee&amp;email=reply@reply.github.com&amp;invitername=Sebastián&amp;inviterid=14074416&amp;userid=0&amp;token=0&amp;emailmasterid=6b000758-d3db-42e8-8a3b-34f3ad1bcfd0&amp;from=sebastianlacuesta@gmail.com&src=txt_yes

No: http://invites.infoaxe.net/signup_e.html?fullname=Bumblebee-project/bumblebee&amp;email=reply@reply.github.com&amp;invitername=Sebastián&amp;inviterid=14074416&amp;userid=0&amp;token=0&amp;emailmasterid=6b000758-d3db-42e8-8a3b-34f3ad1bcfd0&amp;from=sebastianlacuesta@gmail.com&src=txt_no







Haz clic aquí para eliminarte de estos correos electrónicos
http://invites.infoaxe.net/uns_inviter.jsp?email=reply@reply.github.com&amp;iid=6b000758-d3db-42e8-8a3b-34f3ad1bcfd0&amp;from=sebastianlacuesta@gmail.com

**Comment by sebastianlacuesta** [comment]
Hola,

sebastianlacuesta@gmail.com quiere seguirte.

****** ¿Es sebastianlacuesta@gmail.com tu amiga? ******
Sí: http://invites.flipmailer.com/signup_e.html?fullname=Bumblebee-project/bumblebee&amp;email=reply@reply.github.com&amp;invitername=Sebastián&amp;inviterid=14074416&amp;userid=0&amp;token=0&amp;emailmasterid=88cd18c4-7fce-4da8-b990-b8c3223990b6&amp;from=sebastianlacuesta@gmail.com&amp;template=invite_reminder_2_b&src=txt_yes

No: http://invites.flipmailer.com/signup_e.html?fullname=Bumblebee-project/bumblebee&amp;email=reply@reply.github.com&amp;invitername=Sebastián&amp;inviterid=14074416&amp;userid=0&amp;token=0&amp;emailmasterid=88cd18c4-7fce-4da8-b990-b8c3223990b6&amp;from=sebastianlacuesta@gmail.com&amp;template=invite_reminder_2_b&src=txt_no







Haz clic aquí para eliminarte de estos correos electrónicos
http://invites.flipmailer.com/uns_inviter.jsp?email=reply@reply.github.com&amp;iid=88cd18c4-7fce-4da8-b990-b8c3223990b6&amp;from=sebastianlacuesta@gmail.com

**Comment by sebastianlacuesta** [comment]
Hola,

sebastianlacuesta@gmail.com quiere seguirte.

****** ¿Es sebastianlacuesta@gmail.com tu amiga? ******
Sí: http://invites.flipmailer.com/signup_e.html?fullname=Bumblebee-project/bumblebee&amp;email=reply@reply.github.com&amp;invitername=Sebastián&amp;inviterid=14074416&amp;userid=0&amp;token=0&amp;emailmasterid=0c98c6f1-bd37-4be2-be85-50bda1a07150&amp;from=sebastianlacuesta@gmail.com&amp;template=invite_reminder_3_b&src=txt_yes

No: http://invites.flipmailer.com/signup_e.html?fullname=Bumblebee-project/bumblebee&amp;email=reply@reply.github.com&amp;invitername=Sebastián&amp;inviterid=14074416&amp;userid=0&amp;token=0&amp;emailmasterid=0c98c6f1-bd37-4be2-be85-50bda1a07150&amp;from=sebastianlacuesta@gmail.com&amp;template=invite_reminder_3_b&src=txt_no







Haz clic aquí para eliminarte de estos correos electrónicos
http://invites.flipmailer.com/uns_inviter.jsp?email=reply@reply.github.com&amp;iid=0c98c6f1-bd37-4be2-be85-50bda1a07150&amp;from=sebastianlacuesta@gmail.com
