### ISSUE TITLE
Fedora 19, CUDA, nvidia-319

### ISSUE THREAD

**Issue by MrSampson** [Bumblebee-Project/Bumblebee#453]
Howdy,
I'm trying to get CUDA installed on my Fedora 19 Bumblebee system and I've bumped into something I don't know how to get around:

I installed the not-in-the-repository version of bumblebee-nvidia-319 (which CUDA 5.5 requires), and so far that's working well. (I don't usually need to run anything using optirun.)

So, when I try to yum the CUDA pakages, I get 
*******************
$ sudo yum install cuda
Loaded plugins: langpacks, refresh-packagekit
Resolving Dependencies
--> Running transaction check
---> Package cuda.x86_64 0:5.5-22 will be installed
--> Processing Dependency: cuda-5-5 = 5.5-22 for package: cuda-5.5-22.x86_64
--> Running transaction check
---> Package cuda-5-5.x86_64 0:5.5-22 will be installed
--> Processing Dependency: cuda-command-line-tools-5-5 = 5.5-22 for package: cuda-5-5-5.5-22.x86_64
--> Processing Dependency: cuda-headers-5-5 = 5.5-22 for package: cuda-5-5-5.5-22.x86_64
--> Processing Dependency: cuda-documentation-5-5 = 5.5-22 for package: cuda-5-5-5.5-22.x86_64
--> Processing Dependency: cuda-samples-5-5 = 5.5-22 for package: cuda-5-5-5.5-22.x86_64
--> Processing Dependency: cuda-visual-tools-5-5 = 5.5-22 for package: cuda-5-5-5.5-22.x86_64
--> Processing Dependency: cuda-core-libs-5-5 = 5.5-22 for package: cuda-5-5-5.5-22.x86_64
--> Processing Dependency: cuda-license-5-5 = 5.5-22 for package: cuda-5-5-5.5-22.x86_64
--> Processing Dependency: cuda-core-5-5 = 5.5-22 for package: cuda-5-5-5.5-22.x86_64
--> Processing Dependency: cuda-misc-5-5 = 5.5-22 for package: cuda-5-5-5.5-22.x86_64
--> Processing Dependency: cuda-extra-libs-5-5 = 5.5-22 for package: cuda-5-5-5.5-22.x86_64
--> Processing Dependency: xorg-x11-drv-nvidia-devel(x86-32) >= 319.00 for package: cuda-5-5-5.5-22.x86_64
--> Processing Dependency: xorg-x11-drv-nvidia-libs(x86-32) >= 319.00 for package: cuda-5-5-5.5-22.x86_64
--> Processing Dependency: xorg-x11-drv-nvidia-devel(x86-64) >= 319.00 for package: cuda-5-5-5.5-22.x86_64
--> Processing Dependency: nvidia-xconfig >= 319.00 for package: cuda-5-5-5.5-22.x86_64
--> Processing Dependency: cuda-driver >= 319.00 for package: cuda-5-5-5.5-22.x86_64
--> Processing Dependency: nvidia-settings >= 319.00 for package: cuda-5-5-5.5-22.x86_64
--> Processing Dependency: nvidia-modprobe >= 319.00 for package: cuda-5-5-5.5-22.x86_64
--> Running transaction check
---> Package cuda-command-line-tools-5-5.x86_64 0:5.5-22 will be installed
---> Package cuda-core-5-5.x86_64 0:5.5-22 will be installed
---> Package cuda-core-libs-5-5.x86_64 0:5.5-22 will be installed
---> Package cuda-documentation-5-5.x86_64 0:5.5-22 will be installed
---> Package cuda-extra-libs-5-5.x86_64 0:5.5-22 will be installed
---> Package cuda-headers-5-5.x86_64 0:5.5-22 will be installed
---> Package cuda-license-5-5.x86_64 0:5.5-22 will be installed
---> Package cuda-misc-5-5.x86_64 0:5.5-22 will be installed
---> Package cuda-samples-5-5.x86_64 0:5.5-22 will be installed
---> Package cuda-visual-tools-5-5.x86_64 0:5.5-22 will be installed
---> Package nvidia-modprobe.x86_64 0:319.37-1.fc18 will be installed
---> Package nvidia-settings.x86_64 0:319.37-30.fc18 will be installed
---> Package nvidia-xconfig.x86_64 0:319.37-27.fc18 will be installed
---> Package xorg-x11-drv-nvidia.x86_64 1:319.37-2.fc18 will be installed
--> Processing Dependency: xorg-x11-drv-nvidia-libs(x86-64) = 1:319.37-2.fc18 for package: 1:xorg-x11-drv-nvidia-319.37-2.fc18.x86_64
--> Processing Dependency: nvidia-kmod >= 319.37 for package: 1:xorg-x11-drv-nvidia-319.37-2.fc18.x86_64
---> Package xorg-x11-drv-nvidia-devel.i686 1:319.37-2.fc18 will be installed
---> Package xorg-x11-drv-nvidia-devel.x86_64 1:319.37-2.fc18 will be installed
---> Package xorg-x11-drv-nvidia-libs.i686 1:319.37-2.fc18 will be installed
--> Running transaction check
---> Package nvidia-kmod.x86_64 1:319.37-1.fc18 will be installed
---> Package xorg-x11-drv-nvidia-libs.x86_64 1:319.37-2.fc18 will be installed
--> Processing Conflict: bumblebee-nvidia-319.23-1.fc19.x86_64 conflicts xorg-x11-drv-nvidia
--> Processing Conflict: bumblebee-nvidia-319.23-1.fc19.x86_64 conflicts xorg-x11-drv-nvidia-libs
--> Processing Conflict: bumblebee-nvidia-319.23-1.fc19.x86_64 conflicts xorg-x11-drv-nvidia-libs
--> Processing Conflict: bumblebee-nvidia-319.23-1.fc19.x86_64 conflicts nvidia-x11-drv-32bit
--> Processing Conflict: bumblebee-nvidia-319.23-1.fc19.x86_64 conflicts nvidia-x11-drv
--> Processing Conflict: bumblebee-nvidia-319.23-1.fc19.x86_64 conflicts nvidia-settings
--> Processing Conflict: bumblebee-nvidia-319.23-1.fc19.x86_64 conflicts nvidia-xconfig
--> Finished Dependency Resolution
Error: bumblebee-nvidia conflicts with nvidia-settings-319.37-30.fc18.x86_64
Error: bumblebee-nvidia conflicts with 1:xorg-x11-drv-nvidia-libs-319.37-2.fc18.x86_64
Error: bumblebee-nvidia conflicts with 1:xorg-x11-drv-nvidia-libs-319.37-2.fc18.i686
Error: bumblebee-nvidia conflicts with nvidia-xconfig-319.37-27.fc18.x86_64
Error: bumblebee-nvidia conflicts with 1:xorg-x11-drv-nvidia-319.37-2.fc18.x86_64
 You could try using --skip-broken to work around the problem
** Found 2 pre-existing rpmdb problem(s), 'yum check' output follows:
bumblebee-3.2.1-4.fc19.x86_64 is a duplicate with bumblebee-3.2.1-2.fc19.x86_64
***************

I don't know if skipping the broken packages is the right thing here. Is there something else going on with the packaging? Any tips?

Thanks,
Oliver

**Comment by ArchangeGabriel** [comment]
I didn’t read through that issue, but it’s quite old, and since there is already an issue open about Fedora packaging and another about current issue with nvidia specific to Fedora, is still something here usefull or should we close this issue?

**Comment by MrSampson** [comment]
Well, I haven't looked at this in a while, since the need has gone. Fedora 19 is almost EOL anyhow. After I move to Fedora 21, and if the need arises, I'll have a look again. If I can contribute anything worthwhile, and if the problem still exists, I'll open the issue again.
