### ISSUE TITLE
On kernel 3.10 bumblebee will be unable to turn the nvidia card back on or even unexpetedly shutdown the computer

### ISSUE THREAD

**Issue by rechapit** [Bumblebee-Project/Bumblebee#455]
Distro: debian jessie/sid
kernel: Linux ncc-74656-a 3.10-2-amd64 #1 SMP Debian 3.10.5-1 x86_64 GNU/Linux
bumblebee version: 3.2.1
baseboard-manufacturer: ASUSTeK COMPUTER INC.
baseboard-product-name: N56VZ
baseboard-version     : 1.0       
system-manufacturer   : ASUSTeK COMPUTER INC.
system-product-name   : N56VZ
system-version        : 1.0       
bios-vendor           : American Megatrends Inc.
bios-version          : N56VZ.216
bios-release-date     : 12/06/2012

Works perfectly with kernel 3.9.8 but on kernel 3.10.5 the nvidia card will fail to start or computer might shutdown:
Output from /var/log/messages
Aug 12 10:18:13 ncc-74656-a kernel: [  150.039613] bbswitch: enabling discrete graphics
Aug 12 10:18:14 ncc-74656-a kernel: [  150.456339] pci 0000:01:00.0: power state changed by ACPI to D0
Aug 12 10:18:14 ncc-74656-a kernel: [  150.662868] nvidia: module license 'NVIDIA' taints kernel.
Aug 12 10:18:14 ncc-74656-a kernel: [  150.662873] Disabling lock debugging due to kernel taint
Aug 12 10:18:14 ncc-74656-a kernel: [  150.675549] vgaarb: device changed decodes: PCI:0000:01:00.0,olddecodes=io+mem,decodes=none:owns=none
Aug 12 10:18:14 ncc-74656-a kernel: [  150.675655] NVRM: loading NVIDIA UNIX x86_64 Kernel Module  325.15  Wed Jul 31 18:50:56 PDT 2013
Aug 12 10:18:20 ncc-74656-a kernel: [  157.107624] NVRM: GPU at 0000:01:00.0 has fallen off the bus.
Aug 12 10:18:20 ncc-74656-a kernel: [  157.107639] NVRM: os_pci_init_handle: invalid context!
Aug 12 10:18:20 ncc-74656-a kernel: [  157.107642] NVRM: os_pci_init_handle: invalid context!
Aug 12 10:18:20 ncc-74656-a kernel: [  157.107648] NVRM: GPU at 0000:01:00.0 has fallen off the bus.
Aug 12 10:18:20 ncc-74656-a kernel: [  157.107653] NVRM: os_pci_init_handle: invalid context!
Aug 12 10:18:20 ncc-74656-a kernel: [  157.107654] NVRM: os_pci_init_handle: invalid context!
Aug 12 10:18:20 ncc-74656-a kernel: [  157.137672] NVRM: RmInitAdapter failed! (0x25:0x28:1157)
Aug 12 10:18:20 ncc-74656-a kernel: [  157.137683] NVRM: rm_init_adapter(0) failed

Attachment:

- [bumblebee-bugreport-20130812_103716.tar.gz](https://gist.github.com/Lekensteyn/6211401/raw/022c1f410dffc92ba4b34e7657722e2c4696b70d/bumblebee-bugreport-20130812_103716.tar.gz)

**Comment by ArchangeGabriel** [comment]
For information, this is fixed in 3.19 (per this commit https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=commit/?id=74b51ee152b6d99e61ba329799a039453fb9438f), and might be backported to older kernel, but not sure about this.

**Comment by ArchangeGabriel** [comment]
I’m closing this since the fix is normally largely documented and also most recent distro have >=3.19 kernel.

**Comment by Xiaoming94** [comment]
Hello, I am currently running in on this error in kernel 4.12.13 on Arch.

Adding ```rcutree.rcu_idle_gp_delay=1``` Doesn't have any effect and apparetly I don't have the ```/sys/module/rcutree/parameters/rcu_idle_gp_delay``` file. SO the sudo tee method doesn't work Either

**Comment by y-usuzumi** [comment]
I still occasionally run into this issue:
kernel 4.13.5. `rcutree.rcu_idle_gp_delay=1` didn't help.

dmesg:
```
[18454.962751] nvidia-nvlink: Nvlink Core is being initialized, major device number 242
[18454.963239] NVRM: The NVIDIA GPU 0000:01:00.0
               NVRM: (PCI ID: 10de:139b) installed in this system has
               NVRM: fallen off the bus and is not responding to commands.
[18454.963267] nvidia: probe of 0000:01:00.0 failed with error -1
[18454.963286] NVRM: The NVIDIA probe routine failed for 1 device(s).
[18454.963287] NVRM: None of the NVIDIA graphics adapters were initialized!
[18454.963382] nvidia-nvlink: Unregistered the Nvlink Core, major device number 242
```

**Comment by grubshka** [comment]
I'm using 4.19.0.9 and `rcutree.rcu_idle_gp_delay` does not exist anymore.
I tried `rcutree.gp_init_delay=1` and now averything is back !
