### ISSUE TITLE
Optirun & Primusrun performs slower than Intel integrated card

### ISSUE THREAD

**Issue by chrym44** [Bumblebee-Project/Bumblebee#478]
Hi all.

I have SAMSUNG RF 511 S02 laptop with GeForce 540M. I have openSUSE 12.3 with 2 kernels (3.7.10-desktop with default .config and 3.6.11 with my custom .config). Bumblebee works without any errors. I've tried 3 versions of nVIDIA drivers and 3 ways  of installing them:
1. http://smithfarm-thebrain.blogspot.com/2013/03/opensuse-123-how-to-install-bumblebee.html (with 325.15 DKMS proprietary drivers from Overman79 repo)
2. http://forums.opensuse.org/english/get-technical-help-here/how-faq-forums/unreviewed-how-faq/469419-opensuse-12-1-optimus-laptop.html (with G02 packages from NVIDIA openSUSE repo, version 304.88)
3. the hard way (with .run script, version 319.49)

All were successful, however I can't get more than 14 FPS in glxspheres using primusrun & optirun on my 3.7.10 kernel (44 FPS on 3.6.11). Using Intel integrated card I can reach 120 FPS with V-sync off (using vblank_mode=0)

Could you tell me what might be the bottleneck of my discrete graphics?

**Comment by guss77** [comment]
I'm having the same issue on Ubuntu 16.04 64bit with bumblbee 3.2.1 on a Dell E5440 with Optimus GTX 720M:

    $ vblank_mode=0 glxgears
    ATTENTION: default value of option vblank_mode overridden by environment.
    ATTENTION: default value of option vblank_mode overridden by environment.
    37612 frames in 5.0 seconds = 7522.209 FPS
    $ vblank_mode=0 primusrun glxgears
    ATTENTION: default value of option vblank_mode overridden by environment.
    ATTENTION: default value of option vblank_mode overridden by environment.
    ATTENTION: default value of option vblank_mode overridden by environment.
    ATTENTION: default value of option vblank_mode overridden by environment.
    4205 frames in 5.0 seconds = 840.868 FPS

**Comment by karolherbst** [comment]
this is because of pcie overhead, please test with a real benchmark in the future

**Comment by guss77** [comment]
I'm not sure what pcie overhead is and why that causes glxgears to not be a "real benchmark", but I'm no GPU expert so I'll defer to your opinion.

I ran the Unigen Vally benchmark normally (on the Intel IGD) and under primusrun, and here are the results:

[unigen-igd-primus-benchmark.zip](https://github.com/Bumblebee-Project/Bumblebee/files/150481/unigen-igd-primus-benchmark.zip)

The 0910 test is the IGD, with an average 8.0 FPS and the 0914 test is under primusrun with an average 10 FPS. So bumblebee isn't slower than the IGD, but not faster as I would have expected.

**Comment by karolherbst** [comment]
the GTX 720M is just really slow, too. Every Intel Iris GPU will beat it.

**Comment by karolherbst** [comment]
Also PCIe overhead is that bumblebee has to copy the frames over the PCIe bus when using the nvidia gpu and with enough data, the pcie link isn't fast enough to provide the required bandwidth. That's why every high fps benchmarks or high fps OpenGL application will see really bad performance with bumblebee

**Comment by guss77** [comment]
While what you say make sense, I fail to see how it negates the fact that
on Ubuntu 14.04 with the same hardware, I'm getting between 2 times and 3
times better performance on the Nvidia GPU in glxgears and my favorite
games.

-- 
Oded
PSTN/GSM 03.40: +972-54-7340014
SMTP/XMPP: oded@geek.co.il

**Comment by karolherbst** [comment]
do you use primusrun or optirun? primusrun usually performance better and optirun has different options which affect the performance.

It could also be a different issue or something else is funny though.

**Comment by guss77** [comment]
I was using primusrun in the test above.

If there are any tests that you suggest I can run, I'd be glad to do so.

**Comment by ArchangeGabriel** [comment]
@guss77 Consider opening a new issue if you still have issue (rather against https://github.com/amonakov/primus BTW) with performances outside of PCIe bottleneck.
