### ISSUE TITLE
Bumblebee, Screenclone, Asus N53S and a Wacom Cintiq (3 monitor config)

### ISSUE THREAD

**Issue by jlbrewer** [Bumblebee-Project/Bumblebee#489]
One of these things just doesn't belong?

Following the directions at http://blog.linuxacademy.com/linux/ubuntu-bumblebee-optimus-and-multi-monitor-support/ I've been trying to put together a multi-monitor set-up with the following:

* An Asus N53S Laptop
* A standard Samsung monitor, 1920x1080, hooked into the VGA port (left side)
* A Wacom Cintiq 21UX (circa 2005), 1600 x 1200, hooked up to the HDMI port with a DVI-HDMI adapter plug. (right side)
* Ubuntu 12.04.3 with applicable current (both since starting and updated yesterday) drivers and Bumblebee (with the patched Intel driver for screenclone based on 2.20 in x-swat-updates) and Cinnamon (2.0 as of yesterday). Also trying with MATE to rule out possible issues there (Cinnamon uses graphics acceleration, MATE as far as I know does not).

After checking and rechecking my setup and several wild goose chases of theories, I have not been able to get a working setup with all three monitors. I've made the following observations along the way:

* The monitors are being seen and detected by the system and work one at a time, but having the VGA monitor plugged in will switch to VGA output no mater what (though it sometimes won't be seen until rebooting.
* Screenclone has been observed working correctly when only the Cintiq is plugged in (I can tell if I make the virtual display resolution smaller than the screen)
* The Nvidia driver detects the Cintq as a CRT, which I'm not convinced is correct. Enabling Option "ConnectedMonitor" "DFP" in the xorg.conf.nvidia device section doesn't seem to change anything. (However, without giving it DPI settings, it will fail to calculate them on its own.
* Twice, at the login screen, I have seen simultaneous mirrored output on both external monitors. I thought this was impossible given that all the config happens after login. (Other times the Cintiq displays an Out of Range error: after login that changes to No Signal)
* None of the directions I've seen for three-monitor setups have been reported (working or otherwise) on Asus laptops.
* XKCD has the right idea about xorg.conf

I'm out of ideas: if it's possible for this to work at all with this combination of hardware, something may be forcing it to output only one external monitor at a time. I can't find anything obviously wrong in logs or configs even turning on debugging and verbosity.

Pastbin of Xorg.0.log: http://pastebin.com/nvCekMzR

Paste of screenclone script (run from startup-applications at login):

```bash
#!/bin/bash

optirun -vv true && logger screenclone-setup: enabling optirun
sleep 3
xrandr --verbose --output LVDS1 --auto --output VGA1 --auto --left-of LVDS1 --output VIRTUAL --mode 1600x1200 --right-of LVDS1 && logger screenclone-setup: configuring X output
sleep 3
screenclone -d :8 -x 1
```

Refer to the above LinuxAcademy link for their sample bumblebee.conf and xorg.conf.nvidia, which I'm using.

**Comment by ArchangeGabriel** [comment]
This report is almost three years old… I’m closing, in the event you still have an issue with this, fell free to reopen.
