### ISSUE TITLE
Could not Open Nvidia-Settings

### ISSUE THREAD

**Issue by hanynowsky** [Bumblebee-Project/Bumblebee#49]
Updated to version 3.0.

With or without bumblebeed running, I cannot open the Nvidia-settings properly!
On terminal if I type:   optirun nvidia-settings -c :8
I get the message "You do not appear to be using Nvidia drivers...."

Was it disabled in this release?

**Comment by zaxoavoki** [comment]
When I enter `option nvidia-settings -c :8` I get:

```
[ 3300.095298] [ERROR]Cannot access secondary GPU - error: [XORG] (EE) Failed to load module "nvidia" (module does not exist, 0)

[ 3300.095323] [ERROR]Aborting because fallback start is disabled.
```
