### ISSUE TITLE
bumblebeed[1718]: [XORG] (WW) NVIDIA(0): Unable to get display device for DPI computation.

### ISSUE THREAD

**Issue by ghost** [Bumblebee-Project/Bumblebee#497]
I am running Peppermint 3 on my ASUS N53SV. Bumblebee daemon runs fine, optirun seems to be working (tested via optirun glxspheres). Running bumblebeed --debug and optirun --debug returns no errors

BUT, I noticed this line a few times in syslog:
Nov  5 21:59:35 andy-N53SV-Peppermint bumblebeed[1718]: [XORG](WW) NVIDIA(0): Unable to get display device for DPI computation.

I have my laptop connected to an external ASUS monitor via HDMI, and the laptop display is turned off during boot (HDMI monitor is turned on). Could it be due to this?

**Comment by antoniomerlin** [comment]
well my external monitor is connected to HDMI port which is link to my NVIDIA graphic card and i am unable to get any output signal over my external monitor 
`NVIDIA(0): Unable to get display device for DPI computation.`
can anyone please help me to setup my external monitor and also the monitor is connected using a HDMI to DVI converter
