### ISSUE TITLE
Standby issues + kernel soft lockup

### ISSUE THREAD

**Issue by thpar** [Bumblebee-Project/Bumblebee#502]
Bumblebee has worked nicely for a while on my laptop (Alienware m14x) until recently (in hindsight, until I updated to kernel 3.11 probably). I'm using Fedora 19.

When bumblebee-nvidia (319.49-1) is installed, recovering from standy now takes 22s (instead of immediate when it's not installed).

Most of the time, I can run applications with optirun or primusrun, at least until the first time I put the laptop in standby. I haven't found an absolute pattern yet.

Sometimes trying to use optirun causes the error "Cannot access secondary GPU. Server terminated successfully". On other occasions I keep getting this message on regular intervals until I reboot:

    Message from syslogd@atuin at Nov 15 20:29:37 ...
    kernel:[ 6941.316073] BUG: soft lockup - CPU#3 stuck for 22s! [Xorg:4333]

(the 22s probably not by coincidence the time it takes to wake up from standby)

**Comment by ArchangeGabriel** [comment]
Is still issue this here with recent packages?

**Comment by ArchangeGabriel** [comment]
No news for two years, closing. If still a problem, please open a new issue describing the standby issue, if possible with logs.
