### ISSUE TITLE
[Nouveau] Failed to set drm interface version

### ISSUE THREAD

**Issue by fervi** [Bumblebee-Project/Bumblebee#511]
Hello!

Few months ago i use Bumblebee with my Nvidia Geforce 310m and Nouveau Driver

I try to use it again (now) and i can't - i got a error

fervi@ThunderStorm:~$ optirun --debug file-roller
[  749.814721] [DEBUG]optirun version 3.2.1 starting...
[  749.814795] [DEBUG]Active configuration:
[  749.814827] [DEBUG] bumblebeed config file: /etc/bumblebee/bumblebee.conf
[  749.814873] [DEBUG] X display: :8
[  749.814896] [DEBUG] LD_LIBRARY_PATH: 
[  749.814925] [DEBUG] Socket path: /var/run/bumblebee.socket
[  749.814955] [DEBUG] Accel/display bridge: auto
[  749.814983] [DEBUG] VGL Compression: proxy
[  749.815015] [DEBUG] VGLrun extra options: 
[  749.815040] [DEBUG] Primus LD Path: /usr/lib/x86_64-linux-gnu/primus:/usr/lib/i386-linux-gnu/primus:/usr/lib/primus:/usr/lib32/primus
[  749.815101] [DEBUG]Using auto-detected bridge virtualgl
[  749.949348] [INFO]Response: No - error: [XORG](EE) NOUVEAU(0): [drm] failed to set drm interface version.

[  749.949377] [ERROR]Cannot access secondary GPU - error: [XORG](EE) NOUVEAU(0): [drm] failed to set drm interface version.

[  749.949386] [DEBUG]Socket closed.
[  749.949414] [ERROR]Aborting because fallback start is disabled.
[  749.949428] [DEBUG]Killing all remaining processes.

Debian GNU/Linux jessie/sid \n \l

Linux ThunderStorm 3.11-2-amd64 #1 SMP Debian 3.11.10-1 (2013-12-04) x86_64 GNU/Linux

baseboard-manufacturer: ASUSTeK Computer Inc.  
baseboard-product-name: K52Jc
baseboard-version     : 1.0  
system-manufacturer   : ASUSTeK Computer Inc.  
system-product-name   : K52Jc
system-version        : 1.0  
bios-vendor           : American Megatrends Inc.
bios-version          : K52Jc.216
bios-release-date     : 01/25/2011

optirun (Bumblebee) 3.2.1

If you need any information - write here

Thanks for help

**Comment by stuaxo** [comment]
I've got this issue on Ubuntu 15.04 with Nvidia 650M and Nouveau.

I've set the BUSID to ```BusID "PCI:01:00:0"``` and I have nouveau in blacklisted modules.

I'd like to use the Nouveau driver, since historically I have had some many problems with the proprietary driver (IE X doesn't start and spend hours trying to fix).

**Comment by stuaxo** [comment]
Hey @ArchangeGabriel would it be OK to re-open this ?

**Comment by ArchangeGabriel** [comment]
@stuaxo If you still have issues, please open a new bug.
