### ISSUE TITLE
CUDA UVM Module Prevents DGPU Shut Down

### ISSUE THREAD

**Issue by Tanner-Lin** [Bumblebee-Project/Bumblebee#565]
CUDA 6 added a new feature named Unified Virtual Memory, which requires a separate kernel module `nvidia-uvm` that depends on the main driver module. This module is automatically loaded (if not already) when a CUDA/OpenCL context is initiated.

If Bumblebee tries to shut down the DGPU after this happens, the UVM module would block the main NV driver module removal, and the following BBSwitch call would fail as well.

Please add code to handle the UVM module before disabling the main driver module.

**Comment by hypnotoad** [comment]
A workaround until the patched binaries find their way into the distributions:

create an executable file with the following contents and run in once a minute with cron
```
#!/bin/bash

# check if server is running
if ps aux | grep 'Xorg :8' | grep -q -v grep; then
    #echo "Server running, not unloading"
    exit 0
fi

nvmods=`lsmod | grep ^nvidia | cut -d' ' -f 1`

if [ -n "$nvmods" ] ; then
    echo "Unloading nvidia modules" > /dev/kmsg
    for m in $nvmods; do
	#modprobe -r $m
	rmmod $m
    done
fi

if grep ON -q <  /proc/acpi/bbswitch; then
    echo OFF > /proc/acpi/bbswitch
fi
```

**Comment by Garoe** [comment]
In case it is useful for anyone, I took https://github.com/Bumblebee-Project/Bumblebee/pull/618 pull request and I changed it so it would work on Ubuntu 14.04, the code is in https://github.com/Garoe/Bumblebee/tree/patch-1

**Comment by karolherbst** [comment]
same goes for nvidia-modeset now :/, which seems to be loaded like always (even glxinfo does)

**Comment by ArchangeGabriel** [comment]
OK, we need to handle both nvidia_uvm and nvidia_modeset (and in Ubuntu, probably tons of version names).

**Comment by ArchangeGabriel** [comment]
We continue in #719.
