### ISSUE TITLE
Cannot access secondary GPU

### ISSUE THREAD

**Issue by mpeterson2** [Bumblebee-Project/Bumblebee#567]
# Specifications

Distro: `Manjaro`

Kernel: `Linux Michael-Laptop 3.10.33-2-MANJARO #1 SMP Tue Mar 18 23:46:21 UTC 2014 x86_64 GNU/Linux`

Manufacturer and model:

```
baseboard-manufacturer: Micro-Star International Co., Ltd.
baseboard-product-name: MS-1762
baseboard-version     : REV:1.0
system-manufacturer   : Micro-Star International Co., Ltd.
system-product-name   : GT70 0NC/GT70 0NC
system-version        : REV:1.0
bios-vendor           : American Megatrends Inc.
bios-version          : E1762IMS.10C
bios-release-date     : 04/26/2012
```

Bumblebee version: `3.2.1`
# The Problem

When I try to run anything with optirun, or primusrun, I get an error. Here's the output of `optirun -vv glxspheres64`:

```
[ 2036.223216] [DEBUG]Reading file: /etc/bumblebee/bumblebee.conf
[ 2036.223455] [INFO]Configured driver: nvidia
[ 2036.223682] [DEBUG]optirun version 3.2.1 starting...
[ 2036.223698] [DEBUG]Active configuration:
[ 2036.223702] [DEBUG] bumblebeed config file: /etc/bumblebee/bumblebee.conf
[ 2036.223706] [DEBUG] X display: :8
[ 2036.223710] [DEBUG] LD_LIBRARY_PATH: /usr/lib/nvidia:/usr/lib32/nvidia
[ 2036.223714] [DEBUG] Socket path: /var/run/bumblebee.socket
[ 2036.223718] [DEBUG] Accel/display bridge: auto
[ 2036.223722] [DEBUG] VGL Compression: proxy
[ 2036.223726] [DEBUG] VGLrun extra options: 
[ 2036.223729] [DEBUG] Primus LD Path: /usr/lib/primus:/usr/lib32/primus
[ 2036.223757] [DEBUG]Using auto-detected bridge virtualgl
[ 2036.758737] [INFO]Response: No - error: Could not load GPU driver

[ 2036.758752] [ERROR]Cannot access secondary GPU - error: Could not load GPU driver

[ 2036.758757] [DEBUG]Socket closed.
[ 2036.758771] [ERROR]Aborting because fallback start is disabled.
[ 2036.758775] [DEBUG]Killing all remaining processes.
```

Here's the output of `primusrun glxspheres64`

```
primus: fatal: Bumblebee daemon reported: error: Could not load GPU driver
```
# What I've done

I've posted a [thread](http://forum.manjaro.org/index.php?topic=12057.0) on the Manjaro Forums, and they told me to do several things, and it ended up not working, and now I'm posting this bug report.

The first thing I did was follow this [guide](http://forum.manjaro.org/index.php?topic=9107.msg80641#msg80641) which had me reinstall bumblebee for nonfree nvidia. This fixed my first issue, but then I had a second one.

```
[ERROR]Cannot access secondary GPU - error: [XORG] (EE) NVIDIA(0): Failed to assign any connected display devices to X screen 0.
```

Next I edited the file `/etc/bumblebee/xorg.conf.nvidia`. I changed the line `Option "ConnectedMonitor" "DFP"` to be `Option "UseDisplayDevice" "none"`. This fixed the issue for a little bit, and everything worked.

I'm not sure what happened next, because now I'm back to having the first issue again.

Thanks for looking into this.

**Comment by bhashithe** [comment]
@mpeterson2 im having the same problem, my laptop is alsoo overheating. I suspect thats because of the GPU module is not loading correctly. Im going to try and load the other kernel and see
