### ISSUE TITLE
bbswitch always reports ON

### ISSUE THREAD

**Issue by peschkaj** [Bumblebee-Project/Bumblebee#592]
**Distribution:** Arch Linux
**kernel:** `Linux heavy-messing 3.15.4-1-ARCH #1 SMP PREEMPT Mon Jul 7 07:42:54 CEST 2014 x86_64 GNU/Linux`
**Make & Model info:**

```
baseboard-manufacturer: LENOVO
baseboard-product-name: 20BGCTO1WW
baseboard-version     : SDK0E50512 Std
system-manufacturer   : LENOVO
system-product-name   : 20BGCTO1WW
system-version        : ThinkPad W540
bios-vendor           : LENOVO
bios-version          : GNET65WW (2.13 )
bios-release-date     : 06/20/2014
```

**Bumblebee** `optirun (Bumblebee) 3.2.1`

**Problem description**

`cat /proc/acpi/bbswitch` always returns ON.

Immediately after executing `sudo tee /proc/acpi/bbswitch <<<OFF` , `dmesg` shows me the following warning:

```
[ 3485.934313] bbswitch: disabling discrete graphics
[ 3485.934323] ACPI Warning: \_SB_.PCI0.PEG_.VID_._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20140214/nsarguments-95)
```

**Comment by ptrcarta** [comment]
I had to add both acpi_osi=\"!Windows 2013\" and acpi_osi=Linux to have it work on my lenovo W550s (4.1.2-2-ARCH)

**Comment by jdevelop** [comment]
acpi_osi=\"!Windows 2013\" acpi_osi=Linux works fine here in Arch 4.2.3-1-ARCH

thanks for the hint!

**Comment by mmedum** [comment]
@jdevelop @ptrcarta  Do you see any change in your battery life when adding those boot parameters? bbswitch reports the card is off, but im getting the same battery time left on a i3wm installation with a lenovo w550s

**Comment by ptrcarta** [comment]
@mmedum 
Currently I only have acpi=Linux on the kernel command line, as with more recent kernels it seems to be enough
Inspecting power usage with powertop I see that the battery reports an average discharge rate of 8W with /proc/acpi/bbswitch turned off, while I get 10.5W with it turned on. This is with medium brightness and browser open.
I'd say it's working for me. Have you tried powertop?

**Comment by mmedum** [comment]
@ptrcarta 
Nope im using tlp because of the lenovo w550s, and have both parameters. Im still thinking that the new quadro 620M is the culprit here and it not proverly deactivated.

**Comment by ArchangeGabriel** [comment]
This is https://github.com/Bumblebee-Project/bbswitch/issues/112.
