### ISSUE TITLE
ubuntu 14.04 - 3.13.0-30 - nvidia 820M - Asus EB1037

### ISSUE THREAD

**Issue by ant-thomas** [Bumblebee-Project/Bumblebee#593]
I've been having serious issues trying to get the nvidia driver and bumblebee working with my nvidia 820M based optimus system.

The error that seems to dominate is a vbios error

    Jul 14 21:35:21 EB1037 kernel: [  262.835802] vgaarb: this pci device is not a vga device
    Jul 14 21:35:21 EB1037 kernel: [  262.837556] nvidia 0000:01:00.0: irq 113 for MSI/MSI-X
    Jul 14 21:35:21 EB1037 kernel: [  262.844137] NVRM: failed to copy vbios to system memory.
    Jul 14 21:35:21 EB1037 kernel: [  262.845774] NVRM: RmInitAdapter failed! (0x30:0xffffffff:720)
    Jul 14 21:35:21 EB1037 kernel: [  262.845788] NVRM: rm_init_adapter failed for device bearing minor number 0
    Jul 14 21:35:21 EB1037 kernel: [  262.845824] NVRM: nvidia_frontend_open: minor 0, module->open() failed, error -5

The nouveau driver seemed to have a similar problem when enabled and needed to be initially disabled in the grub boot command to get ubuntu to even boot (then blacklisted).

I've tried the patches that have been mentioned for these issues for 331.38 but I've had no success. I have realised though that the 820M doesn't seem to be supported in 331.38 (I could be wrong there, especially since it's a re-badged older nvidia chip).

Using 340.24 unpatched doesn't seem to work either.

I believe I have an EFI/CSM issue here.

Hopefully someone can help with this. Any logs that are required I can post.

This is the nouveau error that causes the boot process to hang:
![eb1037-vbios](https://cloud.githubusercontent.com/assets/1029851/3577490/30dbc680-0b9d-11e4-83ff-10058d89ae96.jpg)

**Comment by ArchangeGabriel** [comment]
I supposed this to be #615 if you’re still affected. Closing as duplicate.
