### ISSUE TITLE
ERROR: Unable to load the kernel module 'nvidia.ko'.

### ISSUE THREAD

**Issue by hevanaa** [Bumblebee-Project/Bumblebee#594]
I have this long-standing problem that the nvidia module compile fails with the bumblebee-nvidia script. My system is MSI GE60 with Nvidia Geforce GTX 660M/2GB. OS is Fedora 20. Bumblebee worked last year, but at some point this problem began, and I stopped using bumblebee. I have since used the Intel GPU only, but I thought to give it a try once more, but I can't really see what the problem is.

Any ideas how to proceed? nvidia-installer.log says (last rows in log file):

[  354.684474] vgaarb: device changed decodes: PCI:0000:01:00.0,olddecodes=none,decodes=none:owns=none
[  354.684494] NVRM: The NVIDIA GPU 0000:01:00.0 (PCI ID: 10de:0fd4)
NVRM: installed in this system is not supported by the 337.25
NVRM: NVIDIA Linux driver release.  Please see 'Appendix
NVRM: A - Supported NVIDIA GPU Products' in this release's
NVRM: README, available on the Linux driver download page
NVRM: at www.nvidia.com.
[  354.684524] nvidia: probe of 0000:01:00.0 failed with error -1
[  354.685304] NVRM: The NVIDIA probe routine failed for 1 device(s).
[  354.685307] NVRM: None of the NVIDIA graphics adapters were initialized!
[  354.685309] [drm] Module unloaded
[  354.685433] NVRM: NVIDIA init module failed!
ERROR: Installation has failed.  Please see the file '/var/log/nvidia-installer.log' for details.  You may find suggestions on fixing installation problems in the README available on the Linux driver download page at www.nvidia.com.

The complete nvidia-installer.log is available at http://paste.fedoraproject.org/118523/31569140

**Comment by ArchangeGabriel** [comment]
@hevanaa: Are you still facing this issue? If so, could you try disabling bbswitch and bumblebee, reboot, and manually load nvidia driver (with modprobe)?

**Comment by hevanaa** [comment]
Well, I got it somehow working by reinstalling a lot of X related stuff and compiling the nvidia driver manually. I think it is some kind of conflict with the system and the nvidia driver. It would probably be resolved by reinstalling the OS. Now it is working with optirun, but primusrun crashes gnome-shell.

**Comment by ArchangeGabriel** [comment]
OK, please report the primusrun crash to primus tracker.
