### ISSUE TITLE
Bumblebee does not activate the "companion" audio device

### ISSUE THREAD

**Issue by floe** [Bumblebee-Project/Bumblebee#599]
In addition to the NVidia graphics controller itself, my laptop also contains an NVidia audio device connected to the HDMI port. However, when starting the machine in Optimus mode, the audio device appears to be hidden and does not show up in lspci, even when bbswitch activates the graphics device. Are there any workarounds regarding the audio device?

**Comment by ArchangeGabriel** [comment]
When you say you have tried with nouveau, did you also try with PRIME (http://nouveau.freedesktop.org/wiki/Optimus/, section Using outputs on discrete GPU)?

**Comment by floe** [comment]
Yes, I've tried that and (as far as I can remember) it didn't have any influence on the audio device.

**Comment by redfudd** [comment]
Hi. It seems i got the same problem and wanted to provide any help, even if i probably can only try anything i am told ...

**Comment by motdef** [comment]
I also have this issue on my Thinkpad T430i. lspci -H 1 doesn't show the audio device once I've toggled bbswitch on but it works fine with Optimus disabled.

**Comment by motdef** [comment]
Is there anything affected users can do to help solve this issue?

**Comment by sherter** [comment]
Same problem on Lenovo T420 (VGA compatible controller: NVIDIA Corporation GF119M [Quadro NVS 4200M]). If someone is able to provide patches, I would love to help test them :wink:

**Comment by ArchangeGabriel** [comment]
People still having this issue, is that also the case for PRIME with recent kernel?

Also, this is potentially related to https://github.com/Bumblebee-Project/bbswitch/issues/18.

**Comment by sherter** [comment]
With PRIME (`xf86-video-nouveau 1.0.12`) I have the same symptoms as @floe (`lspci -H1` _does_ show the audio device, but normal `lspci` doesn't).

```
$ uname-a
Linux simon-t420 4.7.1-1-ARCH #1 SMP PREEMPT Wed Aug 17 08:13:35 CEST 2016 x86_64 GNU/Linux
```

**Comment by Lekensteyn** [comment]
This is not something that Bumblebee can fix, it is up to the drivers. Bug for nouveau is at https://bugs.freedesktop.org/show_bug.cgi?id=75985

**Comment by sherter** [comment]
@Lekensteyn But the audio device _does_ work when I switch to discrete graphics only in BIOS and use the Nvidia driver. So it is not really a Nvidia driver problem, is it?

**Comment by Lekensteyn** [comment]
@sherter The driver must do something special to activate the device. See the linked bug for the needed commands.

**Comment by fheday** [comment]
Sorry for posting on such an old thread.
I have a laptop with the GTX1050 linked to the HDMI port. The audio device only shows up when using  NVidia's 'magic' to make it activate (https://devtalk.nvidia.com/default/topic/1024022/linux/gtx-1060-no-audio-over-hdmi-only-hda-intel-detected-azalia/).
Here is it gets interesting: using bumblebee, I get the same "!!! Unknown header type 7f" that @floe  mentioned, and no audio (also I get severam messages: "snd_hda_codec_hdmi hdaudioC1D0: out of range cmd 0:7:707:ffffffbf" -  I suspect these may be correlated.). Moreover: pulseaudio says that the HDMI output of my Nvidia card is disconnected.
When I disactivate bumblebee and enable OPTIMUS, then I get output in my television and the "!!! Unknown header type 7f" message dissapears.
Reading a bit about the nvidia driver, I've found some information that might be relevant in https://download.nvidia.com/XFree86/gpu-hdmi-audio-document/#_pulseaudio_default_device when they mention probe_mask... 
I hope this can help somehow... My knowledge of linux drivers and audio/video system is not that great, but I thought it would be interesting mentioning (and if you want/need I can help by either testing in my hardware or maybe trying some code).
Thanks
