### ISSUE TITLE
linux mint 17 permission denied

### ISSUE THREAD

**Issue by cjano** [Bumblebee-Project/Bumblebee#609]
i'm getting permission denied each time i run optirun
even after clean installation

$ optirun glxspheres
[ 1417.876995] [ERROR]Cannot access secondary GPU - error: [XORG] (EE) intel(0): [drm] failed to set drm interface version: Permission denied [13].

**Comment by ArchangeGabriel** [comment]
No, you can also get this with NVIDIA. See #580, I’m closing this one as a duplicate.
