### ISSUE TITLE
HDMI 1.4, mini Display-Port 1.2 not detected.

### ISSUE THREAD

**Issue by arithran** [Bumblebee-Project/Bumblebee#610]
My laptop is an MSI GT70 2OC
http://www.msi.com/product/nb/GT70-2OC.html#hero-overview

It is running Fedora 20 and I have installed Bumblebee according to the documentation on the fedora site.
https://fedoraproject.org/wiki/Bumblebee

It has the following external display ports.
- HDMI 1.4 
- mini Display-Port 1.2 
- VGA port

This is the output of `xrandr`

```
eDP1 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 382mm x 215mm
   1920x1080     60.02*+
   1400x1050     59.98  
   1280x1024     60.02  
   1280x960      60.00  
   1024x768      60.00  
   800x600       60.32    56.25  
   640x480       59.94  
VGA1 disconnected (normal left inverted right x axis y axis)
```

Can someone let me know how I can get HDMI and Display Ports working ?

**Comment by ArchangeGabriel** [comment]
@arithran Any news? If it’s still not working, please take a look at AllowEmptyInitialConfiguration in the develop branch commits.

**Comment by arithran** [comment]
I still couldn't get it working , I will try the AllowEmptyInitialConfiguration and let you know, thanks for keeping this active.

**Comment by ArchangeGabriel** [comment]
OK, you might also want to try with PRIME (http://nouveau.freedesktop.org/wiki/Optimus/, Using outputs on discrete GPU).

**Comment by ArchangeGabriel** [comment]
@arithran Hey, any news here?

**Comment by arithran** [comment]
All the outputs are working as of fedora 24
