### ISSUE TITLE
Fedora 21 and bumblebee-nvidia (SELinux)

### ISSUE THREAD

**Issue by MalcolmMielle** [Bumblebee-Project/Bumblebee#619]
Hello !

I switched to Fedora21 and using bumblebee-nvidia yield to the error
```bash
[malcolm@localhost ~]$ optirun glxgears
[13636.585161] [ERROR]Cannot access secondary GPU - error: [XORG] (EE) systemd-logind: failed to get session: PID 18039 does not belong to any known session
[13636.585236] [ERROR]Aborting because fallback start is disabled.
```

A solution I found is to set `setenforce` to 0 but that is not a very handy solution =P.

**Comment by Azrael3000** [comment]
I have the same problem as OP after an f20 -> f21 upgrade.

```
Jan 17 10:46:38 goedel bumblebeed[5897]: [ 1906.913590] [ERROR]X did not start properly
Jan 17 10:46:38 goedel bumblebeed[5897]: [ 1906.913586] [ERROR][XORG] (EE) Server terminated with error (1). Closing log file.
Jan 17 10:46:38 goedel bumblebeed[5897]: [ 1906.913582] [ERROR][XORG] (EE)
Jan 17 10:46:38 goedel bumblebeed[5897]: [ 1906.913578] [ERROR][XORG] (EE) Please also check the log file at "/var/log/Xorg.8.log" for additional information.
Jan 17 10:46:38 goedel bumblebeed[5897]: [ 1906.913572] [ERROR][XORG] (EE)
Jan 17 10:46:38 goedel bumblebeed[5897]: [ 1906.913569] [ERROR][XORG] (EE)
Jan 17 10:46:38 goedel bumblebeed[5897]: [ 1906.913566] [ERROR][XORG] (EE) xf86OpenConsole: Cannot open /dev/tty0 (No such file or directory)
Jan 17 10:46:38 goedel bumblebeed[5897]: [ 1906.913562] [ERROR][XORG] (EE)
Jan 17 10:46:38 goedel bumblebeed[5897]: [ 1906.913556] [ERROR][XORG] (EE) Failed to load module "mouse" (module does not exist, 0)
Jan 17 10:46:38 goedel bumblebeed[5897]: [ 1906.913551] [WARN][XORG] (WW) Warning, couldn't open module mouse
Jan 17 10:46:38 goedel bumblebeed[5897]: [ 1906.913544] [ERROR][XORG] (EE) /dev/dri/card0: failed to set DRM interface version 1.4: Permission denied
Jan 17 10:46:38 goedel bumblebeed[5897]: [ 1906.913526] [ERROR][XORG] (EE) systemd-logind: failed to get session: PID 6241 does not belong to any known session
```

there were 2 selinux warnings at first, and I resolved them using the standard audit2allow. They were both related to xorg. But now I get no more selinux warning but still the same error message plus the above in journalctl. The output of /var/log/Xorg.8.log can be found at http://sprunge.us/PKMF

**Comment by fewspider** [comment]
so sad.today i update 20 to 21.it happen againT_T

**Comment by gsgatlin** [comment]
Thank you for your patience.

The selinux security issues are fixed in bumblebee-nvidia-346.35-3. You can yum update to that version beginning  today. I will update the red hat bugzilla this evening with the troubleshooting technique I used in case it is helpful to other packagers experiencing similar selinux issues on fedora / rhel based distros.

My main laptop here is running enforcing mode and minecraft is working ok with primus.

If using nouveau module instead of nvidia bumblebee-nouveau-1.2.0 is required which is also available beginning any time today.

**Comment by MalcolmMielle** [comment]
So I tried installing bumblebee-nouveau and I got this : 

```
[root@localhost ~]# yum install bumblebee-nouveau
Loaded plugins: langpacks
Resolving Dependencies
--> Running transaction check
---> Package bumblebee-nouveau.noarch 0:1.2.0-1.fc21 will be installed
--> Processing Conflict: bumblebee-nouveau-1.2.0-1.fc21.noarch conflicts xorg-x11-drv-modesetting
--> Finished Dependency Resolution
Error: bumblebee-nouveau conflicts with xorg-x11-drv-modesetting-0.9.0-2.fc21.x86_64
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```
I'm wondering if it means I need to remove something like bumblebee package ?

**Comment by MalcolmMielle** [comment]
So I tried installing bumblebee-nouveau and I got this : 

```
[root@localhost ~]# yum install bumblebee-nouveau
Loaded plugins: langpacks
Resolving Dependencies
--> Running transaction check
---> Package bumblebee-nouveau.noarch 0:1.2.0-1.fc21 will be installed
--> Processing Conflict: bumblebee-nouveau-1.2.0-1.fc21.noarch conflicts xorg-x11-drv-modesetting
--> Finished Dependency Resolution
Error: bumblebee-nouveau conflicts with xorg-x11-drv-modesetting-0.9.0-2.fc21.x86_64
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```
I'm switching to bumblebee-nvidia and I'll tell you how it went.

**Comment by gsgatlin** [comment]
If you have bumblebee-nvidia installed you should not try to install bumblebee-nouveau. (I will add that as a conflict now that I think about it)

If you really want to use bumblebee with the nouveau driver then you have to remove xorg-x11-drv-modesetting rpm because modesetting conflicts with using bumblebee + nouveau. Also, a reboot is required so that the 10-disable_prime.conf file can get loaded by the main X. But I did test it today and it did work on my spare laptop in enforcing mode with nouveau.

**Comment by MalcolmMielle** [comment]
Sorry for the confusion, I meant it like I tried bumble-nouveau without having bumblebee-nvidie first and got this error on install. 

Bumblebee-nvidia is working perfectly fine for now, thanks a lot for your work. I'll check with nouveau if I have the time =)

**Comment by gsgatlin** [comment]
Ok. Great. Glad its working for you now.
