### ISSUE TITLE
possible libdrm issue

### ISSUE THREAD

**Issue by WhiteWolf1776** [Bumblebee-Project/Bumblebee#624]
I recently came up against this same issue on slackware:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=768045

Not sure if it is primus or bumblebee or valve at this point but would appreciate any thoughts you may have on a possible fix. The downgrade does indeed 'fix' this for now... but that can't be a long term solution.

Thanks.

**Comment by ArchangeGabriel** [comment]
Is anyone still having an issue here? If so, please provide Xorg.0.log, Xorg.8.log and dmesg output after reboot+optirun.

**Comment by WhiteWolf1776** [comment]
The updated Nvidia driver 346.35 seems to have corrected the issue, so it was their problem, not bumblebee.  Wasn't sure at the time.

Closing this issue.
