### ISSUE TITLE
Errors in bumblebee status after primus.

### ISSUE THREAD

**Issue by artemjackson** [Bumblebee-Project/Bumblebee#627]
Step1:
```
$ sudo systemctl status bumblebeed
● bumblebeed.service - Bumblebee C Daemon
   Loaded: loaded (/usr/lib/systemd/system/bumblebeed.service; enabled; vendor preset: disabled)
   Active: active (running) since Вт 2015-01-13 13:54:40 MSK; 2s ago
 Main PID: 4988 (bumblebeed)
   CGroup: /system.slice/bumblebeed.service
           └─4988 /usr/bin/bumblebeed

Jan 13 13:54:40 zenbook bumblebeed[4988]: [  867.551692] [INFO]/usr/bin/bumblebeed 3.2.1 started
```

Step2:
```
$ primusrun glxspheres64
Polygons in scene: 62464
Visual ID of window: 0x20
Context is Direct
OpenGL Renderer: GeForce GT 620M/PCIe/SSE2
62.258621 frames/sec - 69.480621 Mpixels/sec
```

Step3:
```
$ sudo systemctl status bumblebeed
● bumblebeed.service - Bumblebee C Daemon
   Loaded: loaded (/usr/lib/systemd/system/bumblebeed.service; enabled; vendor preset: disabled)
   Active: active (running) since Вт 2015-01-13 13:54:40 MSK; 22s ago
 Main PID: 4988 (bumblebeed)
   CGroup: /system.slice/bumblebeed.service
           └─4988 /usr/bin/bumblebeed

Jan 13 13:54:40 zenbook bumblebeed[4988]: [  867.551692] [INFO]/usr/bin/bumblebeed 3.2.1 started
Jan 13 13:54:51 zenbook bumblebeed[4988]: [  878.397311] [ERROR][XORG] (EE) systemd-logind: failed to get session: PID 5003 does not belong to any known session
Jan 13 13:54:51 zenbook bumblebeed[4988]: [  878.397343] [ERROR][XORG] (EE) /dev/dri/card0: failed to set DRM interface version 1.4: Permission denied
Jan 13 13:54:51 zenbook bumblebeed[4988]: [  878.397370] [WARN][XORG] (WW) NVIDIA(0): Unable to get display device for DPI computation.
Jan 13 13:54:51 zenbook bumblebeed[4988]: [  878.397378] [ERROR][XORG] (EE) NVIDIA(0): Failed to initiate mode change.
Jan 13 13:54:51 zenbook bumblebeed[4988]: [  878.397383] [ERROR][XORG] (EE) NVIDIA(0): Failed to complete mode change
Jan 13 13:54:51 zenbook bumblebeed[4988]: [  878.397404] [ERROR][XORG] (EE) /dev/dri/card0: failed to set DRM interface version 1.4: Permission denied
Jan 13 13:54:54 zenbook bumblebeed[4988]: [  881.936926] [ERROR][XORG] (EE) Server terminated successfully (0). Closing log file.
```

All application still work with primusrun in spite of errors in status.
So, is such status ok or  wrong?

**Comment by ArchangeGabriel** [comment]
All of those are errors reported by xorg as you can see, and they are all harmless (except maybe the mode change that I’ve never seen before).

The first one is because of rootless X.
The DRM error is because the NVIDIA card is handled by nvidia instead of a xf86 driver I think.
The DPI warning is obviously because you don’t have any screen wired to the card.
The closing at the end is normal.

The NVIDIA mode changes are unknown to me, the whole log would be usefull to get more infos about them.

**Comment by artemjackson** [comment]
Thank you again, ArchangeGabriel !
How can I get whole log?

**Comment by ArchangeGabriel** [comment]
It’s there: /var/log/Xorg.8.log.

**Comment by artemjackson** [comment]
You are welcome.
logs on the step 1: https://gist.github.com/artemjackson/b0b6cf58fed14f0406e8
logs on the step 3: https://gist.github.com/artemjackson/cac792ae595a013289d4

**Comment by ArchangeGabriel** [comment]
You’re not having those errors anymore. If they ever appear again (can check this with `grep EE /var/log/Xorg.8.log` after having run something with optirun), please report the file.

**Comment by excieve** [comment]
Having this too. Doesn't seem to be causing any visible troubles though.
Here's the log: https://gist.github.com/excieve/b1dfc678366d5bc95046
/dev/dri/card0 (which has this permission error) is really the Intel card. Not sure why is it trying to do anything to it.
