### ISSUE TITLE
Numlock not working after primusrun

### ISSUE THREAD

**Issue by pando85** [Bumblebee-Project/Bumblebee#629]
It's similar to [#470](https://github.com/Bumblebee-Project/Bumblebee/issues/470).
When I launch one program with primusrun my numlock stop working correctly. 
*I press it and can't lock it. 
*If I press caps lock my numlock becomes active.
*When I stop primusrun program the problem dissapear.
```bash
$ uname -a
Linux ***** 3.18.3-1-MANJARO #1 SMP PREEMPT Fri Jan 16 21:08:54 UTC 2015 x86_64 GNU/Linux
```
My laptop is Lenovo Z50 series.

**Comment by ArchangeGabriel** [comment]
Sorry for the delay, been busy for last three weeks.

We should just keep the discussion on #470. I’m closing this one and re-opening the other one, please go through it and report the result of the asked test cases.
