### ISSUE TITLE
Bumblebee/bbswitch issues with kernel 3.19.x

### ISSUE THREAD

**Issue by akien-mga** [Bumblebee-Project/Bumblebee#632]
Since I updated my system to kernel 3.19.0, I'm having unpredictable issues with bumblebee/bbswitch.
Sometimes calling ```optirun -b virtualgl glxspheres64``` instantly freezes the laptop (same with primus BTW), and sometimes it works, but the card won't get turned off once glxspheres64 (or any other application for that matter) stops using it.

It works fine with 3.18.3, and the bbswitch dkms module builds fine against both kernels. I have nvidia 346.35 modules for both kernels, and my bumblebee package [1] used to work fine since I created it (against kernel 3.12 at that time).

I don't know if the problem is related to bumblebee or bbswitch (or a kernel regression, for that matter). I've already found some warnings about bbswitch reported in Bumblebee-Project/bbswitch/issues/106.

I'll post some logs that correspond to a session where I booted, ran ```optirun -b virtualgl glxspheres``` and got a hard freeze forcing me to shutdown.

[1] http://svnweb.mageia.org/packages/cauldron/bumblebee/current/SPECS/bumblebee.spec?view=markup

**Comment by akien-mga** [comment]
- /var/log/dmesg: https://framalab.org/zerobin/?f6516a16351059cd#2+NHFJoCJydEMgtZPuqT05rkYzpI8QPzx/5KIDrw7R8=
- /var/log/Xorg.0.log: https://framalab.org/zerobin/?3457b235e3ed2d7b#4RW/TKtNYTWfVqiaB7rLF+qTgcN27MjyLBCZnOcbdtA=
- /var/log/Xorg.8.log: https://framalab.org/zerobin/?97ca525c1824eaf2#0oFOKf6XprloB3vJdPRkvLUDRUcGGLNNOFlpyWUHTao=
- /var/log/syslog (trimmed to the relevant part): https://framalab.org/zerobin/?29449a9bd7e2333b#mr5BbGQJMi27bstsdHuD0K1hl5cm03+P5Gb1VEPZRDk=

**Comment by akien-mga** [comment]
I also opened a bug report at Mageia's: https://bugs.mageia.org/show_bug.cgi?id=15288

**Comment by amonakov** [comment]
Your configuration looks very unusual. Normally nouveau kernel module is blacklisted, and nvidia kernel module is not loaded before bbswitch. In your syslog, both nouveau and nvidia modules are loaded before bumblebee loads bbswitch. I don't know what specifically can trigger freezes, but your situation is a minefield, so I strongly recommend you to look into why modules are loaded automatically rather than through optirun/bumblebeed, and fix that.

**Comment by ArchangeGabriel** [comment]
As @amonakov said, the problem is on your side, you shouldn’t have nouveau and/or nvidia loaded without bumblebee asking for this. I’m closing this issue, since it’s not something on our side, but feel free to ask for support if something isn’t clear.

**Comment by akien-mga** [comment]
I've blacklisted nouveau and nvidia, and the hard freezes are fixed (or at least I haven't experienced them since I added the blacklisting instructions). I used:
```
$ cat /etc/modprobe.d/bumblebee.conf 
blacklist nvidia-current
blacklist nouveau
```
I'm still puzzled as to why it uses to work without blacklisting with all kernels from 3.10 to 3.18, but no longer with 3.19, but at least, it's working again :)


Now, I still have a big issue with bumblebee or bbswitch: after I've used bumblebee once, the nvidia GPU stays ON and can't be powered off, even though the processes that were using it are properly terminated:

```
# tee /proc/acpi/bbswitch <<<OFF
OFF
# cat /proc/acpi/bbswitch 
0000:01:00.0 ON
```

In dmesg, I get:
```
[23836.737763] bbswitch: device 0000:01:00.0 is in use by driver 'nvidia', refusing OFF
```

**Comment by ArchangeGabriel** [comment]
Can you post the following logs after a reboot plus twice optirun something?

dmesg
/var/log/Xorg.0.log
/var/log/Xorg.8.log
/var/log/Xorg.8.log.old

Please use gist or pastebin for the logs.

**Comment by akien-mga** [comment]
Here are the logs. I did: reboot, ```optirun -b glxspheres64```, checked that /proc/acpi/bbswitch was still on "ON" after glxspheres64 was stopped, tried to tee "OFF", then ran ```optirun -b glxspheres64``` again.

* dmesg: https://framalab.org/zerobin/?dca1490a9c138ea7#h9SbQ/gggW9+55onn6Qbqxl1Q/J65+dOQu8LssOX5bw=
* /var/log/Xorg.0.log: https://framalab.org/zerobin/?4018650c67d44fab#trEk/X+XDMmeQBBWHd9q2WWYzylM2t+bEY2y2+Ot9tQ=
* /var/log/Xorg.8.log: https://framalab.org/zerobin/?8b39f704a4cdc58e#G4xFlb5tnjAwdoJi7ok5Z3hcYUaiwwB4tDxkkcAqgY4=
* /var/log/Xorg.8.log.old: https://framalab.org/zerobin/?ccbfde9a546f7c1a#Y+3+z5Yj26MKv9/2JGGbXB5GrkQHfEsin4Ll/NPKJyg=

**Comment by akien-mga** [comment]
Also valid with kernel 3.19.1.

**Comment by akien-mga** [comment]
Still valid with kernel 3.19.8 for that matter, I haven't tested 4.x yet.

**Comment by f4th0m** [comment]
Hello,

I have a similar problem on my Thinkpad yoga 14. (geforce 940m).
It works on first boot, but after first sleep, it stops to work.
Optirun results in the following:
[249247.189597] [ERROR]Cannot access secondary GPU - error: Could not load GPU driver

[249247.189639] [ERROR]Aborting because fallback start is disabled.

dmesg and xorg logs attached.

**Comment by akien-mga** [comment]
We finally found a solution for Mageia by enhancing /etc/modprobe.d/bumblebee.conf to take into account the naming difference between Mageia's "nvidia-current" driver and the "nvidia" that bumblebee expects.

I have no clue why it was working fine before kernel 3.19.x, but well :)
