### ISSUE TITLE
Fedora 21 not booting after installing bumblebee-nvidia

### ISSUE THREAD

**Issue by rudrab** [Bumblebee-Project/Bumblebee#633]
I used to have bumblebee-nvidia for more than 2 years now and even used it in f21. But after a recent reinstall, I cant boot my machine anymore.

After installation and reboot, it gives error like
nvidia-tls no such file or directory
 and something about XPCOM

Dell Inc.
baseboard-product-name: 0MY6GN
baseboard-version     : A00
system-manufacturer   : Dell Inc.         
system-product-name   : Dell System XPS L502X
system-version        : Not Specified
bios-vendor           : Dell Inc.         
bios-version          : A12
bios-release-date     : 09/07/2012

Linux roddur 3.18.5-201.fc21.x86_64 #1 SMP Mon Feb 2 21:00:58 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by rudrab** [comment]
https://drive.google.com/file/d/0B02WblgE6NEvTmVuNHh1OUlaMms/view?usp=sharing 
is the `journalctl -b` output

**Comment by gsgatlin** [comment]
@rudrab sorry for delay in getting back to you. Yeah, there is something going on with multilib. Try removing bumblebee-nvidia for now. I'm working on trying to figure out something in the shell script. Please see #634 also. I should have something to test late today I would think...

**Comment by rudrab** [comment]
@gsgatlin  Thanks for your reply.
I have actually installed it as given it http://fedoraproject.org/wiki/Bumblebee. 
I don't know how, but right now, I have installed bumblebee-nvidia-340 (dated 15/01/2015) and everything is working fine. Its the 346 thats creating problem.
Hope, this will help.

**Comment by ArchangeGabriel** [comment]
Isn’t it #619 again? Even if the 340/346 change helps, it could be related.

**Comment by gsgatlin** [comment]
Sorry. I did not have time to post it yet.

This is fixed in bumblebee-nvidia-346.35-3. You can upgrade beginning any time today. You may need to run

yum clean all

or

dnf clean all

to see the new package. Thanks so much for the bug report.

**Comment by ArchangeGabriel** [comment]
Oh, nice, thanks. For reference, what was changed and how have you fixed it?

(Closing this also)

**Comment by ArchangeGabriel** [comment]
Also, gsgatlin, I’ve invited you to the project organization, this way I will be able to assign you Fedora/RPM packaging issue, and you might create bumblebee-RPM repo on the project page to add your packaging scripts and keep track of their evolution, plus let anyone who want to contribute, and also specific issues might then be reported there.

**Comment by gsgatlin** [comment]
So in my shell script I had to add this section:

http://fpaste.org/186268/42412549/

If you have mesa-libGL.i686 installed (as I did) you will not notice this except if  using --debug in which case you will see:

http://fpaste.org/186270/14241256/

But this error message should be ignored because the installer is making the wrong assumption.


Hope that helps. Cheers,

**Comment by rudrab** [comment]
I can confirm this solves the problem

**Comment by gsgatlin** [comment]
@ArchangeGabriel Thanks. Ran out of time to look at it last night. I will try to upload some files soon.
