### ISSUE TITLE
Fedora 21 and Bumblebee

### ISSUE THREAD

**Issue by iulianR** [Bumblebee-Project/Bumblebee#639]
Hey. I tried installing bumblebee exactly as described here [1] but I get this [2] error when running ```optirun glxgears -info | grep "GL_VENDOR```. If I try ```bumblebeed``` I get this [3] error. I tried the different solutions posted in the latest issues but it just seems I made it worse. Can anyone help me out? (pinging @gsgatlin)

[1] http://fedoraproject.org/wiki/Bumblebee
[2]
 ```[ 1419.959179] [ERROR]The Bumblebee daemon has not been started yet or the socket path /var/run/bumblebee.socket was incorrect. ```
 ```[ 1419.959286] [ERROR]Could not connect to bumblebee daemon - is it running?```
[3]
  ```modprobe: FATAL: Module bbswitch not found. ```
 ```[ 1407.128770] [ERROR]Module bbswitch could not be loaded (timeout?) ```
 ```[ 1407.128842] [WARN]No switching method available. The dedicated card will always be on. ```
 ```[ 1407.130950] [ERROR]Module 'nvidia' is not found. ```

**Comment by gsgatlin** [comment]
Hi. Make sure you have the package "kernel-devel" installed. It is required for compiling out of tree kernel modules.

yum install kernel-devel

After that is installed try running the following command:

bumblebee-nvidia --check

Can you paste the output from that? Thanks.

**Comment by iulianR** [comment]
Thank you for the prompt reply.

I have the package installed.
The output of the command is:
```--force compile selected via /etc/sysconfig/nvidia/compile-nvidia-driver
Warning! This NVIDIA driver has not compiled successfully before on kernel 3.17.4-301.fc21.x86_64!
Warning! This NVIDIA driver userland
 /usr/lib64/nvidia-bumblebee/libGL.so.1 library is missing!


Warning! nvidia.ko was not created in in the kernel tree!
modinfo output for NVIDIA:

modinfo: ERROR: Module nvidia not found.

Check bbswitch kernel module...

Warning! bbswitch is not loaded into this kernel!
Since bbswitch is not loaded into the kernel, lets do additional checks on it...
dkms status bbswitch output:
bbswitch, 0.8.0: added

if the bbswitch package is installed, you may wish to try:
/usr/sbin/dkms add -m bbswitch -v 0.8.0
/usr/sbin/dkms build -m bbswitch -v 0.8.0
/usr/sbin/dkms install -m bbswitch -v 0.8.0
/sbin/modprobe bbswitch

To get clues as to why bbswitch is failing on this kernel...
All NVIDIA checks completed, but there were 1 or more failures...
Try running this script with the --debug option to find clues about what has
gone wrong with the NVIDIA driver compile process.```

**Comment by gsgatlin** [comment]
Ok, so try running the commands the check suggested, namely:

/usr/sbin/dkms add -m bbswitch -v 0.8.0
/usr/sbin/dkms build -m bbswitch -v 0.8.0
/usr/sbin/dkms install -m bbswitch -v 0.8.0
/sbin/modprobe bbswitch


You will need to run these as root. Do you see any errors in the output?

One other thing, if you have a laptop with uefi you may need to disable secure boot in your boot screen. Its similar to a BIOS screen. That could be why you can't add these modules...

**Comment by iulianR** [comment]
/usr/sbin/dkms add -m bbswitch -v 0.8.0
```Error! DKMS tree already contains: bbswitch-0.8.0
You cannot add the same module/version combo more than once.```

Build and install gives:
```Error! DKMS tree already contains: bbswitch-0.8.0
You cannot add the same module/version combo more than once.```

The last one:
```/sbin/modprobe bbswitch```

I don't have UEFI.

**Comment by gsgatlin** [comment]
Ok, so I'm guessing the output from 

bumblebee-nvidia --check 

should be a little different now? Or is it still complaining about bbswitch module?

**Comment by iulianR** [comment]
Oh, I pasted the wrong thing. Build and install gives:
Error! Could not locate dkms.conf file.
File:  does not exist.

Seems I'm missing a config file

**Comment by gsgatlin** [comment]
Try

yum remove bbswitch


then 

yum install bbswitch

And see if its any different.

**Comment by iulianR** [comment]
Can't believe that made a difference. It seems I'm missing "nvidia" module
--force compile selected via /etc/sysconfig/nvidia/compile-nvidia-driver
Warning! This NVIDIA driver has not compiled successfully before on kernel 3.17.4-301.fc21.x86_64!
Warning! This NVIDIA driver userland
 /usr/lib64/nvidia-bumblebee/libGL.so.1 library is missing!


Warning! nvidia.ko was not created in in the kernel tree!
modinfo output for NVIDIA:

modinfo: ERROR: Module nvidia not found.

Check bbswitch kernel module...

bbswitch is loaded into the current kernel ok.

All NVIDIA checks completed, but there were 1 or more failures...
Try running this script with the --debug option to find clues about what has
gone wrong with the NVIDIA driver compile process.

**Comment by gsgatlin** [comment]
ok, thats good. next try running

/usr/sbin/bumblebee-nvidia

as root.

it should either print a green "OK" or a red "FAILED"

**Comment by iulianR** [comment]
--force compile selected via /etc/sysconfig/nvidia/compile-nvidia-driver
Building NVIDIA video drivers: Creating directory NVIDIA-Linux-x86_64-346.35
Verifying archive integrity... OK
Uncompressing NVIDIA Accelerated Graphics Driver for Linux-x86_64 346.35...........................................................................................................................................................................................................................................................
patching file kernel/nv-drm.c
Hunk #1 succeeded at 22 with fuzz 2 (offset 4 lines).
patching file kernel/nv-drm.c
Hunk #1 succeeded at 133 (offset 4 lines).
				   [FAILED]

**Comment by gsgatlin** [comment]
Hmnn. Ok, I would suggest a reboot at this point.

If it doesn't work in a couple of minutes after the reboot, try running as root:

/usr/sbin/bumblebee-nvidia --debug

**Comment by iulianR** [comment]
Still not working:
ERROR: Unable to build the NVIDIA kernel module.
ERROR: Installation has failed.  Please see the file '/var/log/nvidia-installer.log' for details.  You may find suggestions on fixing installation problems in the README available on the Linux driver download page at www.nvidia.com.

Contents of the log:
http://paste.fedoraproject.org/189396/14247212

Can I somehow use the nouveau drivers? Not sure if that log helps.

**Comment by gsgatlin** [comment]
Yes, it is possible to use the nouveau drivers.

One thing I notice is that your kernel is older.

I am using 

3.18.7-200.fc21.x86_64

and your box has

3.17.4-301.fc21.x86_64

which is a lot older.

Can you update your system so that it has the newest kernel and other libraries?

yum update

And then reboot into that newer kernel?

If you don't want to mess with nvidia, then the instructions are a little different.

yum remove bumblebee-nvidia

then 

yum install  bumblebee-nouveau

you will have to remove the modesetting package that conflicts if you end up going that route. Also a reboot is required for disabling prime.

**Comment by iulianR** [comment]
Updating the system fixed the problem apparently. Thank you for your help. The issue can be closed.
