### ISSUE TITLE
[ERROR]No discrete video card found, quitting / fresh sid installation

### ISSUE THREAD

**Issue by swing0486** [Bumblebee-Project/Bumblebee#642]
**Distro**: Debian GNU/Linux 8  (provided by cat /etc/issue)

**Kernel** : Linux vostroSid 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt7-1 (2015-03-01) x86_64 GNU/Linux (provided by $ uname -a )

**Manufacturer and model**:
baseboard-manufacturer: Dell Inc.
baseboard-product-name: ......
baseboard-version     : A10
system-manufacturer   : Dell Inc.
system-product-name   : Vostro 3700
system-version        : A10
bios-vendor           : Dell Inc.
bios-version          : A10
bios-release-date     : 10/25/2010

**Bumblebee version** : optirun (Bumblebee) 3.2.1
Bumblebee has been installed from the Sid repository.

**Issue description** 
It seems that bbswitch disable the discrete video card
It is a multiboot system with both Debian Stable and Debian Sid.
Bumblebee is not installed on Debian Stable and the command "$ lspci | grep VGA" provides

    00:02.0 VGA compatible controller: Intel Corporation Core Processor Integrated Graphics Controller (rev 18)
    01:00.0 VGA compatible controller: NVIDIA Corporation GT216 [GeForce GT 330M] (rev a2)

in Debian Stable.  -> It is well an Optimus computer.

In Debian Sid, "$ lspci | grep VGA" provides 

    00:02.0 VGA compatible controller: Intel Corporation Core Processor Integrated Graphics Controller (rev 18)
-> The nVidia card is not available

The command "# egrep -w 'bbswitch|bumblebeed' /var/log/syslog" provides 

    Mar 13 16:35:29 vostroSid bumblebeed[673]: [   26.378680] [INFO]/usr/sbin/bumblebeed 3.2.1 started
    Mar 13 16:35:29 vostroSid kernel: [   26.511023] bbswitch: version 0.8
    Mar 13 16:35:29 vostroSid kernel: [   26.511031] bbswitch: Found integrated VGA device 0000:00:02.0: \_SB_.PCI0.GFX0
    Mar 13 16:35:29 vostroSid kernel: [   26.511039] bbswitch: Found discrete VGA device 0000:01:00.0: \_SB_.PCI0.P0P1.PEGP
    Mar 13 16:35:29 vostroSid kernel: [   26.511442] bbswitch: detected a nVidia _DSM function
    Mar 13 16:35:29 vostroSid kernel: [   26.511551] bbswitch: Succesfully loaded. Discrete card 0000:01:00.0 is on
    Mar 13 16:35:29 vostroSid kernel: [   26.513912] bbswitch: disabling discrete graphics
    Mar 13 16:35:29 vostroSid kernel: [   26.631162] Modules linked in: bbswitch(O) binfmt_misc nfsd auth_rpcgss oid_registry nfs_acl nfs lockd fscache sunrpc uvcvideo videobuf2_vmalloc videobuf2_memops videobuf2_core v4l2_common videodev media arc4 joydev brcmsmac intel_powerclamp dell_wmi iTCO_wdt snd_hda_codec_idt snd_hda_codec_hdmi snd_hda_codec_generic cordic brcmutil sparse_keymap coretemp b43 kvm_intel mac80211 cfg80211 ssb rng_core pcmcia pcmcia_core dell_laptop i915 rfkill iTCO_vendor_support snd_hda_intel mxm_wmi dcdbas snd_hda_controller kvm evdev bcma snd_hda_codec psmouse snd_hwdep serio_raw snd_pcm pcspkr drm_kms_helper intel_ips i2c_i801 snd_timer drm dell_smo8800 battery snd tpm_tis tpm acpi_cpufreq mei_me lpc_ich wmi video ac shpchp soundcore i2c_algo_bit i2c_core processor button mei mfd_core loop fuse parport_pc ppdev lp parport autofs4 hid_generic hid_belkin usbhid hid ext4 crc16 mbcache jbd2 sd_mod crc_t10dif crct10dif_generic sg sr_mod cdrom crct10dif_common ahci libahci ehci_pci ehci_hcd libata crc32c_intel firewire_ohci sdhci_pci sdhci scsi_mod firewire_core crc_itu_t mmc_core r8169 mii usbcore usb_common thermal thermal_sys

What I highlight is : "[   26.513912] bbswitch: disabling discrete graphics"

Running "$ optirun -vv glxgears" the first time provides:

    [  137.740362] [DEBUG]Reading file: /etc/bumblebee/bumblebee.conf
    [  137.740735] [INFO]Configured driver: nvidia
    [  137.740914] [DEBUG]optirun version 3.2.1 starting...
    [  137.740941] [DEBUG]Active configuration:
    [  137.740961] [DEBUG] bumblebeed config file: /etc/bumblebee/bumblebee.conf
    [  137.740984] [DEBUG] X display: :8
    [  137.741005] [DEBUG] LD_LIBRARY_PATH: /usr/lib/x86_64-linux-gnu/nvidia:/usr/lib/i386-linux-gnu/nvidia:/usr/lib/nvidia
    [  137.741028] [DEBUG] Socket path: /var/run/bumblebee.socket
    [  137.741050] [DEBUG] Accel/display bridge: auto
    [  137.741071] [DEBUG] VGL Compression: proxy
    [  137.741092] [DEBUG] VGLrun extra options: 
    [  137.741114] [DEBUG] Primus LD Path: /usr/lib/x86_64-linux-gnu/primus:/usr/lib/i386-linux-gnu/primus:/usr/lib/primus:/usr/lib32/primus
    [  137.741245] [DEBUG]Using auto-detected bridge primus
    [  137.758757] [DEBUG]Socket closed.
    [  137.758783] [DEBUG]Killing all remaining processes.

Runnig "$ optirun -vv glxgears" afterwhile provides:

    [  143.883022] [DEBUG]Reading file: /etc/bumblebee/bumblebee.conf
    [  143.883339] [INFO]Configured driver: nvidia
    [  143.883405] [ERROR]Could not connect to /var/run/bumblebee.socket! Error: Connection refused
    [  143.883423] [DEBUG]Socket closed.
    [  143.883444] [ERROR]Could not connect to bumblebee daemon - is it running?

After running this, the system added the below lines to the /var/log/syslog file

    Mar 13 16:42:44 vostroSid kernel: [  137.776442] CPU: 3 PID: 673 Comm: bumblebeed Tainted: G        W  O  3.16.0-4-amd64 #1 Debian 3.16.7-ckt7-1
     Mar 13 16:42:44 vostroSid kernel: [  137.776637] RIP: 0010:[<ffffffffa0759035>]  [<ffffffffa0759035>] dis_dev_get+0x15/0x40 [bbswitch]
    Mar 13 16:42:44 vostroSid kernel: [  137.777453]  [<ffffffffa07590ee>] ? bbswitch_proc_show+0xe/0x70 [bbswitch]
    Mar 13 16:42:44 vostroSid kernel: [  137.778250] RIP  [<ffffffffa0759035>] dis_dev_get+0x15/0x40 [bbswitch]
    Mar 13 16:42:44 vostroSid systemd[1]: bumblebeed.service: main process exited, code=killed, status=11/SEGV
    Mar 13 16:42:44 vostroSid systemd[1]: Unit bumblebeed.service entered failed state.
    Mar 13 16:43:44 vostroSid bumblebeed[1784]: [  197.779704] [ERROR]No discrete video card found, quitting
    Mar 13 16:43:44 vostroSid systemd[1]: bumblebeed.service: main process exited, code=exited, status=1/FAILURE
    Mar 13 16:43:44 vostroSid systemd[1]: Unit bumblebeed.service entered failed state.

I don't find any /var/log/Xorg.8.log file. I only find a /var/log/Xorg.0.log file !

I Googled quiet a lot and only found a similar situation [here] (https://bbs.archlinux.org/viewtopic.php?id=187160)
But for him, the problem solved by himself after a kernel update (if I understood well).

Thanks in advance for your help and time !!!

**Comment by ArchangeGabriel** [comment]
We need the whole dmesg output, you’re exactly cutting around the crash.

**Comment by swing0486** [comment]
Hi ArchangeGabriel,
I suppose that I don't have to submit the all report here ...

I saw that the dmesg is included in the bumblebee-bugreport.
I tried to email it through a Launchpad account to bumblebee@lists.launchpad.net, but I didn't understood how to submit a file in that system   ;os.

I finally emailed it to lekensteyn@gmail.com as explained in the [reporting issue page](https://github.com/Bumblebee-Project/Bumblebee/wiki/Reporting-Issues).

 Is there something else I can do to supply it to your team ?
Thanks !

**Comment by ArchangeGabriel** [comment]
You can [gist] it. ;)

[gist]:https://gist.github.com

**Comment by swing0486** [comment]
You're as fast as flash ;o))
[Here is it !] (https://gist.github.com/swing0486/0effaa4530f52a1d6442)

**Comment by ArchangeGabriel** [comment]
OK. So this will require @Lekensteyn to look at this, seems to be an issue on bbswitch or kernel side.

**Comment by ArchangeGabriel** [comment]
@Lekensteyn?

**Comment by Lekensteyn** [comment]
I think I have seen this reported before, but do not know where. It looks like a kernel issue which is likely fixed in recenter kernels.

@swing0486 Does it still occur on recent kernels?

**Comment by swing0486** [comment]
I tried to make it run on Debian Sid. I update it everyday. Sid is normally the most up-to-date version of Debian (if I understood well). I still have the same problem.
Perhaps did I made something wrong ...
I installed Bumblebee from the repository like explained [here](https://wiki.debian.org/Bumblebee).
The only thing I made differently is to work as root instead of using sudo.

**Comment by ArchangeGabriel** [comment]
Hi, it’s been sometime… Do you still have this issue?

**Comment by swing0486** [comment]
Hi, I bypassed the issue by purchasing an AMD laptop ...
I didn't solved the issue.

My idea was to install Ubuntu on that machine and to test if I have the
same issue. (And also ArchLinux, but I don't know that distribution).
But currently, I have other priorities ...

I was just asking myself if there was not a previous technology, that was
not Optimus yet, but that already used two graphical cards.
Nothing tells it use Optimus technology in the documentation.

Thank you for making follow-up on this !

Laurent

2016-05-06 15:30 GMT+02:00 Bruno Pagani <notifications@github.com>:

**Comment by ArchangeGabriel** [comment]
OK… You’re right, there was a technology before Optimus from Nvidia. I haven’t seen it featured on something else than ASUS UL**Vt however.

OK, I’ll close this for now, but don’t hesitate to reopen if you ever get some time to look into this.

**Comment by Cypher1** [comment]
18 days... Now It's my turn (I won't resurrect this thread any more unless I find a solution)

**Comment by olleharstedt** [comment]
Same problem:

```
$ lspci | grep VGA
00:02.0 VGA compatible controller: Intel Corporation 4th Generation Core Processor Family Integrated Graphics Controller (rev 06)
```
