### ISSUE TITLE
Ubuntu 15.04 works with upstart, doesn't with systemd

### ISSUE THREAD

**Issue by nazar-pc** [Bumblebee-Project/Bumblebee#644]
Currently Ubuntu switched to systemd by default, unfortunately bumblebee is not working in this case.
I have proprietary nvidia driver and bumblebee from standard repository, kernel 3.19.0.
> nazar-pc@nazar-pc ~> optirun steam
[  523.733713] [ERROR]Cannot access secondary GPU - error: Could not load GPU driver

> [  523.733754] [ERROR]Aborting because fallback start is disabled.

with `Driver=`
> nazar-pc@nazar-pc ~> sudo service bumblebeed status
● bumblebeed.service - Bumblebee C Daemon
   Loaded: loaded (/lib/systemd/system/bumblebeed.service; enabled; vendor preset: enabled)
   Active: active (running) since ср 2015-03-25 03:56:04 CET; 31s ago
 Main PID: 16229 (bumblebeed)
   Memory: 292.0K
   CGroup: /system.slice/bumblebeed.service
           └─16229 /usr/sbin/bumblebeed

> бер 25 03:56:04 nazar-pc systemd[1]: Started Bumblebee C Daemon.
бер 25 03:56:04 nazar-pc systemd[1]: Starting Bumblebee C Daemon...
бер 25 03:56:04 nazar-pc bumblebeed[16229]: [  495.736332] [INFO]/usr/sbin/bumblebeed 3.2.1 started
бер 25 03:56:32 nazar-pc bumblebeed[16229]: modprobe: ERROR: ../libkmod/libkmod-module.c:816 kmod_module_insert_module() could not find module by name='off'
бер 25 03:56:32 nazar-pc bumblebeed[16229]: modprobe: ERROR: could not insert 'off': Function not implemented
бер 25 03:56:32 nazar-pc bumblebeed[16229]: [  523.733668] [ERROR]Module nouveau could not be loaded (timeout?)
бер 25 03:56:32 nazar-pc bumblebeed[16229]: [  523.733678] [ERROR]Could not load GPU driver

with `Driver=nvidia`
> nazar-pc@nazar-pc ~> sudo service bumblebeed status
● bumblebeed.service - Bumblebee C Daemon
   Loaded: loaded (/lib/systemd/system/bumblebeed.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since ср 2015-03-25 04:01:52 CET; 1s ago
  Process: 18370 ExecStart=/usr/sbin/bumblebeed (code=exited, status=1/FAILURE)
 Main PID: 18370 (code=exited, status=1/FAILURE)

> бер 25 04:01:52 nazar-pc systemd[1]: Unit bumblebeed.service entered failed state.
бер 25 04:01:52 nazar-pc systemd[1]: bumblebeed.service failed.

When booted with upstart - works perfectly

**Comment by Lekensteyn** [comment]
Looks like a compatibility issue with the modprobe configuration file on Ubuntu, please take this downstream (on Launchpad).

**Comment by nazar-pc** [comment]
Did you mean write to systemd developers on launchpad or what?

**Comment by nazar-pc** [comment]
Reported here: https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1438106

**Comment by Lekensteyn** [comment]
Surely you could at least copy some details to the Launchpad tracker instead of pasting a link :-P

When I said compatibility, I think that systemd(/kmod?) does not like the `alias nvidia off` line in some modprobe configuration as supplied by the nvidia package.

**Comment by nazar-pc** [comment]
@Lekensteyn, done, I just hate launchpad because it still doesn't support any formatting and long text like this is barely readable.

**Comment by martinpitt** [comment]
This is unrelated to systemd or any other init, but how kmod behaves. "alias nvidia off" isn't a "magic" value in any way (it's undocumented in man modprobe.d either), if you try to load that module you will get that `could not find module by name='off'` error. It seems bumblebee stumbles over this?

This should be reopened.

**Comment by Lekensteyn** [comment]
@martinpitt IIRC it was done to prevent `modprobe nvidia` from working at all (`blacklist nvidia` would only disable automatic loading). I still think this is not an issue in the Bumblebee upstream configuration, there is no `alias nvidia off` in the repository.

Isn't the nvidia packaging on Ubuntu responsible for this module configuration snippet?

**Comment by martinpitt** [comment]
I don't know who/what creates that  "alias nividia off" thing, to be honest. It's not the bumblebee package as far as I can see, but it could certainly be the nvidia driver, or one of its configuration helpers.

I also don't know what bumblebee does, so please forgive my ignorance :-) If Bumblebee makes sense to run without the "nvidia" module, then it should be robust against modprobe failing. If it doesn't make sense, then failing its .service seems exactly right?

**Comment by Lekensteyn** [comment]
@martinpitt Bumblebee basically works like this:

 - The daemon starts up, unloads the nvidia driver if it is loaded.
 - When the user invokes the client (optirun), bumblebee tries to load the (nvidia) driver.
 - On acknowledgement from the daemon, the client starts the program.

When configured to use the nvidia driver, then the daemon fails if it cannot find the nvidia module as shown in the first post.

**Comment by nazar-pc** [comment]
Just got systemd-related update of kmod, now everything works fine)

**Comment by Lekensteyn** [comment]
Thanks for reporting back!

**Comment by CODeRUS** [comment]
@nazar-pc what package did you got updated and which version? i just upgraded to 15.04 and nvidia-346, installed all updates, and having same problem.

**Comment by nazar-pc** [comment]
1. I have Nvidia 349 from xorg-edgers and, consequently, all other graphics-related pakages from there, kernel 4.0 compiled by myself
2. Usually it doesn't work after wakeup, but today even reboot didn't help, but `sudo modprobe nvidia_349` before using `optirun` helps

It should work out of the box since we should have same versions of packages (systemd and related at least).

**Comment by CODeRUS** [comment]
```
coderus@inspiron:~$ sudo systemctl status bumblebeed
● bumblebeed.service - Bumblebee C Daemon
   Loaded: loaded (/lib/systemd/system/bumblebeed.service; enabled; vendor preset: enabled)
   Active: active (running) since Сб. 2015-04-25 13:05:17 YEKT; 1min 52s ago
 Main PID: 749 (bumblebeed)
   CGroup: /system.slice/bumblebeed.service
           └─749 /usr/sbin/bumblebeed

апр. 25 13:05:17 inspiron systemd[1]: Started Bumblebee C Daemon.
апр. 25 13:05:17 inspiron systemd[1]: Starting Bumblebee C Daemon...
апр. 25 13:05:17 inspiron bumblebeed[749]: [    4.320229] [INFO]/usr/sbin/bumblebeed 3.2.1 started
апр. 25 13:07:06 inspiron bumblebeed[749]: modprobe: ERROR: ../libkmod/libkmod-module.c:816 kmod_module_insert_module() could not find module by name='off'
апр. 25 13:07:06 inspiron bumblebeed[749]: modprobe: ERROR: could not insert 'off': Function not implemented
апр. 25 13:07:06 inspiron bumblebeed[749]: [  113.104710] [ERROR]Module nouveau could not be loaded (timeout?)
апр. 25 13:07:06 inspiron bumblebeed[749]: [  113.104739] [ERROR]Could not load GPU driver
```
bumblebee-bugreport: https://www.dropbox.com/s/gun4k1xvbl86b7k/bumblebee-bugreport-20150425_131051.tar.gz?dl=0

**Comment by nazar-pc** [comment]
Did you set `Driver=nvidia` in `/etc/bumblebee/bumblebee.conf`?
Here is content of my file (as I remember `nvidia-current` was there by default):
```
# Configuration file for Bumblebee. Values should **not** be put between quotes

## Server options. Any change made in this section will need a server restart
# to take effect.
[bumblebeed]
# The secondary Xorg server DISPLAY number
VirtualDisplay=:8
# Should the unused Xorg server be kept running? Set this to true if waiting
# for X to be ready is too long and don't need power management at all.
KeepUnusedXServer=false
# The name of the Bumbleblee server group name (GID name)
ServerGroup=bumblebee
# Card power state at exit. Set to false if the card shoud be ON when Bumblebee
# server exits.
TurnCardOffAtExit=false
# The default behavior of '-f' option on optirun. If set to "true", '-f' will
# be ignored.
NoEcoModeOverride=false
# The Driver used by Bumblebee server. If this value is not set (or empty),
# auto-detection is performed. The available drivers are nvidia and nouveau
# (See also the driver-specific sections below)
Driver=nvidia
# Directory with a dummy config file to pass as a -configdir to secondary X
XorgConfDir=/etc/bumblebee/xorg.conf.d

## Client options. Will take effect on the next optirun executed.
[optirun]
# Acceleration/ rendering bridge, possible values are auto, virtualgl and
# primus.
Bridge=auto
# The method used for VirtualGL to transport frames between X servers.
# Possible values are proxy, jpeg, rgb, xv and yuv.
VGLTransport=proxy
# List of paths which are searched for the primus libGL.so.1 when using
# the primus bridge
PrimusLibraryPath=/usr/lib/x86_64-linux-gnu/primus:/usr/lib/i386-linux-gnu/primus
# Should the program run under optirun even if Bumblebee server or nvidia card
# is not available?
AllowFallbackToIGC=false


# Driver-specific settings are grouped under [driver-NAME]. The sections are
# parsed if the Driver setting in [bumblebeed] is set to NAME (or if auto-
# detection resolves to NAME).
# PMMethod: method to use for saving power by disabling the nvidia card, valid
# values are: auto - automatically detect which PM method to use
#         bbswitch - new in BB 3, recommended if available
#       switcheroo - vga_switcheroo method, use at your own risk
#             none - disable PM completely
# https://github.com/Bumblebee-Project/Bumblebee/wiki/Comparison-of-PM-methods

## Section with nvidia driver specific options, only parsed if Driver=nvidia
[driver-nvidia]
# Module name to load, defaults to Driver if empty or unset
KernelDriver=nvidia
PMMethod=auto
# colon-separated path to the nvidia libraries
LibraryPath=/usr/lib/nvidia-349:/usr/lib32/nvidia-349
# comma-separated path of the directory containing nvidia_drv.so and the
# default Xorg modules path
XorgModulePath=/usr/lib/nvidia-349/xorg,/usr/lib/xorg/modules
XorgConfFile=/etc/bumblebee/xorg.conf.nvidia

## Section with nouveau driver specific options, only parsed if Driver=nouveau
[driver-nouveau]
KernelDriver=nouveau
PMMethod=auto
XorgConfFile=/etc/bumblebee/xorg.conf.nouveau

```
Also if you have `nvidia-current` in `/etc/bumblebee/xorg.conf.nvidia` try to replace that by just `nvidia`.

**Comment by CODeRUS** [comment]
installed nvidia-349 from edgers
```
# Configuration file for Bumblebee. Values should **not** be put between quotes

## Server options. Any change made in this section will need a server restart
# to take effect.
[bumblebeed]
# The secondary Xorg server DISPLAY number
VirtualDisplay=:8
# Should the unused Xorg server be kept running? Set this to true if waiting
# for X to be ready is too long and don't need power management at all.
KeepUnusedXServer=false
# The name of the Bumbleblee server group name (GID name)
ServerGroup=bumblebee
# Card power state at exit. Set to false if the card shoud be ON when Bumblebee
# server exits.
TurnCardOffAtExit=false
# The default behavior of '-f' option on optirun. If set to "true", '-f' will
# be ignored.
NoEcoModeOverride=false
# The Driver used by Bumblebee server. If this value is not set (or empty),
# auto-detection is performed. The available drivers are nvidia and nouveau
# (See also the driver-specific sections below)
Driver=
# Directory with a dummy config file to pass as a -configdir to secondary X
XorgConfDir=/etc/bumblebee/xorg.conf.d

## Client options. Will take effect on the next optirun executed.
[optirun]
# Acceleration/ rendering bridge, possible values are auto, virtualgl and
# primus.
Bridge=auto
# The method used for VirtualGL to transport frames between X servers.
# Possible values are proxy, jpeg, rgb, xv and yuv.
VGLTransport=proxy
# List of paths which are searched for the primus libGL.so.1 when using
# the primus bridge
PrimusLibraryPath=/usr/lib/x86_64-linux-gnu/primus:/usr/lib/i386-linux-gnu/primus
# Should the program run under optirun even if Bumblebee server or nvidia card
# is not available?
AllowFallbackToIGC=false


# Driver-specific settings are grouped under [driver-NAME]. The sections are
# parsed if the Driver setting in [bumblebeed] is set to NAME (or if auto-
# detection resolves to NAME).
# PMMethod: method to use for saving power by disabling the nvidia card, valid
# values are: auto - automatically detect which PM method to use
#         bbswitch - new in BB 3, recommended if available
#       switcheroo - vga_switcheroo method, use at your own risk
#             none - disable PM completely
# https://github.com/Bumblebee-Project/Bumblebee/wiki/Comparison-of-PM-methods

## Section with nvidia driver specific options, only parsed if Driver=nvidia
[driver-nvidia]
# Module name to load, defaults to Driver if empty or unset
KernelDriver=nvidia
PMMethod=auto
# colon-separated path to the nvidia libraries
LibraryPath=/usr/lib/nvidia-349:/usr/lib32/nvidia-349
# comma-separated path of the directory containing nvidia_drv.so and the
# default Xorg modules path
XorgModulePath=/usr/lib/nvidia-349/xorg,/usr/lib/xorg/modules
XorgConfFile=/etc/bumblebee/xorg.conf.nvidia

## Section with nouveau driver specific options, only parsed if Driver=nouveau
[driver-nouveau]
KernelDriver=nouveau
PMMethod=auto
XorgConfFile=/etc/bumblebee/xorg.conf.nouveau
```
still the same:
```
* bumblebeed.service - Bumblebee C Daemon
   Loaded: loaded (/lib/systemd/system/bumblebeed.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2015-04-25 13:31:06 YEKT; 1min 12s ago
 Main PID: 1969 (bumblebeed)
   CGroup: /system.slice/bumblebeed.service
           `-1969 /usr/sbin/bumblebeed

Apr 25 13:31:06 inspiron systemd[1]: Started Bumblebee C Daemon.
Apr 25 13:31:06 inspiron systemd[1]: Starting Bumblebee C Daemon...
Apr 25 13:31:06 inspiron bumblebeed[1969]: [   46.391309] [INFO]/usr/sbin/bumblebeed 3.2.1 started
Apr 25 13:31:08 inspiron bumblebeed[1969]: modprobe: ERROR: ../libkmod/libkmod-module.c:816 kmod_module_insert_module() could not find module by name='off'
Apr 25 13:31:08 inspiron bumblebeed[1969]: modprobe: ERROR: could not insert 'off': Function not implemented
Apr 25 13:31:08 inspiron bumblebeed[1969]: [   48.565693] [ERROR]Module nouveau could not be loaded (timeout?)
Apr 25 13:31:08 inspiron bumblebeed[1969]: [   48.565713] [ERROR]Could not load GPU driver
```
bumblebee-bugreport: https://www.dropbox.com/s/dmg9zj05jayzv9v/bumblebee-bugreport-20150425_133237.tar.gz?dl=0

**Comment by nazar-pc** [comment]
I've posted my configuration for you to try it.

**Comment by CODeRUS** [comment]
WIth your configuration i'm getting black screen.
btw, i added Driver=nvidia to [bumblebeed] section and it working again. ```kmod_module_insert_module() could not find module by name='off'``` error is caused when loading noveau driver, not nvidia, and nvidia driver itself working good.

**Comment by nazar-pc** [comment]
> btw, i added Driver=nvidia to [bumblebeed] section and it working again

Our configurations in fact differ only in that single line, there is no way for black screen with my config and working with changed line, because contents is identical.
So, finally, is it working for you?

**Comment by fisadev** [comment]
I'm having the same issue with systemd and bumblebee not starting properly. Tinkering with it, I got to the same problems than some of you had (not being able to load the gpu driver). Tried some of the solutions here with no luck. So before breaking more stuff, I wanted to ask, having these packages installed from the official ubuntu repos:

* bumblebee (3.2.1-7)
* bumblebee-nvidia (3.2.1-7)
* primus (0~20140711-1)
* nvidia-346
* linux-headers-generic (3.19.0.25.24)

Was there a special order in which I should have installed them?
What should my bumblebee.conf say? 
Just installing them and configuring my bumblebee.conf is enough or are there other steps I should do?

The defaults in bumblebee.conf were "Driver=" and "KernelDriver=nvidia-current", but they fail to load the gpu. I tried with  "Driver=nvidia" and "KernelDriver=nvidia", but they gave me a black screen on the first boot, then a normal second boot but still not able to load the gpu drivers. I also tried to manually starting bumblebee via systemctl and manually calling modprobe on nvidia_346, with the same results.

**Comment by nazar-pc** [comment]
1) Order doesn't matter, primus should be installed automatically, no need to specify it explicitly
2) Currently I'm using Nvidia 352 driver from xorg-edgers, so I've replaced paths to libraries in config accrdingly
3) Also I needed to call `modprobe nvidia_352` before running `optirun steam`, while bumblebee itself started fine

After last bumblebee update in Ubuntu 15.10 (yes, unstable) I do not need to call `modprobe nvidia_352` anymore, but nvidia GPU keeps working after first run until restarting...

**Comment by Lekensteyn** [comment]
As for the nvidia issue, that happens because nvidia is not properly unloaded since the change from rmmod to modprobe. It is a known issue for which a fix was attempted in edd81b063ec1bda63ae8a3b10d8051e02eec282b, but it is possible that the fix does not work. Can you report whether you can really unload a module via modprobe?

1. Use `lsmod | grep nvidia` to confirm that "nvidia" is loaded (it should really be named "nvidia", not "nvidia-352" or something like that). Please provide the output. If it is loaded (and no applications are using it, continue with the next step.)
2. Use `sudo modprobe -vr nvidia` and check again with `lsmod | grep nvidia`. The former command will probably give no output (which is what causes this issue) and the second command confirms that the module is still loaded.
3. Use `sudo modprobe -vr nvidia-352` and check again with `lsmod | grep nvidia`. The former command should give some output, while the second command should have less details.

Failing this, you can run the `sudo rmmod nvidia` command directly (which is the legacy behavior), possibly after `sudo rmmod nvidia-uvm`.

**Comment by fisadev** [comment]
Ok, I found my issue: I had to use "nvidia-346" instead of just "nvidia" in the KernelDriver setting of the [driver-nvidia] section. Having those listed packages installed (my previous comment), my working config is this:

    # Configuration file for Bumblebee. Values should **not** be put between quotes
    
    ## Server options. Any change made in this section will need a server restart
    # to take effect.
    [bumblebeed]
    # The secondary Xorg server DISPLAY number
    VirtualDisplay=:8
    # Should the unused Xorg server be kept running? Set this to true if waiting
    # for X to be ready is too long and don't need power management at all.
    KeepUnusedXServer=false
    # The name of the Bumbleblee server group name (GID name)
    ServerGroup=bumblebee
    # Card power state at exit. Set to false if the card shoud be ON when Bumblebee
    # server exits.
    TurnCardOffAtExit=false
    # The default behavior of '-f' option on optirun. If set to "true", '-f' will
    # be ignored.
    NoEcoModeOverride=false
    # The Driver used by Bumblebee server. If this value is not set (or empty),
    # auto-detection is performed. The available drivers are nvidia and nouveau
    # (See also the driver-specific sections below)
    Driver=nvidia
    # Directory with a dummy config file to pass as a -configdir to secondary X
    XorgConfDir=/etc/bumblebee/xorg.conf.d
    
    ## Client options. Will take effect on the next optirun executed.
    [optirun]
    # Acceleration/ rendering bridge, possible values are auto, virtualgl and
    # primus.
    Bridge=auto
    # The method used for VirtualGL to transport frames between X servers.
    # Possible values are proxy, jpeg, rgb, xv and yuv.
    VGLTransport=proxy
    # List of paths which are searched for the primus libGL.so.1 when using
    # the primus bridge
    PrimusLibraryPath=/usr/lib/x86_64-linux-gnu/primus:/usr/lib/i386-linux-gnu/primus
    # Should the program run under optirun even if Bumblebee server or nvidia card
    # is not available?
    AllowFallbackToIGC=false
    
    
    # Driver-specific settings are grouped under [driver-NAME]. The sections are
    # parsed if the Driver setting in [bumblebeed] is set to NAME (or if auto-
    # detection resolves to NAME).
    # PMMethod: method to use for saving power by disabling the nvidia card, valid
    # values are: auto - automatically detect which PM method to use
    #         bbswitch - new in BB 3, recommended if available
    #       switcheroo - vga_switcheroo method, use at your own risk
    #             none - disable PM completely
    # https://github.com/Bumblebee-Project/Bumblebee/wiki/Comparison-of-PM-methods
    
    ## Section with nvidia driver specific options, only parsed if Driver=nvidia
    [driver-nvidia]
    # Module name to load, defaults to Driver if empty or unset
    KernelDriver=nvidia-346
    PMMethod=auto
    # colon-separated path to the nvidia libraries
    LibraryPath=/usr/lib/nvidia-346:/usr/lib32/nvidia-346
    # comma-separated path of the directory containing nvidia_drv.so and the
    # default Xorg modules path
    XorgModulePath=/usr/lib/nvidia-346/xorg,/usr/lib/xorg/modules
    XorgConfFile=/etc/bumblebee/xorg.conf.nvidia
    
    ## Section with nouveau driver specific options, only parsed if Driver=nouveau
    [driver-nouveau]
    KernelDriver=nouveau
    PMMethod=auto
    XorgConfFile=/etc/bumblebee/xorg.conf.nouveau

**Comment by nazar-pc** [comment]
@Lekensteyn, unloading is not working properly in any way you've mentioned, I've already tried all of that before, here is some details:
```
nazar-pc@nazar-pc ~> lsmod | grep nvidia
nvidia               8593408  0 
drm                   352256  10 i915,drm_kms_helper,nvidia
nazar-pc@nazar-pc ~> sudo modprobe -vr nvidia
modprobe: FATAL: Module nvidia not found.
nazar-pc@nazar-pc ~> sudo modprobe -vr nvidia-352
nazar-pc@nazar-pc ~> lsmod | grep nvidia
nvidia               8593408  0 
drm                   352256  10 i915,drm_kms_helper,nvidia
nazar-pc@nazar-pc ~> sudo rmmod nvidia
nazar-pc@nazar-pc ~> sudo rmmod nvidia-uvm
rmmod: ERROR: Module nvidia_uvm is not currently loaded
nazar-pc@nazar-pc ~> sudo rmmod nvidia
rmmod: ERROR: Module nvidia is not currently loaded
nazar-pc@nazar-pc ~> lsmod | grep nvidia
nazar-pc@nazar-pc ~> 
```

So it seems that driver is not loaded anymore, but discrete GPU indicator on laptop is still working.

**Comment by Lekensteyn** [comment]
@nazar-pc Thanks for testing this, can you test another thing:

 1. Create `/etc/modprobe.d/nvidia-alias.conf` containing `alias nvidia nvidia-352`
 2. Trigger loading nvidia: `optirun true`
 3. Confirm it is loaded: `lsmod | grep nvidia`
 4. Try to unload it: `sudo modprobe -vr nvidia`
 5. Check its result: `lsmod | grep nvidia`

If this still does not work, then we must revert the change for Ubuntu users. To disable card manually, unload the driver and write OFF:

    sudo rmmod nvidia
    sudo tee /proc/acpi/bbswitch <<<OFF

**Comment by nazar-pc** [comment]
Unfortunately doesn't, reboot is not needed after file creation, right?
```
nazar-pc@nazar-pc ~> optirun true
nazar-pc@nazar-pc ~> lsmod | grep nvidia
nvidia               8593408  0 
drm                   352256  9 i915,drm_kms_helper,nvidia
nazar-pc@nazar-pc ~> sudo modprobe -vr nvidia
nazar-pc@nazar-pc ~> lsmod | grep nvidia
nvidia               8593408  0 
drm                   352256  9 i915,drm_kms_helper,nvidia
nazar-pc@nazar-pc ~> sudo modprobe -vr nvidia-352
nazar-pc@nazar-pc ~> lsmod | grep nvidia
nvidia               8593408  0 
drm                   352256  9 i915,drm_kms_helper,nvidia
```
I'm on kernel 4.0-rc4 currently if it makes any difference.

**Comment by Lekensteyn** [comment]
Nope, a reboot is not needed as modprobe consults the file at runtime. The rmmod->modprobe change is about to be reverted for Ubuntu, but this in turn makes it not possible to unload nvidia-uvm before unloading nvidia... Can you try another modprobe configuration:

    remove nvidia rmmod nvidia-uvm nvidia

This should work, just tested something similar.

**Comment by nazar-pc** [comment]
Sorry, probably there is some type there, since I don't have `remove` command.
I'm wondered why `modprobe -r` doesn't work if module was loaded with `modprobe`?.. I guess some systemd-specific issue or what?
If so - we need to report it to appropriate developers.

**Comment by Lekensteyn** [comment]
That was a line for a file in `/etc/modprobe.d/`

**Comment by nazar-pc** [comment]
Yes, `remove nvidia rmmod nvidia-uvm nvidia` works!

**Comment by bluca** [comment]
Hi, I'll mention this here as well (for traceability more than anything else), here's a proposed solution until the driver packages change: https://github.com/Bumblebee-Project/bumblebee-ppa/pull/34
