### ISSUE TITLE
"error: Could not enable discrete graphics card" after suspend.

### ISSUE THREAD

**Issue by Celti** [Bumblebee-Project/Bumblebee#649]
**Distro**: Arch Linux (Latest)
**Kernel**: Linux siduri.celti.name 3.19.3-1-ARCH #1 SMP PREEMPT Thu Mar 26 14:56:16 CET 2015 x86_64 GNU/Linux
**Manufacturer & Model**:
```
baseboard-manufacturer: LENOVO
baseboard-product-name: Durian 7A1
baseboard-version     : 31900058Std
system-manufacturer   : LENOVO
system-product-name   : 20250
system-version        : Lenovo Z710
bios-vendor           : LENOVO
bios-version          : 7FCN88WW
bios-release-date     : 10/08/2013
```
**Bumblebee Version:** optirun (Bumblebee) 3.2.1 (primus 20150118)
**bumblebee-bugreport file:** https://ilmatar.celti.name/~celti/esoterica/bumblebee-bugreport-20150405_203301.tar.gz

Issue is simple enough: before suspending, everything works great. If I try and do `optirun` or `primusrun` after resuming, I get the following:

```
celti@siduri ~/projects/bumblebee $ optirun steam
[ 1059.116690] [ERROR]Cannot access secondary GPU - error: Could not enable discrete graphics card

[ 1059.116719] [ERROR]Aborting because fallback start is disabled.
```
This situation is greatly improved from a few weeks ago, when I suffered from a similar issue to #625 ; that is no longer the case on the most recent bumblebee.

**Comment by Celti** [comment]
The issue persists using bumblebee, primus, and bbswitch compiled from latest git. I've also tried some fiddling with ACPI parameters to no avail (setting acpi_osi_name to various Windows versions as well as Linux).

**Comment by Celti** [comment]
Also of note, this laptop does not work with nouveau due to a (possibly distantly related?) [bug](https://bugs.freedesktop.org/show_bug.cgi?id=82152), so testing with nouveau instead of nvidia is impossible.

**Comment by ArchangeGabriel** [comment]
Do you know what changed since you where hitting #625?

I think it might still be a kernel issue, but not being able to test with nouveau forbids reporting against it…

**Comment by Celti** [comment]
Unfortunately, I don't know what changed. I never had a chance to do any testing until I discovered that the situation had changed.

**Comment by gnu3ra** [comment]
I have a strange twist on this bug. After a single suspend, I get Could not enable discrete graphics card as expected. I check the card with bbswitch and it is marked as off. Trying to enable it results in  nvidia 0000:04:00.0: Refused to change power state, currently in D3 in the dmesg log. After a second suspend, though, the card can be re-enabled, but with  optirun throwing Could not load GPU driver, beause the gpu dropout from the first suspend did something with the pci and the driver.

**Comment by k3nda** [comment]
Same problem here. After reboot I can run "optirun" and it is working, but after suspend PC it is not working and have this error:

> [ 4190.513040] [ERROR]Cannot access secondary GPU - error: Could not enable discrete graphics card
> [ 4190.513084] [ERROR]Aborting because fallback start is disabled.

if you want some logs or details tell me what you need. Please repair this bug bcs it is really annoying when I need reboot PC everytime I need NVIDIA graphics

**Comment by Yamakuzure** [comment]
Are the modules still loaded?

The command

` $ lsmod | grep -P "(nvidia|bbswitch)"`

Should only return "bbswitch"

But if the output looks more like this:

`$ lsmod | grep -P "(nvidia|bbswitch)"`
`nvidia_modeset        700096  3`
`nvidia_uvm             71368  0`
`nvidia               8688342  57 nvidia_modeset,nvidia_uvm`
`bbswitch                4960  0`

Then something loaded the drivers on resume. Maybe some hibernate-script or pm-utils config?

You might try

`modprobe -r nvidia`

to get them off your back and bbswitch should be able to take back control for you.

**Comment by iataato** [comment]
Same here. After suspend can not get nvidia working. Modules are not loaded:
`lsmod | grep -P "(nvidia|bbswitch)"`
`bbswitch               16384  0`

`optirun glxgears`
`[ 8641.019399] [ERROR]Cannot access secondary GPU - error: Could not enable discrete graphics card`

`[ 8641.019492] [ERROR]Aborting because fallback start is disabled.`

and in journalctl I get:

`kernel: bbswitch: enabling discrete graphics`
`kernel: pci 0000:07:00.0: Refused to change power state, currently in D3`
`bumblebeed[540]: [ 8641.019280] [ERROR]Could not enable discrete graphics card`

**Comment by ArchangeGabriel** [comment]
OK, so this is more something for https://github.com/Bumblebee-Project/bbswitch, please open a new bug here with dmesg logs after a fresh boot + suspend/resume.

Closing here.

**Comment by AdamMartinCote** [comment]
Is there a solution for this bug yet ? I experiencing the exact same bug right now, the one describe in the bbswitch github's is different.

Asus k501ux with geforce gtx950m on antergos linux

**Comment by Lekensteyn** [comment]
@AdamMartinCote The "could not enable discrete graphics card" is a symptom, but based on the gfx hw I guess it may be #764
