### ISSUE TITLE
Nvidia module does not exist with correct bumblebee.conf (nvidia-346-updates)

### ISSUE THREAD

**Issue by RlndVt** [Bumblebee-Project/Bumblebee#655]
Similar to the error mentioned in the last paragraph of the [troubleshooting](https://github.com/Bumblebee-Project/Bumblebee/wiki/Troubleshooting#bumblebeed-module-nvidia-is-not-found), optirun returns a [error](http://paste.ubuntu.com/10881797/) stating that the nvidia module does not exist. However, contrary to the proposed solution, I believe my [/etc/bumblebee/bumblebee.conf](http://paste.ubuntu.com/10881840/) is set up correctly already.

Trying to fix this issue I've also changed /etc/modprobe.d/bumblebee.conf adding 346 to the  blacklist. 

I'm running Ubuntu 15.04, using the default repositories.
[More details](http://paste.ubuntu.com/10886574/)

Any help would be greatly appreciated.

[bumblebee-bugreport.tar.gz](http://expirebox.com/download/934936ea9e82cffe16db0f1ed0ae05ef.html)

**Comment by ArchangeGabriel** [comment]
What happens if you try this:
```
sudo modprobe -v nvidia-346-updates
```

**Comment by RlndVt** [comment]
Thank you for the response. 

I just noticed that I missed a s in line 61 of bumblebee.conf, changed that and restarted bumblebeed and now everything seems to be working.

Fwiw
```
roland@Roland-TP:~$ sudo modprobe -v nvidia-346-updates
insmod /lib/modules/3.19.0-15-generic/updates/dkms/nvidia_346_updates.ko 
```


Sorry, issue can be closed.

PS. If someone in the future notices something similar: double and triple check of everyline.
