### ISSUE TITLE
optirun not work when launching as a subprocess under scrotwm

### ISSUE THREAD

**Issue by tobixen** [Bumblebee-Project/Bumblebee#658]
Not really sure if this is a bug with scrotwm or with bumblebee ... but this problem is not observed with primusrun, only with optirun.

I have a .xinitrc which launches two xterms and then the window manager scrotwm.  If I run i.e. "optirun glxgears" (or any other application) from one of those two xterms, then everything works fine.  However, if I attempt to launch optirun directly from the WM, or from an xterm started from the WM, then the application will quite immediately do a core dump.  I haven't investigated the core files yet.

Here is some information about my environment:

Arch linux ... Linux changry-laptop 4.0.1-1-ARCH #1 SMP PREEMPT Wed Apr 29 12:00:26 CEST 2015 x86_64 GNU/Linux ... 

```
[tobias@changry-laptop ~]$ pacman -S dmidecode
[tobias@changry-laptop ~]$ for keyword in baseboard-manufacturer baseboard-product-name baseboard-version system-manufacturer system-product-name system-version bios-vendor bios-version bios-release-date; do     printf "%-22s: " "$keyword";     sudo dmidecode -s "$keyword"; done
baseboard-manufacturer: # SMBIOS implementations newer than version 2.7 are not
# fully supported by this version of dmidecode.
 
baseboard-product-name: # SMBIOS implementations newer than version 2.7 are not
# fully supported by this version of dmidecode.
MS-16H2
baseboard-version     : # SMBIOS implementations newer than version 2.7 are not
# fully supported by this version of dmidecode.
REV:0.B
system-manufacturer   : # SMBIOS implementations newer than version 2.7 are not
# fully supported by this version of dmidecode.
 
system-product-name   : # SMBIOS implementations newer than version 2.7 are not
# fully supported by this version of dmidecode.
 
system-version        : # SMBIOS implementations newer than version 2.7 are not
# fully supported by this version of dmidecode.
To be filled by O.E.M.
bios-vendor           : # SMBIOS implementations newer than version 2.7 are not
# fully supported by this version of dmidecode.
American Megatrends Inc.
bios-version          : # SMBIOS implementations newer than version 2.7 are not
# fully supported by this version of dmidecode.
E16H2IG6.106
bios-release-date     : # SMBIOS implementations newer than version 2.7 are not
# fully supported by this version of dmidecode.
05/13/2014

[tobias@changry-laptop ~]$ bumblebeed -V
bumblebeed (Bumblebee) 3.2.1
```

**Comment by tobixen** [comment]
Logs etc at http://oppetid.no/~tobixen/bumblebee-bugreport-20150501_003420.tar.gz

**Comment by ArchangeGabriel** [comment]
I suspect VirtualGL not handling correctly your setup. Just use primusrun (or `optirun -b primus`, or set it as default in /etc/bumblebeee/bumblebee.conf) if you have no issue with it then, VirtualGL is here only for compatibility with some program.
