### ISSUE TITLE
in bumblebee.conf, PrimusLibraryPath always installing with /usr/lib32/primus

### ISSUE THREAD

**Issue by WhiteWolf1776** [Bumblebee-Project/Bumblebee#660]
I'm working back through the bumblebee git to see if I can find where this happened, but I am getting reports from slackware users that this is being set in the config improperly.

It should be (and was in the past working) set to:
PrimusLibraryPath=/usr/lib/primus:/usr/lib64/primus

now on new installs of bumblebee it is being set to:
PrimusLibraryPath=/usr/lib/primus:/usr/lib32/primus

I've tried passing in a compile argument to remedy this, and even patching the configure.ac as part of the slackware package build, but it is still obstinately setting itself to lib32.

Any ideas on how to get this set properly at build time so the users do not need to hand edit it?

Thanks.

**Comment by ArchangeGabriel** [comment]
What are the standard path in slackware? /usr/lib64 for 64bit lib and /usr/lib for 32bit lib? That looks a bit odd to me…

Anyway, setting it through CONF_PRIMUS_LD_PATH should work.

**Comment by WhiteWolf1776** [comment]
Yes, those are the standard paths, odd or not.  I have tried setting it through CONF_PRIMUS_LD_PATH but no matter what I set i get the paths described.  I have even tried just patching the configure.ac file manually... still no change to the path.

**Comment by ArchangeGabriel** [comment]
That’s look very odd. I see no reason where patching the configure.ac file directly wouldn’t work…

**Comment by WhiteWolf1776** [comment]
Yes, I'm sorry, I edited my comment as it did work, the patch anyway.  I'd prefer to just pass in a build var and not do the patch, but that does not work.

Sry for the confusion.

**Comment by ArchangeGabriel** [comment]
Sorry for the delay. This is very odd. The configure script should let you define the path at build time. It works for me (`./configure CONF_PRIMUS_LD_PATH=/usr/lib/primus:/usr/lib64/primus`), closing.
