### ISSUE TITLE
bbswitch: no suitable _DSM call found

### ISSUE THREAD

**Issue by h4xxflame** [Bumblebee-Project/Bumblebee#669]
Hello, im trying to setup bumblebee on my clevo w355st. but i cant load the bbswitch module, already tried bbswitch bbswitch-mainline bbswitch-dkms (archlinux). everytime i try to load the module i get the following error in dmesg: 
```
[  164.997431] bbswitch: No suitable _DSM call found.
[  231.577796] bbswitch: version 0.8
[  231.577802] bbswitch: Found integrated VGA device 0000:00:02.0: \_SB_.PCI0.GFX0
[  231.577807] bbswitch: Found discrete VGA device 0000:01:00.0: \_SB_.PCI0.PEG0.PEGP
[  231.577818] bbswitch: failed to evaluate \_SB_.PCI0.PEG0.PEGP._DSM {0xF8,0xD8,0x86,0xA4,0xDA,0x0B,0x1B,0x47,0xA7,0x2B,0x60,0x42,0xA6,0xB5,0xBE,0xE0} 0x100 0x0 {0x00,0x00,0x00,0x00}: AE_NOT_FOUND
[  231.577823] bbswitch: failed to evaluate \_SB_.PCI0.PEG0.PEGP._DSM {0xA0,0xA0,0x95,0x9D,0x60,0x00,0x48,0x4D,0xB3,0x4D,0x7E,0x5F,0xEA,0x12,0x9F,0xD4} 0x102 0x0 {0x00,0x00,0x00,0x00}: AE_NOT_FOUND
[  231.577829] bbswitch: failed to evaluate \_SB_.PCI0.GFX0._DSM {0xA0,0xA0,0x95,0x9D,0x60,0x00,0x48,0x4D,0xB3,0x4D,0x7E,0x5F,0xEA,0x12,0x9F,0xD4} 0x102 0x0 {0x00,0x00,0x00,0x00}: AE_NOT_FOUND
[  231.577830] bbswitch: No suitable _DSM call found.
```

**Comment by Lekensteyn** [comment]
Can you post/link more details (see README for acpidump).

**Comment by dodgyb** [comment]
Hi, I am seeing the same issue - believe it may be related to kernels 4.2 and 4.3.  Current setup is:
Intel 6600k / 530 HD / Nvidia 960 
Kubuntu 15.04 - kernel 4.2.0-040200-generic x86_64 / Intel i915.preliminary_hw_support / Nvidia 352.41

dmesg | grep bbswitch gives the following

[ 2249.881000] bbswitch: Found integrated VGA device 0000:00:02.0: \_SB_.PCI0.GFX0
[ 2249.881010] bbswitch: Found discrete VGA device 0000:01:00.0: \_SB_.PCI0.PEG0.PEGP
[ 2249.881034] bbswitch: failed to evaluate \_SB_.PCI0.PEG0.PEGP._DSM {0xF8,0xD8,0x86,0xA4,0xDA,0x0B,0x1B,0x47,0xA7,0x2B,0x60,0x42,0xA6,0xB5,0xBE,0xE0} 0x100 0x0 {0x00,0x00,0x00,0x00}: AE_NOT_FOUND
[ 2249.881048] bbswitch: failed to evaluate \_SB_.PCI0.PEG0.PEGP._DSM {0xA0,0xA0,0x95,0x9D,0x60,0x00,0x48,0x4D,0xB3,0x4D,0x7E,0x5F,0xEA,0x12,0x9F,0xD4} 0x102 0x0 {0x00,0x00,0x00,0x00}: AE_NOT_FOUND
[ 2249.882173] bbswitch: No suitable _DSM call found.

acpi dump file are here:

https://drive.google.com/file/d/0B0bHS25wwor4RGtTYm9uRXExMlU/view?usp=sharing

**Comment by ArchangeGabriel** [comment]
@h4xxflame @dodgyb Could you both open an issue in https://github.com/Bumblebee-Project/bbswitch/issues? This is the proper place for such issues.
