### ISSUE TITLE
primus: fatal: failed to query attributes when trying to combine primusrun with mumble-overlay

### ISSUE THREAD

**Issue by thisischrys** [Bumblebee-Project/Bumblebee#673]
I'm trying to run a minecraft launcher with both primusrun and mumble-overlay (an overlay for a voip program)
I tried primusrun mumble-overlay java -jar MCUpdater.jar and reversed
Both result in the same error.

**Comment by ArchangeGabriel** [comment]
Please report against primus if you still face this issue. And post more logs, not in the title if possible. ;)
