### ISSUE TITLE
WebGL crashes in Chromium (and Firefox)

### ISSUE THREAD

**Issue by spike-spb** [Bumblebee-Project/Bumblebee#674]
Hello!
The Chromium project dev team recommended me to report an issue here, see https://code.google.com/p/chromium/issues/detail?id=509346
(there is full description of the bug).
I have Bumblebee v.3.2.1,
Acer Aspire E15, Nvidia GeForce 840M
64 bit platform.

**Comment by gsgatlin** [comment]
Here are some ideas you can try. Try adding command line arguments such as

primusrun chromium-browser --ignore-gpu-blacklist --disable-gpu-sandbox https://www.chromeexperiments.com/webgl

try also typing

chrome://gpu/

in the URL bar when running chromium with and without primusrun to see if you notice anything obviously different.

Does firefox work if you run it normally with the intel GPU? (no primusrun)

Does chromium crash if you use the intel GPU?  Does the intel GPU show extremely slow graphics with chromium and webgl? The reason I ask is that I would probably personally never launch a web browser using the nvidia GPU as I think the intel GPU is powerful enough for pretty much most web browsing tasks. 

This is similar to why I would never watch videos with vlc or mplayer + primusrun or optirun with the virtualgl bridge. It would just waste power and give sub par performance with lots of video tearing. So I'm guessing watching videos in a web browser started this way will also have similar problems. Anyone feel free to correct me if I'm wrong about that.

**Comment by gsgatlin** [comment]
Sorry. Ignore question about firefox. Was reading info in the google bug tracker wrong.

**Comment by spike-spb** [comment]
If I start Chromium without webgl, get.webgl.org gives me this message:
"Hmm. While your browser seems to support WebGL, it is disabled or unavailable. If possible, please ensure that you are running the latest drivers for your video card."

chrome://gpu log:
GPU process was unable to boot: GPU process launch failed.

```
Log Messages
[31060:31060:0716/013800:ERROR:gl_context_glx.cc(55)] : Failed to create GL context with glXCreateContextAttribsARB.
[31060:31060:0716/013800:ERROR:gpu_info_collector.cc(41)] : gfx::GLContext::CreateGLContext failed
[31060:31060:0716/013800:ERROR:gpu_info_collector.cc(95)] : Could not create context for info collection.
[31060:31060:0716/013800:ERROR:gpu_main.cc(402)] : gpu::CollectGraphicsInfo failed (fatal).
GpuProcessHostUIShim: The GPU process exited normally. Everything is okay.
```
I am not sure.. is this Intel video driver bug?

>primusrun chromium-browser --ignore-gpu-blacklist --disable-gpu-sandbox https://www.chromeexperiments.com/webgl

That helped. Still sometimes webgl stops working (most of the times when the notebook wakes up from stand by mode).

**Comment by despairblue** [comment]
`primusrun chromium-browser --ignore-gpu-blacklist --disable-gpu-sandbox` works for me, but chrome won't survive a suspend.

**Comment by ArchangeGabriel** [comment]
Are this issues still existing? If so, could you make a proper summary of what works, what don’t, and what informations you have about those last cases.

**Comment by ArchangeGabriel** [comment]
No answer, closing.

**Comment by alem0lars** [comment]
I'm still having this issue. After suspend, chromium hangs on Linux
