### ISSUE TITLE
bumblebee-project.org is down.

### ISSUE THREAD

**Issue by srhb** [Bumblebee-Project/Bumblebee#676]

**Comment by Lekensteyn** [comment]
For now I copied the webroot to a different server (and additionally added IPv6 support). TTL was 1h, so it should slowly show up. Thanks for reporting!

@Thulinma do you plan to fix 93.191.133.101 or leave it like this? SSH is still running, but http appears dead.

**Comment by Lekensteyn** [comment]
Changed it and verified it is working again! Thanks @Thulinma

**Comment by Thulinma** [comment]
No problem! Sorry for forgetting to mention the IP changes. :-(
