### ISSUE TITLE
Complete freeze at bbswitch call

### ISSUE THREAD

**Issue by jayzrnr** [Bumblebee-Project/Bumblebee#682]
I have Ubuntu 15.04 running on my Asus UL30VT laptop.
This laptop has a discrete nvidia graphics I'd like to switch permanently off in order to save energy. I just installed the "bumblebee" package without any nvidia drivers.
sudo apt-get install --no-install-recommends bumblebee

uname -a:
Linux jaybox 3.19.0-16-generic #16-Ubuntu SMP Thu Apr 30 16:09:58 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

However, certain actions cause a total freeze of the system:
- suspend
- shutdown
- cat /proc/acpi/bbswitch
- echo OFF > /proc/acpi/bbswitch

This means I cannot check whether the discrete card is switched off or not.

dmesg: http://pastebin.com/y5kmWA9A
/var/log/Xorg.0.log: http://pastebin.com/ze2f3fV0
/var/log/Xorg.0.log.old: http://pastebin.com/mje2hFLB

Do you have any suggestions for what I could try?

**Comment by oanonymos0** [comment]
sorry for the late answer, but i'm new here!!
I suggest you follow these instructions in the answer:
http://askubuntu.com/questions/660913/nvidia-driver-and-heating-problem/662662#662662

When i boot, the card is off (cat /proc/acpi/bbswitch), so it doesn't waste energy!

**Comment by ArchangeGabriel** [comment]
Please report against bbswitch. This might be related to https://github.com/Bumblebee-Project/bbswitch/issues/114.
