### ISSUE TITLE
Turn off GPU by default

### ISSUE THREAD

**Issue by aseempatni** [Bumblebee-Project/Bumblebee#685]
I want to keep graphic card (GT 650M) turned off by default and use it only when i explicitly specify.
I'm unable to do that using bumblebee. By default both integrated and discrete graphic cards are active. Can anyone please help me out.

When I run `sudo bumblebeed --debug` I get 
```
[  838.421478] [DEBUG]bbswitch has been detected.
[  838.421542] [INFO]Switching method 'bbswitch' is available and will be used.
[  838.421562] [DEBUG]Active configuration:
[  838.421579] [DEBUG] bumblebeed config file: /etc/bumblebee/bumblebee.conf
[  838.421597] [DEBUG] X display: :8
[  838.421616] [DEBUG] LD_LIBRARY_PATH: 
[  838.421635] [DEBUG] Socket path: /var/run/bumblebee.socket
[  838.421652] [DEBUG] pidfile: /var/run/bumblebeed.pid
[  838.421670] [DEBUG] xorg.conf file: /etc/bumblebee/xorg.conf.nouveau
[  838.421688] [DEBUG] xorg.conf.d dir: /etc/bumblebee/xorg.conf.d
[  838.421706] [DEBUG] ModulePath: 
[  838.421723] [DEBUG] GID name: bumblebee
[  838.421740] [DEBUG] Power method: auto
[  838.421756] [DEBUG] Stop X on exit: 1
[  838.421775] [DEBUG] Driver: nouveau
[  838.421792] [DEBUG] Driver module: nouveau
[  838.421808] [DEBUG] Card shutdown state: 1
[  838.421962] [DEBUG]Process /sbin/modprobe started, PID 4322.
[  838.422041] [DEBUG]Hiding stderr for execution of /sbin/modprobe
[  838.424352] [DEBUG]SIGCHILD received, but wait failed with No child processes
[  838.424413] [DEBUG]Configuration test passed.
[  838.425121] [INFO]bumblebeed 3.2.1 started
[  838.425562] [INFO]Unloading nvidia driver
[  838.425740] [DEBUG]Process rmmod started, PID 4323.
rmmod: ERROR: Module nvidia is in use
[  838.427021] [DEBUG]Process with PID 4323 returned code 1
[  841.441530] [ERROR]Unloading nvidia driver timed out.
[  841.441628] [DEBUG]Drivers are still loaded, unable to disable card
[  841.441653] [INFO]Initialization completed - now handling client requests
```

It is unable to unload nvidia driver. Any help would be greatly appreciated.

**Comment by amonakov** [comment]
Your bumblebee configuration is set to use Nouveau rather that nVidia. This is unusual and probably not useful, since Nouveau in modern kernels should on its own turn off the card when not in use.

Bumblebee (bbswitch to be precise) doesn't turn off the card because the nvidia module is loaded when you start the daemon (which is also unusual). You can see if there are processes using the nvidia device with this command: `sudo fuser -v /dev/nvidia*`.

If the nvidia-uvm module is loaded, it may also prevent nvidia from unloading, depending on your distribution.

**Comment by aseempatni** [comment]
Thanks for the quick reply. I'm using Ubuntu 14.04 with `nvidia-346` 
```
$ sudo fuser -v /dev/nvidia*
                     USER        PID ACCESS COMMAND
/dev/nvidia0:        root      11800 F...m Xorg
/dev/nvidiactl:      root      11800 F...m Xorg
```
nouveau module isn't loaded. Checked it using `$ lsmod | grep -i nouveau`
```
$ lsmod | grep -i nvidia
nvidia               8379750  27 
drm                   303102  5 i915,drm_kms_helper,nvidia
```
although 
```
$ dpkg -l | grep nouveau
ii  libdrm-nouveau2:amd64                                       2.4.60-2~ubuntu14.04.1                              amd64        Userspace interface to nouveau-specific kernel DRM services -- runtime
ii  libdrm-nouveau2:i386                                        2.4.60-2~ubuntu14.04.1                              i386         Userspace interface to nouveau-specific kernel DRM services -- runtime
ii  xserver-xorg-video-nouveau                                  1:1.0.10-1ubuntu2                                   amd64        X.Org X server -- Nouveau display driver
```
```
$ lspci -nnk | grep -iA2 vga 
00:02.0 VGA compatible controller [0300]: Intel Corporation 3rd Gen Core processor Graphics Controller [8086:0166] (rev 09)
	Subsystem: Samsung Electronics Co Ltd Device [144d:c0d1]
	Kernel driver in use: i915
--
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GK107M [GeForce GT 650M] [10de:0fd1] (rev a1)
	Subsystem: Samsung Electronics Co Ltd Device [144d:c0d1]
	Kernel driver in use: nvidia
```
Nvidia driver is in use and not nouveau. So, Is the problem with bumblebee config? It is set to auto detect the Driver(`Driver=`). And I think it is detecting nouveau instead of nvidia (maybe because nouveau is present). Should I manually change bumblebee config to `Driver=nvidia`? Or should I uninstall nouveau packages? Shouldn't it be automatically detecting nvidia?

**Comment by amonakov** [comment]
`bumblebeed --debug` dumps the auto-detection decision early on: it's not visible in the above log because you've trimmed too much

Since you're on ubuntu, your X server is probably set up to run on the nvidia card via nvidia-prime package, in which case you can switch from the nvidia-settings GUI (for next login or reboot). If you want per-application switching, you'll have to uninstall nvidia-prime first before using bumblebee, afaik.

**Comment by ArchangeGabriel** [comment]
@aseempatni Where you able to figure out your issue?

**Comment by ArchangeGabriel** [comment]
No answer, closing.
