### ISSUE TITLE
PowerMizer stuck at Level 0

### ISSUE THREAD

**Issue by src386** [Bumblebee-Project/Bumblebee#687]
Hi,
I'm going crazy...
I can use primusrun or optirun, it works but it's slower than Intel GPU.

    optirun -b none nvidia-settings -c :8

Show that PowerMizer is stuck at Level 0, that's the explaination.
No matter what I select in "Prefered mode" it's still at Level 0...
So KSP is not playable...

Kernel 4.1.7-1-MANJARO
Nvidia 355.11

**Comment by gsgatlin** [comment]
See: https://forums.opensuse.org/showthread.php/410089-NVidia-Powermizer-how-to-tweak

I think you might want to edit the xorg file under /etc/bumblebee/

**Comment by src386** [comment]
Excellent lead but unfortunately this doesnt works.
/etc/bumblebee/xorg.conf.nvidia : 

    Section "ServerLayout"
        Identifier "Layout0"
        Option "AutoAddDevices" "false"
    EndSection

    Section "Device"
        Identifier  "Device1"
        Driver      "nvidia"
        VendorName "NVIDIA Corporation"
        Option "NoLogo" "true"
        Option "UseEDID" "false"
        Option "ConnectedMonitor" "DFP"
        Option "RegistryDwords" "PowerMizerEnable=0x0; PerfLevelSrc=0x2222; PowerMizerDefault=0x3; PowerMizerDefaultAC=0x3"
    EndSection

**Comment by karolherbst** [comment]
@src386 try to connect disconnect AC after starting optirun. Maybe under some circumstences the blob refuses to go into higher states, when battery mode is detected?

**Comment by src386** [comment]
@karolherbst : Yeah !!! On AC adapter it works.
Thanks.
