### ISSUE TITLE
 systemd-logind: failed to get session

### ISSUE THREAD

**Issue by latot** [Bumblebee-Project/Bumblebee#689]
Hi ppl, here a issue, try runnings optirun glxgears i recieve this error, here logs:

lsmod > https://gist.github.com/latot/78862b12d77bec41e07a#file-lsmod-1-bumblebee
optirun glxgears > https://gist.github.com/latot/78862b12d77bec41e07a#file-optirun-bumblebee
lsmod > https://gist.github.com/latot/78862b12d77bec41e07a#file-lsmod-2-bumblebee
journal > https://gist.github.com/latot/78862b12d77bec41e07a#file-journal-bumblebee
Xorg > https://gist.github.com/latot/78862b12d77bec41e07a#file-xorg-bumblebee
dmesg > https://gist.github.com/latot/78862b12d77bec41e07a#file-dmesg-bumblebee

i'm using gentoo 64.

Here confs:

bumblebee.conf > https://gist.github.com/latot/78862b12d77bec41e07a#file-bumblebee-conf
xorg.conf.nvidia > https://gist.github.com/latot/78862b12d77bec41e07a#file-xorg-conf-nvidia

Thx.

**Comment by karolherbst** [comment]
@latot:
what is the issue?

**Comment by karolherbst** [comment]
also it is quite obviously what the real issue is: (EE) Failed to load module "nvidia" (module does not exist, 0)

**Comment by latot** [comment]
ups, well first, is the message : 
systemd-logind: failed to get session: PID 3081 does not belong to any known session

next is the message of (EE) Failed to load module "nvidia" (module does not exist, 0)

but you can see it exist and is loaded by optirun, its very weird, and the next

(EE) /dev/dri/card0: failed to set DRM interface version 1.4: Permission denied

I do not know which of these actually generates the problem, ..

**Comment by karolherbst** [comment]
obviously the nvidia one

**Comment by latot** [comment]
i really don't know why the message, the nvidia module exist and is loaded correctly with optirun, you can see it in lsmod, and i can manually load and unload it...

**Comment by karolherbst** [comment]
I think you need to adjust XorgModulePath in the bumblebe.conf file.

I use something like this: /usr/lib64/opengl/nvidia/lib,/usr/lib64/opengl/nvidia/extensions,/usr/lib64/xorg/modules/drivers,/usr/lib64/xorg/modules

**Comment by karolherbst** [comment]
but you may have to adjust this to the paths on your system

**Comment by karolherbst** [comment]
mhhh, if you installed the nvidia-drivers package right, it should be alright, maybe the installation is somewhat messed up? I would try reinstalling the package or check if you find any other error somewhere else :/

**Comment by karolherbst** [comment]
there should be this file: /usr/lib64/xorg/modules/drivers/nvidia_drv.so

**Comment by latot** [comment]
are you right, some files are missed, for some reason now the system mask the X use flag in the nvidia-drivers package.
If some one have the same issue here the solution
write in /etc/portage/profile/package.use.mask/{some file}
x11-drivers/nvidia-drivers -X
and emerge --with-bdeps=y -aUDNu @world

Thx.
