### ISSUE TITLE
problem with thinkpad 450s on Centos 7.1

### ISSUE THREAD

**Issue by oglops** [Bumblebee-Project/Bumblebee#690]
my t450s got optimus with nvidia 940m card, I followed the [elrepo wiki](http://elrepo.org/tiki/bumblebee)
after reboot, `optirun glxifo` works,`glxinfo` shows
```
Xlib:  extension "GLX" missing on display ":0.0".
```
and I found this in xorg.0.log
```
(EE) Failed to initialize GLX extension (Compatible NVIDIA X driver not found)
```

so then I went ahead to swap the two lines in `/etc/X11/xorg.conf.d/99-nvidia.conf`
and it looks like this now
```
Section "Files"
        ModulePath   "/usr/lib64/xorg/modules"
        ModulePath   "/usr/lib64/xorg/modules/extensions/nvidia"
EndSection
```
after reboot, in xorg.0.log, the error changes to 
```
(EE) AIGLX error: dlopen of /usr/lib64/dri/i965_dri.so failed
```
so then I did 
```
yum reinstall mesa-libGL  mesa-dri-drivers
```
after reboot, glxinfo has no errors, but direct rendering is off
```
[oglop@t450s Downloads]$ LIBGL_DEBUG=verbose glxinfo
name of display: :0
display: :0  screen: 0
direct rendering: No (If you want to find out why, try setting LIBGL_DEBUG=verbose)
server glx vendor string: SGI
server glx version string: 1.4
server glx extensions:
    GLX_ARB_create_context, GLX_ARB_create_context_profile, 
    GLX_ARB_create_context_robustness, GLX_ARB_fbconfig_float, 
    GLX_ARB_framebuffer_sRGB, GLX_ARB_multisample, 
    GLX_EXT_create_context_es2_profile, GLX_EXT_framebuffer_sRGB, 
    GLX_EXT_import_context, GLX_EXT_texture_from_pixmap, GLX_EXT_visual_info, 
    GLX_EXT_visual_rating, GLX_INTEL_swap_event, GLX_MESA_copy_sub_buffer, 
    GLX_OML_swap_method, GLX_SGIS_multisample, GLX_SGIX_fbconfig, 
    GLX_SGIX_pbuffer, GLX_SGIX_visual_select_group, GLX_SGI_swap_control
client glx vendor string: NVIDIA Corporation
client glx version string: 1.4
client glx extensions:
    GLX_ARB_context_flush_control, GLX_ARB_create_context, 
    GLX_ARB_create_context_profile, GLX_ARB_create_context_robustness, 
    GLX_ARB_fbconfig_float, GLX_ARB_get_proc_address, GLX_ARB_multisample, 
    GLX_EXT_buffer_age, GLX_EXT_create_context_es2_profile, 
    GLX_EXT_create_context_es_profile, GLX_EXT_fbconfig_packed_float, 
    GLX_EXT_framebuffer_sRGB, GLX_EXT_import_context, GLX_EXT_stereo_tree, 
    GLX_EXT_swap_control, GLX_EXT_swap_control_tear, 
    GLX_EXT_texture_from_pixmap, GLX_EXT_visual_info, GLX_EXT_visual_rating, 
    GLX_NV_copy_buffer, GLX_NV_copy_image, GLX_NV_delay_before_swap, 
    GLX_NV_float_buffer, GLX_NV_multisample_coverage, GLX_NV_present_video, 
    GLX_NV_swap_group, GLX_NV_video_capture, GLX_NV_video_out, 
    GLX_SGIX_fbconfig, GLX_SGIX_pbuffer, GLX_SGI_swap_control, 
    GLX_SGI_video_sync
GLX version: 1.4
GLX extensions:
    GLX_ARB_create_context, GLX_ARB_create_context_profile, 
    GLX_ARB_create_context_robustness, GLX_ARB_fbconfig_float, 
    GLX_ARB_get_proc_address, GLX_ARB_multisample, 
    GLX_EXT_create_context_es2_profile, GLX_EXT_framebuffer_sRGB, 
    GLX_EXT_import_context, GLX_EXT_texture_from_pixmap, GLX_EXT_visual_info, 
    GLX_EXT_visual_rating, GLX_SGIX_fbconfig, GLX_SGIX_pbuffer, 
    GLX_SGI_swap_control
OpenGL vendor string: 
OpenGL renderer string: 
OpenGL version string: 
OpenGL extensions:


```

what can I do to enable opengl for intel and nvidia 940m at the same time ? optirun something always works, so I guess bumblebee is mostly working ?

thanks !

**Comment by karolherbst** [comment]
short: your entire gl setup is bricked by your tinkering in etc/X11/xorg.conf.d/99-nvidia.conf

you don't need this file, so maybe if you are lucky, you can simply remove it, restart X and it may work.

**Comment by gsgatlin** [comment]
I'm doing packages for fedora and I also made packages for RHEL/centos 6/7. Here are some crude docs which may help you out to get the packages from my "third party repo" at install.linux.ncsu.edu:

http://fpaste.org/225738/64146143/

I'm trying to write something better but no idea when it would be ready.

I think the guy doing the elrepo stuff has switched to fedora and is no longer supporting it. At least thats what he told me in an email.

**Comment by karolherbst** [comment]
@gsgatlin 

maybe it would make more sense to try to convince distribution not to mess up the gl setup, when just installing nvidia-drivers :/ because this is mostly the main reason why stuff like that happens

**Comment by gsgatlin** [comment]
@karolherbst Hes following instructions and packages I did not create or have anything to do with. I made my own drivers package that does not conflict with the system libraries or drop and xorg.conf for this reason. The ones in the semi official repos don't work with optimus hardware. I would have turned my attention to trying to file bug reports at elrepo or rpmfusion but I'm having trouble even getting the 100% free stuff into fedora. The latest problem is that bumblebee + nouveau does not work with gdm though it does work with other login managers such as lightdm or kdm. I have not had time to figure out exactly what broke it yet. It broke somewhere  after gdm-3.14.2 and before or in gdm-3.16.1.1. :(

The nvidia drivers can't be included in Red Hat or fedora or centos due to the closed nature of them and the rules of the distros about such things.  They have to go in third party external repositories. Like in fedora there are at least 3 different nvidia drivers in use by people. The ones at rpmforge (no optimus support) The ones at negativo.org ( no optimus support, author says bumblebee is bad and a "hack" ) and the drivers I made for myself which do work with bumblebee. Which is why I suggested to @oglops he might have better luck with my packages. Can't say for sure however. But the last time I checked it worked fine on centos 7. I tested it with minecraft.

Cheers.

**Comment by karolherbst** [comment]
messy :/ but with nouveau you should go with DRI_PRIME anyway (better performance), so this only concerns nvidia prop driver.

**Comment by gsgatlin** [comment]
@oglops My suggestion would be to undo everything you did or do a fresh centos 7 install.

Next add bumblebee repo:
 
yum -y --nogpgcheck install http://install.linux.ncsu.edu/pub/yum/itecs/public/bumblebee/rhel7/noarch/bumblebee-release-1.2-1.noarch.rpm
 
add bumblebee nonfree repo for the nvidia driver:

yum -y --nogpgcheck install http://install.linux.ncsu.edu/pub/yum/itecs/public/bumblebee-nonfree/rhel7/noarch/bumblebee-nonfree-release-1.2-1.noarch.rpm

Then run:

yum install bumblebee-nvidia bbswitch primus kernel-devel

(VirtualGL and bumblebee will get pulled in as dependencies)

Then when its finished, reboot. Hope that helps.

**Comment by gsgatlin** [comment]
One more thing I forgot, you'll need to add EPEL repo first for dkms and also VirtuaGL. 

yum install epel-release

https://fedoraproject.org/wiki/EPEL

**Comment by oglops** [comment]
oh so much replys! thanks guys. 
update: I got it working now but the performace is so bad that it's even worse than the integrated intel card, I can't beleive it.

the additional steps I did were
```
rm /etc/ld.so.conf.d/nvidia.conf
ldconfig
```

flip the module search path in /etc/X11/xorg.conf.d/99-nvidia.conf
```
Section "Files"
        ModulePath   "/usr/lib64/xorg/modules"
        ModulePath   "/usr/lib64/xorg/modules/extensions/nvidia"
EndSection
```

reinstall mesa
```
yum reinstall mesa-libGL  mesa-dri-drivers
```

after I have done all of the above, and reboot, it works but the performance is terrible.

```
[oglop@t450s]$ vblank_mode=0  glxspheres64
Polygons in scene: 62464 (61 spheres * 1024 polys/spheres)
ATTENTION: default value of option vblank_mode overridden by environment.
ATTENTION: default value of option vblank_mode overridden by environment.
Visual ID of window: 0x20
Context is Direct
OpenGL Renderer: Mesa DRI Intel(R) HD Graphics 5500 (Broadwell GT2)
183.579885 frames/sec - 204.875151 Mpixels/sec
 
 
# worse than intel hd5550?
[oglop@t450s]$ vblank_mode=0 optirun glxspheres64
Polygons in scene: 62464 (61 spheres * 1024 polys/spheres)
Visual ID of window: 0x20
Context is Direct
OpenGL Renderer: GeForce 940M/PCIe/SSE2
76.068009 frames/sec - 84.891898 Mpixels/sec
77.826314 frames/sec - 86.854166 Mpixels/sec


# I then tried primus, it's a little bit better then optiun, but fps is still so low.
[oglop@t450s]$ vblank_mode=0 optirun -b primus  glxspheres64
Polygons in scene: 62464 (61 spheres * 1024 polys/spheres)
ATTENTION: default value of option vblank_mode overridden by environment.
ATTENTION: default value of option vblank_mode overridden by environment.
Visual ID of window: 0x20
Context is Direct
OpenGL Renderer: GeForce 940M/PCIe/SSE2
ATTENTION: default value of option vblank_mode overridden by environment.
ATTENTION: default value of option vblank_mode overridden by environment.
91.711972 frames/sec - 102.350561 Mpixels/sec
91.697643 frames/sec - 102.334569 Mpixels/sec
```

What is happening here ? Am I doing something wrong ?

**Comment by karolherbst** [comment]
glxspheres is _not_ a benchmark

**Comment by gsgatlin** [comment]
I'm sorry. I can't help you with the elrepo driver or Rob Mokkink's rpm packages. Best of luck though.

**Comment by oglops** [comment]
@karolherbst oh I didn't know that. Then what is the proper way to benchmark ?

**Comment by karolherbst** [comment]
@oglops I think unigine heaven benchmark is a pretty good indicator

**Comment by karolherbst** [comment]
or some games actually

**Comment by karolherbst** [comment]
@oglops the big problem is though, that the intel hd 5500 is pretty fast already, and the nvidia 740M isn't _that_ much faster. The overhead in bumblebee can actually cause that the intel card may run faster. Try primusrun in any case, it should perform better than optirun.

**Comment by karolherbst** [comment]
@oglops do you know if you got the DDR3 or GDDR5 version of the 740M? Because if it's the former, the intel card actually has doubled memory speed, which would kind of suck

**Comment by oglops** [comment]
@karolherbst It's a nvidia 940m card
```
[oglop@t450s ~]$ lspci | grep -i "vga\|nvidia"
00:02.0 VGA compatible controller: Intel Corporation Broadwell-U Integrated Graphics (rev 09)
04:00.0 3D controller: NVIDIA Corporation GM108M [GeForce 940M] (rev a2)

[oglop@t450s ~]$ lspci -v -s 04:00.0
04:00.0 3D controller: NVIDIA Corporation GM108M [GeForce 940M] (rev a2)
        Subsystem: Lenovo Device 5037
        Flags: fast devsel, IRQ 16
        Memory at f1000000 (32-bit, non-prefetchable) [size=16M]
        Memory at c0000000 (64-bit, prefetchable) [size=256M]
        Memory at d0000000 (64-bit, prefetchable) [size=32M]
        I/O ports at 3000 [size=128]
        Expansion ROM at <ignored> [disabled]
        Capabilities: <access denied>

```
[Imgur](http://i.imgur.com/0ejc31s.png)

**Comment by oglops** [comment]
![unigine benchmark basic configuration](http://i.imgur.com/DjrtKDG.png)

intel hd5500
`MESA_EXTENSION_OVERRIDE="-GL_ARB_sample_shading" ./heaven`
![intel](http://i.imgur.com/uw5w0JH.png)

`optiurn ./heaven`
![bumblebee](http://i.imgur.com/XVQPafQ.png)

`optiurn -b primus ./heaven`
![primus](http://i.imgur.com/S6MLeiE.png)

is this normal?

**Comment by karolherbst** [comment]
well, short: your nvidia gpu and motherboard sucks.

1. you only have DDR3 memory on your nvidia gpu, shortly this means memory operations are faster with intel
2. you only have 5.0 pcie speed, this is important for prime, because the rendered frames have to be copied over the pcie bus.

under these circumstances, yes it is normal, and basically you won't get much more performance with your nvidia card. I am often telling it, that it doesn't make sense to build a weak dedicated nvidia/amd gpu into a laptop, when the intel gpu is fast enough already.

I mean it is still +50%, but so it is also "only" + 50%

**Comment by karolherbst** [comment]
@oglops you should have bought a laptop with an intel HD 6x00 instead, they have more performance than a 740M and you don't have to mess with all that prime stuff.

**Comment by ArchangeGabriel** [comment]
Closing this, the OP has a working system with technically expected perfs even if those are disappointing.
