### ISSUE TITLE
Nvidia doesn't turn off after use

### ISSUE THREAD

**Issue by wyvie** [Bumblebee-Project/Bumblebee#691]
After a recent update on my debian testing nvidia stopped being turned off after i quit the application run through primus. When system starts, nvidia is off, everything's fine, intel is used.
Then i start using nvidia for some game, nvidia turns off, give nice graphics and good fps, and doesn't turn off when i quit the game.
What could i do to get rid of the problem or at leas troubleshoot it?

**Comment by karolherbst** [comment]
@wyvie isn't it the same as https://github.com/Bumblebee-Project/Bumblebee/issues/565 but with nvidia-modeset still being loaded?

**Comment by wyvie** [comment]
@karolherbst it might be. thanks, i'll take a look a little bit later and respond then!

**Comment by wyvie** [comment]
I don't have the nvidia_uvm module loaded, the only one loaded is nvidia after primus application is turned off:

wv@i-rum:~$ primusrun glxgears
^C
wv@i-rum:~$ cat /proc/acpi/bbswitch 
0000:01:00.0 ON
wv@i-rum:~$ lsmod | grep nvidia
nvidia              10559488  0
drm                   352256  6 i915,drm_kms_helper,nvidia
wv@i-rum:~$ sudo rmmod nvidia
wv@i-rum:~$ sudo service bumblebeed restart
wv@i-rum:~$ cat /proc/acpi/bbswitch 
0000:01:00.0 OFF

**Comment by karolherbst** [comment]
ohh mhh, maybe you should look into /etc/bumblebee.conf and check there

**Comment by karolherbst** [comment]
the important bits are:

KeepUnusedXServer=false
PMMethod=bbswitch or auto in [nvidia] section

**Comment by wyvie** [comment]
KeepUnusedXServer is false
PMMethod was auto, switched it to bbswitch, didn't help

Also tried to reinstall the whole bumblebee and nvidia software, didn't help :/

**Comment by amonakov** [comment]
Try to find out why unloading the module fails. For example, stop the bumblebee service and run `sudo bumblebeed --debug` to get debug logs. Also `sudo fuser -v /dev/nvidia*` can be used to show processes using the nvidia driver (if any).

**Comment by wyvie** [comment]
That's what happening:

[  242.700519] [INFO]Unloading nvidia driver
[  242.700603] [DEBUG]Process modprobe started, PID 3109.
modprobe: FATAL: Module nvidia not found.
[  242.701203] [DEBUG]Process with PID 3109 returned code 1
[  245.706761] [ERROR]Unloading nvidia driver timed out.
[  245.706801] [DEBUG]Drivers are still loaded, unable to disable card

Looks like modprobe -r can't unload nvidia, because can't find id, but rmmod can and makes it happen. So strange.

**Comment by wyvie** [comment]
wv@i-rum:~$ sudo modprobe -r nvidia
modprobe: FATAL: Module nvidia not found.
wv@i-rum:~$ sudo rmmod nvidia

**Comment by amonakov** [comment]
Sounds like the bumblebee package was updated to use `modprobe -r` instead of `rmmod`, but your nvidia drivers package does not install module aliases required to make that work.

Cc: @vincent-c

**Comment by wyvie** [comment]
Could you give me a hint on which aliases i need? I'll try to make my own driver package then :)

**Comment by amonakov** [comment]
If you're using current Debian packages, in `/etc/nvidia/nvidia-modprobe.conf` there should be:
```
install nvidia modprobe -i nvidia-current $CMDLINE_OPTS

install nvidia-uvm modprobe nvidia ; modprobe -i nvidia-current-uvm $CMDLINE_OPTS

remove nvidia modprobe -r -i nvidia-uvm nvidia
```

I think the last clause requires `alias nvidia nvidia-current` (and ditto for -uvm) to work, but the alias was [removed](http://anonscm.debian.org/viewvc/pkg-nvidia/packages/nvidia-graphics-drivers/trunk/debian/nvidia-modprobe.conf.in?r1=5450&r2=5507) as part of fixing [a debian bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=798207).

I suspect they didn't check if `modprobe -r` still works? Please file a Debian bug.

**Comment by wyvie** [comment]
Weell after some time i managed to file a bug. Even two bugs actually, 802245 and 802246.
Hope i won't get punished for that.
Thank you.

**Comment by wyvie** [comment]
Issue fixed now. Thank you all very much!
