### ISSUE TITLE
Thermal throttling not happening with prime

### ISSUE THREAD

**Issue by oanonymos0** [Bumblebee-Project/Bumblebee#693]
Ubuntu 14.04.3 i5-3210M GT 650M Samsung NP550P5C kernel 3.19 xorg 1.17 nvidia-352

ALL games start limiting their framerates from ~50 to ~15-20 after a few minutes using bumblebee
then go up again, symptoms of thermal throttling...

That didn't happen using nvidia-prime and nvidia-331 (and prime doesn't work with newer drivers for me)!

Cleaning my laptop/swapping thermal paste helped a lot but the problem is still noticeable, especially in wine games..

Changing drivers/kernel didn't help...

For some strange reason with bumblebee throttling is present...
Games start lagging when GPU reaches 83C and CPU 90C..and then throttling happens until GPU reaches 78C and CPU reaches 83C, this doesn't happen on windows 8.1 either.

Also, with prime i could reach 90C+ on GPU (and more on cpu) with no problems whatsoever
CPU usage is at most 60%.

It happens no matter if i use primusrun/optirun and change their specific environment variables.

Tested all drivers from nvidia-340 all the way to nvidia-352 from ppa:mamarley/nvidia
and kernel 3.13-3.19

Any ideas?
Anyone having or once had the same issue?
Anything i can do to help you debug?

**Comment by amonakov** [comment]
`PRIMUS_VERBOSE=2 primusrun ...` will print primus perf data in the terminal. Would be interesting to see how it compares in slow/fast situations.

Also, try running Wine pinned to one core (`taskset -c 0 wine ...`) and look at CPU load at first core. When pinned like that, `PRIMUS_SYNC=1` may help.

**Comment by oanonymos0** [comment]
kk going to do that right now

**Comment by oanonymos0** [comment]
fast: primus: profiling: readback: 1309x747, 46.5 fps, 23.6% app, 68.2% sleep, 7.6% map, 0.6% wait
primus: profiling: display: 1309x747, 46.5 fps, 95.1% wait, 2.8% upload, 2.1% draw+swap
primus: profiling: readback: 1309x747, 35.1 fps, 51.0% app, 44.0% sleep, 4.8% map, 0.2% wait
primus: profiling: display: 1309x747, 35.1 fps, 96.4% wait, 2.1% upload, 1.4% draw+swap
primus: profiling: readback: 1309x747, 40.0 fps, 38.8% app, 54.9% sleep, 6.2% map, 0.1% wait
primus: profiling: display: 1309x747, 40.0 fps, 95.8% wait, 2.4% upload, 1.8% draw+swap
primus: profiling: readback: 1309x747, 47.5 fps, 20.4% app, 71.4% sleep, 7.9% map, 0.3% wait
primus: profiling: display: 1309x747, 47.6 fps, 94.8% wait, 2.9% upload, 2.3% draw+swap
primus: profiling: readback: 1309x747, 46.5 fps, 23.2% app, 69.0% sleep, 7.5% map, 0.3% wait
primus: profiling: display: 1309x747, 46.5 fps, 94.8% wait, 2.9% upload, 2.3% draw+swap
primus: profiling: readback: 1309x747, 42.3 fps, 23.6% app, 68.7% sleep, 7.7% map, 0.1% wait
primus: profiling: display: 1309x747, 42.3 fps, 95.5% wait, 2.6% upload, 1.9% draw+swap
primus: profiling: readback: 1309x747, 41.0 fps, 28.0% app, 64.6% sleep, 7.2% map, 0.2% wait
primus: profiling: display: 1309x747, 41.0 fps, 95.8% wait, 2.5% upload, 1.8% draw+swap
primus: profiling: readback: 1309x747, 48.5 fps, 23.8% app, 68.5% sleep, 7.4% map, 0.3% wait
primus: profiling: display: 1309x747, 48.5 fps, 94.9% wait, 3.1% upload, 2.0% draw+swap
primus: profiling: readback: 1309x747, 43.3 fps, 22.3% app, 69.6% sleep, 7.8% map, 0.3% wait
primus: profiling: display: 1309x747, 43.3 fps, 95.3% wait, 2.8% upload, 1.9% draw+swap
primus: profiling: readback: 1309x747, 43.1 fps, 38.8% app, 54.7% sleep, 5.8% map, 0.6% wait
primus: profiling: display: 1309x747, 43.1 fps, 95.4% wait, 2.7% upload, 1.9% draw+swap
primus: profiling: readback: 1309x747, 42.3 fps, 43.2% app, 50.7% sleep, 5.6% map, 0.5% wait
primus: profiling: display: 1309x747, 42.3 fps, 95.6% wait, 2.6% upload, 1.8% draw+swap
primus: profiling: readback: 1309x747, 26.0 fps, 68.5% app, 28.0% sleep, 3.2% map, 0.3% wait
primus: profiling: display: 1309x747, 26.0 fps, 97.5% wait, 1.5% upload, 1.0% draw+swap
primus: profiling: readback: 1309x747, 16.8 fps, 72.6% app, 24.5% sleep, 2.7% map, 0.1% wait
primus: profiling: display: 1309x747, 16.8 fps, 98.4% wait, 1.0% upload, 0.6% draw+swap
primus: profiling: readback: 1309x747, 17.0 fps, 67.2% app, 29.5% sleep, 3.3% map, 0.1% wait
primus: profiling: display: 1309x747, 17.0 fps, 98.4% wait, 0.9% upload, 0.6% draw+swap
primus: profiling: readback: 1309x747, 33.7 fps, 33.5% app, 59.8% sleep, 6.6% map, 0.1% wait
primus: profiling: display: 1309x747, 33.7

**Comment by oanonymos0** [comment]
primus: profiling: readback: 1309x747, 34.3 fps, 26.0% app, 67.1% sleep, 6.5% map, 0.4% wait
primus: profiling: display: 1309x747, 34.3 fps, 96.2% wait, 2.2% upload, 1.7% draw+swap
primus: profiling: readback: 1309x747, 34.1 fps, 26.5% app, 66.2% sleep, 6.2% map, 1.2% wait
primus: profiling: display: 1309x747, 34.1 fps, 94.0% wait, 3.9% upload, 2.1% draw+swap
primus: profiling: readback: 1309x747, 31.0 fps, 32.7% app, 60.9% sleep, 6.2% map, 0.3% wait
primus: profiling: display: 1309x747, 30.9 fps, 93.7% wait, 3.9% upload, 2.4% draw+swap
primus: profiling: readback: 1309x747, 25.4 fps, 29.8% app, 65.3% sleep, 4.7% map, 0.2% wait
primus: profiling: display: 1309x747, 25.4 fps, 96.9% wait, 1.7% upload, 1.4% draw+swap
primus: profiling: readback: 1309x747, 16.3 fps, 47.8% app, 48.1% sleep, 4.0% map, 0.1% wait
primus: profiling: display: 1309x747, 16.3 fps, 95.7% wait, 1.9% upload, 2.4% draw+swap
is slow

**Comment by oanonymos0** [comment]
primus: profiling: display: 1309x747, 16.0 fps, 98.4% wait, 1.0% upload, 0.7% draw+swap
primus: profiling: readback: 1309x747, 20.6 fps, 49.1% app, 46.3% sleep, 4.4% map, 0.1% wait
primus: profiling: display: 1309x747, 21.1 fps, 96.6% wait, 2.2% upload, 1.1% draw+swap
primus: profiling: readback: 1309x747, 31.7 fps, 35.2% app, 59.0% sleep, 5.6% map, 0.2% wait
primus: profiling: display: 1309x747, 31.4 fps, 96.0% wait, 2.5% upload, 1.5% draw+swap
primus: profiling: readback: 1309x747, 35.2 fps, 25.1% app, 67.8% sleep, 7.1% map, 0.1% wait
primus: profiling: display: 1309x747, 35.7 fps, 95.8% wait, 2.4% upload, 1.8% draw+swap
primus: profiling: readback: 1309x747, 41.8 fps, 4.1% app, 87.2% sleep, 8.5% map, 0.2% wait
primus: profiling: display: 1309x747, 41.4 fps, 94.2% wait, 3.5% upload, 2.3% draw+swap
primus: profiling: readback: 1309x747, 42.6 fps, 6.5% app, 85.1% sleep, 8.0% map, 0.3% wait
primus: profiling: display: 1309x747, 42.8 fps, 94.0% wait, 3.1% upload, 2.8% draw+swap
primus: profiling: readback: 1309x747, 44.5 fps, 6.6% app, 84.8% sleep, 8.1% map, 0.5% wait
primus: profiling: display: 1309x747, 44.8 fps, 94.3% wait, 3.0% upload, 2.8% draw+swap
primus: profiling: readback: 1309x747, 49.3 fps, 2.8% app, 88.1% sleep, 8.9% map, 0.2% wait
primus: profiling: display: 1309x747, 49.4 fps, 93.9% wait, 3.3% upload, 2.8% draw+swap
primus: profiling: readback: 1309x747, 41.2 fps, 16.6% app, 75.7% sleep, 7.4% map, 0.4% wait
primus: profiling: display: 1309x747, 41.0 fps, 94.5% wait, 3.1% upload, 2.4% draw+swap
primus: profiling: readback: 1309x747, 42.6 fps, 19.3% app, 73.5% sleep, 6.7% map, 0.5% wait
primus: profiling: display: 1309x747, 42.8 fps, 93.5% wait, 3.8% upload, 2.7% draw+swap
primus: profiling: readback: 1309x747, 45.8 fps, 11.1% app, 80.9% sleep, 7.4% map, 0.6% wait
primus: profiling: display: 1309x747, 45.5 fps, 94.7% wait, 3.0% upload, 2.3% draw+swap
primus: profiling: readback: 1309x747, 25.0 fps, 31.5% app, 63.3% sleep, 5.1% map, 0.1% wait
primus: profiling: display: 1309x747, 24.8 fps, 94.0% wait, 3.7% upload, 2.3% draw+swap
primus: profiling: readback: 1309x747, 14.8 fps, 52.2% app, 44.0% sleep, 3.8% map, 0.0% wait
primus: profiling: display: 1309x747, 14.9 fps, 98.4% wait, 0.9% upload, 0.6% draw+swap
primus: profiling: readback: 1309x747, 16.2 fps, 47.6% app, 48.4% sleep, 4.0% map, 0.0% wait
finally

**Comment by oanonymos0** [comment]
the lag happens in the 20-10 fps range

**Comment by oanonymos0** [comment]
You were right... taskset -c 0 did help but almost halved the overall framerate, so it is really not  a permanent solution. The actual problem is that the CPU/Intel HD (not the nvidia GPU) throttles with bumblebee but not with prime...

**Comment by oanonymos0** [comment]
Well the 1 core frequently reaches 100% when using taskset...

**Comment by oanonymos0** [comment]
One more info that may help... when the fps drop happens, my whole desktop and other apps are sluggish

**Comment by oanonymos0** [comment]
https://github.com/amonakov/primus/issues/123 deveee here describes exactly what i experience, but further limiting temperature is impossible!

**Comment by oanonymos0** [comment]
any other ideas?

**Comment by oanonymos0** [comment]
well, i discovered what the problem was, it is unrelated to bumblebee and it is the intel_powerclamp driver!!!  "dmesg" gave me some:
    intel_powerclamp: Start idle injection to reduce power
    intel_powerclamp: Stop forced idle injection
which for some reason didn't happen with prime... sorry for bothering you!
Now i just have to figure out how to raise the temperature when it gets activated...

**Comment by oanonymos0** [comment]
fixed: * booting with intel_pstate=disable * running optirun -b none nvidia-settings -c :8  while in battery * setting the cpu governor to conservative (through indicator-cpufreq on ubuntu) * Now max temps are 80C on cpu and 77C GPU and games run just as they were, while using nvidia-prime, or even better than  that. On wine games, i need to limit processor clock to 2.2Ghz, to not get a little throttling!
