### ISSUE TITLE
running opencv_gpu with primusrun but not with optirun

### ISSUE THREAD

**Issue by Ingeborg87** [Bumblebee-Project/Bumblebee#695]
Hi!

i have compiled an opencv using program using cuda-5.0 succesfully with optirun. Why does it run with primusrun but not with optirun? I get this error:

peter@linux-hm6i:~/DA/testCuda> optirun ./a.out
init done 
opengl support available 
OpenCV Error: No GPU support (The library is compiled without CUDA support) in mallocPitch, file /home/abuild/rpmbuild/BUILD/opencv-2.4.9/modules/dynamicuda/include/opencv2/dynamicuda/dynamicuda.hpp, line 126
Error: /home/abuild/rpmbuild/BUILD/opencv-2.4.9/modules/dynamicuda/include/opencv2/dynamicuda/dynamicuda.hpp:126: error: (-216) The library is compiled without CUDA support in function mallocPitch

Thx, peter

**Comment by ArchangeGabriel** [comment]
Did you try `optirun -b primus ./a.out`?

**Comment by ArchangeGabriel** [comment]
No answer, closing.
