### ISSUE TITLE
Problems after resuming from suspend - nvidia is not unloaded when optirun stops /

### ISSUE THREAD

**Issue by Lukypie** [Bumblebee-Project/Bumblebee#706]
So, here is my story. I've got unfortunately an Acer Aspire E5-571G with:
Intel core i5-4210U + intel i915(don't remember exactly the model) , and nvidia GT820M
I've managed how to install bumblebee and how to get it working, but not after standby.
I always had problems with the bbswitch module which can't wake up the discrete card (It always gave me a D3 state error or similar, I don't remember) 
But not today, I don't know why and how but I've managed to make it working, I've got ArchLinux, the latest version, I've installed the acpi_call and acpi package, append this command to the kernel commandline trough grub 'acpi_osi=' and I've got it working. Tried removing the acpi package, it stopped working. Tried also with just acpi_call, the same, so it looked like I needed all of them. 
The big problem came when I had the great Idea to format my pc, reinstalled everything, acpi, acpi call, 'acpi_osi='
But I got the horrible error, 

"primus: fatal: Bumblebee daemon reported: error: [XORG] (EE) /dev/dri/card0: failed to set DRM interface version 1.4: Permission denied"

I've managed how to get it working by manually unloading the nvidia_modeset first, and the nvidia module. 
That's not the clean way to face it. Buuuut, I've also seen that the nvidia module (and the _modeset one) are not unloaded after I run optirun or primus, and that's what is causing the problem, in fact, rebooting the pc and not running primus/optimus, resuming from standby is not causing problems. 
PS: Even if they're still loaded, before going to standby is still working 

I don't know if some workarounds I've applied on the first installation solved the problem (because I've tried many) 
But that's it, so, I have to manually unload the nvidia driver by a systemd suspend hook which unloads the driver after resuming.
Tried many PM Methods, bbswitch, acpi_call, nothing happened.
Maybe I'm forgetting something, I don't know, sorry for my bad english hope you understand
Here is my dmesg
As you can see, after resuming from standby and opening primus/optimus also with the bumblebeed errors, I got

[ 1415.321232] NVRM: RmInitAdapter failed! (0x25:0x40:1353)
[ 1415.321246] NVRM: rm_init_adapter failed for device bearing minor number 0
[ 1415.321267] NVRM: nvidia_frontend_open: minor 0, module->open() failed, error -5

I've also manually unloaded the module, re-run primus, etc. There are also some ACPI errors 

[dmesg.txt](https://github.com/Bumblebee-Project/Bumblebee/files/44363/dmesg.txt)

Xorg.8.log

[xorg.txt](https://github.com/Bumblebee-Project/Bumblebee/files/44366/xorg.txt)

baseboard-manufacturer: Acer
baseboard-product-name: EA50_HB   
baseboard-version     : V1.31
system-manufacturer   : Acer
system-product-name   : Aspire E5-571G
system-version        : V1.31
bios-vendor           : Insyde Corp.
bios-version          : V1.31
bios-release-date     : 08/03/2015

optirun (Bumblebee) 3.2.1

**Comment by Lukypie** [comment]
Some updates, using the nouveau driver cause no problems.

**Comment by ArchangeGabriel** [comment]
Well, we have a potential mix of bbswitch suspend issues and unloading troubles. Let’s wait for those ones to be fixed before going further on bbswitch side. Also, you shouldn’t need acpi_call or acpi at all.

**Comment by ArchangeGabriel** [comment]
I closing this, I will try to centralize everythings that is suspend related.
