### ISSUE TITLE
alias nvidia_352_uvm to nvidia-uvm, opencl working only with sudo

### ISSUE THREAD

**Issue by silgon** [Bumblebee-Project/Bumblebee#707]
I posted this question as an [askubuntu thread](http://askubuntu.com/q/702706/269279). Then I realized I should probably put it here. So here we go:
I'm using the module `nvidia-352` with `bumblebee` in my ubuntu 14.04. OpenGL programs are working fine with optirun. Nonetheless, bumblebee fails to load the module `nvidia_352_uvm` which is necessary for opencl (and probably cuda, but I don't use it). So, based on [another thead][1] I added in `/etc/modprobe.d/bumblebee.conf` the following alias:

    alias nvidia-uvm nvidia_352_uvm

This is half-working. `optirun` is not working but `sudo optirun` is working. Thus, my opencl programs or the command `clinfo` and `darktable -d opencl`, they all need to be runned with `sudo optirun` instead of only `optirun` to work. So, there's some permission that I'm not able to see.

    $ optirun lsmod | grep nvidia  # same output with $ sudo optirun
    nvidia               8642880  25 
    drm                   303102  6 i915,drm_kms_helper,nvidia

As for a bit of information about my `nvidia_352_uvm`.

    $ modinfo nvidia_352_uvm 
    filename:       /lib/modules/3.13.0-68-generic/updates/dkms/nvidia_352_uvm.ko
    supported:      external
    license:        MIT
    srcversion:     A347F556C35EE8E88DF9DEB
    depends:        nvidia
    vermagic:       3.13.0-68-generic SMP mod_unload modversions 
    parm:           NVuvm_prefetch_stats:int
    parm:           NVuvm_prefetch_threshold:int
    parm:           NVuvm_prefetch_adaptive:int
    parm:           NVuvm_prefetch_epoch:int
    parm:           NVuvm_prefetch_sparsity_inc:int
    parm:           NVuvm_prefetch_sparsity_dec:int
    parm:           NVuvm_prefetch:int

I'd appreciate any help.

  [1]: http://askubuntu.com/a/525883/269279

**Comment by sapjunior** [comment]
Try to install nvidia_modprobe (sudo apt-get install nvidia-modprobe) it's works for me

**Comment by silgon** [comment]
Wow... that solved my problem... I was having a headache because of that, thanks!
