### ISSUE TITLE
Dirty fix for work with nvidia 358.16

### ISSUE THREAD

**Issue by dhamp** [Bumblebee-Project/Bumblebee#708]
Distro: ArchLinux current
New nvidia driver coming with new module - nvidia_modeset and stop working with current version of Bumblebee.
Module dep: nvidia_modeset->nvidia->drm
gist with patch and short description: https://gist.github.com/dhamp/1ed0306cd40bafc2e1df

**Comment by karolherbst** [comment]
or just the developer branch

**Comment by karolherbst** [comment]
see here: https://github.com/Bumblebee-Project/Bumblebee/commit/1ada79fe5916961fc4e4917f8c63bb184908d986

**Comment by dhamp** [comment]
>see here: 1ada79f
this commit not full equal my patch, because for unload spawned modprobe -r nvidia, but if nvidia_modeset module loaded -  command return error , 0 modules will be unloaded and bbswitch failed on OFF card. 

```
modinfo nvidia_modeset
filename:       /lib/modules/4.2.5-1-ARCH/extramodules/nvidia-modeset.ko.gz
version:        358.16
supported:      external
license:        NVIDIA
srcversion:     213270A97F2D7044797E528
depends:        nvidia
vermagic:       4.2.5-1-ARCH SMP preempt mod_unload modversions
```

**Comment by karolherbst** [comment]
you still need an entry inside /etc/modprobe.d with something like that: 

remove nvidia rmmod nvidia_uvm nvidia_modeset nvidia
