### ISSUE TITLE
debian jessie permission denied issue

### ISSUE THREAD

**Issue by zenny** [Bumblebee-Project/Bumblebee#713]
Hi, 

Machine is Lenovo y50-70 with:

> 00:02.0 VGA compatible controller: Intel Corporation 4th Gen Core Processor Integrated Graphics Controller (rev 06)
> 01:00.0 3D controller: NVIDIA Corporation GM107M [GeForce GTX 860M] (rev ff)

> $ uname -r
> 3.16.0-4-amd64

I installed bumblebee in debian jessie(1) and got:

> "[ERROR]Cannot access secondary GPU - error: [XORG] (EE) /dev/dri/card0: failed to set DRM interface version 1.4: Permission denied"

Appended the screen section to /etc/bumblebee/xorg.conf.nvidia

>Section "Screen"
>    Identifier "Default Screen"
>    Device "DiscreteNvidia"
> EndSection

The error remained.

Downgraded libdrm from 2.4.58 to 2.4.56-1 as stated here: https://wiki.debian.org/Bumblebee#Common_issues (2)

That didn't make a difference.

Checked by issuing (3):

> sudo tee /sys/module/rcutree/parameters/rcu_idle_gp_delay <<<1

Issued (4):

> iptables -A INPUT -i lo -j ACCEPT

The issue persisted. Any input to overcome this problem?

1) https://wiki.debian.org/Bumblebee
2) https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=768045#15
3) https://github.com/Bumblebee-Project/Bumblebee/issues/455#issuecomment-22497464
4) https://wiki.archlinux.org/index.php/Bumblebee#.2Fdev.2Fdri.2Fcard0:_failed_to_set_DRM_interface_version_1.4:_Permission_denied

**Comment by zenny** [comment]
Upon further online search, I found similar problems with debian jessie with many, but remained oustanding for a long time it seems. For instance,

1) https://github.com/Bumblebee-Project/Bumblebee/issues/697
2) http://unix.stackexchange.com/questions/233953/nvidia-geforece-960m-debian-jessie-bumblebee-problem-ee-dev-dri-card0-faile
3) https://github.com/Bumblebee-Project/Bumblebee/issues/455

@ex0hunt reported at https://github.com/Bumblebee-Project/Bumblebee/issues/455#issuecomment-40286473 that


> CONFIG_HZ_1000=y
> CONFIG_HZ=1000

in kernel 3.14 fixed his problem.

Has anyone reconfirm? Thanks!

**Comment by zenny** [comment]
UPDATE: Very strange things are happening:

§1. Upgraded to the jessie-backports kernel 4.2, but dkms build failed.

```
$ sudo dkms build -m nvidia-current -v 340.65 -k 4.2.0-0.bpo.1-amd64
[sudo] password for zenny: 

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area....
env CCACHE_DISABLE=1 make -C . SYSSRC=/lib/modules/4.2.0-0.bpo.1-amd64/build; env CCACHE_DISABLE=1 make -C uvm SYSSRC=/lib/modules/4.2.0-0.bpo.1-amd64/build.....(bad exit status: 2)
Error! Bad return status for module build on kernel: 4.2.0-0.bpo.1-amd64 (x86_64)
Consult /var/lib/dkms/nvidia-current/340.65/build/make.log for more information.
```

The tail from  /var/lib/dkms/nvidia-current/340.65/build/make.log looks like:

```
Makefile:10: *** mixed implicit and normal rules: deprecated syntax
make -C /usr/src/linux-headers-4.2.0-0.bpo.1-amd64 KBUILD_SRC=/usr/src/linux-headers-4.2.0-0.bpo.1-common \
-f /usr/src/linux-headers-4.2.0-0.bpo.1-common/Makefile modules
test -e include/generated/autoconf.h -a -e include/config/auto.conf || (		\
echo >&2;							\
echo >&2 "  ERROR: Kernel configuration is invalid.";		\
echo >&2 "         include/generated/autoconf.h or include/config/auto.conf are missing.";\
echo >&2 "         Run 'make oldconfig && make prepare' on kernel src to fix it.";	\
echo >&2 ;							\
/bin/false)
mkdir -p /var/lib/dkms/nvidia-current/340.65/build/uvm/.tmp_versions ; rm -f /var/lib/dkms/nvidia-current/340.65/build/uvm/.tmp_versions/*
make -f /usr/src/linux-headers-4.2.0-0.bpo.1-common/scripts/Makefile.build obj=/var/lib/dkms/nvidia-current/340.65/build/uvm
/bin/sh /var/lib/dkms/nvidia-current/340.65/build/uvm/conftest.sh " gcc-4.9" " gcc-4.9" x86 /lib/modules/4.2.0-0.bpo.1-amd64/build /lib/modules/4.2.0-0.bpo.1-amd64/build compile_tests remap_page_range remap_pfn_range irq_handler_t vm_insert_page kmem_cache_create outer_flush_all vm_operations_struct file_operations task_struct address_space address_space_init_once kbasename fatal_signal_pending kuid_t
/bin/sh /var/lib/dkms/nvidia-current/340.65/build/uvm/conftest.sh " gcc-4.9" " gcc-4.9" x86 /lib/modules/4.2.0-0.bpo.1-amd64/build /lib/modules/4.2.0-0.bpo.1-amd64/build patch_check
*** Please build the nvidia.ko module first ***
exit 1
/var/lib/dkms/nvidia-current/340.65/build/uvm/Kbuild:220: recipe for target '/var/lib/dkms/nvidia-current/340.65/build/uvm/../Module.symvers' failed
make[4]: *** [/var/lib/dkms/nvidia-current/340.65/build/uvm/../Module.symvers] Error 1
/usr/src/linux-headers-4.2.0-0.bpo.1-common/Makefile:1403: recipe for target '_module_/var/lib/dkms/nvidia-current/340.65/build/uvm' failed
make[3]: *** [_module_/var/lib/dkms/nvidia-current/340.65/build/uvm] Error 2
Makefile:146: recipe for target 'sub-make' failed
make[2]: *** [sub-make] Error 2
Makefile:8: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.2.0-0.bpo.1-amd64'
Makefile:35: recipe for target 'modules' failed
make: *** [modules] Error 2
make: Leaving directory '/var/lib/dkms/nvidia-current/340.65/build/uvm'

```

However I rebooted to the 4.2 kernel without building the modules, and surprisingly, 
both optirun and vglrun ran without a problem. primusrun ran, but produced blank window as of below:

```
Script started on Wed 16 Dec 2015 10:15:34 AM CET
zenny@MACHINE-i3x-4k:~/Downloads$ uname -a
Linux MACHINE-i3x-4k 4.2.0-0.bpo.1-amd64 #1 SMP Debian 4.2.6-3~bpo8+1 (2015-12-11) x86_64 GNU/Linux
zenny@MACHINE-i3x-4k:~/Downloads$ vglrun -sp +pr /opt/VirtualGL/bin/glxspheres64 
Polygons in scene: 62464 (61 spheres * 1024 polys/spheres)
Visual ID of window: 0x21
Context is Direct
OpenGL Renderer: Mesa DRI Intel(R) Haswell Mobile 
Readback    -  350.59 Mpixels/sec-  130.03 fps
59.238769 frames/sec - 159.718859 Mpixels/sec
Blit        -  673.64 Mpixels/sec-  249.85 fps
Total       -  159.89 Mpixels/sec-   59.30 fps
Readback    -  379.36 Mpixels/sec-  140.70 fps
58.350219 frames/sec - 157.323160 Mpixels/sec
Blit        -  679.30 Mpixels/sec-  251.95 fps
Total       -  157.32 Mpixels/sec-   58.35 fps
Readback    -  379.90 Mpixels/sec-  140.90 fps
58.670892 frames/sec - 158.187755 Mpixels/sec
Blit        -  683.05 Mpixels/sec-  253.34 fps
Total       -  158.18 Mpixels/sec-   58.67 fps
Readback    -  382.34 Mpixels/sec-  141.81 fps
58.496939 frames/sec - 157.718744 Mpixels/sec
Blit        -  684.71 Mpixels/sec-  253.96 fps
Total       -  157.71 Mpixels/sec-   58.50 fps
Blit        -  371.30 Mpixels/sec-  137.71 fps
Total       -  132.15 Mpixels/sec-   49.01 fps
Readback    -  382.89 Mpixels/sec-  142.01 fps
49.176322 frames/sec - 132.588610 Mpixels/sec

zenny@MACHINE-i3x-4k:~/Downloads$ optirun /opt/VirtualGL/bin/glxspheres64
Polygons in scene: 62464 (61 spheres * 1024 polys/spheres)
Visual ID of window: 0x21
Context is Direct
OpenGL Renderer: Gallium 0.4 on NV117
68.247078 frames/sec - 184.006952 Mpixels/sec
67.701234 frames/sec - 182.535254 Mpixels/sec
68.094805 frames/sec - 183.596397 Mpixels/sec
68.010237 frames/sec - 183.368385 Mpixels/sec
67.486404 frames/sec - 181.956032 Mpixels/sec
67.465650 frames/sec - 181.900077 Mpixels/sec
67.785644 frames/sec - 182.762840 Mpixels/sec
67.826000 frames/sec - 182.871648 Mpixels/sec

zenny@MACHINE-i3x-4k:~/Downloads$ primusrun /opt/VirtualGL/bin/glxspheres64 
Polygons in scene: 62464 (61 spheres * 1024 polys/spheres)
Visual ID of window: 0x21
Context is Direct
OpenGL Renderer: Gallium 0.4 on NV117
49.144705 frames/sec - 132.503364 Mpixels/sec
48.013455 frames/sec - 129.453302 Mpixels/sec
47.988278 frames/sec - 129.385420 Mpixels/sec
47.909881 frames/sec - 129.174047 Mpixels/sec
47.855190 frames/sec - 129.026588 Mpixels/sec
48.151404 frames/sec - 129.825238 Mpixels/sec
48.082899 frames/sec - 129.640535 Mpixels/sec

zenny@MACHINE-i3x-4k:~/Downloads$ exit
exit

Script done on Wed 16 Dec 2015 10:17:49 AM CET
```
Normal rendering with Intel cards look like this:

```
zenny@MACHINE-i3x-4k:~/Downloads$ /opt/VirtualGL/bin/glxspheres64
Polygons in scene: 62464 (61 spheres * 1024 polys/spheres)
Visual ID of window: 0x21
Context is Direct
OpenGL Renderer: Mesa DRI Intel(R) Haswell Mobile
47.966178 frames/sec - 129.325833 Mpixels/sec
47.991802 frames/sec - 129.394920 Mpixels/sec
48.007756 frames/sec - 129.437935 Mpixels/sec
47.998627 frames/sec - 129.413321 Mpixels/sec
48.002143 frames/sec - 129.422801 Mpixels/sec
48.003145 frames/sec - 129.425504 Mpixels/sec
```

What does this means? How can I verify that NVIDIA 3D card is working?

Thanks!

**Comment by ArchangeGabriel** [comment]
Well, they are several issues at hand here. For kernels before 3.19, you need to add `rcutree.rcu_idle_gp_delay=1` to kernel parameters.

All your tests with 4.2 kernel are with nouveau, but nouveau can’t use your card before 4.4 (or 4.3 with another added kernel parameter), so it’s falling back to LLVMpipe, which explains your results.

You can’t compile nvidia driver on 4.2 because you’re missing kernel headers apparently.

So, either keep your original kernel and add the requested parameter, or install a newer one (>=3.19) with its header and recompile bbswitch and nvidia against it (or use a DKMS package for both if they exists).

**Comment by diamondman** [comment]
@ArchangeGabriel Your last comment ended in talking about this error with nouveau. I feel this makes my comment relevant enough, but otherwise I will happily create a new issue.

First a brief description of my issue, and what I have done.
I am getting the same error of:
```
Cannot access secondary GPU - error: [XORG] (EE) /dev/dri/card1: failed to set DRM interface version 1.4: Permission denied
```
On Debian, using nouveau drivers. I have tried 'optirun glxgears' with kernel 4.0.1, 4.3, and 4.4 (linux-image-4.4.0-rc6-amd64). I have tried downgrading libdrm (and family) from 2.4.58 to 2.4.56 as suggested by http://www.unixmen.com/how-to-make-nvidia-optimus-technology-work-properly-on-debian/ (I am aware this guide is for the nvidia blob drivers, but I have had trouble finding documentation about this issue for nouveau). I also tried adding a section "Screen" to /etc/bumblebee/xorg.conf.nouveau .

I am kind of at a loss here. I would at the very least appreciate a link describing the kernel parameter required to get this working in 4.3 so I could try it (all searches end up with people using the proprietary blob). Any other input would be greatly appreciated.

**Comment by ArchangeGabriel** [comment]
@diamondman No, I’m not talking of this error. If you have issue running nouveau, please open a new post with optirun log, dmesg output and /var/log/Xorg.{0,8}.log.

**Comment by diamondman** [comment]
@ArchangeGabriel Thanks. Was not sure if this was the same issue, glad I checked.

**Comment by ArchangeGabriel** [comment]
No answer from OP, closing.
