### ISSUE TITLE
Low graphics mode after installing bumblebee

### ISSUE THREAD

**Issue by flashrocket** [Bumblebee-Project/Bumblebee#715]
In my laptop Dell vostro 3546 I have a dGPU nvidia 820M.
So after configuring bumblebee it works awesome. But it doesn't survive a reboot.
After i reboot system goes into low graphics mode and is unbootable.
So after digging a lot i found that in dpkg-alternatives the  **x86_64-linux-gnu_gl_conf** is set to nvidia by some process at every boot.
removing bumblebee fixes the problem.
Using nvidia 352

**Comment by flashrocket** [comment]
It seems that this happens
Install > reboot > no crash >reboot > no crash
Install > reboot > optirun glxinfo > reboot > crash

**Comment by flashrocket** [comment]
syslog here https://gist.github.com/flashrocket/e9269e0cad774b0ab85d

**Comment by flashrocket** [comment]
It seems the issue is fixed in nvidia 358.Everyone having the issue please update to 358 or above. Closing issue

**Comment by flashrocket** [comment]
It seems its happening again. opening issue

**Comment by flashrocket** [comment]
It seems that nvidia created something in my home folder. so reinstalling completey solved the issue.

**Comment by hemenkapadia** [comment]
Facing the exact same issue with nvidia-352. Will check with 358.

**Comment by flashrocket** [comment]
I made it work with nvidia 352 
reinstall completely
install nvidia driver
reboot
go to intel mode
install bumblebee and configure
reboot

it doesnt seem to work with gdm but with lightdm it works

**Comment by hemenkapadia** [comment]
Thanks @flashrocket I managed to get it work. I am planning to write a detailed blog post with the steps. Will share once done.
