### ISSUE TITLE
dGPU stays on after optirun

### ISSUE THREAD

**Issue by flashrocket** [Bumblebee-Project/Bumblebee#716]
bbswitch fails to shut down dGPU as bumblebeed cannot unload nvidia driver.
```
[ 3404.258306] [DEBUG][XORG] (II) AutoAddDevices is off - not adding device.
[ 3404.258376] [INFO]X successfully started in 1 seconds
[ 3404.259905] [DEBUG]Accepted new connection
[ 3404.260304] [INFO]X successfully started in 0 seconds
[ 3404.373165] [DEBUG]Socket closed.
[ 3404.373254] [DEBUG]Socket closed.
[ 3404.373282] [INFO]Stopping X server
[ 3404.432133] [DEBUG]Process with PID 9133 returned code 0
[ 3404.432397] [INFO]Unloading nvidia driver
[ 3404.432568] [DEBUG]Process modprobe started, PID 9156.
[ 3404.433807] [DEBUG]Process with PID 9156 returned code 0
[ 3407.441063] [ERROR]Unloading nvidia driver timed out.
[ 3407.441157] [DEBUG]Drivers are still loaded, unable to disable card
[ 3407.441195] [DEBUG][XORG] (II) UnloadModule: "mouse"
[ 3407.441224] [DEBUG][XORG] (II) NVIDIA(GPU-0): Deleting GPU-0
[ 3407.441246] [DEBUG][XORG] (II) Server terminated successfully (0). Closing log file.

```
dgpu stays on
```
cat /proc/acpi/bbswitch
0000:08:00.0 ON
```
nvidia stays loaded
```
~$ lsmod|grep nvidia
nvidia               8646656  0
drm                   356352  7 i915,drm_kms_helper,nvidia
```
running  ```modprobe -r nvidia``` does nothing

running ``rmmod nvidia`` removes the module

there are no processes running in nvidia

workaround
rename **nvidia** to **nvidia2** in ``/etc/modprobe.d/bumblebee.conf``
```
remove nvidia2 rmmod nvidia-uvm nvidia
```
now running ``modprobe -r nvidia2`` unloads nvidia driver

**Comment by ArchangeGabriel** [comment]
Yes, this is because of nvidia-uvm (and now even nvidia-modeset). We are aware of it and working on this. Closing this issue, they are already several about this.

**Comment by flashrocket** [comment]
strange it seems the bug fixed itself checking dpkg log

**Comment by flashrocket** [comment]
strange the things i installed are mpv, clementine, kate, libsdl2-2.0-0:i386

**Comment by flashrocket** [comment]
Ive found the curlpit. some process changes x86_64-linux-gnu_gl_conf to /usr/lib/nvidia-352-prime/ld.so.conf on every boot.
so changing it to /usr/lib/x86_64-linux-gnu/mesa/ld.so.conf fixes the above issue

**Comment by flashrocket** [comment]
it seems that it was caused by a software known as gpu manager
running 
sudo systemctl mask gpu-manager.service 
fixed it
