### ISSUE TITLE
Archlinux VirtualGL don't intercept libGl for 32bit application

### ISSUE THREAD

**Issue by NaKroTeK** [Bumblebee-Project/Bumblebee#718]
Hello !
This is a follow up from this [thread](https://bbs.archlinux.org/viewtopic.php?id=206681).
I'm trying to get 32 bit glxpsheres running and cs 1.6 steam but i'm getting error.

[Pastbin of](https://ptpb.pw/r8sJ) : 
```$LD_DEBUG=libs VGL_VERBOSE=1 optirun --debug glxspheres32 |& tee /tmp/ld-debug.txt ```

something seems wrong here :
```
/usr/lib32/libpthread.so.0: error: symbol lookup error: undefined symbol: pthread_setname_np, version GLIBC_2.0 (fatal)
[VGL] NOTICE: Replacing dlopen("/usr/lib32/libdl.so.2") with dlopen("libdlfaker.so")
```

I'm using a Asus U35JC nvidia 310M card.
uname -a:
```Linux alexarchhost 4.2.5-1-ARCH #1 SMP PREEMPT Tue Oct 27 08:13:28 CET 2015 x86_64 GNU/Linux```

Thank you for help !
Best regard

**Comment by ArchangeGabriel** [comment]
Not sure about this… Since some other people have it working it might be an issue somewhere in your setup.

What you can do is trying to use `primusrun` or `optirun -b primus`, those are supposed to work better than VirtualGL in all cases and the second one will become the default with (incoming) 4.0 release.

**Comment by NaKroTeK** [comment]
Thanks for the tip !
Unfortunately, it produces the same output with primus, indeed something might be wrong on my side.

**Comment by ArchangeGabriel** [comment]
Could you take a look at https://github.com/amonakov/glsanity and report?

**Comment by NaKroTeK** [comment]
Hello, I took a look with it earlier this week here is the output :
```
optirun ./Downloads/glsanity-bin/glsanity
Running 32-bit tests
info:  libGL.so.1:      loaded from: /usr/lib32/librrfaker.so
info:  X display:       :0
info:  X Ext. "GLX":    present
info:  X Ext. "NV-GLX": not present; OK for non-nVidia drivers
info:  GLX server:      VirtualGL
info:  GLX client:      VirtualGL
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  154 (GLX)
  Minor opcode of failed request:  24 (X_GLXCreateNewContext)
  Value in failed request:  0x0
  Serial number of failed request:  19
  Current serial number in output stream:  20
Running 64-bit tests
info:  libGL.so.1:      loaded from: /usr/lib/librrfaker.so
info:  X display:       :0
info:  X Ext. "GLX":    present
info:  X Ext. "NV-GLX": not present; OK for non-nVidia drivers
info:  GLX server:      VirtualGL
info:  GLX client:      VirtualGL
info:  GL vendor:       NVIDIA Corporation
info:  GL renderer:     GeForce 310M/PCIe/SSE2
info:  GL version:      3.3.0 NVIDIA 340.96
```

Also I tried with ldd to see any problem but i did not notice anything suspicious
```ldd `optirun ./Downloads/glsanity-bin/glsanity``` = [Pastebin](https://ptpb.pw/pRgt)

**Comment by ArchangeGabriel** [comment]
Well, you do have an issue, the line starting with X Error is not normal. Also, could you try runnig glsanity-bbee without optirun?

**Comment by NaKroTeK** [comment]
Hi,
Output of ```:$ glsanity-bbee``` ->[Pastebin](https://ptpb.pw/o4M8)

**Comment by ArchangeGabriel** [comment]
Well, you indeed have some issues.

```
info:  GL vendor:
info:  GL renderer:
info:  GL version:
```

are missing from 32 bit tests. But I think this come from here:
```
info:  libGL.so.1:	symlink to:  /usr/lib32/nvidia/libGL.so.358.16
```

While everywhere else you have 340.96. Could you check list of installed related packages with `pacman -Qs nvidia`?

**Comment by NaKroTeK** [comment]
As requested : 
```
local/bumblebee 3.2.1-10
    NVIDIA Optimus support for Linux through VirtualGL
local/lib32-nvidia-utils 358.16-1
    NVIDIA drivers utilities (32-bit)
local/lib32-opencl-nvidia-340xx 340.96-1
    OpenCL implemention for NVIDIA (32-bit)
local/libvdpau 1.1.1-2
    Nvidia VDPAU library
local/nvidia-340xx 340.96-3
    NVIDIA drivers for linux, 340xx legacy branch
local/nvidia-340xx-utils 340.96-1
    NVIDIA drivers utilities
local/opencl-nvidia-346xx 346.59-1
    OpenCL implemention for NVIDIA (346 Series)
```

I think you got something here !

**Comment by ArchangeGabriel** [comment]
Yes, you should use the same version for every nvidia part. Here You have three different versions at the same time. So, please install `lib32-nvidia-utils-340xx` instead of `opencl-nvidia-346xx` and `opencl-nvidia-340xx` instead of `opencl-nvidia-346xx`. Or use 346xx everywhere. But don’t mix.

**Comment by NaKroTeK** [comment]
yep I was looking into that....What a dummy I am...I keep you posted !

**Comment by NaKroTeK** [comment]
```lib32-nvidia-304xx-utils``` for futur reference, Arch wiki is not referring to this packages, i will try to submit this precision into the Arch wiki about Bumblebee installation.
It Works !
```
optirun ./glsanity
Running 32-bit tests
info:  libGL.so.1:      loaded from: /usr/lib32/librrfaker.so
info:  X display:       :0
info:  X Ext. "GLX":    present
info:  X Ext. "NV-GLX": not present; OK for non-nVidia drivers
info:  GLX server:      VirtualGL
info:  GLX client:      VirtualGL
info:  GL vendor:       NVIDIA Corporation
info:  GL renderer:     GeForce 310M/PCIe/SSE2
info:  GL version:      3.3.0 NVIDIA 340.96
Running 64-bit tests
info:  libGL.so.1:      loaded from: /usr/lib/librrfaker.so
info:  X display:       :0
info:  X Ext. "GLX":    present
info:  X Ext. "NV-GLX": not present; OK for non-nVidia drivers
info:  GLX server:      VirtualGL
info:  GLX client:      VirtualGL
info:  GL vendor:       NVIDIA Corporation
info:  GL renderer:     GeForce 310M/PCIe/SSE2
info:  GL version:      3.3.0 NVIDIA 340.96
```
Thank you very much for your help & patience !
