### ISSUE TITLE
Failed to load module "mouse" (module does not exist, 0) 

### ISSUE THREAD

**Issue by prcastro** [Bumblebee-Project/Bumblebee#725]
I'm using `xf86-input-libinput` package on Arch Linux and having the following issue:

```
bumblebeed[304]: [  117.643544] [WARN][XORG] (WW) Warning, couldn't open module mouse
bumblebeed[304]: [  117.643546] [ERROR][XORG] (EE) Failed to load module "mouse" (module does not exist, 0)
```

One workaround is to install `xf86-input-mouse`, but should it be necessary?

**Comment by ArchangeGabriel** [comment]
No, that’s a false error. See https://github.com/Bumblebee-Project/Bumblebee/commit/524ded140593535d5fd4819eeb819cc3fcd0d71b.
