### ISSUE TITLE
Debian (Jessie) Nouveau Kernel 4.4.0 Permission Denied

### ISSUE THREAD

**Issue by diamondman** [Bumblebee-Project/Bumblebee#727]
Trying to get bumblebee working on my Debian machine. I have tried this on many kernels 4.0.1, 4.3, and now 4.4.0 after hearing that something changed in 4.4.0 to help nouveau work with bumblebee. The Nvidia card is not disabled in the BIOS.

Laptop Model: Lenovo W530
Video Card: Optimus configuration of Intel card and Nvidia Quadro K2000m

uname -a (I removed the # from the 4 in the line below so it did not make a link)

    Linux jessys-laptop 4.4.0-rc6-diamondman 4 SMP Fri Jan 8 00:54:54 PST 2016 x86_64 GNU/Linux

LibDRM2 (and family: libdrm-nouveau2, libdrm-intel2, etc) version: 2.4.58-2
bbswitch module is loaded.
xorg-server version: 2:1.16.4-1

My optirun log is as follows:

    ➜  ~  optirun -vv glxgears -info
    [  302.627502] [DEBUG]Reading file: /etc/bumblebee/bumblebee.conf
    [  302.627728] [INFO]Configured driver: nouveau
    [  302.627823] [DEBUG]optirun version 3.2.1 starting...
    [  302.627829] [DEBUG]Active configuration:
    [  302.627832] [DEBUG] bumblebeed config file: /etc/bumblebee/bumblebee.conf
    [  302.627836] [DEBUG] X display: :8
    [  302.627838] [DEBUG] LD_LIBRARY_PATH: 
    [  302.627845] [DEBUG] Socket path: /var/run/bumblebee.socket
    [  302.627851] [DEBUG] Accel/display bridge: auto
    [  302.627857] [DEBUG] VGL Compression: proxy
    [  302.627861] [DEBUG] VGLrun extra options: 
    [  302.627864] [DEBUG] Primus LD Path: /usr/lib/x86_64-linux-gnu/primus:/usr/lib/i386-linux-gnu/primus:/usr/lib/primus:/usr/lib32/primus
    [  302.629369] [DEBUG]Using auto-detected bridge primus
    [  304.349876] [INFO]Response: No - error: [XORG] (EE) /dev/dri/card1: failed to set DRM interface version 1.4: Permission denied
    
    [  304.349890] [ERROR]Cannot access secondary GPU - error: [XORG] (EE) /dev/dri/card1: failed to set DRM interface version 1.4: Permission denied
    
    [  304.349896] [DEBUG]Socket closed.
    [  304.349910] [ERROR]Aborting because fallback start is disabled.
    [  304.349914] [DEBUG]Killing all remaining processes.

These are the other relevant logs.
[dmesg output](https://github.com/Bumblebee-Project/Bumblebee/files/82490/dmesg.txt)
[Xorg.8.log](https://github.com/Bumblebee-Project/Bumblebee/files/82495/Xorg.8.log.txt)
[Xorg.1.log](https://github.com/Bumblebee-Project/Bumblebee/files/82496/Xorg.1.log.txt)
[Xorg.0.log](https://github.com/Bumblebee-Project/Bumblebee/files/82497/Xorg.0.log.txt)

**Comment by ArchangeGabriel** [comment]
Well, the relevant message is:
```
[   304.349] (EE) NOUVEAU(0): [drm] failed to set drm interface version.
[   304.349] (EE) NOUVEAU(0): [drm] error opening the drm
[   304.349] (EE) NOUVEAU(0): 892: 
```

The problem, that you might see in Xorg.0.log, is that modesetting is catching the card before Bumblebee. As you have a 1.16 xorg-server, you should be able to uninstall modesetting driver.

Also, you might want to try PRIME rather than Bumblebee if you’re only interested in nouveau and not nvidia. ;)

**Comment by diamondman** [comment]
Removing xserver-xorg-video-modesetting did make optirun work (though I get lower framerates on glxgears than without calling optirun, and my gl version is still 3.0. weird).
I thought bumblebee was intended to work with nvidia and nouveau. What is the purpose of PRIME if bumblebee is aiming to do both?

**Comment by ArchangeGabriel** [comment]
> though I get lower framerates on glxgears than without calling optirun, and my gl version is still 3.0. weird

About lower framerates: glxgears is not a benchmark, and also primus (the bumblebee backend you use) is respecting vsync. See https://github.com/amonakov/primus#faq. Also, you can’t have really high FPS throughput with Bumblebee because of the bottlenecks we have.

About GL 3.0: that’s a bit weird, but if your mesa is a bit old, it’s possible though. Can you paste a full optirun glxinfo output?

> I thought bumblebee was intended to work with nvidia and nouveau.

Absolutely

> What is the purpose of PRIME if bumblebee is aiming to do both?

PRIME is low-level solution, with far better potential, especially when talking of performances. However, because of legal issues, NVIDIA cannot support it.

**Comment by karolherbst** [comment]
@diamondman you should try out the 4.5 stuff pending in drm-next, especially those pcie patches, which will give you a performance boost, because it will make the pcie bottleneck less bad.

**Comment by karolherbst** [comment]
(got like 14000 fps through prime in glxgears ;) )

**Comment by diamondman** [comment]
@ArchangeGabriel Interesting. I assume PRIME uses some kernel tricks that anything linking with nvidia can not do because of GPL reasons. 

I did disable the vsync which is why I got a few hundred FPS. I am aware this is a silly way to realistically test things since there is no reason to make 2k FPS, but it is a super simple 'benchmark' to just check that things are running. Good to know more of the limitations.

As for the limits of GL 3.0 (3.3 if requested I found out), I am running Mesa 10.3.2, which according to the http://www.mesa3d.org/relnotes/10.3.2.html only supports GL 3.3 max. Seems I will have to find a way to build a custom mesa without pissing off my package manager, or update to testing. 

@karolherbst I assume you mean Kernel 4.5. I do not even see that in the branches of the git repo I have.

@ArchangeGabriel I do not believe it is useful for me to post that glxgears log anymore, but here it is in case it helps anyone out.



✗ optirun -vvv glxgears -info
[102077.953525] [DEBUG]Reading file: /etc/bumblebee/bumblebee.conf
[102077.953914] [INFO]Configured driver: nouveau
[102077.954247] [DEBUG]optirun version 3.2.1 starting...
[102077.954286] [DEBUG]Active configuration:
[102077.954304] [DEBUG] bumblebeed config file: /etc/bumblebee/bumblebee.conf
[102077.954317] [DEBUG] X display: :8
[102077.954329] [DEBUG] LD_LIBRARY_PATH: 
[102077.954344] [DEBUG] Socket path: /var/run/bumblebee.socket
[102077.954375] [DEBUG] Accel/display bridge: auto
[102077.954383] [DEBUG] VGL Compression: proxy
[102077.954393] [DEBUG] VGLrun extra options: 
[102077.954405] [DEBUG] Primus LD Path: /usr/lib/x86_64-linux-gnu/primus:/usr/lib/i386-linux-gnu/primus:/usr/lib/primus:/usr/lib32/primus
[102077.954487] [DEBUG]Using auto-detected bridge primus
[102080.906876] [INFO]Response: Yes. X is active.

[102080.906918] [INFO]Running application using primus.
[102080.907107] [DEBUG]Process glxgears started, PID 1132.
GL_RENDERER   = Gallium 0.4 on NVE7
GL_VERSION    = 3.0 Mesa 10.3.2
GL_VENDOR     = nouveau
GL_EXTENSIONS = GL_ARB_multisample GL_EXT_abgr GL_EXT_bgra GL_EXT_blend_color GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_copy_texture GL_EXT_polygon_offset GL_EXT_subtexture GL_EXT_texture_object GL_EXT_vertex_array GL_EXT_compiled_vertex_array GL_EXT_texture GL_EXT_texture3D GL_IBM_rasterpos_clip GL_ARB_point_parameters GL_EXT_draw_range_elements GL_EXT_packed_pixels GL_EXT_point_parameters GL_EXT_rescale_normal GL_EXT_separate_specular_color GL_EXT_texture_edge_clamp GL_SGIS_generate_mipmap GL_SGIS_texture_border_clamp GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod GL_ARB_framebuffer_sRGB GL_ARB_multitexture GL_EXT_framebuffer_sRGB GL_IBM_multimode_draw_arrays GL_IBM_texture_mirrored_repeat GL_ARB_texture_cube_map GL_ARB_texture_env_add GL_ARB_transpose_matrix GL_EXT_blend_func_separate GL_EXT_fog_coord GL_EXT_multi_draw_arrays GL_EXT_secondary_color GL_EXT_texture_env_add GL_EXT_texture_filter_anisotropic GL_EXT_texture_lod_bias GL_INGR_blend_func_separate GL_NV_blend_square GL_NV_light_max_exponent GL_NV_texgen_reflection GL_NV_texture_env_combine4 GL_S3_s3tc GL_SUN_multi_draw_arrays GL_ARB_texture_border_clamp GL_ARB_texture_compression GL_EXT_framebuffer_object GL_EXT_texture_compression_s3tc GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_MESA_window_pos GL_NV_packed_depth_stencil GL_NV_texture_rectangle GL_ARB_depth_texture GL_ARB_occlusion_query GL_ARB_shadow GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_mirrored_repeat GL_ARB_window_pos GL_EXT_stencil_two_side GL_EXT_texture_cube_map GL_NV_depth_clamp GL_NV_fog_distance GL_APPLE_packed_pixels GL_APPLE_vertex_array_object GL_ARB_draw_buffers GL_ARB_fragment_program GL_ARB_fragment_shader GL_ARB_shader_objects GL_ARB_vertex_program GL_ARB_vertex_shader GL_ATI_draw_buffers GL_ATI_texture_env_combine3 GL_ATI_texture_float GL_EXT_shadow_funcs GL_EXT_stencil_wrap GL_MESA_pack_invert GL_NV_primitive_restart GL_ARB_depth_clamp GL_ARB_fragment_program_shadow GL_ARB_half_float_pixel GL_ARB_occlusion_query2 GL_ARB_point_sprite GL_ARB_shading_language_100 GL_ARB_sync GL_ARB_texture_non_power_of_two GL_ARB_vertex_buffer_object GL_ATI_blend_equation_separate GL_EXT_blend_equation_separate GL_OES_read_format GL_ARB_color_buffer_float GL_ARB_pixel_buffer_object GL_ARB_texture_compression_rgtc GL_ARB_texture_float GL_ARB_texture_rectangle GL_ATI_texture_compression_3dc GL_EXT_packed_float GL_EXT_pixel_buffer_object GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_rgtc GL_EXT_texture_mirror_clamp GL_EXT_texture_rectangle GL_EXT_texture_sRGB GL_EXT_texture_shared_exponent GL_ARB_framebuffer_object GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_packed_depth_stencil GL_ARB_vertex_array_object GL_ATI_separate_stencil GL_ATI_texture_mirror_once GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_gpu_program_parameters GL_EXT_texture_array GL_EXT_texture_compression_latc GL_EXT_texture_integer GL_EXT_texture_sRGB_decode GL_EXT_timer_query GL_OES_EGL_image GL_ARB_copy_buffer GL_ARB_depth_buffer_float GL_ARB_draw_instanced GL_ARB_half_float_vertex GL_ARB_instanced_arrays GL_ARB_map_buffer_range GL_ARB_texture_rg GL_ARB_texture_swizzle GL_ARB_vertex_array_bgra GL_EXT_texture_swizzle GL_EXT_vertex_array_bgra GL_NV_conditional_render GL_AMD_conservative_depth GL_AMD_draw_buffers_blend GL_AMD_seamless_cubemap_per_texture GL_ARB_ES2_compatibility GL_ARB_blend_func_extended GL_ARB_debug_output GL_ARB_draw_buffers_blend GL_ARB_draw_elements_base_vertex GL_ARB_explicit_attrib_location GL_ARB_fragment_coord_conventions GL_ARB_provoking_vertex GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_shader_texture_lod GL_ARB_texture_cube_map_array GL_ARB_texture_gather GL_ARB_texture_multisample GL_ARB_texture_query_lod GL_ARB_texture_rgb10_a2ui GL_ARB_uniform_buffer_object GL_ARB_vertex_type_2_10_10_10_rev GL_EXT_provoking_vertex GL_EXT_texture_snorm GL_MESA_texture_signed_rgba GL_NV_texture_barrier GL_ARB_get_program_binary GL_ARB_robustness GL_ARB_separate_shader_objects GL_ARB_shader_bit_encoding GL_ARB_texture_compression_bptc GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_NV_vdpau_interop GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_ARB_base_instance GL_ARB_compressed_texture_pixel_storage GL_ARB_conservative_depth GL_ARB_internalformat_query GL_ARB_map_buffer_alignment GL_ARB_shading_language_420pack GL_ARB_shading_language_packing GL_ARB_texture_storage GL_ARB_transform_feedback_instanced GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_transform_feedback GL_AMD_shader_trinary_minmax GL_ARB_ES3_compatibility GL_ARB_clear_buffer_object GL_ARB_explicit_uniform_location GL_ARB_invalidate_subdata GL_ARB_stencil_texturing GL_ARB_texture_query_levels GL_ARB_texture_storage_multisample GL_ARB_vertex_attrib_binding GL_KHR_debug GL_ARB_buffer_storage GL_ARB_multi_bind GL_ARB_seamless_cubemap_per_texture GL_ARB_texture_mirror_clamp_to_edge GL_ARB_vertex_type_10f_11f_11f_rev GL_EXT_shader_integer_mix GL_ARB_conditional_render_inverted GL_ARB_derivative_control GL_ARB_texture_barrier 
VisualID 33, 0x21
^C[102085.357115] [WARN]Received Interrupt signal.
[102085.357145] [DEBUG]Socket closed.
[102085.378093] [DEBUG]SIGCHILD received, but wait failed with No child processes
[102085.378119] [DEBUG]Socket closed.
[102085.378124] [DEBUG]Killing all remaining processes.

**Comment by diamondman** [comment]
Since optirun is working for me, I think the issue is pretty much closed. I will also go check out using PRIME.
One last question: Do you guys know if I should leave the xorg modesetting driver out? Or will not having it cause problems?

**Comment by karolherbst** [comment]
@diamondman with DRI3 and PRIME you won't need any xorg driver for nouveau, not nouveau, not modesetting.

**Comment by diamondman** [comment]
@karolherbst Are DRM and DRI independent? I seem to have dri3 installed, but DRM2.

**Comment by karolherbst** [comment]
@diamondman you have to enable dri3 for your intel ddx most likely in the xserver config

**Comment by diamondman** [comment]
Oh no I forgot to close this issue. Thanks guys.
