### ISSUE TITLE
Cannot boot after installing Bumblebee, Ubuntu 15.10 860M/NV110

### ISSUE THREAD

**Issue by polarathene** [Bumblebee-Project/Bumblebee#728]
Have tried to install a few ways, but all have the same result, last method used was Ubuntu's software center. It seemed to complain about no screens being available.

I've tried to get Nouveau to work as well but I can only seem to boot with `nomodeset` applied which doesn't use the driver then?(New to using linux for desktop)

I'm trying this on a laptop with GTX860M which I've found belongs in the NV110 family, according to this nouveau page all my issues with it might be due to poor support: http://nouveau.freedesktop.org/wiki/FeatureMatrix/

Bumblebee was trying to use proprietary nvidia drivers from what I can tell but they seemed to be quite old, I don't think my card was supported in the driver version mentioned, 304 or something? I could try fix that but I'm not sure how to go about it.

I've been able to boot by purging nvidia drivers and bumblebee with `sudo apt-get purge nvidia* '^bumblebee.*'` From there it tries to load with Nouveau drivers which require me to add the `nomodeset` flag in grub when booting.

This was the xorg.conf that I had when booting with bumblebee(it was dropping me into some sort of gui that consisted only of a prompt with several options, one to edit xorg.conf or view the log.

```
Section "ServerLayout"
    Identifier "layout"
    Screen 0 "nvidia"
    Inactive "intel"
EndSection

Section "Device"
    Identifier "intel"
    Driver "modesetting"
    BusID "PCI:0@0:2:0"
    Option "AccelMethod" "None"
EndSection

Section "Screen"
    Identifier "intel"
    Device "intel"
EndSection
```

Just installed via `sudo apt-get install linux-headers-generic`, `sudo add-apt-repository ppa:bumblebee/stable`, `sudo apt-get update && sudo apt-get install bumblebee bumblebee-nvidia primus
` This is the terminal output that looked relevant:

```
Loading new nvidia-304-304.131 DKMS files...
First Installation: checking all kernels...
Building only for 4.2.0-23-generic
Building for architecture i686
Building initial module for 4.2.0-23-generic
Done.

nvidia_304:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.2.0-23-generic/updates/dkms/

depmod....

DKMS: install completed.
Setting up nvidia-current (304.131-0ubuntu0.15.10.1) ...
Setting up nvidia-opencl-icd-304 (304.131-0ubuntu0.15.10.1) ...
Setting up nvidia-settings (352.21-0ubuntu1) ...
Processing triggers for initramfs-tools (0.120ubuntu6) ...
update-initramfs: Generating /boot/initrd.img-4.2.0-23-generic
Setting up primus (20150328-1~wilyppa1) ...
Setting up bumblebee-nvidia (3.2.1-93~wilyppa1) ...
update-alternatives: using /usr/lib/i386-linux-gnu/mesa/ld.so.conf to provide /etc/ld.so.conf.d/i386-linux-gnu_GL.conf (i386-linux-gnu_gl_conf) in manual mode
Selecting 01:00:0 as discrete nvidia card. If this is incorrect,
edit the BusID line in /etc/bumblebee/xorg.conf.nvidia
Processing triggers for systemd (225-1ubuntu9) ...
Processing triggers for ureadahead (0.100.0-19) ...
Processing triggers for libc-bin (2.21-0ubuntu4) ...
```

**Comment by polarathene** [comment]
Not sure if it was bumblebee or something to do with the uninstall and install of nvidia drivers again but had issues getting it to boot into Ubuntu, got to a point where I'd see the desktop and could right click but nothing else was available. Thankfully it wasn't completely borked and some terminal commands I found on a askubuntu.com question fixed it restoring Unity. I think I'll avoid bumblebee as it seems to be causing a lot of problems with no signs of working.

**Comment by ArchangeGabriel** [comment]
Your card is indeed quite recent, and especially not supported by nouveau. You shouldn’t have any problem with recent nvidia, however note that by default on Ubuntu you get nvidia-304. You should try a newer one. To do that (with 356 instead of 304 for instance):
sudo apt-get install bumblebee bumblebee-nvidia nvidia-356

**Comment by ArchangeGabriel** [comment]
No answer from OP, closing.
