### ISSUE TITLE
Failed to set DRM interface version and nvidia_modeset stays loaded

### ISSUE THREAD

**Issue by claudioap** [Bumblebee-Project/Bumblebee#732]
I'd prefer not to report this error once again since so many people did so, but none of the solutions work anymore.
Judging by my browsing history I've already seen and attempted any fixes in the issues #719 , #116 , #699  , #649 , #652 , #722 and #580 

I got a  laptop by Christmas. It has an Intel APU and a Nvidia 960m card.
Due to some trouble with the CPU and the newer Linux kernels I used Linux Mint (17.3) for a while and managed to set up  the Nvidia card there with bumblebee. No big deal.

In the first weeks of this month, after messing a lot with Arch I managed to get everything working in the mainline kernel (4.4rc8 at the time I think), using Nvidia 358 and dkms for bbswitch.

Recently I attempted to do a PCIe Passthrough of the GPU to KVM, and to do so I disabled bumblebee and blacklisted the Nvidia driver.
It didn't work for some reason (I'll reattempt later) but after cleaning the mess and re-enabling stuff it didn't worked.
Yesterday, after a lot of trial and looking up for the errors, I gave up, grabbed an external HDD and installed a clean system onto it. Just in case I froze the repos to the 10th of Jan, and went ahead.
Exact same errors I'm having.

I still don't understand why the bumblebee worked by then and doesn't work now if it is the exact same software packages. The conditions are exactly the same besides the bios, which was updated, and that this time I had to use dkms for the Nvidia driver since the AUR script was updated and I didn't wanted to bother using GIT to revert back to the script upon version 358.

Here are my logs and some info: https://gist.github.com/claudioap/635502c401d5ed271818
Note that I need "intel_idle.max_cstate=7 nouveau.blacklist=1" to boot, but I think it is not related.

Once again, it worked once, with this same software, for a few days and boots. It isn't the case where it never worked such as in some of the linked issues.

EDIT:
Forgot to say that glxgears / spheres and gputest (any of the tests) work just fine even with the errors. Even supertuxkart worked fine (this one within the external HDD install), the problem is more with serious games such as steam ones, which open up a window for a second or two and the it suddently close. Here is the log of running steam directly with 'optirun steam': https://gist.github.com/claudioap/a543eeaf64fcfcf91915

The same happens with running steam on the intel card and using 'optirun %command%' as games launch parameters.
Optirun / primusrun have the same results

**Comment by claudioap** [comment]
Since then I reinstalled the OS from scratch, very very slowly, with a lot of care to find out what was wrong.
I managed to get past a GNOME minimal environment with bumblebee working as of Nvidia 361.18. Note that all of the errors applied (DRM and Modeset), but at least the system worked even without them. The fan speed was proportional to the load and the games launched normally.

Then a few hours after, 361.28 came. Along with it a lot of packages were installed(manually, not as dependencies) , all of them user programs I think, nothing related to the system/drivers/libraries.
Reboot and... nothing worked. At first 361.28 was to blame due to the glvnd issues, but even after a downgrade it refused to work.

Fan speed goes to "250k RPM" a few seconds after bumblebee loads, acording to lm_sensors, probably ~3000 RPM, and sticks there forever, even if bumblebee gets unloaded.

Can't log to any Xorg based session from GDM with bumblebee on, it just freezes half second after inserting the password and pressing enter. And by freezing I don't mean only gdm, I mean the whole system. An hard reset is required.

Other user with a similar laptop (mine is a GL552VW, he has the 17" version) had similar issues, and fixed them with a clean install, but that was two weeks ago, before the nvidia brekages. Also Im not sure if he did anything more than a minimal system. Maybe something is conflicting with bumblebee.

I'll try to reinstall or at least debug in a week. This is getting really boring to deal with since at some random moment can suddenly stop working.

**Comment by waltercool** [comment]
@claudioap Please try my solution. Works good for me: https://github.com/Bumblebee-Project/Bumblebee/pull/751

**Comment by claudioap** [comment]
@waltercool  I'll try once 364 arrives. I'm hoping it has some bugfixes which make the experience a bit less painful.
Right now I don't even have a driver for the Nvidia card, its fully disabled since I'm avoiding messing with the Xorg settings.
I'm sorry for leaving this bug open until then but I have better things to do in life than gaming.

**Comment by waltercool** [comment]
You don't need to be gamer to use your video card lol, there is a lot of other usages like GPU computing or apps using GPU

**Comment by ArchangeGabriel** [comment]
@claudioap You experience unloading issue like everyone (#719). Should be fixed soon (#762). If you’re still having some issues, feel free to reopen (or rather open a new bug with new logs for the problem).
