### ISSUE TITLE
Another failed to set drm interface version permission denied

### ISSUE THREAD

**Issue by leledumbo** [Bumblebee-Project/Bumblebee#737]
Device: ASUS X455LB-WX034D
Distro: Manjaro Linux 64-bit KDE edition
Kernel: 4.4.1
libdrm version: 2.4.66
Nvidia driver version: 352.79
Logs and configs gist: https://gist.github.com/leledumbo/2b2a743293def655197b

**Comment by leledumbo** [comment]
Managed to get it working by modifying /etc/bumblebee/xorg.conf.nvidia to:

```
Section "ServerLayout"
    Identifier "Layout0"
    Option "AutoAddDevices" "false"
    Option "AutoAddGPU" "false"
EndSection

Section "Device"
        Identifier  "DiscreteNvidia"
        Driver      "nvidia"
        VendorName "NVIDIA Corporation"
        BusId "PCI:4:0:0"
        Option "ProbeAllGpus" "false"
        Option "NoLogo" "true"
        Option "UseEDID" "false"
        Option "UseDisplayDevice" "none"
        Option "ConnectedMonitor" "DFP"
EndSection

Section "Screen"
    Identifier "Default Screen"
    Device "DiscreteNvidia"
EndSection
```

**Comment by ArchangeGabriel** [comment]
So, Manjaro apparently auto-generated the file but get the identifier wrong (just in case anyone came here for the same reason). Besides, they are not using our latest config for quite a long time ago…
