### ISSUE TITLE
No donation link

### ISSUE THREAD

**Issue by lukepalmer** [Bumblebee-Project/Bumblebee#744]
You should add a donation link. 

Considering the next couple of hours of my life will not be spent tinkering with X configs, I'd be happy to support.

**Comment by Lekensteyn** [comment]
Donating time (to weed through open issues) is preferred, we currently don't accept money.

Glad that we could help though :smiley:

**Comment by ArchangeGabriel** [comment]
To add a bit more here, we decided from the start we will not accept donations. Instead, you could donate to upstream projects like freedesktop.org that does the heavy job of PRIME/kernel drivers/mesa/Xorg/Wayland dev.
