### ISSUE TITLE
Cannot access secondary GPU

### ISSUE THREAD

**Issue by bartQu9** [Bumblebee-Project/Bumblebee#749]
Distro: `Debian Stretch (Testing)`
Kernel:`4.4.0-1-amd64 #1 SMP Debian 4.4.6-1 (2016-03-17) x86_64 GNU/Linux`

My bumblebee was working fine but now, when I'm trying to run any aplication on the seccondary GPU via optirun I receive followning error: 

```
root@bartek-debian:/home/bartek# optirun -vv neverball
[ 1259.287028] [DEBUG]Reading file: /etc/bumblebee/bumblebee.conf
[ 1259.287640] [DEBUG]optirun version 3.2.1 starting...
[ 1259.287657] [DEBUG]Active configuration:
[ 1259.287662] [DEBUG] bumblebeed config file: /etc/bumblebee/bumblebee.conf
[ 1259.287667] [DEBUG] X display: :8
[ 1259.287671] [DEBUG] LD_LIBRARY_PATH: /usr/lib/x86_64-linux-gnu/nvidia:/usr/lib/i386-linux-gnu/nvidia:/usr/lib/nvidia
[ 1259.287676] [DEBUG] Socket path: /var/run/bumblebee.socket
[ 1259.287681] [DEBUG] Accel/display bridge: auto
[ 1259.287685] [DEBUG] VGL Compression: proxy
[ 1259.287692] [DEBUG] VGLrun extra options: 
[ 1259.287704] [DEBUG] Primus LD Path: /usr/lib/x86_64-linux-gnu/primus:/usr/lib/i386-linux-gnu/primus:/usr/lib/primus:/usr/lib32/primus
[ 1259.287784] [DEBUG]Using auto-detected bridge primus
[ 1259.295078] [INFO]Response: No - error: [XORG] (EE) 

[ 1259.295100] [ERROR]Cannot access secondary GPU - error: [XORG] (EE) 

[ 1259.295110] [DEBUG]Socket closed.
[ 1259.295140] [ERROR]Aborting because fallback start is disabled.
[ 1259.295151] [DEBUG]Killing all remaining processes.
[bumblebee-bugreport-20160328_140734.tar.gz](https://github.com/Bumblebee-Project/Bumblebee/files/191774/bumblebee-bugreport-20160328_140734.tar.gz)

```

The major problem is that I don't receive any specific error just `Cannot access secondary GPU - error: [XORG] (EE)`

Here is my bumblebee-bugreport:
[bumblebee-bugreport-20160328_140734.tar.gz](https://github.com/Bumblebee-Project/Bumblebee/files/191776/bumblebee-bugreport-20160328_140734.tar.gz)

**Comment by dfszb** [comment]
I had a similar issue (with my Ubuntu 15.10 installation). The problem in my case was an incorrect naming of the NVidia module in the bumblebee.conf file. Also checking your bumblebee.conf file I can see that  [bumblebeed] section's Driver parameter is not set and [driver-nvidia] section's KernelDriver=nvidia-current (I had to change this to specific nvidia module version on ubuntu). 
Also in the xorg.conf.nvidia the BusID is commented out (the correct value can be found using lspci and checking for the nvidia graphic card).

**Comment by Lukypie** [comment]
I'm having the EXACT problem in ubuntu 16.04, in ubuntu 15.10 was working fine. I really can't get out this. Also with nouveau

**Comment by Lukypie** [comment]
Also I don't have any /var/log/Xorg.8.log but in Xorg.0.log i got

[   510.566] (II) config/udev: removing GPU device /sys/devices/pci0000:00/0000:00:1c.4/0000:03:00.0/drm/card1 /dev/dri/card1
[   513.524] (II) config/udev: Adding drm device (/dev/dri/card1) card1 /sys/devices/pci0000:00/0000:00:1c.4/0000:03:00.0/drm/card1
[   513.524] (II) xfree86: Adding drm device (/dev/dri/card1)
[   514.954] (II) LoadModule: "modesetting"
[   514.954] (II) Loading /usr/lib/xorg/modules/drivers/modesetting_drv.so
[   514.954] (II) Module modesetting: vendor="X.Org Foundation"
[   514.954] 	compiled for 1.18.3, module version = 1.18.3
[   514.954] 	Module class: X.Org Video Driver
[   514.954] 	ABI class: X.Org Video Driver, version 20.0
[   514.954] (II) UnloadModule: "modesetting"
[   514.954] (II) Unloading modesetting

I waited a couple of seconds and seems like the module doens't unload.

[   493.451] (II) config/udev: removing GPU device /sys/devices/pci0000:00/0000:00:1c.4/0000:03:00.0/drm/card1 /dev/dri/card1
[   495.654] (II) config/udev: Adding drm device (/dev/dri/card1) card1 /sys/devices/pci0000:00/0000:00:1c.4/0000:03:00.0/drm/card1
[   495.654] (II) xfree86: Adding drm device (/dev/dri/card1)
[   497.123] (II) LoadModule: "modesetting"
[   497.123] (II) Loading /usr/lib/xorg/modules/drivers/modesetting_drv.so
[   497.123] (II) Module modesetting: vendor="X.Org Foundation"
[   497.123] 	compiled for 1.18.3, module version = 1.18.3
[   497.123] 	Module class: X.Org Video Driver
[   497.123] 	ABI class: X.Org Video Driver, version 20.0
[   497.123] (II) UnloadModule: "modesetting"
[   497.123] (II) Unloading modesetting
[   497.123] (II) Failed to load module "modesetting" (already loaded, 0)
[   497.123] xf86: found device 1

**Comment by UlrichViefhaus** [comment]
I have exactly the same problem with Sparky Linux (it is a Debian testing distribution). Exactly the same error message as issuer.
Additionally my Xorg log file shows:

```

May  2 21:03:38 sparky bumblebeed[2410]: [  372.174542] [ERROR][XORG] (EE)

May  2 21:03:38 sparky bumblebeed[2410]: [  372.174580] [ERROR][XORG] (EE)

May  2 21:03:38 sparky bumblebeed[2410]: [  372.174590] [ERROR][XORG] (EE)

May  2 21:03:38 sparky bumblebeed[2410]: [  372.174597] [ERROR][XORG] (EE)

May  2 21:03:38 sparky bumblebeed[2410]: [  372.174604] [ERROR][XORG] (EE)

May  2 21:03:38 sparky bumblebeed[2410]: [  372.174610] [ERROR]X did not start properly

```
My configuration files are edited according to dfszb but it doesn't help.

**Comment by bluca** [comment]
If you are on Debian testing/unstable or ubuntu 16.04 or any derivative with Xorg >= 1.18, make sure you don't have xserver-xorg-legacy installed, as it's incompatible with bumblebee.

**Comment by Lukypie** [comment]
Already tried, but nvidia-361 on ubuntu won't let me login through lightdm (idk why) and it is he only nvidia driver which does not require the xorg-legacy package.

**Comment by bluca** [comment]
Only the legacy 340 series should require the legacy wrapper, not sure why they depend on it in Ubuntu... Anyway, maybe you could try to hack the /usr/bin/Xorg script to never run the wrapper?

**Comment by UlrichViefhaus** [comment]
Thank you bluca. Uninstalling the xserver-org-legacy package solved the problem.
I did search the web, but couldn't find a hint of that incompatibility.

**Comment by Lukypie** [comment]
I'll try this evening to hack the nvidia package and see if the problem is solved.

**Comment by ArchangeGabriel** [comment]
I’m not sure of the state of this issue. Is it a distro-specific problem with Ubuntu way of packaging Xorg?

**Comment by dfszb** [comment]
In my case this was caused by the configuration files, editing the config files helped. (and I guess this means it was a distro-specific issue).

**Comment by ArchangeGabriel** [comment]
Yes, from further reading in #759 and #761, I’ve figured out that things seems quite broken by default on Ubuntu 16.04. Looking for someone using that distro to look into that.

**Comment by ArchangeGabriel** [comment]
Maybe a bug should be filed at https://bugs.launchpad.net/ubuntu/+source/bumblebee.

**Comment by bartQu9** [comment]
I also think it's a distro-specific issue. In my case this problem appeared when I did a kernel upgrade via apt-get, but I'm not able to tell You wheter/ and what packages were required to satisfy dependiencies. Coincidentally I had to do clear inststallation with newer kernel version and then fresh bumblebee installation worked well.

**Comment by bartQu9** [comment]
I want only remind that in my case using distribution is Debian

**Comment by ArchangeGabriel** [comment]
@bartQu9 Yes, but you went able to solve it by reinstalling/cleaning the conf. Other people around here on Ubuntu 16.04 seems to have to modify default conf files/ldconfig to get things working.

**Comment by Lukypie** [comment]
I've got Ubuntu 16.04 and I've solved by manually removing the xorg wrapper from the xorg-legacy package, checked that in Ubuntu 15.10 and it wasn't a dependency, so that's why the problem came just with this version of Ubuntu. This occurs with all versions of the nvidia driver. Strangely, after a second reboot, I wasn't also able to login into unity from lightdm, after doing this trick, so I had to remove/reset the dconf configuration of my user.

**Comment by TiZ-EX1** [comment]
Well this is a conundrum. I run my games in a secondary X server, which I can't start unless I have xserver-xorg-legacy. But bumblebee now conflicts with xserver-xorg-legacy? Is there some way around this? I was thinking I could copy that Xorg wrapper somewhere that it won't get run by default, and have my script's startx invoke it manually, but is there a better way to get around this?

**Comment by ArchangeGabriel** [comment]
If it’s a matter of Xorg wrapper, #743 could help.

**Comment by TiZ-EX1** [comment]
Yeah, that seems like a good thing to have in any case... however, it seems that if I remove xserver-xorg-legacy, my game running script still works as long as my regular user can access my tty dev. I should look into some way to make sure my user can always access the ttys with udev. So never mind my concerns, haha!

**Comment by SG5** [comment]
@bluca after remove package ```xserver-xorg-legacy``` I've got error
> [ERROR]Cannot access secondary GPU - error: [XORG] (EE) Failed to load module "mouse" (module does not exist, 0)

**Comment by bluca** [comment]
I guess xorg doesn't work for you without the legacy wrapper. If you are on Debian, we just uploaded a version that bypasses it without needing to remove it.

**Comment by TiZ-EX1** [comment]
Do you think the package is likely to work on Ubuntu Xenial as well? If so, where can I snag it?

**Comment by ArchangeGabriel** [comment]
No, that’s on 16.04, like everyone else here. We’re quite close to release 4.0, hope for Ubuntu users that @Vincent-C or @happyaron (or even yourself @bluca, I’m not sure who does what now in this packaging team…) will be able to release it to the PPA too.

@TiZ-EX1 Not sure about the state today, but normally it should (when Debian packaging entered the game, we made sure that it would work for both to relieve Ubuntu packaging work when downstreaming).

**Comment by bluca** [comment]
@TiZ-EX1 - the built binary .deb is not compatible, the nvidia-driver is quite different in Ubuntu. However the source is shared, so if you rebuild it locally in Ubuntu it should work. But I've only tested it in 15.10, not in 16.04 (don't have a machine with that yet). Some feedback would actually be useful to have :-) Repo: https://anonscm.debian.org/cgit/pkg-nvidia/bumblebee.git/

@ArchangeGabriel - I'm not sure I've got powers to do releases on the PPA. The package in the official Ubuntu archive is synced automatically, so 16.10 already has the new version with the fix: http://packages.ubuntu.com/yakkety/bumblebee
But AFAIK Ubuntu doesn't sync from Sid after release, so it won't make it in Xenial unless a Ubuntu dev uploads it manually.

**Comment by Vincent-C** [comment]
If anyone needs me to make an upload to the PPA, just give me a shout! I'm only loosely following along with bumblebee since @bluca has basically been taking care of everything on the Debian side (I'm just taking the opportunity to catch up with all my other neglected packages in Debian after being MIA for a while). As for an update via the official Ubuntu archive, I don't think we've ever bothered with that in the past, since Ubuntu SRUs are just as much of a hassle as Debian stable updates, so we've just seemed to expect Ubuntu users to use the PPA.

**Comment by ArchangeGabriel** [comment]
Yeah, we don’t care about official Ubuntu repos because they don’t sync after release indeed. We rely on the PPA instead. About that one, I can give you the required powers @bluca, especially if it suits both you and @Vincent-C that you take care of it. ;)

BTW, I’ve added you the right for the bumblebee-ppa repo already.

**Comment by bluca** [comment]
@Vincent-C thanks Vincent!

@ArchangeGabriel thank you! Sometimes soon (this weekend probably) I'll test everything again on Ubuntu and if it works fine I'll update the PPA.

**Comment by ArchangeGabriel** [comment]
@bluca Just granted you access to the Launchpad group. For the upload, please put things in the dev PPA first, and ask users here or at #759 and #761 to test it before copying to stable. I’m assigning you to these issues.

**Comment by bluca** [comment]
Will do, thanks!

**Comment by TiZ-EX1** [comment]
Yakkety's bumblebee and bumblebee-nvidia packages work fine for me.

**Comment by bluca** [comment]
That's good to know, thanks for the feedback. Yakkety synced across the changes that we uploaded to Debian, which include the patch to change the location of the Xorg binary.

**Comment by bluca** [comment]
I have synchronized the packaging with Debian on the testing PPA.
If someone on 16.04 or older releases could give a hand to test it, it would be really great!

ppa:bumblebee/testing
https://launchpad.net/~bumblebee/+archive/ubuntu/testing

**Comment by SG5** [comment]
@bluca test version throw error with and without `xserver-xorg-legacy` and `xserver-xorg-input-libinput` packages
>Failed to load module "mouse" (module does not exist, 0)

Logs and configuration files - https://gist.github.com/SG5/ead0b116c5b8f5b37e048cf1224a02bb

**Comment by bluca** [comment]
Thanks for the feedback! That is safe to ignore, and in fact the dev branch already does. I will backport a patch until the next release.

Besides this, any other issue?

**Comment by ArchangeGabriel** [comment]
@SG5 You’re affected by https://github.com/Bumblebee-Project/Bumblebee/commit/2073f8537412aa47755eb6f3f22a114403e5285b. You can either compile a version that include this by yourself, or wait for 4.0 to be released (shouldn’t take too long now).

**Comment by bluca** [comment]
We backported that commit, so the version Debian and the PPA already have that fix: https://github.com/Bumblebee-Project/bumblebee-ppa/blob/master/xenial/bumblebee/debian/patches/fix-device-detection.patch

**Comment by ArchangeGabriel** [comment]
Oh, right. Then I think it’s most probably:
```
[ 157.914] (EE) No devices detected.
```

And then all possible xf86 drivers loading (modesetting, nouveau, fbdev…) and finally modesetting trying to make it works. Could it be something like https://github.com/Bumblebee-Project/Bumblebee/issues/604? The dmesg excerpt is very small for a nvidia loading…

**Comment by SG5** [comment]
@ArchangeGabriel on xubuntu 15.10 it`d worked with `ppa:bumblebee/stable`

**Comment by bluca** [comment]
I've published on the test repository a version that should fix all problems with the modules, if someone is available to help testing it would be great!

https://launchpad.net/~bumblebee/+archive/ubuntu/testing

Please make sure that /lib/nvidia-<VERSION>/modprobe.conf is symlinked in /etc/modprobe.d/, otherwise link it and run sudo depmod (and then open a bug in launchpad against nvidia-driver).

**Comment by roketscyntist** [comment]
The testing repo works very well on my MSI laptop with an Intel 4600 and Nvidia 840M, using Nvidia driver 367.18 (beta) on Xenial. I have power saving again after a very long time, and games seem fine.

**Comment by bluca** [comment]
@SG5 - could you please try with the latest version from the testing PPA?

**Comment by SG5** [comment]
@bluca same error with nvidia-361 and nvidia-364
>[ 1014.703069] [INFO]Response: No - error: [XORG] (EE) Failed to load module "mouse" (module does not exist, 0)
>[ 1014.703085] [ERROR]Cannot access secondary GPU - error: [XORG] (EE) Failed to load module "mouse" (module does not exist, 0)

https://gist.github.com/SG5/e9462a8c94a597941833758468600c7d

**Comment by bluca** [comment]
Mmh I still think this is the problem:

```
[   255.552] (EE) modeset(0): eglInitialize() failed
[   255.552] (EE) modeset(0): glamor initialization failed
```

Problems with libglvnd?

**Comment by SG5** [comment]
@bluca nvidia-358 have `eglInitialize() failed` too

**Comment by SG5** [comment]
I try use pure prime. After remove bumblebee* i run `nvidia-settings` and saw nvidia GPU selected. But when i run `glxgears` i've got error
>Error: couldn't get an RGB, Double-buffered visual

After switch to intel and back to nvidia GPU (with logout-login) `nvidia-settings` display nvidia GPU selected but now with extra information (temprature, voltage, power save modes). And now `glxgears` run without any error.
I switch to intel GPU and instal bumblebee. And now i have error from first part
>Xlib:  extension "GLX" missing on display ":8".
>Error: couldn't get an RGB, Double-buffered visual

logs https://gist.github.com/SG5/8d2295a3c85f58e7f20f1a4b74710174

**Comment by Sompom** [comment]
@bluca -- I am having the same symptom as @SG5 was originally having; the Xorg server fails to load the module "mouse" . One very key difference is I am using the Nouveau driver on the 4.6 kernel (that is supposed to work, right? I can't find an Nvidia driver that doesn't blow up KDE, and I like KDE!)

I have band-aided over the original problem by installing xserver-xorg-input-void and adding an input device using that driver to the xorg.conf.nouveau and setting that as the core pointer for the server layout... (See: https://gist.github.com/Sompom/ab3ca27941d32dd0d0ae45b6c22d7154)

Is the error with the mouse driver a problem or just a symptom of a different problem? I am using your lovely testing PPA. Should I try to compile from source for all the goodness bumblebee 4.0 is supposed to offer?

The funny thing about the commit ArchangeGabriel referenced  (2073f8537412aa47755eb6f3f22a114403e5285b) is that lspci says my NVidia card is on 06:00.00, so hopefully hex vs. decimal doesn't make a difference for me

...

After applying that little band-aid, what is probably the actual problem appeared. Xorg says:
```
modeset(0): drmSetMaster failed: Invalid Argument
Fatal server error:
AddScreen/ScreenInit failed for driver 0
```
[Xorg.8.log.txt](https://github.com/Bumblebee-Project/Bumblebee/files/285798/Xorg.8.log.txt)

(I am going to have my foot in my mouth if this is because I don't understand Xorg well enough and it needs some updated nouveau something, etc...)

Do you want more information from me? This is all happening on a 3rd generation Lenovo Yoga 14 with an NVidia 940m and Intel Iris 520.

**Comment by bluca** [comment]
The testing PPA already backports the changes from 4.0.
What Ubuntu version are you running? Do you have xserver-xorg-legacy installed?

I can't prove it yet, as i can't reproduce, but I suspect the mouse issue is a red herring. I'll try sometimes this weekend on my laptop.

**Comment by bluca** [comment]
```
[  3243.421] (EE) [drm] Failed to open DRM device for pci:0000:06:00.0: -19
[  3243.421] (EE) No devices detected.
```

What's your nouveau xorg conf?

**Comment by Sompom** [comment]
@bluca ,
I am running Ubuntu 16.04, I had removed xserver-xorg-legacy per discussion earlier in this ticket, and my xorg.conf.nouveau is here: https://gist.github.com/Sompom/e4d2c65bef33347be4529361eb9051e1
(The xorg.conf.nouveau is the default plus the band-aid to stop the error with the mouse.)

**Comment by bluca** [comment]
@SG5 - I updated to Xenial, and I had the same glxgears error. That had nothing to do with bumblebee packages, but it happened because the update-alternatives mesa symlinks were all screwed up. This is how I fixed it:

sudo apt-get install libgl1-mesa-glx:i386
sudo apt-get install libegl1-mesa:i386
sudo update-alternatives --config i386-linux-gnu_gl_conf
sudo update-alternatives --config i386-linux-gnu_egl_conf
sudo update-alternatives --config x86_64-linux-gnu_gl_conf
sudo update-alternatives --config x86_64-linux-gnu_egl_conf

In ALL selections, when prompted for a choice, pick the MESA provider, NOT the nvidia one. EG: /usr/lib/i386-linux-gnu/mesa/ld.so.conf

**Comment by bluca** [comment]
@Sompom - we are considering dropping support for nouveau, as with modern kernel versions it is becoming unnecessary. I would recommend reading this discussion: https://github.com/Bumblebee-Project/Bumblebee/issues/773 and perhaps considering using the suggestions from there (DRI_PRIME and all that).

**Comment by SG5** [comment]
@bluca There were two with nvidia and two with mesa, but commands has no effect. Same error
>modeset(0): eglInitialize() failed

https://gist.github.com/SG5/a2739e9efed00f689d1c9ed7888a6f29

**Comment by bluca** [comment]
Are you using xorg.conf generated from nvidia-xconfig? Because those will also cause problems - you should clear those up.

Also, I have a glamor_conf xorg file that disables glamor, installed by nvidia-361. Check that you have that too (Xorg log you posted complained about that):
/usr/share/X11/xorg.conf.d/glamoregl.conf, which is a symlink to /etc/alternatives/glamor_conf, which is an alternative with only one provider, /usr/share/nvidia-361/glamor.conf. If the symlink is not set, run:
sudo update-alternatives --config glamor_conf

**Comment by SG5** [comment]
Few weeks ago I do clear installation xubuntu 16.04, and it has only Nouveau drivers.
But have some error "primus: fatal: Bumblebee daemon reported: error: [XORG] (EE) Failed to load module "mouse" (module does not exist, 0)"

https://gist.github.com/SG5/04284128d1543fada28f349c6463b3cc

**Comment by bluca** [comment]
That's a red herring. The real error is at the end:

```
[180013.128] (EE) modeset(0): drmSetMaster failed: Invalid argument
[180013.128] (EE) 
Fatal server error:
[180013.128] (EE) AddScreen/ScreenInit failed for driver 0
```

**Comment by BaronBaleron** [comment]
@SG5 I found solution solved "mouse" problem for me at the end of file /etc/bumblebee/xorg.conf.nvidia include the following screen-section to make bumblebee work:

Section "Screen"
  Identifier "Default Screen"
  Device "DiscreteNvidia"
EndSection

Maybe this will also work for you.

**Comment by ppmt** [comment]
I have the same issue with the mouse (which prevents the application to start)

I implemented the Section "Screen" above and restarted bumblebeed but it still doesn't work

**Comment by bluca** [comment]
The mouse/keyboard errors are red herrings. Please upload the full log to pastebin/gist and link it here. There is most likely another error lurking.

**Comment by ppmt** [comment]
Hello @bluca , thanks for helping. Here the log file Xorg.8.log

https://gist.github.com/ppmt/b35a24b512bf0c37a2e60b883a187844

**Comment by user-az** [comment]
Hi. My workaround for "mouse" problem is 
0. Reading for archlinux forums I'd found smthng like "restart your bumblebee service"
So, after restarting the one and starting 
$optirun --status
Bumblebee status: Ready (3.2.1). X inactive. Discrete video card is off.
But trying 
$optirun glxgears
I still had the same "mouse" problem.

1.I've checked  lspci  for my nvidia card
01:00.0 3D controller: NVIDIA Corporation GK107M [GeForce GT 750M] (rev ff)

2. I have uncommented string in /etc/bumblebee/xorg.conf.nvidia
   BusID "PCI:01:00:0"

Now I can run without errors
$optirun glxgears

Hope it will help somebody on a similar hardware.

**Comment by ppmt** [comment]
@user-az : thanks a lot! that did it for me too. 

I uncommented the BUSID line and now it all works. Optirun will launch the app.

without optirun : 
$ glxgears 
Running synchronized to the vertical refresh.  The framerate should be
approximately the same as the monitor refresh rate.
304 frames in 5.0 seconds = 60.644 FPS
301 frames in 5.0 seconds = 60.037 FPS

and with optirun :
$ optirun glxgears 
9357 frames in 5.0 seconds = 1871.284 FPS
9323 frames in 5.0 seconds = 1864.526 FPS

**Comment by jryaonj** [comment]
I've got the same problem on Ubuntu 16.04, and removing package **xserver-xorg-legacy** really helps!
I use my laptop with only one external screen with HDMI connection (which means no consideration for xserver compatibility issues needed), and now everything seems OK.

**Comment by louisgv** [comment]
I can confirm that doing 
`sudo apt remove xserver-xorg-legacy`

then restart bumblebeed worked for me.

**Comment by davidparks21** [comment]
Confirming that removing xserver-xorg-legacy worked for me on Linux Mint 18.1 on an MSI GS 60 Ghost with 970M and an Intel embedded GPU.

**Comment by jkdf2** [comment]
Thanks to somebody on the Arch forums I have realized that this may be because of TLP disabling the GPU driver. Fix is to blacklist the GPU driver with `RUNTIME_PM_BLACKLIST` and `RUNTIME_PM_DRIVER_BLACKLIST`:

https://bbs.archlinux.org/viewtopic.php?id=218757

**Comment by skarmiglione** [comment]
For me too.

**Comment by leon9923** [comment]
@BaronBaleron could you please post the screen of the xorg nvidia file?

**Comment by HugoPoi** [comment]
LinuxMint 18.1 (Xenial) - Asus U36JC, GT218M [GeForce 310M]
I need package `nvidia-340` (only this one supporting GeForce 310M) but depends on `xserver-xorg-legacy` so I do `sudo dpkg -r --force-all  xserver-xorg-legacy`
After reboot everything work !

**Comment by danielmihai** [comment]
Hello, I have removed xserver-xorg-legacy, and xserver-xorg-videau-nouveau, blacklisted nouveau (to be able to boot/login successfully), the BUSID is uncommented and has the right ID "PCI:01:00:0". I've done the Screen trick, I managed to start bumblebeed, but the error is still in syslog. I've done the TLP trick too.
I'm using nogpumanager in grub. 

I'm running Ubuntu 16.04.4LTS with 4.10.0.20-generic kernel and NVIDIA 378.13 driver.

The syslog: https://pastebin.com/06BCUdRH

This appeared after upgrading to 4.10.0.20-generic. On 4.10.0.19-generic all was running smooth. Couldn't  do it on 4.10.0.19 again.

P

**Comment by bluca** [comment]
What laptop & GPU do you have?

**Comment by danielmihai** [comment]
Hi @bluca , 

Dell XPS 15 9560
gtx 1050 4gb

I added +iglx to /usr/share/lightdm/lightdm.conf.d/50-xserver-command.conf to make normal opengl apps work with intel. Could not run them before. 

I installed nvidia-381 from the apt repos (no nvidia proprietary drivers install, even though I installed 378 by extracting the driver and patching it with a patch from the nvidia forums, https://devtalk.nvidia.com/default/topic/995429/linux/failed-installed-nvidia-with-kernel-4-10/). 

By installing the nvidia-381, apt said a lot of packages were going to be removed (including nvidia-current), I read that sometimes this was the issue. I will make another pastebin. https://pastebin.com/VDNqz13Z This is the terminal output from apt. (apart from the subject, if you know how to solve the 
/sbin/ldconfig.real: /usr/local/lib/libboost_math_tr1l.so.1.62.0 is not a symbolic link errors, I'll send you a beer through paypal :)) )

I changed the bumblebee.conf to point to 381 drivers. Reboot. All works. What should I check for now ? 
I tested runnning glxgears with and without optirun. bbswitch indicator is on when running with optirun, off when running without.

Thanks,
Daniel.

**Comment by bluca** [comment]
Sorry, I'm a bit lost - is it working with 381 or not?

Also make sure to use the Xenial testing PPA if you are on 16.04: https://launchpad.net/~bumblebee/+archive/ubuntu/testing

**Comment by danielmihai** [comment]
Hi Luca,

I was using the testing ppa. Yes, it works now, finally!

What should i check/run to see all runs in between recommended parameters?

Thanks,
Daniel M. Colceag

**Comment by bluca** [comment]
I've just uploaded a new version that will fix apt trying to remove everything when installing nvidia-381.

If you can run "optirun glxgears -info" a couple of times and it works, and it prints that it's using the nvidia GLX driver then you are all good.

**Comment by danielmihai** [comment]
But I guess that's what made it work!
It is possible that, among the old components which were already installed,  the culprit resided. I suspect nvidia-current. Hope I'm not saying horse poo. Correct me if i'm wrong or incomplete, please. Or explain what was wrong 

Thanks

Daniel M. Colceag

**Comment by bluca** [comment]
I'm referring to a different problem - bumblebee-nvidia depends on a list of available drivers, and 381 was missing. It's now been added to the list.

Yes, you shouldn't have multiple versions of the driver packages installed in Ubuntu, they conflict with each other, so it's correct to have only one.

Happy you could get it working - given all issues here seem solved, I'll close now for housekeeping.

**Comment by danielmihai** [comment]
As I've witnessed, the default driver for bumblebee-nvidia was nvidia-304. What version are you going to recommend when one installs bumblebee-nvidia for the first time ?
Installation of the nvidia-381 removed 304 and installed its dependencies, as you can see in the log.

**Comment by bluca** [comment]
It depends on the hardware. Different series support different cards, the distribution should have an autodetect script, else Nvidia's website has the official list

**Comment by danielmihai** [comment]
I get a strange behavior after 1 day of using it. Didn't happen until today, though. I put the laptop to sleep using the right-most menu from the status bar. Touchpad loses its click and tap-to-click on wake-up, same for restart.

**Comment by danielmihai** [comment]
fixed after updating to next version of bumblebee released.

**Comment by JeffMings** [comment]
For those struggling with systems like mine, this may save you the headaches and time I spent:
-System- ThinkPad T430s with I5, intel integrated graphics and Nvidia NVS 5200m.
-Ubuntu 16.04, completely updated
-I was never able to get Bumblebee to work completely, using the test/dev PPA.  Since it is known to work correctly with 16.10, Ubuntu users are probably better off just switching from 16.04 to 16.10.
-Using the NVidia 375 binary/closed driver and Nvidia Prime worked surprisingly well, with very little pain.  I am able to explicitly switch between integrated Intel and Nvidia easily with Nvidia Prime.
-The performance gains from the Nvidia GPU are minor (playing Eve Online under Wine) and the steps necessary to work around the graphics artifacts and rendering issues aren't worth the trouble.  None of the graphics glitches occur using the integrated Intel graphics.
-Amazingly, the frame rate for the Intel graphics improved with the NVidia 375 driver.

**Comment by conema** [comment]
In relation to @jkdf2's comment, powertop give the same problem.

**Comment by msandy** [comment]
> If you are on Debian testing/unstable or ubuntu 16.04 or any derivative with Xorg >= 1.18, make sure you don't have xserver-xorg-legacy installed, as it's incompatible with bumblebee.

### **This!**
Finally fixed the issue on my Dell 5520:

```
$ glxgears -info
GL_RENDERER   = Mesa DRI Intel(R) HD Graphics 630 (Kaby Lake GT2) 
GL_VERSION    = 3.0 Mesa 17.3.9
GL_VENDOR     = Intel Open Source Technology Center
```
```
$ optirun glxgears -info
GL_RENDERER   = Quadro M1200/PCIe/SSE2
GL_VERSION    = 4.6.0 NVIDIA 390.87
GL_VENDOR     = NVIDIA Corporation
```
