### ISSUE TITLE
Cursor is not in the right place when using optirun

### ISSUE THREAD

**Issue by marmistrz** [Bumblebee-Project/Bumblebee#753]
I ran `optirun 0ad` under Arch Linux. Then, the buttons only respond to the clicks if I place the cursor ~50px below the button. Besides, remains of the WM can be seen at the bottom.

This doesn't happen with `primusrun`

**Comment by ArchangeGabriel** [comment]
Does it happens with `optirun -b primus 0ad`?

**Comment by marmistrz** [comment]
It does not

**Comment by ArchangeGabriel** [comment]
OK, this must be an issue of https://github.com/VirtualGL/virtualgl, but seems we are moving to primus backend as default, it doesn’t really matters.
