### ISSUE TITLE
[ERROR]Module 'nvidia' is not found

### ISSUE THREAD

**Issue by AriaAsuka** [Bumblebee-Project/Bumblebee#754]
Hello,
When I run `optirun myprog` terminal throws 
```
[ERROR]The Bumblebee daemon has not been started yet or the socket path /var/run/bumblebee.socket was incorrect.
[ERROR]Could not connect to bumblebee daemon - is it running?
```
and when I run `primusrun myprog` throws
```
socat[5930] E connect(5, AF=1 "/var/run/bumblebee.socket", 27): No such file or directory
primus: fatal: failed to connect to Bumblebee daemon: No such file or directory
```

So what should I do?

**Comment by ArchangeGabriel** [comment]
You seems to have a bad install. Do you still have this issue? If so, what distro, and please post dmesg logs after a fresh boot (use gist to paste them).

**Comment by AriaAsuka** [comment]
I've reinstall the bumblebee, it works normally. 
Thanks
