### ISSUE TITLE
nvidia mieq overflowing although using integrated graphics

### ISSUE THREAD

**Issue by marmistrz** [Bumblebee-Project/Bumblebee#757]
I'm using Bumblebee with the proprietary nvidia drivers. In my X.org log I have information about the mieq overflowing. But I haven't used the discrete graphics at since I booted!

Does bumblebee miss something while disabling the discrete graphics?

**Comment by ArchangeGabriel** [comment]
I don’t know what the `mieq overflowing` is at all. Could you give a bit more logs? (like dmesg after a fresh boot)

**Comment by marmistrz** [comment]
Well, it finally appeared to be an nvidia driver bugs, after upgrading to 364, the problem disappeared. There was an entry in the Arch Linux bugzilla, but I can't find it atm.
