### ISSUE TITLE
Bumblebee not disabling nvidia graphics after upgrade to kernel 4.4.7

### ISSUE THREAD

**Issue by marmistrz** [Bumblebee-Project/Bumblebee#758]
Although the dmesg log claim bbswitch did it. Happened once, disappeared after reboot

**Comment by HileV** [comment]
Upgrade ur kernel to 4.5

**Comment by marmistrz** [comment]
4.4.7 is the lts kernel for Arch, I'm not a fan of frequent kernel upgrades. 
It's happening for me once again

**Comment by marmistrz** [comment]
Ok, I see, the problem is that the nvidia_drm module is not loaded, which depends on nvidia_modeset.

**Comment by ArchangeGabriel** [comment]
Dupe of #719.
