### ISSUE TITLE
Sporadically turns off and on again 1080p ext. HDMI Monitor after upgrade to Ubuntu 16.04

### ISSUE THREAD

**Issue by ixbidie** [Bumblebee-Project/Bumblebee#779]
After upgrade to kubuntu 16.04 my external monitor sporadically turns off and on again when suplied with 1080p. Doesn 't happen with 720p. Issue is gone after I uninstalled bumbleebee. Can't see anything suspicious in logs.

Give me hints or request further information and I suply you with them.

**Comment by Lekensteyn** [comment]
Post your laptop model (preferably with product specification page).
Post the output of:

    lspci -nn | grep 'VGA|3D' -E
    ls -l /sys/class/drm/

**Comment by ixbidie** [comment]
Commands executed without external monitor attached. 


**output of 'lspci' is**

```
00:02.0 VGA compatible controller [0300]: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller [8086:0126] (rev 09)
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GF108M [GeForce GT 540M] [10de:0df4] (rev ff)
```


**The output of 'ls -l /sys/class/drm/' is**
```
lrwxrwxrwx 1 root root    0 Jul  6 11:45 card0 -> ../../devices/pci0000:00/0000:00:02.0/drm/card0
lrwxrwxrwx 1 root root    0 Jul  6 11:45 card0-DP-1 -> ../../devices/pci0000:00/0000:00:02.0/drm/card0/card0-DP-1
lrwxrwxrwx 1 root root    0 Jul  6 11:45 card0-HDMI-A-1 -> ../../devices/pci0000:00/0000:00:02.0/drm/card0/card0-HDMI-A-1
lrwxrwxrwx 1 root root    0 Jul  6 11:45 card0-LVDS-1 -> ../../devices/pci0000:00/0000:00:02.0/drm/card0/card0-LVDS-1
lrwxrwxrwx 1 root root    0 Jul  6 11:45 card0-VGA-1 -> ../../devices/pci0000:00/0000:00:02.0/drm/card0/card0-VGA-1
lrwxrwxrwx 1 root root    0 Jul  6 11:45 card1 -> ../../devices/pci0000:00/0000:00:01.0/0000:01:00.0/drm/card1
lrwxrwxrwx 1 root root    0 Jul  6 11:45 card1-VGA-2 -> ../../devices/pci0000:00/0000:00:01.0/0000:01:00.0/drm/card1/card1-VGA-2
lrwxrwxrwx 1 root root    0 Jul  6 11:45 controlD64 -> ../../devices/pci0000:00/0000:00:02.0/drm/controlD64
lrwxrwxrwx 1 root root    0 Jul  6 11:45 controlD65 -> ../../devices/pci0000:00/0000:00:01.0/0000:01:00.0/drm/controlD65
lrwxrwxrwx 1 root root    0 Jul  6 11:45 renderD128 -> ../../devices/pci0000:00/0000:00:02.0/drm/renderD128
lrwxrwxrwx 1 root root    0 Jul  6 11:45 renderD129 -> ../../devices/pci0000:00/0000:00:01.0/0000:01:00.0/drm/renderD129
lrwxrwxrwx 1 root root    0 Jul  6 11:45 ttm -> ../../devices/virtual/drm/ttm
```

**HOWEVER**: I figured it might be useful to verify that bumblebee actually works. It doesn't. If I run 'optirun glxgears' the xserver crashes immediatly and I'm back to my login screen. Should I close this ticket and make sure it works before asking again?

`The X11 connection broke (error 1). Did the X11 server die?`

**Comment by Lekensteyn** [comment]
I think that the nouveau driver is loaded and controls your external video card. When nouveau is loaded, your primary X server will probably use it too which is why it crashes once you run `optirun glxgears`.

I suggest to remove Bumblebee unless you really need it. nouveau can also power off your video card without bbswitch.

**Comment by ixbidie** [comment]
I once installed it for energy saving purposes, but maybe things changed. However, I will come back if I keep bumblebee, it actually works and the error is still there.
