### ISSUE TITLE
[SOLVED] On a segfault error in libGL.so

### ISSUE THREAD

**Issue by ehingant** [Bumblebee-Project/Bumblebee#783]
Hello every body,

# Context
 I am trying to use bumblebee/optirun on my laptop using debian jessie (3.16.0-4-amd64). My laptop possess a Nvidia Geforce 920M card. I installed everything as it is mentioned in the debian [wiki](https://wiki.debian.org/Bumblebee) except that I update the nvidia-driver with the jessie-backports, because the one in the stable repository does not support the card. Well now I try to use the classical 
`optirun glxgears -info`
in order to check my installation but It remains silent. 

# The problem

A `dmesg` give the following SEGFAULT information about libGL.so.1:  

>[ 3325.633953] glxgears[15459]: segfault at 0 ip 00007feaaec08747 sp 00007ffe27151f50 error 4 in libGL.so.1[7feaaebe3000+41000]

I tried to found solutions on the web, but nothing works... I just found something related to nomodeset but I have not this option in cmdline. Please if somebody can help me it would be very precious, I am totally lost! 

# Other informations

The ouput with option `-vv` is:

> [ 3322.885865] [DEBUG]Reading file: /etc/bumblebee/bumblebee.conf
[ 3322.886476] [INFO]Configured driver: nvidia
[ 3322.886665] [DEBUG]optirun version 3.2.1 starting...
[ 3322.886694] [DEBUG]Active configuration:
[ 3322.886709] [DEBUG] bumblebeed config file: /etc/bumblebee/bumblebee.conf
[ 3322.886727] [DEBUG] X display: :8
[ 3322.886744] [DEBUG] LD_LIBRARY_PATH: /usr/lib/x86_64-linux-gnu/nvidia:/usr/lib/i386-linux-gnu/nvidia:/usr/lib/nvidia
[ 3322.886759] [DEBUG] Socket path: /var/run/bumblebee.socket
[ 3322.886774] [DEBUG] Accel/display bridge: auto
[ 3322.886790] [DEBUG] VGL Compression: proxy
[ 3322.886805] [DEBUG] VGLrun extra options: 
[ 3322.886821] [DEBUG] Primus LD Path: /usr/lib/x86_64-linux-gnu/primus:/usr/lib/i386-linux-gnu/primus:/usr/lib/primus:/usr/lib32/primus
[ 3322.886884] [DEBUG]Using auto-detected bridge primus
[ 3322.887520] [INFO]Response: Yes. X is active.
[ 3322.887565] [INFO]Running application using primus.
[ 3322.887812] [DEBUG]Process glxgears started, PID 15459.
[ 3322.952823] [DEBUG]SIGCHILD received, but wait failed with No child processes
[ 3322.952842] [DEBUG]Socket closed.
[ 3322.952856] [DEBUG]Killing all remaining processes.

My `bumblebee.conf`'s file is: 

>[bumblebeed]
VirtualDisplay=:8
KeepUnusedXServer=false
ServerGroup=bumblebee
TurnCardOffAtExit=false
NoEcoModeOverride=false
Driver=nvidia
XorgConfDir=/etc/bumblebee/xorg.conf.d
XorgBinary=Xorg
[optirun]
Bridge=auto
VGLTransport=proxy
PrimusLibraryPath=/usr/lib/x86_64-linux-gnu/primus:/usr/lib/i386-linux-gnu/primus:/usr/lib/primus:/usr/lib32/primus
AllowFallbackToIGC=false
[driver-nvidia]
KernelDriver=nvidia-current
PMMethod=auto
LibraryPath=/usr/lib/x86_64-linux-gnu/nvidia:/usr/lib/i386-linux-gnu/nvidia:/usr/lib/nvidia
XorgModulePath=/usr/lib/nvidia/nvidia,/usr/lib/xorg/modules
XorgConfFile=/etc/bumblebee/xorg.conf.nvidia
[driver-nouveau]
KernelDriver=nouveau
PMMethod=auto
XorgConfFile=/etc/bumblebee/xorg.conf.nouveau

while the `xorg.conf,nvidia` is 
>Section "Screen"
    Identifier "Default Screen"
    Device "DiscreteNvidia"
EndSection
Section "ServerLayout"
    Identifier  "Layout0"
    Option      "AutoAddDevices" "false"
    Option      "AutoAddGPU" "false"
EndSection
Section "Device"
    Identifier  "DiscreteNvidia"
    Driver      "nvidia"
    VendorName  "NVIDIA Corporation"    
    Option "ProbeAllGpus" "false"
    Option "NoLogo" "true"
    Option "UseEDID" "false"
    Option "UseDisplayDevice" "none"
EndSection

**Comment by bluca** [comment]
Did you install everything from backports, including bumblebee and all its dependencies?

Please upload to gist/pastebin the result of:

reportbug --template nvidia-driver

**Comment by ehingant** [comment]
Hi! Yes everything was update with the backports, bumblebee-nvidia, and many stuffs.
Here is the result you asked. I hope it could held :)
https://gist.github.com/ehingant/a772c706ebe829d9f1f4a9785727e1dd

**Comment by bluca** [comment]
nvidia-modprobe and nvidia-support were not installed from backports, please upgrade them (unrelated to this issue).

Also, did you install/upgrade the packages separately? update-alternative is pointing to the wrong glx implementation.
To fix it, run:

`sudo update-glx --config glx`

And select "/usr/lib/nvidia/bumblebee" and then try again.

**Comment by ehingant** [comment]
Imade the updates. The other packages where updated all together when I install the nvidia-driver from the backports. 

Ifix the config of glx. But nothing new :/ Here is the result of reportbug updated: https://gist.github.com/ehingant/a772c706ebe829d9f1f4a9785727e1dd

Thanks for your help

**Comment by bluca** [comment]
Did you reboot after installing the nvidia-driver?

Also the bumblebee config has a different value for kernel modules from what we ship in backports, you can fix it by changing:

```
-KernelDriver=nvidia-current
+KernelDriver=nvidia
```

And then restart bumblebeed (sudo systemctl restart bumblebeed).

If the problem persists, please enable debug (edit /lib/systemd/system/bumblebeed.service and add `--debug` to the bumblebeed ExecStart line) and also run optirun with `--debug`, and then upload the log (both terminal and `sudo journalctl -b -u bumblebeed`).

**Comment by ehingant** [comment]
I follow yours recommendations but the problem persists. Here is the logs:
>erwan@lasus:~$ optirun --debug glxgears -info
[ 3113.014342] [DEBUG]Reading file: /etc/bumblebee/bumblebee.conf
[ 3113.014621] [INFO]Configured driver: nvidia
[ 3113.014738] [DEBUG]optirun version 3.2.1 starting...
[ 3113.014752] [DEBUG]Active configuration:
[ 3113.014760] [DEBUG] bumblebeed config file: /etc/bumblebee/bumblebee.conf
[ 3113.014769] [DEBUG] X display: :8
[ 3113.014776] [DEBUG] LD_LIBRARY_PATH: /usr/lib/x86_64-linux-gnu/nvidia:/usr/lib/i386-linux-gnu/nvidia:/usr/lib/nvidia
[ 3113.014785] [DEBUG] Socket path: /var/run/bumblebee.socket
[ 3113.014793] [DEBUG] Accel/display bridge: auto
[ 3113.014802] [DEBUG] VGL Compression: proxy
[ 3113.014811] [DEBUG] VGLrun extra options: 
[ 3113.014819] [DEBUG] Primus LD Path: /usr/lib/x86_64-linux-gnu/primus:/usr/lib/i386-linux-gnu/primus:/usr/lib/primus:/usr/lib32/primus
[ 3113.014858] [DEBUG]Using auto-detected bridge primus
[ 3116.494275] [INFO]Response: Yes. X is active.
[ 3116.494286] [INFO]Running application using primus.
[ 3116.494394] [DEBUG]Process glxgears started, PID 11219.
[ 3116.546513] [DEBUG]SIGCHILD received, but wait failed with No child processes
[ 3116.546540] [DEBUG]Socket closed.
[ 3116.546553] [DEBUG]Killing all remaining processes.

and from `journalctl -b -u bumblebeed`

>juil. 13 06:49:02 lasus systemd[1]: Stopping Bumblebee C Daemon...
juil. 13 06:49:02 lasus bumblebeed[10922]: [ 2800.286494] [WARN]Received Terminated signal.
juil. 13 06:49:03 lasus systemd[1]: Starting Bumblebee C Daemon...
juil. 13 06:49:03 lasus systemd[1]: Started Bumblebee C Daemon.
juil. 13 06:49:03 lasus bumblebeed[10950]: [ 2800.450059] [INFO]/usr/sbin/bumblebeed 3.2.1 started
juil. 13 06:49:30 lasus bumblebeed[10950]: [ 2827.937802] [WARN][XORG] (WW) NVIDIA(0): Unable to get display device for DPI computation.
juil. 13 06:53:14 lasus bumblebeed[10950]: [ 3051.434603] [WARN][XORG] (WW) NVIDIA(0): Unable to get display device for DPI computation.
juil. 13 06:54:19 lasus bumblebeed[10950]: [ 3116.494180] [WARN][XORG] (WW) NVIDIA(0): Unable to get display device for DPI computation.

**Comment by bluca** [comment]
Nothing looks wrong in the optirun debug, but sorry, forgot that you have to run:

`sudo systemctl daemon-reload`

Before restarting bumblebeed. The bumblebeed log will be quite large, please upload to gist/pastebin.

**Comment by ehingant** [comment]
After a reboot, I launch again optirun Here is the log: https://gist.github.com/ehingant/ab146bde86eff6b352a55b6a9cc269aa
:(

**Comment by bluca** [comment]
The output there looks good too, all the right modules are being loaded. I'm a bit baffled.

Can you try to run glxgears via gdb to get a backtrace? `gdb --arg optirun glxgears` then type `run` and when it crashes type `bt full`

Also, have you tried any other GL/GLX program? Also have you tried to run glxgears without optirun?

**Comment by ehingant** [comment]
Thanks a lot for helping me, I am totally baffled too, but the reason is I dont understand nothing in those stuff :D Well, glxgears works well without optirun and gdb gives:

>erwan@lasus:~$ gdb --arg optirun glxgears
GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from optirun...(no debugging symbols found)...done.
(gdb) run
Starting program: /usr/bin/optirun glxgears
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Inferior 1 (process 3959) exited with code 0213]
(gdb) bt full
No stack.
(gdb) 

I don'e know which other program should I run... sorry.

**Comment by bluca** [comment]
Sorry, try the other way around:

`optirun gdb glxgears`

**Comment by ehingant** [comment]
We have now: 

>(gdb) run
Starting program: /usr/bin/glxgears 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffec5d4700 (LWP 5275)]
[New Thread 0x7fffebdd3700 (LWP 5276)]
[New Thread 0x7fffeb5d2700 (LWP 5277)]
[New Thread 0x7fffeadd1700 (LWP 5278)]
[New Thread 0x7fffea398700 (LWP 5279)]
[New Thread 0x7fffe9b97700 (LWP 5280)]
[New Thread 0x7fffe9396700 (LWP 5281)]
[New Thread 0x7fffe8b95700 (LWP 5282)]

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff76c2747 in glXCreateContext ()
   from /usr/lib/x86_64-linux-gnu/primus/libGL.so.1
(gdb) bt full
#0  0x00007ffff76c2747 in glXCreateContext ()
   from /usr/lib/x86_64-linux-gnu/primus/libGL.so.1
No symbol table info available.
#1  0x0000000000403778 in ?? ()
No symbol table info available.
#2  0x0000000000401a27 in ?? ()
No symbol table info available.
#3  0x00007ffff6abdb45 in __libc_start_main (main=0x4018d0, argc=1, 
    argv=0x7fffffffe1a8, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fffffffe198) at libc-start.c:287
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {0, -6312449530478370909, 
                4203273, 140737488347552, 0, 0, 6312449529708896163, 
                6312430187119861667}, mask_was_saved = 0}}, priv = {pad = {
              0x0, 0x0, 0x403890, 0x7fffffffe1a8}, data = {prev = 0x0, 
              cleanup = 0x0, canceltype = 4208784}}}
        not_first_call = <optimized out>
#4  0x0000000000402332 in ?? ()
No symbol table info available.
(gdb)

**Comment by bluca** [comment]
It's failing to create the context, I really don't know why would that be sorry.

But there's something else you can try, which is to use the newer version of primus.

Warning: installing packages from testing/unstable is not supported and might lead to problems, in general. In this case it should be pretty safe. When I have time I'll do a backports, but it will take a while.

You can try to install the packages from stretch:

http://ftp.uk.debian.org/debian/pool/main/p/primus/primus-libs_0~20150328-1_amd64.deb
http://ftp.uk.debian.org/debian/pool/main/p/primus/primus_0~20150328-1_amd64.deb

And try again?

**Comment by ehingant** [comment]
Thanks a lot Luca! Well, I will not try this solution for now, I have just one laptop, and I have to make a live usb and a backup before that, because I remember some unpleasant experience doing that :D Maybe in few days and I will keep you in touch. 

Thanks, E.

**Comment by bluca** [comment]
@Lekensteyn @ArchangeGabriel @amonakov any idea why glXCreateContext might fail with primus? The kernel modules and glx loadings all look good

**Comment by ehingant** [comment]
Hi, some news! I found some people pointing out that the problem can be linked to the following result 

>erwan@lasus:~$ glxinfo | grep llvmpipe
OpenGL renderer string: Gallium 0.4 on llvmpipe (LLVM 3.5, 256 bits)

That openGL render string do not point on the GPU... I just found on guy that solves the problem reinstalling the whole system :( Could it be that problem?

E.

**Comment by bluca** [comment]
If you don't run it through optirun then it will go through the Intel card and whatever rendering it's using, so that's normal. You should be getting hardware acceleration though, so you might want to install xserver-xorg-video-intel from backports.

Reinstalling the system won't do anything, Debian is not windows :-)

**Comment by ehingant** [comment]
Yep I surely will not reinstall it :D I just see that, I wa writting a message :) It works well with optirun glxinfo, it says Nvidia Geforce blabala, I am a bit tired today!

**Comment by ehingant** [comment]
PROBLEM SOLVED!  Many  thanks Luca, I reinstalled the backport version of xserver-xorg-video-intel ... I will waste my time on x-plan 10 now :D

**Comment by bluca** [comment]
Good! Closing the issue then.
