### ISSUE TITLE
Could not enable discrete graphics card

### ISSUE THREAD

**Issue by freedomwarrior** [Bumblebee-Project/Bumblebee#789]
Machine - dell inspiron 7720 with gtx 650m/
System - `Linux debian 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) x86_64 GNU/Linux`
After installing bumblebee from this tutorial - http://fixmynix.com/install-and-configure-nvidia-optimus-with-bumblebee-in-debian/, I can't run `optirun glxspheres`, I just have this error:

```
[  541.868250] [ERROR]Cannot access secondary GPU - error: Could not enable discrete graphics card

[  541.868329] [ERROR]Aborting because fallback start is disabled.
```

**Comment by bluca** [comment]
Please don't use virtualgl, there's really no point. Install primus instead.
Also, please try with bumblebee and primus from jessie-backports.
