### ISSUE TITLE
Shutdown takes a long time

### ISSUE THREAD

**Issue by Fry-kun** [Bumblebee-Project/Bumblebee#790]
Had this issue as of upgrading Fedora 23 -> 24 (so possibly related to my problem in #784)

During shutdown, a timer is displayed -- it waits for 1.5min before killing a hung process. This can be worked around with sysrq command I (kill all tasks) -- or just by waiting for 1:30 (but who has the time to do that?? :)

When I saw this problem in F23, the solution was to add options to /etc/modprobe.d/my_own_config.conf
``` 
options bbswitch load_state=0 unload_state=0
```

As of F24, it's still present but no longer helps

**Comment by bluca** [comment]
If you check with `lsmod | grep nvidia` before shutdown, do you still see modules loaded? What about `cat /proc/acpi/bbswitch` ?

**Comment by Lekensteyn** [comment]
Does this also apply to suspend/resume? Please try to obtain a kernel log for the previous boot. Once you reboot, you can run `journalctl -kb-1` for that.

**Comment by Fry-kun** [comment]
lsmod | grep nvidia  --> nothing
cat /proc/acpi/bbswitch  --> 0000:01:00.0 OFF

suspend/resume --> no issue

reboot without logging in (from lightdm) --> no hang
reboot after logging into XFCE session --> hang


"shutdown*" logs obtained by following https://www.freedesktop.org/wiki/Software/systemd/Debugging/#index2h1



[journalctl-clean.txt](https://github.com/Bumblebee-Project/Bumblebee/files/394516/journalctl-clean.txt)
[journalctl-hang.txt](https://github.com/Bumblebee-Project/Bumblebee/files/394519/journalctl-hang.txt)
[shutdown-log-clean.txt](https://github.com/Bumblebee-Project/Bumblebee/files/394518/shutdown-log-clean.txt)
[shutdown-log-hang.txt](https://github.com/Bumblebee-Project/Bumblebee/files/394517/shutdown-log-hang.txt)

**Comment by Lekensteyn** [comment]
Are you sure it is caused by Bumblebee? Have you tried disabling the bumblebeed service?

**Comment by Fry-kun** [comment]
I've retraced everything and looks like bumblebee is not involved in this bug.
Sorry about that!
