### ISSUE TITLE
how bumblee know whether it is a Optimus device

### ISSUE THREAD

**Issue by amazingfate** [Bumblebee-Project/Bumblebee#795]
Some machine also have intel+nvidia graphics card,but not Optimus device. Do Optimus devices have something different on linux?

**Comment by bluca** [comment]
No, and AFAIK there is no way to detect that short of having a full list of devices.

**Comment by Lekensteyn** [comment]
Bumblebee currently has simple detection logic, if it finds a video card from Intel and another one from Nvidia, it assumes an Optimus setup. This is probably wrong for desktop systems, but then you should just not install it on such systems.

Actually, it can detect Optimus (indirectly). By default, the "bbswitch" power management method is used. If this method is not available, bumblebeed will fail to start. This method depends on a kernel module, called (unsurprisingly) "bbswitch".

bbswitch uses certain ACPI methods to control the Nvidia video card. If it cannot find such ACPI methods, it will refuse to load. It happens that only Nvidia Optimus systems have such ACPI methods, and therefore it is indeed possible to know whether you have an Optimus method or not.

**Comment by amazingfate** [comment]
thank you very much~
