### ISSUE TITLE
bumblebee does not start

### ISSUE THREAD

**Issue by xzr5** [Bumblebee-Project/Bumblebee#796]
the command output:
optirun glxgears

```
[  568.571137] [ERROR]Cannot access secondary GPU - error: [XORG] (EE) 
[  568.571214] [ERROR]Aborting because fallback start is disabled.
```

which steps to follow to fix?

**Comment by Lekensteyn** [comment]
1. read logs
2. search issue tracker/Google for hints

when reporting bugs, include your hardware details and software environment.
