### ISSUE TITLE
Bumblebee fps performance 

### ISSUE THREAD

**Issue by DaiAtlas** [Bumblebee-Project/Bumblebee#799]
Hello everyone, 
I'm under **Debian sid with linux 4.6.0-1-amd64 with gtx 960m and HD Graphics 530, i installed bumblebee-nvidia 3.2.1-13**

I have a strange problem : 
When i'm using glxgears im at **8000** fps, but if i used optimus, im at **3000** fps.
I installed nvidia-settings, but when im using it with optirun, he tell me "You do not appear to be using the NVIDIA X driver ...." 

I installed nvidia-detect and with optimus it's telling me : **No NVIDIA GPU detected.**
I don't used any Xorg configuration. I can see the graphic led working when i used optimus, it's mean that working. 

But if i used **nvidia-smi with optimus** , he **detect** my GPU and the driver.
And if i used nvidia-smi when glxgears working with optimus , **nvidia-smi** telling me than he working at **90%.**
And if i used **cat /proc/acpi/bbswitch** when glxgears wokring with optimus  it's **on.**

**Just for information** : i cant used gnome with Xorg but only with wayland. It's freeze with Xorg, I cant get any log unfortunately. If i used the nouveau driver it's freeze when i shutdown my computer for example or if im using the command lspci, It's give me a error : nouveau pci: failed to adjust inkctl speed. The solution was to blacklist nouveau with modprob.d\.

I don't know if it's right place to post this problem because it's not only about bumblebee. But thank for any help in advance.

**Comment by bluca** [comment]
1) nvidia-detect does not support optimus
2) for nvidia-settings, you need -c :8, eg: ```optirun nvidia-settings -c :8``` and then it will work
3) glxgears FPS count means very little. Run it with -info to confirm it's using the discrete gpu: ```optirun glxgears -info```
4) It's really not recommended to run the whole X session with optirun, just use it to launch gpu-intensive applications
5) nvidia-driver will have automatically blacklisted nouveau when installed

**Comment by DaiAtlas** [comment]
Thank you so much for the very quick answer !

1) :+1:   
2)Woah, thank you so much, its working ! :+1: :heart:  :sunny: 
3) Whe 
4) :+1: 
5) :+1:

**Comment by DaiAtlas** [comment]
Thank you so much for the very quick answer !

1) :+1:
2)Woah, thank you so much, its working ! :+1: :heart: :sunny:
3) When i run **optirun glxgears -info**, it's not mentioning discrete gpu, so here what's its telling me 

> 
> GL_RENDERER   = GeForce GTX 960M/PCIe/SSE2
> GL_VERSION    = 4.5.0 NVIDIA 361.45.18
> GL_VENDOR     = NVIDIA Corporation
> GL_EXTENSIONS =  .........
> 


4) :+1:
5) :+1:


Than you @bluca  :kiss:

**Comment by bluca** [comment]
Yes the output looks good. I'll close the issue now since all the questions have been solved, if you encounter other issues and can't find a resolution in previous tickets feel free to open another.

**Comment by karolherbst** [comment]
maybe for the future: you should add to the readme, that glxgears is not a valid benchmark for bumblebee, because of the pcie overhead, the performance on the dedicated side is usually lower.

**Comment by DaiAtlas** [comment]
Ok instead of using glxgears, i used glxshepres64 : 

- [ ] 236.021066 Mpixels/sec for GeForce GTX 960M

- [ ] 202.453807 Mpixels/sec  for Mesa DRI Intel(R) HD Graphics 530

When web look the difference beween intel 530 and nvidia 960m, we can tell than 960m don't use all of this power. [http://gpu.userbenchmark.com/Compare/Nvidia-GTX-960M-vs-Intel-HD-530-Desktop-Skylake/m27242vsm33102](url)

This dude as the same problem and he find a solution where glxspheres64 can go to 1400 Mpixels/sec.
[http://askubuntu.com/a/658043](url) 
But im on debian, and primus-nvidia is not availaible, and im sure there is an other solution for that is not working with bumblebee.

**Comment by bluca** [comment]
You did nothing wrong, this is expected. There is an additional overhead when using bumblebee+primus. PRIME is a bit faster but the usability is terrible as it requires to switch a flag and reboot every time you want to switch card.
Note that for everyday usage rather than benchmarks bumblebee is fine. If you want to run benchmarks then you'll have to either switch to Ubuntu or set up PRIME by yourself (not supported here nor by Debian maintainers)
