### ISSUE TITLE
Fedora 24 libGL.so missing

### ISSUE THREAD

**Issue by DrPyser** [Bumblebee-Project/Bumblebee#803]
I'm using the Fedora 24 repository for the closed source driver(see https://fedoraproject.org/wiki/Bumblebee#For_closed_source_solution).

 I'm having pretty much the exact problem as issue #721, except the kernel-devel package is not the problem(I have the right version for my kernel). 

My GPUs:
`lspci | grep -E "VGA|3D"`
```
00:02.0 VGA compatible controller: Intel Corporation 4th Gen Core Processor Integrated Graphics Controller (rev 06)
01:00.0 3D controller: NVIDIA Corporation GK208M [GeForce 920M] (rev a1)
```

Here's the results of `bumblebee-nvidia --check` after I've run the bbswitch check, build and install manually:

```
Warning! This NVIDIA driver userland
 /usr/lib64/nvidia-bumblebee/libGL.so.1 library is missing!


nvidia.ko compiled into in the kernel tree ok.
modinfo output for NVIDIA:

filename:       /lib/modules/4.7.3-200.fc24.x86_64/kernel/drivers/video/nvidia.ko
alias:          char-major-195-*
version:        367.44
supported:      external
license:        NVIDIA
srcversion:     62594DC43B355E37A82EB4C
alias:          pci:v000010DEd00000E00sv*sd*bc04sc80i00*
alias:          pci:v000010DEd*sv*sd*bc03sc02i00*
alias:          pci:v000010DEd*sv*sd*bc03sc00i00*
depends:        
vermagic:       4.7.3-200.fc24.x86_64 SMP mod_unload 
parm:           NVreg_Mobile:int
parm:           NVreg_ResmanDebugLevel:int
parm:           NVreg_RmLogonRC:int
parm:           NVreg_ModifyDeviceFiles:int
parm:           NVreg_DeviceFileUID:int
parm:           NVreg_DeviceFileGID:int
parm:           NVreg_DeviceFileMode:int
parm:           NVreg_UpdateMemoryTypes:int
parm:           NVreg_InitializeSystemMemoryAllocations:int
parm:           NVreg_UsePageAttributeTable:int
parm:           NVreg_MapRegistersEarly:int
parm:           NVreg_RegisterForACPIEvents:int
parm:           NVreg_CheckPCIConfigSpace:int
parm:           NVreg_EnablePCIeGen3:int
parm:           NVreg_EnableMSI:int
parm:           NVreg_TCEBypassMode:int
parm:           NVreg_UseThreadedInterrupts:int
parm:           NVreg_MemoryPoolSize:int
parm:           NVreg_RegistryDwords:charp
parm:           NVreg_RmMsg:charp
parm:           NVreg_AssignGpus:charp

Check bbswitch kernel module...

bbswitch is loaded into the current kernel ok.

All NVIDIA checks completed, but there were 1 or more failures...
Try running this script with the --debug option to find clues about what has
gone wrong with the NVIDIA driver compile process.
```

Here's an example result of `optirun glxinfo`:

```
name of display: :0
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
      after 9 requests (9 known processed) with 0 events remaining.
```

Thanks.

**Comment by gsgatlin** [comment]
What is the output from

bumblebee-nvidia --debug

?

You will need to run it as root.

**Comment by DrPyser** [comment]
`--debug mode selected.`

Nothing...

**Comment by gsgatlin** [comment]
Sorry. How strange. try:

 bumblebee-nvidia --debug --force

On my machine here is the output:

https://paste.fedoraproject.org/429187/08203414/

Also, nouveau is no longer supported. I'm sorry. nouveau already has power saving. You should just use PRIME with that. I have not had a chance to update the docs. see:
https://github.com/Bumblebee-Project/Bumblebee/issues/773

Sorry about that. maybe this weekend since I can't possibly do it at work. :(

**Comment by DrPyser** [comment]
```
--debug mode selected.
--force compile selected.
Building NVIDIA video drivers: Creating directory NVIDIA-Linux-x86_64-367.44
Verifying archive integrity... OK
Uncompressing NVIDIA Accelerated Graphics Driver for Linux-x86_64 367.44............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
WARNING: You do not appear to have an NVIDIA GPU supported by the 367.44
         NVIDIA Linux graphics driver installed in this system.  For
         further details, please see the appendix SUPPORTED NVIDIA GRAPHICS
         CHIPS in the README available on the Linux driver download page at
         www.nvidia.com.
Received signal SIGINT; aborting.
```

**Comment by gsgatlin** [comment]
Can you post /var/log/nvidia-installer.log to a site such as pastebin.com or fpaste.org?

The problem is that the "nvidia-installer" program is crashing on your laptop for some reason.

**Comment by gsgatlin** [comment]
Ok. Yeah. The installer wrapper (bumblebee-nvidia) detects if it "fails" but if it crashes part way through it doesn't detect that... hmnnn.  In any event, it needs to not crash in order to work on your machine. So hopefully it would be possible to figure out what is going on there.

**Comment by gsgatlin** [comment]
Did it ever print out a green [ok]?

**Comment by DrPyser** [comment]
Sorry, I was being an idiot and aborted when I saw the warning. Still, the problem persist. The installation does print out a green `[ok]`. Still, the same problem persist(libGL.so missing, ...).

In case it might be useful, here's pastebin link for nvidia-installer.log: http://pastebin.com/QMmFj0Sc(I set an expiration date of 1 week).

**Comment by DrPyser** [comment]
Also, a probably related problem is that my screen stays blank I wake up from sleep.

**Comment by DrPyser** [comment]
Okay. I reinstalled Fedora 24, and now it works perfectly. I think the problem is that the nvidia module was blacklisted in /etc/modprobe.d/ or elsewhere.
