### ISSUE TITLE
Ubuntu 16.04 [ERROR]Cannot access secondary GPU - error: [XORG] (EE) Failed to load module "mouse" (module does not exist, 0)

### ISSUE THREAD

**Issue by nwoods** [Bumblebee-Project/Bumblebee#807]
**Distro:** Ubuntu 16.04.1 LTS
**Kernel:** `4.4.0-36-generic #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
**Make and model:**
```
baseboard-manufacturer: Dell Inc.
baseboard-product-name: XPS 15 9530
baseboard-version     : A02
system-manufacturer   : Dell Inc.
system-product-name   : XPS 15 9530
system-version        : A02
bios-vendor           : Dell Inc.
bios-version          : A02
bios-release-date     : 12/18/2013
```
**Bumblebee version:** `optirun (Bumblebee) 3.2.1`

When trying to use optirun with Nvidia drivers `nvidia-370`, not Nouveau as in #804), I get an error message about the "mouse" module:
```
$ optirun -vv glxgears
[ 3206.354076] [DEBUG]Reading file: /etc/bumblebee/bumblebee.conf
[ 3206.354341] [INFO]Configured driver: nvidia
[ 3206.354464] [DEBUG]optirun version 3.2.1 starting...
[ 3206.354472] [DEBUG]Active configuration:
[ 3206.354475] [DEBUG] bumblebeed config file: /etc/bumblebee/bumblebee.conf
[ 3206.354479] [DEBUG] X display: :8
[ 3206.354482] [DEBUG] LD_LIBRARY_PATH: /usr/lib/nvidia-370:/usr/lib32/nvidia-370
[ 3206.354486] [DEBUG] Socket path: /var/run/bumblebee.socket
[ 3206.354491] [DEBUG] Accel/display bridge: auto
[ 3206.354496] [DEBUG] VGL Compression: proxy
[ 3206.354501] [DEBUG] VGLrun extra options: 
[ 3206.354505] [DEBUG] Primus LD Path: /usr/lib/x86_64-linux-gnu/primus:/usr/lib/i386-linux-gnu/primus
[ 3206.354548] [DEBUG]Using auto-detected bridge virtualgl
[ 3208.599502] [INFO]Response: No - error: [XORG] (EE) Failed to load module "mouse" (module does not exist, 0)

[ 3208.599514] [ERROR]Cannot access secondary GPU - error: [XORG] (EE) Failed to load module "mouse" (module does not exist, 0)

[ 3208.599517] [DEBUG]Socket closed.
[ 3208.599528] [ERROR]Aborting because fallback start is disabled.
[ 3208.599531] [DEBUG]Killing all remaining processes.
```

I tried a few solutions found online, including the addition to `xorg.cong.nvidia` suggested [here](http://askubuntu.com/a/790317). I don't think I'm the only one having the problem, but nothing I found worked. What should I try next?

**Comment by bluca** [comment]
The mouse message is always a red herring. Try the testing PPA: https://launchpad.net/~bumblebee/+archive/ubuntu/testing

**Comment by nwoods** [comment]
Thanks for answering! Indeed the mouse thing was a red herring. It seems to come up enough that it might be worth a note on the Troubleshooting page. 

In case it might help anyone else with the same issue, the problem was fixed by uncommenting the `BusID` line in `/etc/bumblebee/xorg.conf.nvidia` and replacing the number in it with the bus ID from `lspci | grep -i nvidia`. It looks like the same message masks a variety of errors, though, so YMMV...

**Comment by edupulpillo** [comment]
using nouveau driver instead nvidida, the same problem is observed, even specifying the BusID correctly. So as nwoods suggest "It looks like the same message masks a variety of errors".

**Comment by krichter722** [comment]
Please see whether #867 is a duplicate.

**Comment by garibarba** [comment]
From #867, this solved it for me:

> Got it working. Had to edit the file /etc/bumblebee/xorg.conf.nvidia to include the following screen-section to make bumblebee work:

>Section "Screen"
Identifier "Default Screen"
Device "DiscreteNvidia"
EndSection

>Then I restarted the bumblebee service and it worked with optirun glxgears.

**Comment by luispabon** [comment]
I had the same problem, totally out of the blue on a bumblebee setup that was alaready working. The screen section above also fixed it. Thank you @garibarba

**Comment by Alejandroem** [comment]
I managed to fix this issue by installing this package 
https://packages.debian.org/search?keywords=xserver-xorg-input-mouse

Then i just fixed the bus id in the /etc/bumblebee/xorg.conf.nvidia you can find your bus id by running  lspci | egrep 'VGA|3D'

**Comment by deven96** [comment]
> > I managed to fix this issue by installing this package
> > https://packages.debian.org/search?keywords=xserver-xorg-input-mouse
> 
> > > Then i just fixed the bus id in the /etc/bumblebee/xorg.conf.nvidia you can find your bus id by running lspci | egrep 'VGA|3D'
> 
> This worked for me, now I get this error: `failed to set drm interface version`

I also got the mouse error fixed by installing the xserver-xorg-input-mouse issue but then it led to the `failed to set drm interface version`. Is there any way you solved it @tallysmartins

**Comment by pl-buiquang** [comment]
You may want to look at x logs (/var/log/Xorg.*.log).
I have the same issue and (though not yet tested) it seems to be solvable if you follow instructions in this link : https://devtalk.nvidia.com/default/topic/1050786/linux/nvidia-drivers-430-09-causes-xorg-segfault-at-start-/3

**Comment by pl-buiquang** [comment]
@matiux This is an unrelated issue.
I tested the fix I mentionned in my previous comment and it works
