### ISSUE TITLE
Jessie, Skylake & Nvidia GTX 950m and Bumblebee

### ISSUE THREAD

**Issue by l0l1t4** [Bumblebee-Project/Bumblebee#812]
Hi everyone. 

http://forums.debian.net/viewtopic.php?f=7&t=130272

What I do wrong? Can you help me please?

> sudo optirun -vv glxspheres
[55562.416881] [DEBUG]Reading file: /etc/bumblebee/bumblebee.conf
[55562.417113] [DEBUG]optirun version 3.2.1 starting...
[55562.417124] [DEBUG]Active configuration:
[55562.417131] [DEBUG] bumblebeed config file: /etc/bumblebee/bumblebee.conf
[55562.417139] [DEBUG] X display: :8
[55562.417146] [DEBUG] LD_LIBRARY_PATH: 
[55562.417154] [DEBUG] Socket path: /var/run/bumblebee.socket
[55562.417161] [DEBUG] Accel/display bridge: auto
[55562.417168] [DEBUG] VGL Compression: proxy
[55562.417176] [DEBUG] VGLrun extra options: 
[55562.417183] [DEBUG] Primus LD Path: /usr/lib/x86_64-linux-gnu/primus:/usr/lib/i386-linux-gnu/primus:/usr/lib/primus:/usr/lib32/primus
[55562.417211] [DEBUG]Using auto-detected bridge primus
[55562.422531] [INFO]Response: No - error: [XORG] (EE) [drm] KMS not enabled

[55562.422539] [ERROR]Cannot access secondary GPU - error: [XORG] (EE) [drm] KMS not enabled

[55562.422542] [DEBUG]Socket closed.
[55562.422549] [ERROR]Aborting because fallback start is disabled.
[55562.422552] [DEBUG]Killing all remaining processes.

**Comment by bluca** [comment]
Which version of the drivers and bumblebee packages are you running?

With the 950 you'll need the drivers from backports.

```apt-get install -t jessie-backports bumblebee-nvidia``` should pull down everything you need.

**Comment by l0l1t4** [comment]
Hi, Bluca. thanks for answer. 

I just added to  /etc/apt/sources.list

> deb http://httpredir.debian.org/debian jessie-backports main contrib non-free

Then install drivers from backports

> sudo apt-get install -t jessie-backports bumblebee-nvidia

Then reboot my laptop.

Now its runs

> sudo service bumblebeed status
● bumblebeed.service - Bumblebee C Daemon
   Loaded: loaded (/lib/systemd/system/bumblebeed.service; enabled)
   Active: active (running) since Вт 2016-10-25 15:36:38 MSK; 1min 6s ago
 Main PID: 628 (bumblebeed)
   CGroup: /system.slice/bumblebeed.service
           └─628 /usr/sbin/bumblebeed

oct 25 15:36:38 l0l1t4 systemd[1]: Starting Bumblebee C Daemon...
oct 25 15:36:38 l0l1t4 systemd[1]: Started Bumblebee C Daemon.
oct 25 15:36:38 l0l1t4 bumblebeed[628]: [   38.933835] [INFO]/usr/sbin/bumblebeed 3.2.1 started


> glxinfo |grep OpenGL
OpenGL vendor string: VMware, Inc.
OpenGL renderer string: Gallium 0.4 on llvmpipe (LLVM 3.5, 256 bits)
OpenGL version string: 3.0 Mesa 10.3.2
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:

>lspci | egrep 'VGA|3D'
00:02.0 VGA compatible controller: Intel Corporation Device 1916 (rev 07)
01:00.0 3D controller: NVIDIA Corporation Device 139a (rev ff)

>sudo optirun glxgears -info
[  594.751920] [ERROR]Cannot access secondary GPU - error: [XORG] (EE) NVIDIA(GPU-0): Failed to initialize the NVIDIA GPU at PCI:1:0:0.  Please

[  594.751938] [ERROR]Aborting because fallback start is disabled.

Help me please, what to do.

**Comment by bluca** [comment]
Check what the value of BusID is in the file /etc/bumblebee/xorg.conf.nvidia, and if it does not matches (or is not set), set it to match what lspci tells you, the restart bumblebeed and try again.

Also you don't need to run optirun with sudo.

If this doesn't work either, then get the logs from journalctl, especially interested to see if the kernel modules get loaded.

Finally, post the exact laptop model you have, as there are problems with more recent laptops due to ACPI changes.

**Comment by l0l1t4** [comment]
>#   If the X server does not automatically detect your VGA device,
#   you can manually set it here.
#   To get the BusID prop, run `lspci | egrep 'VGA|3D'` and input the data
#   as you see in the commented example.
#   This Setting may be needed in some platforms with more than one
#   nvidia card, which may confuse the proprietary driver (e.g.,
#   trying to take ownership of the wrong device). Also needed on Ubuntu 13.04.
    BusID "PCI:01:00:0"


I just uncomment BusID and restart bumblebee

> sudo service bumblebeed restart

Than start optirun again

> ~$ optirun glxgears -info
[ 2395.839923] [ERROR]Cannot access secondary GPU - error: [XORG] (EE) NVIDIA(GPU-0): Failed to initialize the NVIDIA GPU at PCI:1:0:0.  Please

[ 2395.839994] [ERROR]Aborting because fallback start is disabled.

>  lspci | egrep 'VGA|3D'
00:02.0 VGA compatible controller: Intel Corporation Device 1916 (rev 07)
01:00.0 3D controller: NVIDIA Corporation Device 139a (rev a2)

It is error again. 

>  sudo dmidecode | grep -A3 '^System Information'
System Information
	Manufacturer: Acer
	Product Name: Aspire F5-573G
	Version: V1.04

**Comment by l0l1t4** [comment]
>If this doesn't work either, then get the logs from journalctl, especially interested to see if the kernel modules get loaded.

Do you want to see /var/log/kern.log in pastebin ?

**Comment by bluca** [comment]
journalctl --since "2 minutes ago" immediately after you run optirun should have everything, yes in pastebin please

**Comment by l0l1t4** [comment]
Here you are.
http://pastebin.com/izA9w8PR

**Comment by l0l1t4** [comment]
And full log with "optirun"

http://pastebin.com/uK6UtvDb

**Comment by l0l1t4** [comment]
Debian guys says me that Jessie does't support "Skylake" and i need to waiting "Stretch Release" .

**Comment by bluca** [comment]
That sounds reasonable, otherwise I suspect you'd need to fetch at a minimum kernel, firmware, xorg drivers, mesa and libdrm from backports.

So I'll close this for housekeeping for now, if you still have problems once you upgrade please do come back.

BTW given it's Skylake it's new hardware, and there were other reports of problems due to ACPI, see these discussions on bbswitch:

https://github.com/Bumblebee-Project/bbswitch/issues/115
https://github.com/Bumblebee-Project/bbswitch/issues/118

**Comment by l0l1t4** [comment]
Hi. again. Good news! I'm just install Archlinux and Bumblebee is working now! :)  Red eyes and grow beard, lol.

Processor: i7 6500U (Skylake)
Integrated Graphics:  Intel HD 520
Discrete Graphics: Nvidia 950M

optirun -b none nvidia-settings -c :8  (work)
optirun glxgears (work)
optirun glxspheres64 (work)

tee /proc/acpi/bbswitch <<<ON (work)
tee /proc/acpi/bbswitch <<<OFF (work)

cat /proc/acpi/bbswitch (work)

After install arch just added linux-mainline 4.9rc3-1 from AUR and bbswitch-mainline and it's works. I love you, thanks :+1: 

> [nickaz@l0l1t4 ~]$ uname -r
4.8.6-1-ARCH
[nickaz@l0l1t4 ~]$ optirun glxgears
4456 frames in 5.0 seconds = 891.133 FPS
4511 frames in 5.0 seconds = 902.138 FPS
4540 frames in 5.0 seconds = 907.950 FPS
4550 frames in 5.0 seconds = 909.930 FPS
4487 frames in 5.0 seconds = 897.237 FPS
