### ISSUE TITLE
Will it be available for Xenial ?

### ISSUE THREAD

**Issue by obernardovieira** [Bumblebee-Project/Bumblebee#817]
thats it

**Comment by bluca** [comment]
It already is, both in the official repo and on our ppa:

http://packages.ubuntu.com/xenial/bumblebee
https://launchpad.net/~bumblebee/+archive/ubuntu/testing

**Comment by obernardovieira** [comment]
Ohh, you're right. I'm so sorry.
Because I was using
`sudo add-apt-repository ppa:bumblebee/stable`
instead and this gave me an error saying it's not available for xenial yet.
Yhank you btw :+1: :smile:
