### ISSUE TITLE
What's the right case for the PmMethod key in bumblebee.conf?

### ISSUE THREAD

**Issue by GabLeRoux** [Bumblebee-Project/Bumblebee#831]
Hi,
I'm running arch on a zbook 15 g2 with bumblebee, followed [instructions on arch wiki](https://wiki.archlinux.org/index.php/bumblebee).

But I'm still trying to make my multi display setup working. Anyway, I saw this in the [wiki of the repos]():
> In order to use an external monitor through the nvidia chip, power management must be disabled for this. Edit `/etc/bumblebee/bumblebee.conf` and change `PmMethod=auto` to `PmMethod=none` (twice).

On arch wiki, it's written `PMmethod`, in local wiki, it's `PmMethod` in 4 places and on my own config (can't remember if I did input this myself or if key was already there) It's `PMMethod`, so question is simple, what's the right case for this key and are settings case sensitive?

**Comment by Lekensteyn** [comment]
The capitalization is `PMMethod`. If you want to use external monitors, I suggest to look into using PRIME.
