### ISSUE TITLE
bbswitch_write: wrong use of fwrite

### ISSUE THREAD

**Issue by Celelibi** [Bumblebee-Project/Bumblebee#836]
At `src/switch/sw_bbswitch.c:73`, `fwrite` is called like this:

    fwrite(msg, sizeof msg, strlen(msg) + 1, bbs);

Since msg is a pointer, it means we write 4 or 8 times the string length on the file descriptor. This should have no consequence whatsoever as long as there's some readable memory right after the string pointed to by `msg`. If not, this could lead to a segmentation fault.

I also find that `+1` questionable. Why send the NUL byte to the procfs? I would rather suggest something like this.

    fwrite(msg, sizeof(*msg), strlen(msg), bbs);

Best regards.

**Comment by Lekensteyn** [comment]
Well spotted, the first sizeof of a pointer and the +1 to include the NUL byte is also bogus. Would you mind preparing a PR to fix these issues? `fputs(bbs, msg)` would probably be good enough.

(the sw_switcheroo file needs similar treatment)

**Comment by hassec** [comment]
Hi, 
I have been browsing a little to understand how bumblebee works in general, and noticed that, if I am not mistaken, this issue was fixed by #838, right? 

Hopefully I can contribute in a more meaningful way soon, but I figured I would mention it as the issue has been open for a while 😄

**Comment by Celelibi** [comment]
I think you're right, but I'll let @Lekensteyn close this bug report. Maybe he wants to actually close the bug report after a release or something.

**Comment by Lekensteyn** [comment]
Fixed by #838, let's close it :)
