### ISSUE TITLE
optirun working but external display not detected

### ISSUE THREAD

**Issue by dzhu** [Bumblebee-Project/Bumblebee#842]
I have a Thinkpad W530 running Ubuntu 16.04, and I'm trying to get an external display working on the VGA port, which is connected to the Nvidia card. Right now, running programs with `optirun` works, but connecting the VGA cable and running `intel-virtual-output` does nothing for the outputs available to `xrandr`; similarly, running `xrandr -d :8` shows no outputs. `nvidia-xconfig` shows the display as connected. (This laptop worked fine under Ubuntu 14.04, and was also working in 16.04 until a recent reboot.)

I'm running off the bumblebee testing PPA (since the stable one doesn't have anything for 16.04). Compiling from the develop branch of git seems to have the same problem.

Relevant information: https://gist.github.com/dzhu/dcdca129f1aef59585ddb74a757e42c9

**Comment by Celelibi** [comment]
If your laptop is anything like mine (internal monitor connected to the iGPU and external monitor connected to the dGPU), the solution was to not use Bumblebee at all. I don't know what `intel-virtual-output` exactly does, but IIRC it's a deprecated method.

What I did was to run Xorg with the nvidia driver and use the *provideroutputsource* thing to use the internal laptop monitor as well.
See this link for the exact configuration: http://us.download.nvidia.com/XFree86/Linux-x86_64/370.23/README/randr14.html

**Comment by Lekensteyn** [comment]
Correct, with multiple monitors you likely want to use PRIME output slaving. I'll close this since there is nothing to do here (except maybe updating the FAQ). Feel free to re-open if needed though.

**Comment by dzhu** [comment]
My impression was that those solutions force the dGPU to be on constantly. For power-saving purposes, I consider it important to be able to turn the card off (without quitting X or rebooting). If that's still possible with those solutions, then I'd certainly want to consider non-deprecated options.

Anyway, I have things working now with bumblebee. The nvidia-367 drivers load extra kernel modules, which get marked as in-use by some graphical process or other, and so can't be unloaded while X is running, preventing the card from turning off. If you quit X, manually unload those modules, and restart X, optirun continues working and you can turn off the card, but apparently external displays stop working, and I didn't make that connection until later. I went back to nvidia-340 and everything works swimmingly. Perhaps not the most correct modern solution, but it does exactly what I want.

**Comment by Lekensteyn** [comment]
@dzhu I am using PRIME output slaving with nouveau (and a GTX 965M). If there is no monitor connected, the dGPU automatically powers off via runtime PM. If I connect a monitor and run lspci (to trigger runtime PM resume) and xrandr (to trigger Plasma), then the external monitor works.

(Note: the lspci trick should not be needed with kernel 4.10 anymore, but I have not tested that yet)
