### ISSUE TITLE
primusrun stopped working on 4.9.11

### ISSUE THREAD

**Issue by ziflex** [Bumblebee-Project/Bumblebee#847]
Hey guys,

I'm using Fedora 25 and after latest kernel update ```primusrun``` stopped working.

```sh
primus: fatal: failed to load any of the libraries: /usr/$LIB/libGL.so.1
/usr/lib64/libGL.so.1: undefined symbol: _glapi_tls_Current
```
```optirun``` works though.

I guess it's not a direct issue of Bumblebee but, maybe you have thoughts how to fix it.

**Comment by gsgatlin** [comment]
This should be fixed in 
bumblebee-nvidia-375.39-2 or bumblebee-nvidia-3.0-3 (un-managed)

It can be dnf updated beginning now. Did upgrading fix the problem?

**Comment by ziflex** [comment]
@gsgatlin yes, it's totally fixed! Thanks!
