### ISSUE TITLE
Debian sid: Cannot access secondary GPU - error: Could not load GPU driver

### ISSUE THREAD

**Issue by tobiasBora** [Bumblebee-Project/Bumblebee#849]
Hello,

First thank you for your job. I'm running debian sid, and I have a computer with an optimus NVIDIA Geforce 840M:

    04:00.0 3D controller: NVIDIA Corporation GM108M [GeForce 840M] (rev a2)

I tried to install bumblebee in order to have CUDA on blender. Here is how I installed it:

    $ sudo apt-get install bumblebee-nvidia primus primus-libs:i386 nvidia-cuda-dev

I also added myself to the ```bumblebee``` group, but after a reboot here is what I get:

    $ optirun -vv glxinfo
    [  882.494348] [DEBUG]Reading file: /etc/bumblebee/bumblebee.conf
    [  882.494628] [DEBUG]optirun version 3.2.1 starting...
    [  882.494647] [DEBUG]Active configuration:
    [  882.494652] [DEBUG] bumblebeed config file: /etc/bumblebee/bumblebee.conf
    [  882.494657] [DEBUG] X display: :8
    [  882.494661] [DEBUG] LD_LIBRARY_PATH: /usr/lib/x86_64-linux-gnu/nvidia:/usr/lib/i386-linux-gnu/nvidia:/usr/lib/nvidia
    [  882.494665] [DEBUG] Socket path: /var/run/bumblebee.socket
    [  882.494670] [DEBUG] Accel/display bridge: auto
    [  882.494674] [DEBUG] VGL Compression: proxy
    [  882.494678] [DEBUG] VGLrun extra options: 
    [  882.494682] [DEBUG] Primus LD Path: /usr/lib/x86_64-linux-gnu/primus:/usr/lib/i386-linux-gnu/primus:/usr/lib/primus:/usr/lib32/primus
    [  882.494755] [DEBUG]Using auto-detected bridge primus
    [  882.752071] [INFO]Response: No - error: Could not load GPU driver
    
    [  882.752085] [ERROR]Cannot access secondary GPU - error: Could not load GPU driver
    
    [  882.752089] [DEBUG]Socket closed.
    [  882.752103] [ERROR]Aborting because fallback start is disabled.
    [  882.752107] [DEBUG]Killing all remaining processes.
    
and here is bumblebeed status:

    $ sudo systemctl status bumblebeed
    ● bumblebeed.service - Bumblebee C Daemon
       Loaded: loaded (/lib/systemd/system/bumblebeed.service; enabled; vendor preset: enabled)
       Active: active (running) since Tue 2017-03-07 12:17:23 CET; 13min ago
     Main PID: 2756 (bumblebeed)
        Tasks: 1 (limit: 4915)
       CGroup: /system.slice/bumblebeed.service
               └─2756 /usr/sbin/bumblebeed
    
    mars 07 12:17:23 leodeb systemd[1]: Started Bumblebee C Daemon.
    mars 07 12:17:23 leodeb bumblebeed[2756]: [  675.130435] [ERROR]Module 'bbswitch' not found.
    mars 07 12:17:23 leodeb bumblebeed[2756]: [  675.130456] [WARN]No switching method available. The dedicated card will always be on.
    mars 07 12:17:23 leodeb bumblebeed[2756]: [  675.130898] [INFO]/usr/sbin/bumblebeed 3.2.1 started
    mars 07 12:17:26 leodeb bumblebeed[2756]: modprobe: FATAL: Module nvidia-current not found in directory /lib/modules/4.9.0-1-amd64
    mars 07 12:17:26 leodeb bumblebeed[2756]: libkmod: ERROR ../libkmod/libkmod-module.c:977 command_do: Error running install command for nvidia
    mars 07 12:17:26 leodeb bumblebeed[2756]: [  677.897382] [ERROR]Could not load GPU driver
    mars 07 12:20:51 leodeb bumblebeed[2756]: modprobe: FATAL: Module nvidia-current not found in directory /lib/modules/4.9.0-1-amd64
    mars 07 12:20:51 leodeb bumblebeed[2756]: libkmod: ERROR ../libkmod/libkmod-module.c:977 command_do: Error running install command for nvidia
    mars 07 12:20:51 leodeb bumblebeed[2756]: [  882.751778] [ERROR]Could not load GPU driver
    
I tried several things, but no one works. Any idea?

**Comment by bluca** [comment]
Did the install of bumblebee-nvidia install the nvidia-driver packages as well? Do you have by any chance the install-recommends functionality of apt-get turned off?

**Comment by bluca** [comment]
And bbswitch too should have been installed

What's the output of ```sudo dkms status```

**Comment by tobiasBora** [comment]
Thank you for your help. nvidia-driver has indeed been installed, here is the result of dkms status:


    $ sudo dkms status
    bbswitch, 0.8: added
    nvidia-current, 375.39: added
    
    leo@leodeb:~$ sudo apt-cache policy nvidia-driver
    nvidia-driver:
      Installé : 375.39-1
      Candidat : 375.39-1
     Table de version :
     *** 375.39-1 500
            500 http://ftp.fr.debian.org/debian sid/non-free amd64 Packages
            100 /var/lib/dpkg/status

**Comment by tobiasBora** [comment]
By the way I'm currently upgrading my system because I'm wondering if there is not a clash between my current kernel version 4.9.0-1-amd64 and the last kernel version 4.9.0-2-amd64.

**Comment by bluca** [comment]
The problem is that the module is added but not installed. Did something go wrong when you ran apt-get install? Did you have the kernel headers package installed?

Run:

```
sudo dkms install nvidia-current/375.39 -k 4.9.0-2-amd64
sudo dkms install bbswitch/0.8 -k 4.9.0-2-amd64
```

**Comment by tobiasBora** [comment]
I updated my system, my kernel, and when I ran your two commands, I got something like "Already installed". But after a reboot, I can know run ```optirun blender``` ! So first thank you for making optirun working for me.

There is however another problem: even when I (opti)run blender, I cannot set in the user preferences "GPU", the only option I have is "CPU"... Do you know what I could do to make GPU working ?

**Comment by bluca** [comment]
Sorry, I am not familiar with Blender.

If you install the mesa-utils package and run:

```optirun glxgears -info```

and it shows that it's running on the Nvidia card, that means bumblebee itself is working.

**Comment by tobiasBora** [comment]
It's now working, thank you very much for your help ! (I just need to install nvidia-cuda-toolkit to have cuda now)

**Comment by Kinkypeter** [comment]
I think this might have to do with some changes to the LSB rules and
grub2 and how it reads the name of the kernel image. I know I have a
machine that I reloaded the system because it would not load the latest
nvidia driver. This machine is a desktop. They updated the driver that
is now the long term supported driver and it was also when there was a
kernel patch to 4.10. I thought I had screwed up my system because I
can't leave it alone but that system worked great with 4.9.9. I hope
this might help someone.

My system is Centos 7.3:1611 - If I get anymore info I will pass it on.

Peter

**Comment by Kinkypeter** [comment]
Wow, I will have to check this as well on my systems when I get home as
I think on both my laptop and the desktop were having that problems with
the video driver not loading that is.  I had just done a reinstall with
my laptop and gotten by the "Oh no, error" when Gnome tries to boot
after the HUGE update the machine goes through after  I loaded Centos
7.3:1611 by switching to MATE. I'll be home soon and I can send you this
data.

Thanks for the help.
