### ISSUE TITLE
Can't install primus from ppa:bumblebee/testing after HWE 16.04

### ISSUE THREAD

**Issue by Void97** [Bumblebee-Project/Bumblebee#857]
I've installed the latest Hardware Enablement Stack on KDE Neon 5.9.4, and whereas `bumblebee-nvidia` package from `ppa:bumblebee/testing` works fine after [these changes](https://github.com/Bumblebee-Project/bumblebee-ppa/pull/42), `primus` package goes in conflict with `xorg`:

`sudo apt install primus
...
The following packages will be REMOVED:
  neon-desktop xorg xserver-xorg-core-hwe-16.04 xserver-xorg-hwe-16.04 xserver-xorg-input-all-hwe-16.04 xserver-xorg-input-evdev-hwe-16.04 xserver-xorg-input-synaptics-hwe-16.04
  xserver-xorg-input-wacom-hwe-16.04 xserver-xorg-video-all-hwe-16.04 xserver-xorg-video-amdgpu-hwe-16.04 xserver-xorg-video-ati-hwe-16.04 xserver-xorg-video-fbdev-hwe-16.04
  xserver-xorg-video-nouveau-hwe-16.04 xserver-xorg-video-qxl-hwe-16.04 xserver-xorg-video-radeon-hwe-16.04 xserver-xorg-video-vesa-hwe-16.04 xserver-xorg-video-vmware-hwe-16.04`

**Comment by bluca** [comment]
This is an issue in the primus packaging - please reopen in https://github.com/Bumblebee-Project/bumblebee-ppa
I've already fixed bumblebee but failed to notice the same issue in the primus package, will fix it over the weekend

**Comment by Void97** [comment]
Okay, I'll reopen this in the proper repository. Thank you for the quick reply and for your work.
