### ISSUE TITLE
[Fedora 25] Cannot access secondary GPU - error: [XORG] (EE) /dev/dri/card0: failed to set DRM interface version 1.4: Permission denied

### ISSUE THREAD

**Issue by hebertjulio** [Bumblebee-Project/Bumblebee#859]
**OS**
> Fedora 25

**Kernel**
> Linux 5470 4.10.6-200.fc25.x86_64 #1 SMP Mon Mar 27 14:06:23 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**This error occurs when I execute the command: vblank_mode=0 optirun -b primus glxspheres64**
> [ 2107.529582] [ERROR]Cannot access secondary GPU - error: [XORG] (EE) /dev/dri/card0: failed to set DRM interface version 1.4: Permission denied
> [ 2107.529668] [ERROR]Aborting because fallback start is disabled.

**bumblebee-nvidia -c**
> nvidia.ko compiled into in the kernel tree ok.
> modinfo output for NVIDIA:
> 
> filename:       /lib/modules/4.10.6-200.fc25.x86_64/kernel/drivers/video/nvidia.ko
> alias:          char-major-195-*
> version:        375.39
> supported:      external
> license:        NVIDIA
> srcversion:     02F9F40DB2D0FC489009343
> alias:          pci:v000010DEd00000E00sv*sd*bc04sc80i00*
> alias:          pci:v000010DEd*sv*sd*bc03sc02i00*
> alias:          pci:v000010DEd*sv*sd*bc03sc00i00*
> depends:        
> vermagic:       4.10.6-200.fc25.x86_64 SMP mod_unload 
> parm:           NVreg_Mobile:int
> parm:           NVreg_ResmanDebugLevel:int
> parm:           NVreg_RmLogonRC:int
> parm:           NVreg_ModifyDeviceFiles:int
> parm:           NVreg_DeviceFileUID:int
> parm:           NVreg_DeviceFileGID:int
> parm:           NVreg_DeviceFileMode:int
> parm:           NVreg_UpdateMemoryTypes:int
> parm:           NVreg_InitializeSystemMemoryAllocations:int
> parm:           NVreg_UsePageAttributeTable:int
> parm:           NVreg_MapRegistersEarly:int
> parm:           NVreg_RegisterForACPIEvents:int
> parm:           NVreg_CheckPCIConfigSpace:int
> parm:           NVreg_EnablePCIeGen3:int
> parm:           NVreg_EnableMSI:int
> parm:           NVreg_TCEBypassMode:int
> parm:           NVreg_UseThreadedInterrupts:int
> parm:           NVreg_MemoryPoolSize:int
> parm:           NVreg_RegistryDwords:charp
> parm:           NVreg_RmMsg:charp
> parm:           NVreg_AssignGpus:charp
> 
> Check bbswitch kernel module...
> 
> Warning! bbswitch is not loaded into this kernel!
> Since bbswitch is not loaded into the kernel, lets do additional checks on it...
> dkms status bbswitch output:
> bbswitch, 0.8.0, 4.10.5-200.fc25.x86_64, x86_64: installed
> bbswitch, 0.8.0, 4.10.6-200.fc25.x86_64, x86_64: installed
> 
> if the bbswitch package is installed, you may wish to try:
> /usr/sbin/dkms add -m bbswitch -v 0.8.0
> /usr/sbin/dkms build -m bbswitch -v 0.8.0
> /usr/sbin/dkms install -m bbswitch -v 0.8.0
> /sbin/modprobe bbswitch
> 
> To get clues as to why bbswitch is failing on this kernel...
> All checks completed successfully! NVIDIA driver appears to have compiled ok.
> 
> Documentation on bumblebee for RHEL / CentOS / fedora can be found at:
> https://www.linux.ncsu.edu/bumblebee/

**bumblebee-nvidia -f --debug**
> --debug mode selected.
> --force compile selected.
> Building NVIDIA video drivers: Creating directory NVIDIA-Linux-x86_64-375.39
> Verifying archive integrity... OK
> Uncompressing NVIDIA Accelerated Graphics Driver for Linux-x86_64 375.39.........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
> patching file kernel/common/inc/nv-mm.h
> patching file kernel/nvidia-drm/nvidia-drm-fence.c
> patching file kernel/nvidia-drm/nvidia-drm-gem.h
> patching file kernel/nvidia-drm/nvidia-drm-priv.h
> patching file kernel/nvidia/nv-pat.c
> 
> WARNING: Unable to determine the path to install the libglvnd EGL vendor library config files. Check that you have pkg-config and the libglvnd
>          development libraries installed, or specify a path with --glvnd-egl-config-path.
> 
> 
> WARNING: The symbolic link '/usr/lib/libGL.so.1' does not point to '/usr/lib64/nvidia-bumblebee/libGL.so.1' as is necessary for correct operation of
>          the NVIDIA Accelerated Graphics Driver for Linux-x86_64.  It is possible that `ldconfig` has created this incorrect symbolic link because
>          libGL.so.1.2.0;5846061a's "soname" conflicts with that of /usr/lib64/nvidia-bumblebee/libGL.so.1.  It is recommended that you remove or
>          rename the file 'libGL.so.1.2.0;5846061a' and create the necessary symbolic link by running `ln -sf /usr/lib64/nvidia-bumblebee/libGL.so.1
>          /usr/lib/libGL.so.1`.
> 
>                    [  OK  ]

There are a similar issue #824 reported at Dec 9, 2016, but no solution.

**Comment by gsgatlin** [comment]
If you create a file at the path:

/etc/modules-load.d/bbswitch

with the contents:

# Load bbswitch.ko at boot
bbswitch


and reboot does that help with bbswitch not being loaded? Does it help with optirun?

**Comment by gsgatlin** [comment]
Sorry, just have the text

bbswitch

in that file.

**Comment by hebertjulio** [comment]
@gsgatlin it's not work. :(

**Comment by kostaldavid8** [comment]
I have the same issue, from update to kernel 4.10.
Tried to insert bbswitch module manually (`sudo modprobe bbswitch`)
And output is:
```
modprobe: ERROR: could not insert 'bbswitch': No such device
```

Output of dmesg after trying to modprobe:
```
[  450.710694] bbswitch: version 0.8
[  450.710700] bbswitch: Found integrated VGA device 0000:00:02.0: \_SB_.PCI0.GFX0
[  450.710707] bbswitch: Found discrete VGA device 0000:09:00.0: \_SB_.PCI0.RP05.PXSX
[  450.710718] bbswitch: failed to evaluate \_SB_.PCI0.RP05.PXSX._DSM {0xF8,0xD8,0x86,0xA4,0xDA,0x0B,0x1B,0x47,0xA7,0x2B,0x60,0x42,0xA6,0xB5,0xBE,0xE0} 0x100 0x0 {0x00,0x00,0x00,0x00}: AE_NOT_FOUND
[  450.710725] bbswitch: failed to evaluate \_SB_.PCI0.RP05.PXSX._DSM {0xA0,0xA0,0x95,0x9D,0x60,0x00,0x48,0x4D,0xB3,0x4D,0x7E,0x5F,0xEA,0x12,0x9F,0xD4} 0x102 0x0 {0x00,0x00,0x00,0x00}: AE_NOT_FOUND
[  450.710733] ACPI Warning: \_SB.PCI0.GFX0._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20160930/nsarguments-95)
[  450.710785] bbswitch: No suitable _DSM call found.
```

**Comment by jpts** [comment]
Can confirm I have the same problem:

kernel: `Linux 4.10.6-200.fc25.x86_64 `
OS: `Fedora 25`

dmesg output:
```
[  872.125752] bbswitch: version 0.8
[  872.125760] bbswitch: Found integrated VGA device 0000:00:02.0: \_SB_.PCI0.GFX0
[  872.125770] bbswitch: Found discrete VGA device 0000:04:00.0: \_SB_.PCI0.RP05.PXSX
[  872.125787] bbswitch: failed to evaluate \_SB_.PCI0.RP05.PXSX._DSM {0xF8,0xD8,0x86,0xA4,0xDA,0x0B,0x1B,0x47,0xA7,0x2B,0x60,0x42,0xA6,0xB5,0xBE,0xE0} 0x100 0x0 {0x00,0x00,0x00,0x00}: AE_NOT_FOUND
[  872.125794] bbswitch: failed to evaluate \_SB_.PCI0.RP05.PXSX._DSM {0xA0,0xA0,0x95,0x9D,0x60,0x00,0x48,0x4D,0xB3,0x4D,0x7E,0x5F,0xEA,0x12,0x9F,0xD4} 0x102 0x0 {0x00,0x00,0x00,0x00}: AE_NOT_FOUND
[  872.125812] bbswitch: failed to evaluate \_SB_.PCI0.GFX0._DSM {0xA0,0xA0,0x95,0x9D,0x60,0x00,0x48,0x4D,0xB3,0x4D,0x7E,0x5F,0xEA,0x12,0x9F,0xD4} 0x102 0x0 {0x00,0x00,0x00,0x00}: AE_NOT_FOUND
[  872.125813] bbswitch: No suitable _DSM call found.

**Comment by gsgatlin** [comment]
Maybe @Lekensteyn might have some ideas about how one would get around that?

**Comment by gsgatlin** [comment]
You may wish to open a new issue here?

https://github.com/Bumblebee-Project/bbswitch

Maybe he will respond?

I'm very sorry but I don't know how to troubleshoot these out of tree kernel module problems.

**Comment by gsgatlin** [comment]
Also, for your specific laptop make/model can you follow the instructions here?

https://bugs.launchpad.net/lpbugreporter/+bug/752542

**Comment by gsgatlin** [comment]
Also, you'll want to follow the instructions here:

https://github.com/Bumblebee-Project/bbswitch/#reporting-bugs

as far as output so he has all the information he needs in your issue you open.

I'm guessing maybe you may need some extra kernel options to get it to work. But thats just a guess...

**Comment by hebertjulio** [comment]
Open new issue at https://github.com/Bumblebee-Project/bbswitch

**Comment by tkalfaoglu** [comment]
do a:
cd /dev/dri
ls -l 
Mine looked like:
crw-rw----+  1 root video 226,   0 Jan 28 08:55 card0

If your user is NOT part of "video" group, you can't access it.
so do a:
   usermod -G video turgut
where "turgut" is your username :)
