### ISSUE TITLE
Optirun performance is lower than Intel

### ISSUE THREAD

**Issue by moscoquera** [Bumblebee-Project/Bumblebee#865]
I just reinstalled Bumblebee because it go broken after a random fedora update.  after finally reinstall it again, solving some problems, bumblebee seems working, but when i run optirun the performance is terrible, im getting a third of the intel's performace.

running glxspheres without optirun i get 60 fps. but when start it using optirun i get 10 FPS. i tried running Unigine's heaven test, but it crashes when is called with optirun, giving me this error:
```Loading "libGPUMonitor_x64.so"...
Loading "libGL.so.1"...
Loading "libopenal.so.1"...
Set 1366x768 fullscreen video mode
X Error of failed request:  GLXBadFBConfig
  Major opcode of failed request:  153 (GLX)
  Minor opcode of failed request:  34 ()
  Serial number of failed request:  36
  Current serial number in output stream:  35
AL lib: (EE) alc_cleanup: 1 device not closed
```

i dont know what to do to solve it, those are my Xorg logs.
Xorg.0.log: https://pastebin.com/c746AbYD
Xorg.8.log: https://pastebin.com/FDSAfBvP

Nvidia-Xconfig is breaking Xorg, so i dont have an Xorg.conf file.

**Comment by gsgatlin** [comment]
Are you using primus or virtualgl bridge? I think you will get better performance with primus bridge...

optirun -b primus SOMEAPP

I just upgraded my kernel to 4.10.9-200.fc25.x86_64 and tried the video game "Minecraft" with primus bridge and I get 60 FPS.

I did notice on your kernel command line rd.driver.blacklist=nouveau is listed twice but I doubt that would slow things down or affect it.

I don't actually have a xorg.conf and I think most bumblebee users on fedora won't have an xorg.conf.

Thanks,

**Comment by gsgatlin** [comment]
Or to be more precise, we are using /etc/bumblebee/xorg.conf.nvidia 
(If you were needing to mess with powemizer or something)

**Comment by moscoquera** [comment]
Hi gsgatlin.
i tried using primus as you suggested but still no difference, the fun part is that using primus the process goes black but still printing FPS info. also tried modifying xorg.conf.nvidia like this:
```
Section "Device"
    Identifier  "DiscreteNvidia"
    Driver      "nvidia"
    VendorName  "NVIDIA Corporation"
    Option "ProbeAllGpus" "false"
    Option "NoLogo" "true"
    Option "UseEDID" "false"
    Option "UseDisplayDevice" "none"
    Option "RegistryDwords" "PowerMizerEnable=0x1; PerfLevelSrc=0x2222; PowerMizerDefault=0x3; PowerMizerDefaultAC=0x3  #added this line
EndSection
```

but still the same, in "auto" mode.

**Comment by moscoquera** [comment]
update: also tried moving the xorg.conf.nvidia to /etc/X11/xorg.conf.d and started to get "screen not found" error.

**Comment by moscoquera** [comment]
I'm going to close it because i found the culprit. I'm using kernel 4.10 and as far as we know Nvidia doens't compile on it, i dont know why but i decided to patch it, make a .run file again and install bumblebee unmanaged version (i use the unmanaged version because "is pure" or something like that). doing some checks using "bumblebee-nvidia --check" it looked like my driver was broken so i decided to uninstall the unmanaged version and install the managed one. that solved my problem, everything looks working fine now.
