### ISSUE TITLE
When will you support Ubuntu 17.04 Zesty? The ppa doesn't contain builds for it.

### ISSUE THREAD

**Issue by SammDu** [Bumblebee-Project/Bumblebee#870]
Hi!
I found out that after I've upgraded to Ubuntu 17.04, the ppa's doesn't work anymore...the bumblebee packages are reserved but I can't get updates, and `apt` always show this error:

> Err http://ppa.launchpad.net/bumblebee/stable/ubuntu zesty Release                                                                                                              
  404  Not Found
Err http://ppa.launchpad.net/bumblebee/testing/ubuntu zesty Release                                                                                                             
  404  Not Found

Could you please start working on Zesty packages, or maybe consider general packages that work across distro versions if possible?
Thanks!

**Comment by bluca** [comment]
There is no need for a ppa for zesty, the packages included in the distro are up to date. Please just use those.
