### ISSUE TITLE
Fedora 25 with kernel 4.11

### ISSUE THREAD

**Issue by kmare** [Bumblebee-Project/Bumblebee#875]
@gsgatlin Using the bumblebee fedora repo, I can't boot anymore with kernel 4.11. Kernel 4.10 was just fine. Perhaps it needs to be updated to a newer nvidia driver version? at the moment it's at 376 while 381 is out.
Thanks in advance!

**Comment by kmare** [comment]
UPDATE:
adding: acpi_osi=! acpi_osi='Windows 2009'
allowed me to boot. Should add that I didn't need this option until kernel 4.11. My laptop is Asus ZenBook UX501VW.

**Comment by gsgatlin** [comment]
Hello @kmare . I just updated my system to kernel 4.11.3-200.fc25.x86_64 and it seems to be working ok for me. I have bumblebee-nvidia-375.66-1.fc25.x86_64. But I had to add "acpi_osi=!Windows 2013" when I was first assigned this machine to make it work. Its a thinkpad t540p.

Does optirun or primusrun work after adding acpi_osi=! acpi_osi='Windows 2009' to your kernel comand line? 375.66 seems to build the shim ok for 4.11 kernel in fedora 25. I also tested fedora 26 alpha on Friday last week and it was working for 4.11 kernel there also.

Thanks.

**Comment by gsgatlin** [comment]
I tested with 

optirun -b primus glxgears -info

but I'll try out a game like minecraft tonight when I get home.

**Comment by kmare** [comment]
hello @gsgatlin , 
I played around a little bit and apparently with acpi_osi='Windows 2009' it's all working fine like before. Also tried a few OpenGL apps like GPUtest and Minecraft, all good. When I tried with 'Windows 2013' it just kept freezing.

PS: thank you so much for all the support and the repository you're providing for fedora!

**Comment by kmare** [comment]
hello @gsgatlin , 
I played around a little bit and apparently with acpi_osi='Windows 2009' it's all working fine like before. Also tried a few OpenGL apps like GPUtest and Minecraft, all good. When I tried with 'Windows 2013' it just kept freezing.

PS: thank you so much for all the support and the repository you're providing for fedora!

**Comment by gsgatlin** [comment]
No problem. Glad you got it working.

**Comment by gforceg** [comment]
What file do I add these strings to?
`acpi_osi=! acpi_osi='Windows 2009'`

Also I am not dual booting.

Does the 'Windows 2009' value have something to do w/ dual booting because I'm not running any other OSes, only Fedora 25.

Thanks!

**Comment by gforceg** [comment]
Nevermind, I made the changes in grub at boot time... I also turned acpi on (forgot that it was off) this fixed my issues. thanks!

**Comment by Lekensteyn** [comment]
`acpi_osi=` is a workaround to avoid a lockup, see #764

(Closing this issue since the problem appears to be solved for the reporter)
