### ISSUE TITLE
[MSI/GT 950M] Computer freeze after login

### ISSUE THREAD

**Issue by EgamoPi** [Bumblebee-Project/Bumblebee#896]
Good morning, 

I already had a problem while installing and you helped me before : https://github.com/Bumblebee-Project/Bumblebee/issues/862 . However after doing a fresh install of debian stretch I tried to install Bumblebee back with the same help that you gave me last time, and by following this tutorial : https://fixmynix.com/install-and-configure-nvidia-optimus-with-bumblebee-in-debian/ . This time I make sure to add the good repositories, I installed from the backports, updated everything. But after the final reboot the computer crashes after the login screen. But just before bumblebee seems to work because i'm on my nvidia card. I also checked on the tty (before login) and "dkms status" returns that bbswitch and nvidia-current is installed and I make sure that the provider of my glx is bumblebee.

Thanks for your help,
Jonathan.

EDIT : I purged the nvidia and bumblebee package to be able to use my laptop.

**Comment by bluca** [comment]
What do you mean with installing from backports? There's no nvidia packages in stretch-backports

**Comment by EgamoPi** [comment]
`sudo apt-get install -t jessie-backports bumblebee-nvidia nvidia-driver`
Sorry not packages driver

**Comment by bluca** [comment]
You shouldn't use jessie repository in stretch

**Comment by EgamoPi** [comment]
Sorry it's updated, but in the terminal it was stretch and not jessie (Just double checked)

**Comment by EgamoPi** [comment]
Can I give you any other informations ?

**Comment by bluca** [comment]
run ```sudo apt install bumblebee-nvidia``` if everything is up to date it should do nothing. Then make sure with ```sudo update-glx --config glx``` that bumblebee is selected

**Comment by EgamoPi** [comment]
It installed it, i had a progress bar then I my computer automatically switched to the intel card, I checked the provider and it was well "bumblebee" then reboot.. still freezes

**Comment by Lekensteyn** [comment]
Could it be #764?

**Comment by EgamoPi** [comment]
@Lekensteyn Hey ! First of all thank and sorry for the delay. 
I red the fix that you propose, changing the workaround to (acpi=! acpi="Windows 2009"). I didn't know where to change it because to be honest when your english is not that good and that you have to navigate between 200comments it's quite hard.
So what I did, before that debian booted I changed the grub parameters and added your solution. Surprise it worked(I still didn't run all the test to check but no more freezing and i'm on the intel card and not the nvidia).. Can you please enlight me with that solution ? On jessie I didn't have to do this. That was the problem that i had : https://github.com/Bumblebee-Project/Bumblebee/issues/862 .
Thank you, I run the test and if everything is ok i close the toppic.

**Comment by EgamoPi** [comment]
Every test works so I close this topic. 
Thank you
