### ISSUE TITLE
documentation missleading! different methods for multi monitor setup

### ISSUE THREAD

**Issue by TheTesla** [Bumblebee-Project/Bumblebee#899]
https://github.com/Bumblebee-Project/Bumblebee/wiki/Multi-monitor-setup

> "Using the intel-virtual-output tool"
> ...
> "Getting started with the nvidia chip" 
> ...

This looks like all the things have to be done. I tried it and found out, that are completely different methods. (With intel-virtual-output PMMethod=auto and KeepUnusedXServer=false are both allowed.)

**Comment by Lekensteyn** [comment]
If you have tested it, please feel free to share your knowledge by editing the wiki. This is a community effort :)
