### ISSUE TITLE
Optirun [ERROR]Cannot access secondary GPU

### ISSUE THREAD

**Issue by nwg-piotr** [Bumblebee-Project/Bumblebee#909]
ASUSTeK model: P751JF v: 1.0
Dual graphics: Intel/NVIDIA GM108M (full info attached below)
Manjaro GNOME Edition (17.0.2) (same error appears on Ubuntu Gnome 16.04)
Bumblebee 3.2.1-18

It seems my secondary graphics doesn't work at all, does it? Could I configure it to work? I tried all the solutions found on the web - still no luck.

$ optirun -vv glxinfo
[ 1838.352037] [DEBUG]Reading file: /etc/bumblebee/bumblebee.conf
[ 1838.352234] [INFO]Configured driver: nvidia
[ 1838.352459] [DEBUG]optirun version 3.2.1-2017-02-27-Format:%h$ starting...
[ 1838.352470] [DEBUG]Active configuration:
[ 1838.352473] [DEBUG] bumblebeed config file: /etc/bumblebee/bumblebee.conf
[ 1838.352476] [DEBUG] X display: :8
[ 1838.352478] [DEBUG] LD_LIBRARY_PATH: /usr/lib/nvidia:/usr/lib32/nvidia:/usr/lib:/usr/lib32
[ 1838.352481] [DEBUG] Socket path: /var/run/bumblebee.socket
[ 1838.352483] [DEBUG] Accel/display bridge: auto
[ 1838.352486] [DEBUG] VGL Compression: proxy
[ 1838.352492] [DEBUG] VGLrun extra options: 
[ 1838.352498] [DEBUG] Primus LD Path: /usr/lib/primus:/usr/lib32/primus
[ 1838.352600] [DEBUG]Using auto-detected bridge primus
[ 1840.953573] [INFO]Response: No - error: [XORG] (EE) Screen 1 deleted because of no matching config section.

[ 1840.953588] [ERROR]Cannot access secondary GPU - error: [XORG] (EE) Screen 1 deleted because of no matching config section.

[ 1840.953590] [DEBUG]Socket closed.
[ 1840.953605] [ERROR]Aborting because fallback start is disabled.
[ 1840.953610] [DEBUG]Killing all remaining processes.

- [output of hwinfo --gfx](https://gist.github.com/nwg-piotr/d70280f444b4213b5b5d534041a56939) 
- [output of inxi -Fxzc0](https://gist.github.com/nwg-piotr/dda7aee9525831e7ac1064cb1d663542)
- [content of bumblebee.conf](https://gist.github.com/nwg-piotr/95a6c96322b91c59ff8a52da45f34d6d)
- [content of intel.conf](https://gist.github.com/nwg-piotr/86d208ec740ce3e1147dcdf6d53684ce)
- [content of xorg.conf.nvidia](https://gist.github.com/nwg-piotr/5a8d7979db87c65ded988b58413d3b7f)
- [Xorg.0.log](https://gist.github.com/nwg-piotr/1fdf4474f2be04b331b57b5703494621)
- [Xorg.8.log](https://gist.github.com/nwg-piotr/7608d534d1cab1b2d373115d9124a5af)
- [output of dmesg](https://gist.github.com/nwg-piotr/f0ce3a1472b708011aac149f5f72b833)
- [systemctl status bumblebeed.service](https://gist.github.com/nwg-piotr/05a2f2399c354f07d22deac66ab0c084)

**Comment by vfbsilva** [comment]
same problem here have you somehow solved it?

**Comment by nwg-piotr** [comment]
Well, I failed resolving the issue on Manjaro. The solution for my hardware was to install Antergos, and follow [this guide](https://antergos.com/wiki/en/hardware/bumblebee-for-nvidia-optimus).

**Comment by nwg-piotr** [comment]
By the way: same steps do the job on vanilla Arch.
