### ISSUE TITLE
intel-virtual-output: No VIRTUAL outputs on ":0".

### ISSUE THREAD

**Issue by dbacc** [Bumblebee-Project/Bumblebee#912]
[Xorg.0.log.txt](https://github.com/Bumblebee-Project/Bumblebee/files/1272090/Xorg.0.log.txt)
[Xorg.8.log.txt](https://github.com/Bumblebee-Project/Bumblebee/files/1272089/Xorg.8.log.txt)

[Xorg.0.log.txt](https://github.com/Bumblebee-Project/Bumblebee/files/1272088/Xorg.0.log.txt)
[Xorg.8.log.txt](https://github.com/Bumblebee-Project/Bumblebee/files/1272087/Xorg.8.log.txt)

Hey,
I'm trying to get my dual-screen setup to work on my Lenovo W520.
I'm using bumblebee with nvidia, I don't have any graphics related files in xorg.conf.d .
The discrete graphics card can be used to render output to LVDS1, so in principle bumblebee seems to work.
When I now try to use my external outputs (such as DP-1) by invoking intel-virtual-output I get the error message:
No VIRTUAL outputs on ":0".
And indeed, xrandr doesn't show any digital outputs:

```Screen 0: minimum 320 x 200, current 1920 x 1080, maximum 8192 x 8192
LVDS-1 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 344mm x 193mm
   1920x1080     60.00*+  50.00  
   1400x1050     59.98  
   1280x1024     60.02  
   1280x960      60.00  
   1024x768      60.04    60.00  
   960x720       60.00  
   928x696       60.05  
   896x672       60.01  
   800x600       60.00    60.32    56.25  
   700x525       59.98  
   640x512       60.02  
   640x480       60.00    59.94  
   512x384       60.00  
   400x300       60.32    56.34  
   320x240       60.05  
VGA-1 disconnected (normal left inverted right x axis y axis)
```

However, the additional Xserver on Display :8 seems to have started:
```DISPLAY=:8 xrandr
Screen 0: minimum 8 x 8, current 1920 x 1080, maximum 16384 x 16384
VGA-0 disconnected primary (normal left inverted right x axis y axis)
LVDS-0 disconnected (normal left inverted right x axis y axis)
DP-0 disconnected (normal left inverted right x axis y axis)
DP-1 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 510mm x 287mm
   1920x1080     60.00*+  50.00  
   1680x1050     59.95  
   1600x1200     60.00  
   1440x900      59.89  
   1280x1024     75.02    60.02  
   1280x960      60.00  
   1280x800      59.81  
   1280x720      60.00    50.00  
   1152x864      75.00  
   1024x768      75.03    70.07    60.00  
   800x600       75.00    72.19    60.32    56.25  
   720x576       50.00  
   720x480       59.94  
   640x480       75.00    72.81    59.94  
DP-2 disconnected (normal left inverted right x axis y axis)
DP-3 disconnected (normal left inverted right x axis y axis)
DP-4 disconnected (normal left inverted right x axis y axis)
DP-5 disconnected (normal left inverted right x axis y axis)```

Attached find my X11 log files.

**Comment by TheTesla** [comment]
You need _AllowEmptyInitialConfiguration_ in your /etc/bumblebee/xorg.conf.nvidia

```
Section "ServerLayout"
    Identifier  "Layout0"
    Option      "AutoAddDevices" "false"
    Option      "AutoAddGPU" "false"
EndSection
 
Section "Device"
    Identifier  "DiscreteNvidia"
    Driver      "nvidia"
    VendorName  "NVIDIA Corporation"
    Option "ProbeAllGpus" "false"
    Option "NoLogo" "true"
    Option "AllowEmptyInitialConfiguration"
EndSection
```

**Comment by dbacc** [comment]
Unfortunately adding this option doesn't change anything:/

`cat /etc/bumblebee/xorg.conf.nvidia  
Section "ServerLayout"
    Identifier  "Layout0"
#    Option      "AutoAddDevices" "false"
    Option      "AutoAddGPU" "false"
EndSection

Section "Device"
    Identifier  "DiscreteNvidia"
    Driver      "nvidia"
    VendorName  "NVIDIA Corporation"

#   If the X server does not automatically detect your VGA device,
#   you can manually set it here.
#   To get the BusID prop, run `lspci | egrep 'VGA|3D'` and input the data
#   as you see in the commented example.
#   This Setting may be needed in some platforms with more than one
#   nvidia card, which may confuse the proprietary driver (e.g.,
#   trying to take ownership of the wrong device). Also needed on Ubuntu 13.04.
#   BusID "PCI:01:00:0"

#   Setting ProbeAllGpus to false prevents the new proprietary driver
#   instance spawned to try to control the integrated graphics card,
#   which is already being managed outside bumblebee.
#   This option doesn't hurt and it is required on platforms running
#   more than one nvidia graphics card with the proprietary driver.
#   (E.g. Macbook Pro pre-2010 with nVidia 9400M + 9600M GT).
#   If this option is not set, the new Xorg may blacken the screen and
#   render it unusable (unless you have some way to run killall Xorg).
    Option "ProbeAllGpus" "false"
    Option "AllowEmptyInitialConfiguration"
    Option "NoLogo" "true"
#    Option "UseEDID" "false"
    Option "UseDisplayDevice" "none"
EndSection
`

**Comment by dbacc** [comment]
This worked for me:
https://unix.stackexchange.com/questions/321151/do-not-manage-to-activate-hdmi-on-a-laptop-that-has-optimus-bumblebee
