### ISSUE TITLE
Cannot access secondary GPU - error: [XORG] (EE) 

### ISSUE THREAD

**Issue by jucajuca** [Bumblebee-Project/Bumblebee#915]
Hello,

I'm trying to get my nvidia card to work wit ubuntu 16.04.3.

So far I have installed nvidia-381 and bumblebeed. However only the intel card is working. For **unity to work** I need to do:

$ prime-select intel

Otherwise (wiht prime-select nvidia) unity won't start (login loop).

As far as I can understand the problem is that Xorg fails to load the nvidia driver AND also to create the screen for the driver. The service Bumbleebed is active but it reports errors (see below). When I look at Xorg.0.log I see the following (below the text).

My guess is that I first need to generate a valid xorg.conf file... and then make sure that the nvidia module is correctly loaded. But I need some input for this.

I have to add that I have been trying thinkering a lot.
I really want to get my nvidia card working with linux.

You can download the bumblebee-bugreport here:

http://send.juan-carlos.info/download.php?id=39&token=cicpw40vdEgO7aoUE3NboYpmaXC0KMQM

******************************

ANY HELP IS HIGHLY APPRECIATED. 

THANK YOU.

******************************

-----------------------

cat /var/log/Xorg.0.log | grep EE
> 	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
> [    38.334] (EE) Failed to load module "nvidia" (module does not exist, 0)
> [    38.334] (EE) Failed to load module "nvidia" (module does not exist, 0)
> [    38.334] (EE) Failed to load module "nouveau" (module does not exist, 0)
> [    38.786] (EE) open /dev/fb0: No such file or directory
> [    38.786] (EE) open /dev/fb0: No such file or directory
> [    38.786] (EE) Screen 0 deleted because of no matching config section.
> [    38.786] (EE) Screen 0 deleted because of no matching config section.
> [    39.529] (EE) AIGLX: reverting to software rendering

cat /var/log/Xorg.1.log | grep EE
> 	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
> [  5067.982] (EE) Problem parsing the config file
> [  5067.982] (EE) Error parsing the config file
> [  5067.982] (EE) 
> [  5067.982] (EE) no screens found(EE) 
> [  5067.982] (EE) 
> [  5067.982] (EE) Please also check the log file at "/var/log/Xorg.1.log" for additional information.
> [  5067.982] (EE) 
> [  5067.982] (EE) Server terminated with error (1). Closing log file.

-----------------------

sudo service bumblebeed status
```
● bumblebeed.service - Bumblebee C Daemon
   Loaded: loaded (/lib/systemd/system/bumblebeed.service; enabled; vendor preset: enabled)
   Active: active (running) since Fre 2017-09-08 10:46:56 CEST; 17min ago
 Main PID: 867 (bumblebeed)
    Tasks: 1
   Memory: 1.2M
      CPU: 16ms
   CGroup: /system.slice/bumblebeed.service
           └─867 /usr/sbin/bumblebeed

Sep 08 10:46:56 laptop systemd[1]: Started Bumblebee C Daemon.
Sep 08 10:46:57 laptop bumblebeed[867]: [   23.535209] [INFO]/usr/sbin/bumblebeed 3.2.1 started
Sep 08 10:47:00 laptop bumblebeed[867]: [   26.543013] [ERROR]Unloading nvidia driver timed out.
Sep 08 10:49:26 laptop bumblebeed[867]: [  172.368223] [ERROR][XORG] (EE)
Sep 08 10:49:26 laptop bumblebeed[867]: [  172.368238] [ERROR][XORG] (EE)
Sep 08 10:49:26 laptop bumblebeed[867]: [  172.368241] [ERROR][XORG] (EE)
Sep 08 10:49:26 laptop bumblebeed[867]: [  172.368243] [ERROR][XORG] (EE)
Sep 08 10:49:26 laptop bumblebeed[867]: [  172.368246] [ERROR][XORG] (EE)
Sep 08 10:49:26 laptop bumblebeed[867]: [  172.368248] [ERROR]X did not start properly
```
-----------------------

Ubuntu 16.04.3 LTS \n \l

-----------------------

Linux laptop 4.4.0-93-generic #116-Ubuntu SMP Fri Aug 11 21:17:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

-----------------------

baseboard-manufacturer: Micro-Star International Co., Ltd.
baseboard-product-name: MS-16GH
baseboard-version     : REV:1.0
system-manufacturer   : Micro-Star International Co., Ltd.
system-product-name   : GP60 2PE
system-version        : REV:1.0
bios-vendor           : American Megatrends Inc.
bios-version          : E16GHIMS.10B
bios-release-date     : 10/23/2014

-----------------------

optirun (Bumblebee) 3.2.1
Copyright (C) 2011 The Bumblebee Project
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

-----------------------

Device lspci -nnk | grep -iA3 3D

> 01:00.0 3D controller [0302]: NVIDIA Corporation GM108M [GeForce 840M] [10de:1341] (rev a2)
> 	Subsystem: Micro-Star International Co., Ltd. [MSI] GM108M [GeForce 840M] [1462:1113]
> 	Kernel driver in use: nvidia
> 	Kernel modules: nvidiafb, nouveau, nvidia_381, nvidia_381_drm

Device lspci -nnk | grep -iA3 vga

> 00:02.0 VGA compatible controller [0300]: Intel Corporation 4th Gen Core Processor Integrated Graphics Controller [8086:0416] (rev 06)
> 	DeviceName:  Onboard IGD
> 	Subsystem: Micro-Star International Co., Ltd. [MSI] 4th Gen Core Processor Integrated Graphics Controller [1462:1113]
> 	Kernel modules: i915

--------------------------

lsmod | grep nvidia

> nvidia_uvm            643072  0
> nvidia_drm             53248  0
> nvidia_modeset        811008  1 nvidia_drm
> drm_kms_helper        155648  2 i915,nvidia_drm
> nvidia              11550720  2 nvidia_modeset,nvidia_uvm
> drm                   364544  4 i915,drm_kms_helper,nvidia_drm

--------------------------

sudo lshw -C display
```
  *-display               
       description: 3D controller
       product: GM108M [GeForce 840M]
       vendor: NVIDIA Corporation
       physical id: 0
       bus info: pci@0000:01:00.0
       version: a2
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress bus_master cap_list rom
       configuration: driver=nvidia latency=0
       resources: irq:16 memory:f6000000-f6ffffff memory:e0000000-efffffff memory:f0000000-f1ffffff ioport:e000(size=128) memory:f7000000-f707ffff
  *-display UNCLAIMED
       description: VGA compatible controller
       product: 4th Gen Core Processor Integrated Graphics Controller
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 06
       width: 64 bits
       clock: 33MHz
       capabilities: msi pm vga_controller bus_master cap_list
       configuration: latency=0
       resources: memory:f7400000-f77fffff memory:d0000000-dfffffff ioport:f000(size=64)
```

--------------------------

optirun -vv glxgears
```
[  172.324388] [DEBUG]Reading file: /etc/bumblebee/bumblebee.conf
[  172.324577] [INFO]Configured driver: nvidia
[  172.324674] [DEBUG]optirun version 3.2.1 starting...
[  172.324679] [DEBUG]Active configuration:
[  172.324689] [DEBUG] bumblebeed config file: /etc/bumblebee/bumblebee.conf
[  172.324699] [DEBUG] X display: :1
[  172.324707] [DEBUG] LD_LIBRARY_PATH: /usr/lib/nvidia-381:/usr/lib32/nvidia-381
[  172.324717] [DEBUG] Socket path: /var/run/bumblebee.socket
[  172.324727] [DEBUG] Accel/display bridge: auto
[  172.324734] [DEBUG] VGL Compression: proxy
[  172.324742] [DEBUG] VGLrun extra options: 
[  172.324748] [DEBUG] Primus LD Path: /usr/lib/x86_64-linux-gnu/primus:/usr/lib/i386-linux-gnu/primus
[  172.331657] [DEBUG]Using auto-detected bridge primus
[  172.368271] [INFO]Response: No - error: [XORG] (EE) 

[  172.368310] [ERROR]Cannot access secondary GPU - error: [XORG] (EE) 

[  172.368323] [DEBUG]Socket closed.
[  172.368341] [ERROR]Aborting because fallback start is disabled.
[  172.368362] [DEBUG]Killing all remaining processes.
```

--------------------------
--------------------------
--------------------------

sudo gpu-manager
```
last_boot_file: /var/lib/ubuntu-drivers-common/last_gfx_boot
new_boot_file: /var/lib/ubuntu-drivers-common/last_gfx_boot
/etc/modprobe.d is not a file
can't access /run/u-d-c-fglrx-was-loaded file
/etc/modprobe.d is not a file
/etc/modprobe.d is not a file
/etc/modprobe.d is not a file
/etc/modprobe.d is not a file
Looking for fglrx modules in /lib/modules/4.4.0-93-generic/updates/dkms
Looking for nvidia modules in /lib/modules/4.4.0-93-generic/updates/dkms
Found nvidia module: nvidia_381_drm.ko
Is nvidia loaded? yes
Was nvidia unloaded? no
Is nvidia blacklisted? yes
Is fglrx loaded? no
Was fglrx unloaded? no
Is fglrx blacklisted? no
Is intel loaded? yes
Is radeon loaded? no
Is radeon blacklisted? no
Is amdgpu loaded? no
Is amdgpu blacklisted? no
Is nouveau loaded? no
Is nouveau blacklisted? yes
Is fglrx kernel module available? no
Is nvidia kernel module available? yes
Vendor/Device Id: 8086:416
BusID "PCI:0@0:2:0"
Is boot vga? yes
Error: can't access /sys/bus/pci/devices/0000:00:02.0/driver
The device is not bound to any driver. Skipping...
Vendor/Device Id: 10de:1341
BusID "PCI:1@0:0:0"
Is boot vga? no
Skipping "/dev/dri/card0", driven by "nvidia-drm"
Skipping "/dev/dri/card0", driven by "nvidia-drm"
Skipping "/dev/dri/card0", driven by "nvidia-drm"
Skipping "/dev/dri/card0", driven by "nvidia-drm"
Does it require offloading? no
last cards number = 1
Has amd? no
Has intel? no
Has nvidia? yes
How many cards? 1
Has the system changed? No
main_arch_path x86_64-linux-gnu, other_arch_path i386-linux-gnu
update-alternatives: error: no alternatives for x86_64-linux-gnu_gfxcore_conf
Current alternative: /usr/lib/nvidia-381-prime/ld.so.conf
Current core alternative: (null)
Current egl alternative: /usr/lib/nvidia-381-prime/ld.so.conf
Is nvidia enabled? no
Is nvidia egl enabled? no
Is fglrx enabled? no
Is mesa enabled? no
Is mesa egl enabled? no
Is pxpress enabled? no
Is prime enabled? yes
Is prime egl enabled? yes
Is nvidia available? yes
Is nvidia egl available? no
Is fglrx available? no
Is fglrx-core available? no
Is mesa available? yes
Is mesa egl available? yes
Is pxpress available? no
Is prime available? yes
Is prime egl available? no
Single card detected
No change - nothing to do
```

**Comment by bluca** [comment]
Hi, you are mixing up different mechanism. Either use prime, or bumblebee, not both.
