### ISSUE TITLE
Bbswitch causes laptop to fail to boot.

### ISSUE THREAD

**Issue by ItsDeadEnd** [Bumblebee-Project/Bumblebee#918]
when bbswitch is installed my laptop wont boot, it will either say 
![this](https://user-images.githubusercontent.com/19259091/31063074-7589b0e6-a71f-11e7-8d77-a6b3d81c3b9b.jpg)
or
![or this](https://user-images.githubusercontent.com/19259091/31063075-758d1d08-a71f-11e7-8e9e-6361d0467e5f.jpg)

my laptop is the asus zenbook pro ux501vw

**Comment by Lekensteyn** [comment]
must have been some other issue I guess?

**Comment by ItsDeadEnd** [comment]
I realized that the console output I had happened anyway. Bbswitch still
won't allow my computer to boot but it's likely a problem with X and the
information I provided is likely insufficient.
