### ISSUE TITLE
Segfault in libGL.so

### ISSUE THREAD

**Issue by Pikrass** [Bumblebee-Project/Bumblebee#934]
Hi!

This issue looks similar to some old ones (#516, #783) but the fixes implied installing more recent versions of some packages (or removing `nomodeset`, which I already don't have), and I'm already quite a few versions ahead of the affected ones in these bug reports.

The issue: I can't use optirun with any program using OpenGL. It fails with no output. If I look at `dmesg` or run it through `optirun bash` I learn this is due to a segmentation fault.

```
[16341.951029] glxgears[7971]: segfault at 0 ip 00007faf19e25293 sp 00007fff07ffa220 error 4 in libGL.so.1[7faf19e00000+3f000]
```

Optirun used to work, but I don't know from which version it started to fail, sorry.
I'm using Debian Sid.
```
$ uname -a
Linux Inlandsis 4.14.0-2-amd64 #1 SMP Debian 4.14.7-1 (2017-12-22) x86_64 GNU/Linux
```
```
$ cat /proc/cmdline 
BOOT_IMAGE=/main/boot/vmlinuz-4.14.0-2-amd64 root=UUID=ee6eaf30-835c-4400-9b1b-6cb8fb9dd484 ro rootflags=subvol=main rcutree.rcu_idle_gp_delay=1 quiet
```
```
baseboard-manufacturer: Acer
baseboard-product-name: Aspire VN7-592G
baseboard-version     : V1.03
system-manufacturer   : Acer
system-product-name   : Aspire VN7-592G
system-version        : V1.03
bios-vendor           : Insyde Corp.
bios-version          : V1.03
bios-release-date     : 09/25/2015
```
```
$ optirun -V
optirun (Bumblebee) 3.2.1
```
```
$ apt-cache policy bumblebee
bumblebee:
  Installed: 3.2.1-17
  Candidate: 3.2.1-17
  Version table:
 *** 3.2.1-17 990
        500 http://ftp.fr.debian.org/debian buster/main amd64 Packages
        990 http://ftp.fr.debian.org/debian sid/main amd64 Packages
        100 /var/lib/dpkg/status
     3.2.1-14 500
        500 http://ftp.fr.debian.org/debian stretch/main amd64 Packages
     3.2.1-7 500
        500 http://ftp.fr.debian.org/debian jessie/main amd64 Packages
```
```
$ optirun gdb glxgears
GNU gdb (Debian 7.12-6+b1) 7.12.0.20161007-git
[...]
Reading symbols from glxgears...(no debugging symbols found)...done.
(gdb) run
Starting program: /usr/bin/glxgears 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffeb1b2700 (LWP 8952)]
[New Thread 0x7fffea9b1700 (LWP 8953)]
[New Thread 0x7fffea1b0700 (LWP 8954)]
[New Thread 0x7fffe99af700 (LWP 8955)]

Thread 1 "glxgears" received signal SIGSEGV, Segmentation fault.
0x00007ffff76b9293 in glXCreateContext () from /usr/lib/x86_64-linux-gnu/primus/libGL.so.1
```

**Comment by bluca** [comment]
Makre sure you have the non-glvnd packages, eg: ```apt install libgl1-nvidia-glx libegl1-nvidia nvidia-nonglvnd-vulkan-common```

**Comment by Pikrass** [comment]
That last package wasn't installed. I did and rebooted, the issue's still there.

**Comment by bluca** [comment]
Please run ```reportbug --template nvidia-driver``` and upload the result to pastebin or gist

**Comment by Pikrass** [comment]
https://pastebin.com/cYAbRfNX

**Comment by Pikrass** [comment]
With `gdb`, I traced the segfault back to primus' `match_fbconfig`. Looks like `glXChooseFBConfig` returns NULL, but that's as far as I can get obviously.

**Comment by Pikrass** [comment]
Switched to kernel 4.14.0-3-amd64 from Debian's repo, and removed and installed again all relevant packages. I still get the same issue.

**Comment by Pikrass** [comment]
The problem was solved today after upgrading. The only relevant package I found in the list was libvulkan1 (upgraded to version 1.0.65.2+dfsg1-1 in Debian Sid).
