### ISSUE TITLE
Fedora with kernel 4.14.11

### ISSUE THREAD

**Issue by kmare** [Bumblebee-Project/Bumblebee#935]
After upgrading to kernel 4.14.11, the nvidia module won't compile any more, Kinda weird for a micro release bump. There is a patch available here:
https://devtalk.nvidia.com/default/topic/1028016/linux/patch-for-compiling-v384-98-modules-with-linux-v4-14-9-/
@gsgatlin could you please apply the patch?

Thank you in advance and happy new year!

[nvidia-installer.log](https://github.com/Bumblebee-Project/Bumblebee/files/1603364/nvidia-installer.log)

**Comment by gsgatlin** [comment]
Hello. Thanks for the heads up. I have pushed bumblebee-nvidia-384.98-2 which has the patch so try that one and see if it works.

**Comment by kmare** [comment]
Updated and working great. Thank you again for the quick fix!
btw, is it possible to set a github repo just for fedora builds where others could also help with patches and issues specific to it?

**Comment by gsgatlin** [comment]
Yes. The links are:

https://github.com/gsgatlin/bumblebee-nvidia

and

https://github.com/gsgatlin/optimus-rpms

It works on fedora and RHEL 6/7.

Cheers,

**Comment by kmare** [comment]
Argh, no clue how I managed to miss your github repos all this time! Next time I'll use them instead.

Thank you again.
