### ISSUE TITLE
bumblebee does not start " socket was in correct"

### ISSUE THREAD

**Issue by habi3000** [Bumblebee-Project/Bumblebee#938]
hi, first of all thanks for the great project 
**distro** debian 9 with gnome 3.22
**kernal** `Linux  4.9.0-4-amd64 #1 SMP Debian 4.9.65-3+deb9u1 (2017-12-23) x86_64 GNU/Linux`
output of `$ sudo lspci | grep -E "VGA|3D"`
`00:02.0 VGA compatible controller: Intel Corporation HD Graphics 530 (rev 06)
01:00.0 3D controller: NVIDIA Corporation GM107M [GeForce GTX 960M] (rev a2)`
i installed  Bumblebee following  [debian wiki](https://wiki.debian.org/Bumblebee) from repository using proprietary nvidia driver 

when i run `$ optirun glxgears ` i get 
`[ 9000.393226] [ERROR]The Bumblebee daemon has not been started yet or the socket path /var/run/bumblebee.socket was incorrect.
[ 9000.393239] [ERROR]Could not connect to bumblebee daemon - is it running?`
the file `/var/run/bumblebee.socket` does not exist , i tried to run it as sudo it is the same 

when i run `$ sudo modprobe nvidia` i get
`modprobe: FATAL: Module nvidia-current not found in directory /lib/modules/4.9.0-4-amd64
modprobe: ERROR: ../libkmod/libkmod-module.c:977 command_do() Error running install command for nvidia
modprobe: ERROR: could not insert 'nvidia': Operation not permitted`

when i run `$ bumblebee-nvidia --check` i get 
`bash: bumblebee-nvidia: command not found`

when i run`$ sudo systemctl status bumblebeed` i get
`● bumblebeed.service - Bumblebee C Daemon
   Loaded: loaded (/lib/systemd/system/bumblebeed.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Sat 2018-01-13 17:26:10 +03; 48s ago
  Process: 17501 ExecStart=/usr/sbin/bumblebeed (code=exited, status=1/FAILURE)
 Main PID: 17501 (code=exited, status=1/FAILURE)

Jan 13 17:26:10 asus systemd[1]: bumblebeed.service: Unit entered failed state.
Jan 13 17:26:10 asus systemd[1]: bumblebeed.service: Failed with result 'exit-code'.`

what i have tried 
setting KernelDriver=nvidia-current and KernelDriver=nvidia

hope these information are enough

**Comment by bluca** [comment]
That's likely the kernel module failing to build, which is not related to bumblebee, check with:

```sudo dkms status```

You'll probably need to install libelf-dev and rebuild the module

**Comment by habi3000** [comment]
Thanks a lot for your quick response,
I fixed that. But now after reboot it freezes after grub with the fan at max speed which is really annoying. I can only go to recovery mode and have a root shell

**Comment by habi3000** [comment]
finally fixed it and every thing seams to be working correctly . while installing cuda following debian  [wiki](https://wiki.debian.org/NvidiaGraphicsDrivers)  i found this message 
`warning: forcing reinstallation of alternative /usr/lib/nvidia/bumblebee because link group glx is broken`
so i tried to reinstall Bumblebee which worked :) 
thanks for your project.
