### ISSUE TITLE
Nvdia installed but graphic still mobile on information setting

### ISSUE THREAD

**Issue by harmloh** [Bumblebee-Project/Bumblebee#949]
I have installed Nvidia optimus from Bumblebee, but my information system on Fedora graphic still use Mobile not nvidia , 
Is there any wrong with it ? 
I follow all method from the Bumblebee Fedora 

`lspci -k | grep -A 2 VGA
00:02.0 VGA compatible controller: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller (rev 09)
	Subsystem: Dell Device 04c8
	Kernel driver in use: i915
01:00.0 VGA compatible controller: NVIDIA Corporation GF108M [GeForce GT 540M] (rev ff)
	Kernel modules: nouveau, nvidia_drm, nvidia`

[this is the pic of my information graphic](https://my.pcloud.com/publink/show?code=XZ2Im47ZxaAyrsRNT67mIhkbGXR0EzPcnhxX)

**Comment by gsgatlin** [comment]
what happens if you run

optirun -b primus glxgears -info

? 

Does one of the lines of output say

GL_VENDOR     = NVIDIA Corporation

? 

You will probably have to scroll up in your terminal to see that.

How about

optirun -b none nvidia-settings -c :8

Does that show you the nvidia control panel?

**Comment by harmloh** [comment]
*Optimun -b Optirun glxgears -info*
180.705905 error unknown Accel/display bridge : optimus

*Optirun -b money nvdia-srttinf -c :8*
Error running Nvidia -settinf : no such file or directory


I tried 2 methods so far from Bumbleee and if-not-true-then-flase.com as well, always failed to display the Nvidia :(

**Comment by gsgatlin** [comment]
optirun -b primus glxgears -info

optirun -b none nvidia-settings -c :8

**Comment by harmloh** [comment]
`<pre>optirun -b primus glxgears -info
GL_RENDERER   = GeForce GT 540M/PCIe/SSE2
GL_VERSION    = 4.6.0 NVIDIA 390.25
GL_VENDOR     = NVIDIA Corporation
</pre>`
`<pre>primus: warning: dropping a frame to avoid deadlock
primus: warning: timeout waiting for display worker</pre>`


`optirun -b none nvidia-settings -c :8
[  258.707304] [ERROR]Error running "nvidia-settings": No such file or directory`



am i missing something ??

**Comment by gsgatlin** [comment]
Ok. So you need to use the optirun command and it appears to be working.

If you used rpmfusion or negativo17 video drivers maybe someone else can help with how to install "nvidia-settings" program? Its probably some subpackage. But your bumblebee installation appears to working correctly. Hope that helps.

**Comment by gsgatlin** [comment]
Here is a video that purports to explain how optimus is supposed to work:

https://www.youtube.com/watch?v=nv1S9amZiCU

So most of the time, your display uses the Intel Mobile graphics. Yes.

When you need to play a 3d game or some other heavy 3d application, you can use "optirun" for increased performance.

Hope that helps.

**Comment by harmloh** [comment]
Is that mean Bumblebee is working on my computer ? 
And is that mean the graphics will automatically?
Thanks for your respond and I appreciate your help here

**Comment by gsgatlin** [comment]
In negativo17's repository, the nvidia-settings program is provided by the nvidia-settings package. So you can install that with dnf. I am not sure about rpmfusion but maybe its the same name for that package.

Yes, I think your bumblebee setup is working normally as expected. When you want to play a 3d game, use:

optirun -b primus NAMEOFGAMEEXECUTABLE

Where NAMEOFGAMEEXECUTABLE is some 3d opengl game. Like for minecraft it would be

optirun -b primus java -jar Minecraft.jar

This is just an example. It should work with most 3d type games. You do not want to use this for a 2d game or a web browser or similar. Your intel GPU is powerful enough to handle such applications.

It does not operate automatically. You have to use the "optirun" command or the "primusrun" shell script to invoke a program using the nvidia graphics card. This is the biggest difference between how it works on Windows OS and how it works on Linux. primus bridge will give you better performance then VirtualGL will in most cases. (-b primus with optirun command)

You can type

man optirun

and

man primusrun

for all command options to optirun and primusrun.

Hope that helps.

**Comment by harmloh** [comment]
i got it buddy, thanks a lot, i hope your project work on FreeBSD soon, it would be good and make some optimus user not get difficult to configure Xorg,
