### ISSUE TITLE
Bumblebee Can't Use Secondary GPU

### ISSUE THREAD

**Issue by HEndLess** [Bumblebee-Project/Bumblebee#952]
I have a laptop which has 2 graphic cards (Intel and Nvidia Gt940m). I am running kali linux. I updated kali few days ego and now I can't use optirun command. When I try to use it I get this error:

```
optirun glxgears
[ 2146.097923] [ERROR]Cannot access secondary GPU - error: Could not load GPU driver

[ 2146.097954] [ERROR]Aborting because fallback start is disabled.
```

**Comment by cosmicog** [comment]
Did you do configurations before? Not now but before I tried on Kali with Ubuntu tutorials. Also you need to install working Nvidia driver. You can try to configure like this:
http://www.webupd8.org/2016/08/how-to-install-and-configure-bumblebee.html

**Comment by HEndLess** [comment]
After a fresh install kali and drivers I finally managed to get it working.
