### ISSUE TITLE
Dont working on my Linux mint 19

### ISSUE THREAD

**Issue by souzaramon** [Bumblebee-Project/Bumblebee#971]
Hello guys, I'm in trouble, 

i update the system and the drivers using Mint applications tools, then i installed the following packages:

- bumblebee
- bumblebee-nvidia
- primus

and then i select intel graphc card using nvdia-settings, reboot and when i run bumblebee  i get this:

$ primusrun glxgears      

/usr/bin/primusrun: line 41: warning: command substitution: ignored null byte in input
primus: fatal: Bumblebee daemon reported: error: Could not load GPU driver

$ sudo optirun glxgears

[ 1193.080708] [ERROR]Cannot access secondary GPU - error: Could not load GPU driver
[ 1193.080728] [ERROR]Aborting because fallback start is disabled.

have i missing something?
thank you anyways!

**Comment by kelebek333** [comment]
You can install Bumblebee to Linux Mint 19

**1. Installation of required packages**

```
sudo add-apt-repository ppa:graphics-drivers/ppa -y
sudo apt update
sudo apt install bumblebee nvidia-390 primus  primus-libs-ia32 linux-headers-$(uname -r) -y
```

**2. Post-installation configuration**

Change following lines from 

```
LibraryPath=/usr/lib/nvidia-current:/usr/lib32/nvidia-current
XorgModulePath=/usr/lib/nvidia-current/xorg,/usr/lib/xorg/modules
```

to

```
LibraryPath=/usr/lib/x86_64-linux-gnu:/usr/lib/i386-linux-gnu
XorgModulePath=/usr/lib/x86_64-linux-gnu/nvidia/xorg,/usr/lib/xorg/modules,/usr/lib/xorg/modules/input
```
in _/etc/bumblebee/bumblebee.conf_ file.

Add following line to _/etc/environment_ file.

`__GLVND_DISALLOW_PATCHING=1`

Add following line to _/etc/modprobe.d/blacklist-nvidia.conf_ file.

```
blacklist nouveau
blacklist nvidia
blacklist nvidia-drm
blacklist nvidia-modeset
alias nouveau off
alias nvidia-drm off
alias nvidia-modeset off
```

**3. Disable gpumanager**

You can disable gpumanager with following commands.

`echo 'GRUB_CMDLINE_LINUX="$GRUB_CMDLINE_LINUX nogpumanager"' | sudo tee  /etc/default/grub.d/nogpumanager.cfg`
`sudo update-grub`

**3a.** Add acpi parameter for some BIOS types with following commands.

`echo 'GRUB_CMDLINE_LINUX="$GRUB_CMDLINE_LINUX acpi_osi=! acpi_osi=\"Windows 2009\""' | sudo tee  /etc/default/grub.d/nvidia-acpi.cfg`
`sudo update-grub`

`4. Disable unnecessary services`

`sudo systemctl disable nvidia-fallback.service`
`sudo systemctl disable nvidia-persistenced.service`

`5. Reboot`

[Source](https://forum.linuxmint.net.tr/index.php?topic=9347.0)

**Comment by souzaramon** [comment]
Thanks, I followed the steps line by line, but I continued stuck in an error message, after so much frustration I gave up and switched to another linux distribution.

**Comment by Tomcat9** [comment]
@kelebek333
Thank you so much. It worked like a charm on this Schenker XMG 407. :-)

**Comment by evg-zhabotinsky** [comment]
@kelebek333 Thanks! It actually worked!

Only in the end, it complained that it could not find `/usr/lib/x86_64-linux-gnu/mesa/libGL.so.1`. Turned out I did not have that `mesa` directory at all, probably due to using fresh Intel drivers from Oibaf ppa. Doing `ln -sv . /usr/lib/x86_64-linux-gnu/mesa` solved the problem.

Also, if you are using graphics-drivers ppa for newer Nvidia drivers, package name is now `nvidia-driver-396` instead of `nvidia-396`.

**Comment by kelebek333** [comment]
@evg-zhabotinsky , @tberghuis , @Tomcat9 ; not at all!

For GPUs of fermi series must install Nvidia-390. GPUs of 9x0 series and above series could install Nvidia-396.

https://nvidia.custhelp.com/app/answers/detail/a_id/4656/~/list-of-fermi-series-geforce-gpus
