### ISSUE TITLE
glxinfo Error: couldn't get an RGB, Double-buffered visual

### ISSUE THREAD

**Issue by ZhuFengdaaa** [Bumblebee-Project/Bumblebee#982]
I have a Ubuntu 16.04 server with 3 Quadro P5000. I downloaded `LINUX X64 (AMD64/EM64T) DISPLAY DRIVER` with version number `390.77`
I installed several mesa packages
```
$ apt list --installed | grep mesa
libegl1-mesa/xenial-updates,now 18.0.5-0ubuntu0~16.04.1 amd64 [installed,automatic]
libgl1-mesa-dev/xenial-updates,now 18.0.5-0ubuntu0~16.04.1 amd64 [installed]
libgl1-mesa-dri/xenial-updates,now 18.0.5-0ubuntu0~16.04.1 amd64 [installed]
libgl1-mesa-glx/xenial-updates,now 18.0.5-0ubuntu0~16.04.1 amd64 [installed]
libglapi-mesa/xenial-updates,now 18.0.5-0ubuntu0~16.04.1 amd64 [installed,automatic]
libglu1-mesa/xenial,now 9.0.0-2.1 amd64 [installed,automatic]
libglu1-mesa-dev/xenial,now 9.0.0-2.1 amd64 [installed,automatic]
libwayland-egl1-mesa/xenial-updates,now 18.0.5-0ubuntu0~16.04.1 amd64 [installed,automatic]
mesa-common-dev/xenial-updates,now 18.0.5-0ubuntu0~16.04.1 amd64 [installed]
mesa-utils/xenial,now 8.3.0-1 amd64 [installed]
mesa-vdpau-drivers/now 17.2.8-0ubuntu0~16.04.1 amd64 [installed,upgradable to: 18.0.5-0ubuntu0~16.04.1]
```
Then I tried
```
$ glxgears
Error: couldn't get an RGB, Double-buffered visual
```
I tried optirun
```
$ optirun -d $DISPLAY glxgears
[VGL] NOTICE: Automatically setting VGL_CLIENT environment variable to
[VGL]    138.25.150.116, the IP address of your SSH client.
Error: couldn't get an RGB, Double-buffered visual
```
My display management service is lightdm, so there is no xorg.log. However, I didn't find useful lightdm log in `/var/log/lightdm`. It looks like a common problem but all solution online are tried without progress. Does anyone knows how to debug it ?

**Comment by Lekensteyn** [comment]
This does not sound like a hybrid graphics setup and is out-of-scope for Bumblebee. You're probably better off with configuring Xorg directly to use these GPUs.

What are you trying to do? Do you have monitors connected to these GPUs?

**Comment by ZhuFengdaaa** [comment]
I tried both cuda runtime installer and NVIDIA driver runtime installer to install GPU driver. I use nvidia-smi to monitor GPU. This command working regularly. But I don't use any other like xorg to config since it is a remote server. 

I'm new to this because I just used cuda to run deep learning program before. 

Thanks.

**Comment by FateRover** [comment]
Ubuntu不知道，但是在Debian SID（ubuntu基于debian sid）上，由于libgl.so.1路径的改变（印象里是390.xx驱动文件路径有变化，造成这个问题的主要原因），
会出现这个问题，安装bumblebee的时候，除了按debian wiki 上安装    `sudo dpkg --add-architecture i386 && sudo apt-get update && sudo apt-get install bumblebee-nvidia primus primus-libs:i386` 
 还需要额外安装
`sudo apt install libgl1-nvidia-glx libegl1-nvidia nvidia-nonglvnd-vulkan-common  ` 另外还要升级 mesa到18.1.6（18.1.1-18.1.5之间有bug，会导致段错误）

**Comment by ZhuFengdaaa** [comment]
@FateRover 我是mac ssh 连 ubuntu的，需不需要在mac上装 3D openGL driver?

**Comment by Lekensteyn** [comment]
> But I don't use any other like xorg to config since it is a remote server.
> I'm new to this because I just used cuda to run deep learning program before.

In that case, I think Bumblebee is really the wrong project for your purposes. If you are trying to use CUDA with such your setup, try to remove everything related to Bumblebee (bumblebee, bbswitch) and reinstall the Nvidia driver.

**Comment by ZhuFengdaaa** [comment]
Sorry for lack of intention: I want to create a pipeline rendering 3D on remote server and visualize locally. But I am new to 3D rendering and openGL. I found VirtualGL a helpful tool to do this, but I met the bug above when configuring VirtualGL. 

Meanwhile, I want keep CUDA to run GPU in pytorch. I'm not sure if there is a conflict between the NVIDIA driver of CUDA and  of OpenGL/GLX. 

I will add the intention at the very beginning, can you help me reopen this issue ? Thanks.
