### ISSUE TITLE
Arch hangs on boot

### ISSUE THREAD

**Issue by xQsme** [Bumblebee-Project/Bumblebee#990]
I'm running arch 4.18.8, i've never been able to get bumblebee working on this laptop, it's an Asus FZ50VX (6300HQ and 950M).

As soon as i enable the bumblebee daemon the system can't boot into graphical interface, it seems to get stuck in a loop because the fans ramp up after a bit.

I've made a post on [reddit](https://www.reddit.com/r/archlinux/comments/8s8e54/systemctl_enable_bumblebeedservice_freezes_startx/) a while back about this issue, please take a look and let me know if you need any extra info.

Thanks

**Comment by FateRover** [comment]
https://github.com/Bumblebee-Project/Bumblebee/issues/764     maybe

**Comment by xQsme** [comment]
acpi_osi=! acpi_osi="Windows 2009" solved it, thanks mate

**Comment by narutowindy** [comment]
@xQsme close this issue!!
